// The blocker guard validates issue bodies as local data. Only the operator's
// validated --org argument selects a forge query; blocker identifiers never do.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"html"
	"io"
	"os"
	"os/exec"
	"os/signal"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"syscall"
	"time"
	"unicode"
)

const help = `Verify open blocked-labelled issues carry a visible **Blocker:** record, that
no open issue declares a blocker without carrying the blocked label, and that
no Security issue is left unstarted with no record of why.

  **Blocker:** <identifier> | <blocker-kind> | last-verified <YYYY-MM-DD>: <result>
  **Blocker:** <what only the maintainer can do> | authority | last-verified <YYYY-MM-DD>: <result> | asked <pr|slack|session> <YYYY-MM-DD>

The blocker kind is upstream, authority or outcome. Explicit authority records
may name an account action, credential or permission in plain language. Legacy
records infer authority only from the literal identifier text "maintainer
authority". An outcome record says in words which event the delivered work
waits on -- a release being published, the next production occurrence -- and
never carries an ask, because nobody can be asked for an event.
The independent provider outage cause belongs in the result, for example
"outage-cause=credentials/auth; access is still missing".
Ask channels: pr = a draft PR; slack = the Slack DM to the maintainer's own user
(his self-DM), never a Slack channel, because every channel in the workspace is
public; session = the native ask tool in an interactive session. No other word
is a channel token, and the check reads any other word as NO-ASK. That includes
push, whether it means a git push or the runtime's push notification, and
issue: a GitHub comment records an ask and is not one.

A pull request is parked by the blocked label, and its record is a comment,
because a dependency bot rewrites the body of its own pull request. The record
comment is written by devantler, begins with the "> 🤖 Generated by the"
disclosure line, carries <!-- pr-blocker-record --> on a line of its own and
holds the same **Blocker:** line. A parked pull request has exactly one: update
it in place. None is MISSING and more than one is DUPLICATE; the one record is
otherwise read as an issue's is. A pull request without the label is not
parked and is never reported, whatever its comments say.

An UNLABELLED row is an issue whose visible record declares a blocker while the
issue has no blocked label; "**Blocker:** none ..." declares none and is skipped.

An UNRECORDED row is a Security issue that has gone unstarted for longer than
the bound with nothing on record to explain it. Unstarted: no open sub-issue,
and no open pull request mentions it (a dependency bot's pull request, hidden
text and a "Deferred:" line do not count). Nothing on record: no blocked label,
no declared blocker and no open native blocker. An assignee is not a start,
because a claim lapses after about two hours; such a row is marked [assigned].
"**Blocker:** none" is not a reason either, and its row says so. An issue a
dependency bot opened is the bot's own and is never reported. Only Security is
read this way: it outranks every other issue whatever its age, while an older
issue of another type may simply be queued behind older ones.

Sources (exactly one): --org <org> (every open issue, label or not, and every
                       open pull request, for the issues it mentions) or
         --input <file>|- (a JSON array; a record without a "labels" array is
                       read as blocked-labelled, the shape of earlier payloads;
                       one with a "pull_request" key is a pull request; and an
                       unlabelled issue that declares no blocker must carry
                       "type", null when it has none; a blocked-labelled
                       pull request must carry "comments", an array of
                       {"user":{"login":...},"body":...})
Options: --today <YYYY-MM-DD> (default UTC today)
         --ask-max-age-days <n> (default 14)
         --verify-max-age-days <n> (default 7; an otherwise conforming record
                       whose last-verified date is older is reported STALE,
                       because skipping a blocked issue needs a live check)
         --unrecorded-max-age-days <n> (default 7; how long a Security issue
                       may stay unstarted before it needs a record)
         --quiet (findings only)
         --ask-digest (emit declared authority blockers with missing or stale
                       ask records, oldest first, for verification before
                       asking the maintainer)
         --parked-digest (pull requests only: one row per open
                       blocked-labelled pull request, PARKED with its blocker
                       and a note when its one record conforms, was
                       re-verified recently and names no blocker known to be
                       closed, ACTIONABLE with the reason otherwise
                       (record=BLOCKER-CLOSED when an issue or pull request
                       the record names has closed, BLOCKER-SELF when it
                       names the pull request itself, BLOCKER-UNREADABLE when
                       a reference has no usable number; only this
                       organization's are read, and an authority blocker's
                       state never is), then
                       a CHECKED line counting every one read; issue findings
                       are not part of it and do not change its exit)
Write a record with the compose subcommand (compose --help), never by hand.
Park a pull request with the park subcommand (park --help): it writes the
record and the blocked label together and reads both back.
Exit: 0 conforms; 1 findings; 2 UNKNOWN (usage, unreadable or incomplete input).
      With --parked-digest: 0 every labelled pull request is parked (or none is
      labelled); 1 at least one is ACTIONABLE; 2 UNKNOWN.
`

// askChannels is the closed set of tokens an ask record may name. The ask
// expression and the digest are built from it and the help is pinned to it by
// test, so none of them can accept or advertise a token the others do not.
var askChannels = []string{"pr", "slack", "session"}

// askExpression matches an ask record that names one of channels. Each token
// is quoted, so one that holds a metacharacter can only ever match itself and
// never widens what counts as asked.
func askExpression(channels []string) *regexp.Regexp {
	quoted := make([]string, len(channels))
	for i, channel := range channels {
		quoted[i] = regexp.QuoteMeta(channel)
	}
	return regexp.MustCompile(`\| asked (` + strings.Join(quoted, "|") + `) ([0-9]{4}-[0-9]{2}-[0-9]{2})[\t ]*$`)
}

var (
	orgRE          = regexp.MustCompile(`^[A-Za-z0-9._-]+$`)
	dateRE         = regexp.MustCompile(`^[0-9]{4}-[0-9]{2}-[0-9]{2}$`)
	identifierRE   = regexp.MustCompile(`#[0-9]+|maintainer authority|[A-Za-z0-9._-]+/[A-Za-z0-9._-]+`)
	urlRE          = regexp.MustCompile(`([A-Za-z][A-Za-z0-9+.-]*:[^\s]|//|www\.|[A-Za-z0-9_-]+(\.[A-Za-z0-9_-]+)*\.[A-Za-z]{2,}/)[^\s]*`)
	askRE          = askExpression(askChannels)
	verificationRE = regexp.MustCompile(`^([0-9]{4}-[0-9]{2}-[0-9]{2}): (.*)$`)
)

type options struct {
	org, input       string
	today            time.Time
	maxAge           int64
	verifyMaxAge     int64
	unrecordedMaxAge int64
	quiet            bool
	askDigest        bool
	parkedDigest     bool
}

func civilDate(value string) (time.Time, error) {
	if !dateRE.MatchString(value) || strings.HasPrefix(value, "0000-") {
		return time.Time{}, errors.New("not a civil date")
	}
	return time.Parse("2006-01-02", value)
}

// defaultOptions holds the bounds a sweep applies unless told otherwise. The
// composer reads the same ones, so a record it prints is judged as it was composed.
func defaultOptions() options {
	return options{maxAge: 14, verifyMaxAge: 7, unrecordedMaxAge: 7}
}

func arguments(args []string) (options, bool, error) {
	o := defaultOptions()
	today := time.Now().UTC().Format("2006-01-02")
	for i := 0; i < len(args); i++ {
		arg := args[i]
		switch arg {
		case "--help", "-h":
			return o, true, nil
		case "--quiet":
			o.quiet = true
		case "--ask-digest":
			o.askDigest = true
		case "--parked-digest":
			o.parkedDigest = true
		case "--org", "--input", "--today", "--ask-max-age-days", "--verify-max-age-days", "--unrecorded-max-age-days":
			i++
			if i == len(args) {
				return o, false, fmt.Errorf("%s requires a value", arg)
			}
			value := args[i]
			switch arg {
			case "--org":
				o.org = value
			case "--input":
				o.input = value
			case "--today":
				today = value
			case "--ask-max-age-days", "--verify-max-age-days", "--unrecorded-max-age-days":
				if len(value) > 9 {
					return o, false, fmt.Errorf("%s must have at most 9 digits", arg)
				}
				if value == "" || strings.IndexFunc(value, func(r rune) bool { return r < '0' || r > '9' }) >= 0 {
					return o, false, fmt.Errorf("%s must be a non-negative integer", arg)
				}
				days, _ := strconv.ParseInt(value, 10, 64)
				switch arg {
				case "--ask-max-age-days":
					o.maxAge = days
				case "--verify-max-age-days":
					o.verifyMaxAge = days
				default:
					o.unrecordedMaxAge = days
				}
			}
		default:
			return o, false, fmt.Errorf("unknown argument %q", arg)
		}
	}
	if o.parkedDigest && (o.askDigest || o.quiet) {
		return o, false, errors.New("--parked-digest is a report of its own and takes neither --ask-digest nor --quiet")
	}
	if (o.org == "") == (o.input == "") {
		return o, false, errors.New("exactly one of --org or --input is required")
	}
	if o.org != "" && !orgRE.MatchString(o.org) {
		return o, false, errors.New("--org must match [A-Za-z0-9._-]+")
	}
	var err error
	o.today, err = civilDate(today)
	if err != nil {
		return o, false, errors.New("--today must be a real YYYY-MM-DD calendar date")
	}
	return o, false, nil
}

// visibleRecord retains the existing Markdown contract: the first visible,
// column-zero marker continues until a blank line or a fence. Comments are
// stripped only outside fences; their literal contents cannot forge a close.
func visibleRecord(body string) string {
	var record string
	var fence byte
	var fenceLength int
	inComment := false
	for _, raw := range strings.Split(body, "\n") {
		line := strings.TrimSuffix(raw, "\r")
		if fence == 0 {
			var visible strings.Builder
			for line != "" {
				if inComment {
					end := strings.Index(line, "-->")
					if end < 0 {
						break
					}
					line = line[end+3:]
					inComment = false
				} else {
					start := strings.Index(line, "<!--")
					if start < 0 {
						visible.WriteString(line)
						break
					}
					visible.WriteString(line[:start])
					line = line[start+4:]
					inComment = true
				}
			}
			line = visible.String()
		}
		candidate := strings.TrimLeft(line, " \t")
		indent := len(line) - len(candidate)
		if indent <= 3 && len(candidate) >= 3 && (candidate[0] == '`' || candidate[0] == '~') {
			ch := candidate[0]
			n := 0
			for n < len(candidate) && candidate[n] == ch {
				n++
			}
			if n >= 3 {
				if fence == 0 {
					if record != "" {
						return record
					}
					fence = ch
					fenceLength = n
					continue
				}
				if ch == fence && n >= fenceLength && strings.Trim(candidate[n:], " \t") == "" {
					fence = 0
					continue
				}
			}
		}
		if fence != 0 {
			continue
		}
		if record != "" {
			if strings.Trim(line, " \t") == "" {
				return record
			}
			record += " " + strings.TrimLeft(line, " \t")
		} else if strings.HasPrefix(line, "**Blocker:**") {
			record = line
		}
	}
	return record
}

// classify separates blocker kind (who can clear it) from the result's outage
// cause (why a provider stopped serving). Delimiter cardinality is checked before
// reading the kind, so an extra segment cannot turn authority into upstream.
func classify(line string, today time.Time, maxAge int64) (string, bool) {
	if line == "" {
		return "MISSING", false
	}
	if !strings.HasPrefix(line, "**Blocker:** ") || strings.IndexFunc(line, func(r rune) bool { return unicode.IsControl(r) && r != '\t' }) >= 0 {
		return "MALFORMED", false
	}
	parts := strings.Split(line, " | last-verified ")
	if len(parts) != 2 {
		return "MALFORMED", false
	}
	head := strings.Split(strings.TrimPrefix(parts[0], "**Blocker:** "), " | ")
	if len(head) > 2 {
		return "MALFORMED", false
	}
	for _, segment := range head {
		if strings.Contains(segment, "|") {
			return "MALFORMED", false
		}
	}
	legacy := len(head) == 1
	kind := "upstream"
	if legacy {
		if strings.Contains(head[0], "maintainer authority") {
			kind = "authority"
		}
	} else {
		kind = head[1]
		if kind != "upstream" && kind != "authority" && kind != "outcome" {
			return "MALFORMED", false
		}
	}
	identifier := strings.TrimSpace(urlRE.ReplaceAllString(head[0], ""))
	if kind == "outcome" {
		// An outcome wait names an event, which only words can do: a bare
		// reference is a tracked item, and waiting on one is an upstream blocker.
		// Nobody can be asked for an event, so an ask record contradicts the kind
		// (#3426).
		if strings.IndexFunc(identifier, unicode.IsLetter) < 0 || identifierOnlyRE.MatchString(html.UnescapeString(identifier)) || strings.Contains(parts[1], "| asked ") {
			return "MALFORMED", false
		}
	} else if !legacy && kind == "authority" {
		// An explicit authority kind makes plain descriptive text unambiguous.
		if !identifierRE.MatchString(identifier) && strings.IndexFunc(identifier, unicode.IsLetter) < 0 {
			return "MALFORMED", false
		}
	} else if !identifierRE.MatchString(identifier) {
		return "MALFORMED", false
	}
	verification := verificationRE.FindStringSubmatch(parts[1])
	if verification == nil {
		return "MALFORMED", false
	}
	// A future verification date cannot be fresh evidence, so it is never read as one.
	if verified, err := civilDate(verification[1]); err != nil || verified.After(today) {
		return "MALFORMED", false
	}
	result := strings.SplitN(verification[2], "| asked ", 2)[0]
	if strings.TrimSpace(result) == "" {
		return "MALFORMED", false
	}
	if kind == "upstream" || kind == "outcome" {
		return "CONFORMS", legacy
	}
	ask := askRE.FindStringSubmatch(line)
	if ask == nil {
		return "NO-ASK", legacy
	}
	askDate, err := civilDate(ask[2])
	if err != nil || askDate.After(today) {
		return "MALFORMED", legacy
	}
	// Unix days avoid time.Duration's roughly 290-year subtraction limit.
	age := today.Unix()/86400 - askDate.Unix()/86400
	if age > maxAge {
		return "STALE-ASK", legacy
	}
	return "CONFORMS", legacy
}

// staleVerification reports whether an otherwise conforming record was last
// verified more than maxAge days before today. A blocker skip requires a live
// re-verification on every run, and a `blocked` label never expires, so a
// record nobody has re-checked can park an issue indefinitely while its shape
// still conforms (#3161). Callers apply it only to records classify accepted,
// which already rejects an unparseable or future date.
func staleVerification(line string, today time.Time, maxAge int64) bool {
	parts := strings.Split(line, " | last-verified ")
	if len(parts) != 2 {
		return false
	}
	verification := verificationRE.FindStringSubmatch(parts[1])
	if verification == nil {
		return false
	}
	verified, err := civilDate(verification[1])
	if err != nil {
		return false
	}
	return today.Unix()/86400-verified.Unix()/86400 > maxAge
}

// askRow is one declared authority blocker with a missing or stale ask record.
// The declaration still needs verification before asking the maintainer.
type askRow struct {
	repo     string
	number   int64
	created  string
	age      int64
	agedKnow bool
	request  string
	stale    bool // asked once, but the ask has since gone stale
	legacy   bool // authority inferred from prose, not an explicit class token
	opaque   bool // the record names an identifier but no concrete action
}

var ghReferenceRE = regexp.MustCompile(`(?i)gh-[0-9]+`)

// neutralize breaks GitHub's active syntax in untrusted text. The digest is
// built to be pasted into a PR, Slack or a session, and no Markdown construct
// hides a mention from a bot -- bots parse the raw text -- so the token itself
// must stop being a live mention, command or autolink. URL spans are omitted;
// zero-width spaces leave mention/reference/command text readable without live tokens.
func neutralize(s string) string {
	s = urlRE.ReplaceAllString(s, "[URL omitted]")
	s = ghReferenceRE.ReplaceAllStringFunc(s, func(reference string) string {
		return reference[:1] + "\u200b" + reference[1:]
	})
	var out strings.Builder
	for i, r := range s {
		out.WriteRune(r)
		if r != '@' && r != '#' && r != '/' {
			continue
		}
		rest := s[i+len(string(r)):]
		if next := []rune(rest); len(next) > 0 && (unicode.IsLetter(next[0]) || unicode.IsDigit(next[0])) {
			out.WriteRune('​')
		}
	}
	return out.String()
}

// identifierOnlyRE matches a record whose identifier names a thing but no
// action -- a bare issue reference, a repository reference, or the legacy
// phrase alone.
var identifierOnlyRE = regexp.MustCompile(`^(#[0-9]+|(?i:gh)-[0-9]+|[A-Za-z0-9._-]+(/[A-Za-z0-9._-]+)?#[0-9]+|[A-Za-z0-9._-]+/[A-Za-z0-9._-]+|maintainer authority)[.,;:]?$`)

// askRequest renders what the maintainer is actually being asked to do -- the
// identifier segment of the blocker line. The body stays untrusted data, so it
// is bounded and control-stripped exactly as the verdict report's snippet is.
func askRequest(line string) string {
	return digestText(strings.SplitN(strings.TrimPrefix(line, "**Blocker:** "), " | ", 2)[0])
}

// digestText bounds and renders every input-authored digest field as inert
// Markdown, including repository names supplied through --input.
func digestText(text string) string {
	// Decode before bounding and stripping controls so Markdown destinations
	// cannot hide schemes or introduce a newline after sanitization.
	text = html.UnescapeString(text)
	runes := []rune(strings.TrimSpace(text))
	if len(runes) > 100 {
		runes = runes[:100]
	}
	safe := strings.Map(func(r rune) rune {
		if unicode.IsControl(r) {
			return unicode.ReplacementChar
		}
		return r
	}, string(runes))
	if safe == "" {
		return "(no description in record)"
	}
	// Keep Markdown links and HTML inert, including nested entities and an
	// existing backslash that could otherwise unescape an opening bracket.
	return strings.NewReplacer(
		`\`, `\\`, "[", `\[`, "<", "&lt;", ">", "&gt;", "&", "&amp;",
	).Replace(neutralize(safe))
}

// requestIsOpaque reports a record that names an identifier but no action a
// maintainer could actually perform. Delivering such a row and recording it as
// asked would mark a non-actionable message as delivered.
func requestIsOpaque(line string) bool {
	text := strings.SplitN(strings.TrimPrefix(line, "**Blocker:** "), " | ", 2)[0]
	text = html.UnescapeString(text)
	return identifierOnlyRE.MatchString(strings.TrimSpace(text))
}

// issueAge reports whole days open. A missing or unparseable creation date is
// not fatal: the ask is still owed, so the row is kept and marked unknown.
func issueAge(createdAt string, today time.Time) (int64, bool) {
	if len(createdAt) < 10 {
		return 0, false
	}
	created, err := civilDate(createdAt[:10])
	if err != nil {
		return 0, false
	}
	return today.Unix()/86400 - created.Unix()/86400, true
}

const digestDisclosure = "> 🤖 Generated by the Agentic Engineer\n\n"

// askDigestReport renders declarations oldest first for verification. Issue
// text and ask records do not establish that the maintainer must act.
func askDigestReport(rows []askRow) string {
	if len(rows) == 0 {
		return digestDisclosure + "ASK DIGEST -- no declared authority blocker has a missing or stale ask record.\n"
	}
	sort.SliceStable(rows, func(i, j int) bool {
		a, b := rows[i], rows[j]
		if a.agedKnow != b.agedKnow {
			return a.agedKnow // undated rows sort last
		}
		if a.agedKnow && a.age != b.age {
			return a.age > b.age
		}
		if a.repo != b.repo {
			return a.repo < b.repo
		}
		return a.number < b.number
	})
	seen := map[string]bool{}
	var repos []string
	for _, r := range rows {
		if !seen[r.repo] {
			seen[r.repo] = true
			repos = append(repos, digestText(r.repo))
		}
	}
	sort.Strings(repos)
	var out strings.Builder
	// The sheet is built to be delivered. Slack authenticates as the
	// maintainer's own account, so without a leading disclosure a pasted digest
	// reads as him writing to himself.
	_, _ = fmt.Fprint(&out, digestDisclosure)
	_, _ = fmt.Fprintf(&out, "ASK DIGEST -- %d declared authority blocker(s) to verify before asking for a maintainer action.\n", len(rows))
	_, _ = fmt.Fprint(&out, "Verify current capabilities and prerequisites; complete work the agent can perform.\n")
	_, _ = fmt.Fprint(&out, "Only for a remaining maintainer-only action, deliver an ask through a canonical channel\n")
	_, _ = fmt.Fprintf(&out, "(%s), then append `| asked <channel> <YYYY-MM-DD>` to that issue's **Blocker:** line.\n", strings.Join(askChannels, " | "))
	// Every channel in the workspace is public, and an ask can name a weakness.
	_, _ = fmt.Fprint(&out, "slack means the maintainer's own Slack self-DM, never a Slack channel: every channel in the workspace is public.\n")
	// Repository visibility is not in the search payload, so this tool cannot
	// establish it. Say so rather than let a private row reach a public PR.
	_, _ = fmt.Fprint(&out, "CHECK BEFORE DELIVERY: this tool does not establish repository visibility.\n")
	_, _ = fmt.Fprintf(&out, "Treat these rows as private until each repository is confirmed public: %s\n", strings.Join(repos, ", "))
	_, _ = fmt.Fprint(&out, "Descriptions are quoted untrusted issue text with mentions broken and URLs omitted.\n\n")
	for _, r := range rows {
		age := "age unknown"
		if r.agedKnow {
			age = fmt.Sprintf("opened %s  %dd", r.created, r.age)
		}
		kind := "no ask recorded"
		if r.stale {
			kind = "ask record is stale -- verify before renewing"
		}
		notes := ""
		if r.legacy {
			notes += "  [legacy: no class token]"
		}
		if r.opaque {
			notes += "  [NO ACTION DESCRIBED -- reopen the issue before delivering]"
		}
		_, _ = fmt.Fprintf(&out, "  %s#\u200b%d  %s  (%s)%s\n  > %s\n", digestText(r.repo), r.number, age, kind, notes, r.request)
	}
	return out.String()
}

type issue struct {
	Repo          string `json:"repo"`
	Number        int64  `json:"number"`
	Body          string `json:"body"`
	RepositoryURL string `json:"repository_url"`
	CreatedAt     string `json:"created_at"`
	// Labels is nil when the record carries no "labels" array at all. Only an
	// --input record may omit it (see blocked); a forge record must carry one.
	Labels *[]struct {
		Name string `json:"name"`
	} `json:"labels"`
	// The rest decides whether an unlabelled issue that declares no blocker is
	// being skipped or is simply new or in flight (see unrecorded). Type stays
	// raw, and the others are pointers, so a record that lacks one of them can
	// be told from one that carries it empty (see missingFact).
	Type      json.RawMessage    `json:"type"`
	Assignees *[]json.RawMessage `json:"assignees"`
	User      struct {
		Login string `json:"login"`
	} `json:"user"`
	Dependencies *struct {
		BlockedBy *int64 `json:"blocked_by"`
	} `json:"issue_dependencies_summary"`
	SubIssues *struct {
		Total     *int64 `json:"total"`
		Completed *int64 `json:"completed"`
	} `json:"sub_issues_summary"`
	// PullRequest is the key search puts on a pull request and on nothing else.
	// A pull request is never judged as an issue: its body is read for the
	// issues it mentions. pull is set by the loaders, from that key or from the
	// read the record came from.
	PullRequest json.RawMessage `json:"pull_request"`
	pull        bool
	// Comments is the comments of an --input record. It is read only for a
	// parked pull request, into thread; under --org the thread is read from the
	// forge instead (see parked.go).
	Comments json.RawMessage `json:"comments"`
	thread   []comment
	// BlockerState is, on an --input pull request, whether the blocker its
	// record names is "open" or "closed". Only the parked digest reads it; under
	// --org the state is read from the forge instead (see pulldigest.go).
	BlockerState string `json:"blocker_state"`
}

// unrecordedType is the one issue type read for being unstarted: a Security
// issue outranks every other issue regardless of age, so one still unstarted
// after the bound was passed over by every run that started anything else. An
// older issue of another type may be queued behind older ones in its own rung,
// so reading those the same way would report the backlog (#3415).
const unrecordedType = "Security"

// dependencyBots are the two dependency-automation authors as the search
// surface names them. An issue one of them opened is a control surface the bot
// owns, never agent work, so it is never reported; and a pull request one of
// them opened quotes upstream release notes, whose "#N" are not ours.
var dependencyBots = map[string]bool{"renovate[bot]": true, "dependabot[bot]": true}

// missingFact names the first fact an unrecorded verdict rests on that the
// record does not carry. A missing native-blocker or sub-issue summary is
// UNKNOWN: read as zero, it would tell a run to start an issue that may be
// blocked or already carried by its sub-issues.
func (i issue) missingFact() string {
	switch {
	case i.Assignees == nil:
		return "assignees"
	case i.Dependencies == nil || i.Dependencies.BlockedBy == nil:
		return "issue_dependencies_summary.blocked_by"
	case i.SubIssues == nil || i.SubIssues.Total == nil || i.SubIssues.Completed == nil:
		return "sub_issues_summary"
	}
	return ""
}

// typeName reads the issue type's name. An absent or null type is an untyped
// issue; anything else must be an object that names its type, so a shape this
// guard does not know is refused instead of read as "not Security".
func (i issue) typeName() (string, error) {
	if len(i.Type) == 0 || string(i.Type) == "null" {
		return "", nil
	}
	var named struct {
		Name string `json:"name"`
	}
	if err := json.Unmarshal(i.Type, &named); err != nil || named.Name == "" {
		return "", errors.New("unreadable type")
	}
	return named.Name, nil
}

var (
	// An HTML comment is not part of the rendered body, and one left open hides
	// everything after it.
	hiddenRE = regexp.MustCompile(`(?s)<!--.*?(-->|$)`)
	// A "Deferred: #N" line names an issue the pull request leaves alone.
	deferredRE = regexp.MustCompile(`(?mi)^[\t ]*([-*+][\t ]+)?Deferred:.*$`)
)

// mentioned reports whether an open pull request refers to the issue: a bare
// #N from its own repository, or <owner>/<repo>#N or .../<repo>/issues/N from
// anywhere. A mention counts without a closing keyword, because a pull request
// that says "Part of #N" is work on the issue too. Bodies are untrusted and
// are only matched against the issue's own name and number, and only where
// the text can be a reference of ours:
//   - a dependency bot's pull request is skipped, and so are hidden text and
//     Deferred lines;
//   - a bare # is not one that ends a repository name, an HTML entity
//     (&#8203;1403) or the text of an anchor (">#32598</a>");
//   - the number is not the start of a longer one or of a hex colour (#42a5f5);
//   - under --org a qualified reference must name that org, so another
//     owner's repository of the same name does not count.
func mentioned(item issue, pulls []issue, org string) bool {
	number := strconv.FormatInt(item.Number, 10)
	owner := `[A-Za-z0-9._-]+`
	if org != "" {
		owner = regexp.QuoteMeta(org)
	}
	end := `($|[^0-9A-Za-z_])`
	bare := regexp.MustCompile(`(^|[^A-Za-z0-9._/&>-])#` + number + end)
	qualified := regexp.MustCompile(`(?i)(^|[^A-Za-z0-9._-])` + owner + `/` + regexp.QuoteMeta(item.Repo) + `(#|/issues/)` + number + end)
	for _, pull := range pulls {
		if dependencyBots[pull.User.Login] {
			continue
		}
		text := deferredRE.ReplaceAllString(hiddenRE.ReplaceAllString(pull.Body, ""), "")
		if qualified.MatchString(text) || (strings.EqualFold(pull.Repo, item.Repo) && bare.MatchString(text)) {
			return true
		}
	}
	return false
}

// unrecorded reports whether an unlabelled issue that declares no blocker has
// gone unstarted for longer than maxAge days, and how many days it has been
// open. What clears it is what the contract treats as a visible reason not to
// start an issue: an open pull request and an open native blocker are live
// structured facts, and open sub-issues carry a decomposed one. An assignee is
// not among them: an assignment is a claim that lapses after about two hours,
// so one that stayed would hide the issue for good. A fact that cannot be read
// is UNKNOWN: it is not shown to clear the issue, nor to leave it standing.
func unrecorded(item issue, pulls []issue, org string, today time.Time, maxAge int64) (int64, bool, error) {
	// run has already refused a record whose type cannot be read.
	name, _ := item.typeName()
	if !strings.EqualFold(name, unrecordedType) || dependencyBots[item.User.Login] {
		return 0, false, nil
	}
	if missing := item.missingFact(); missing != "" {
		return 0, false, fmt.Errorf("%s#%d carries no %s, so what holds it is unproven -- UNKNOWN", item.Repo, item.Number, missing)
	}
	if *item.Dependencies.BlockedBy > 0 || *item.SubIssues.Total > *item.SubIssues.Completed || mentioned(item, pulls, org) {
		return 0, false, nil
	}
	// A creation date after today cannot be an age, as classify reads a future
	// verification or ask date.
	age, known := issueAge(item.CreatedAt, today)
	if !known || age < 0 {
		return 0, false, fmt.Errorf("%s#%d has no readable created_at on or before today, so its age is unproven -- UNKNOWN", item.Repo, item.Number)
	}
	return age, age > maxAge, nil
}

// blocked reports whether the issue carries the blocked label. An --input
// record without a labels array predates the label-independent enumeration,
// when every payload was the label:blocked search result, so it reads as
// labelled; searchIssues refuses a forge record without one.
func (i issue) blocked() bool {
	if i.Labels == nil {
		return true
	}
	for _, label := range *i.Labels {
		// Search matches labels case-insensitively, so the earlier label:blocked
		// read included a "Blocked" label; keep reading it as labelled.
		if strings.EqualFold(label.Name, "blocked") {
			return true
		}
	}
	return false
}

// "none" must be a whole word: followed by the end, whitespace, or prose
// punctuation that is itself followed by whitespace. An identifier that merely
// begins with none (none/repo#7, none.io/x, none-x) still declares a blocker.
var noBlockerRE = regexp.MustCompile(`(?i)^\*\*Blocker:\*\*[\t ]*none([\t ]|[—–]|[.,;:!]([\t ]|$)|$)`)

// declaresBlocker reports whether a visible record names a blocker. The
// "**Blocker:** none -- agent-actionable" form declares that there is none, and
// an issue carrying it is correctly unlabelled (#3142).
func declaresBlocker(line string) bool {
	return line != "" && !noBlockerRE.MatchString(line)
}

func inputIssues(raw []byte) ([]issue, error) {
	if !strings.HasPrefix(strings.TrimSpace(string(raw)), "[") {
		return nil, errors.New("payload is not a JSON array -- UNKNOWN")
	}
	var issues []issue
	if err := json.Unmarshal(raw, &issues); err != nil {
		return nil, errors.New("could not parse payload -- UNKNOWN")
	}
	for i := range issues {
		issues[i].pull = len(issues[i].PullRequest) > 0 && string(issues[i].PullRequest) != "null"
		if issues[i].pull && issues[i].parked() {
			thread, err := inputComments(issues[i])
			if err != nil {
				return nil, err
			}
			issues[i].thread = thread
		}
	}
	return issues, nil
}

// searchIssues decodes every concatenated page from gh --paginate. Count and
// completeness are independent requirements; partial results never mean zero.
// typed is set for the issue read, whose items must each carry a type key.
func searchIssues(raw []byte, typed bool) ([]issue, error) {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	expected := -1
	var issues []issue
	for {
		var page struct {
			Total      *int    `json:"total_count"`
			Incomplete *bool   `json:"incomplete_results"`
			Items      []issue `json:"items"`
		}
		err := decoder.Decode(&page)
		if err == io.EOF {
			break
		}
		if err != nil || page.Total == nil || page.Incomplete == nil || page.Items == nil || *page.Total < 0 {
			return nil, errors.New("unreadable search page -- UNKNOWN")
		}
		if *page.Incomplete {
			return nil, errors.New("search reported incomplete_results -- UNKNOWN")
		}
		if expected >= 0 && expected != *page.Total {
			return nil, errors.New("search total_count changed -- UNKNOWN")
		}
		expected = *page.Total
		for _, item := range page.Items {
			// Without labels an unlabelled issue would read as labelled and its
			// declared blocker would never be compared against the label.
			if item.Labels == nil {
				return nil, errors.New("search item without labels -- UNKNOWN")
			}
			// The forge sends the key on every issue, null when untyped. Without
			// it every issue would read as untyped and none as unrecorded.
			if typed && len(item.Type) == 0 {
				return nil, errors.New("search item without type -- UNKNOWN")
			}
			// The same holds for what an unrecorded verdict rests on: the
			// forge sends each on every issue, so one missing is a changed
			// payload, not an issue with no blocker and no sub-issue.
			if missing := item.missingFact(); typed && missing != "" {
				return nil, fmt.Errorf("search item without %s -- UNKNOWN", missing)
			}
			item.pull = !typed
			item.Repo = item.RepositoryURL[strings.LastIndex(item.RepositoryURL, "/")+1:]
			issues = append(issues, item)
		}
	}
	if expected < 0 || len(issues) != expected {
		return nil, errors.New("truncated search read -- UNKNOWN")
	}
	return issues, nil
}

// searchEndpoint reads every open issue, not only label:blocked ones: a
// declared blocker without the label is invisible to a label-filtered read
// (#3142). Search serves at most 1000 results, so a larger org fails
// searchIssues' count check rather than reading as complete.
func searchEndpoint(org string) string {
	return "search/issues?q=org:" + org + "+is:issue+state:open+archived:false&per_page=100"
}

// pullEndpoint reads every open pull request, draft or not. Their bodies say
// which issues are in flight: without them an issue whose draft has waited a
// week for review would read as unstarted (#3415).
func pullEndpoint(org string) string {
	return "search/issues?q=org:" + org + "+is:pr+state:open+archived:false&per_page=100"
}

// forgeRead is the one place the guard reaches the forge; tests replace it.
var forgeRead = func(endpoint string) ([]byte, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
	defer cancel()
	return exec.CommandContext(ctx, "gh", "api", endpoint, "--paginate").Output()
}

func load(o options, stdin io.Reader) ([]issue, error) {
	if o.input != "" {
		var raw []byte
		var err error
		if o.input == "-" {
			raw, err = io.ReadAll(stdin)
		} else {
			raw, err = os.ReadFile(o.input)
		}
		if err != nil {
			return nil, errors.New("could not read payload -- UNKNOWN")
		}
		return inputIssues(raw)
	}
	// Two reads, each complete or the whole result UNKNOWN: the issues to
	// judge, then the pull requests that show which of them are in flight.
	var records []issue
	for _, read := range []struct {
		endpoint string
		typed    bool
	}{{searchEndpoint(o.org), true}, {pullEndpoint(o.org), false}} {
		raw, err := forgeRead(read.endpoint)
		if err != nil {
			return nil, errors.New("forge read failed -- UNKNOWN, never zero")
		}
		page, err := searchIssues(raw, read.typed)
		if err != nil {
			return nil, err
		}
		records = append(records, page...)
	}
	// One more read per parked pull request, for its record comment. Each is
	// complete or the whole result is UNKNOWN, like the two reads above.
	for i := range records {
		if records[i].pull && records[i].parked() {
			thread, err := forgeComments(o.org, records[i])
			if err != nil {
				return nil, err
			}
			records[i].thread = thread
		}
	}
	return records, nil
}

func run(args []string, stdin io.Reader, stdout, stderr io.Writer) int {
	// compose writes a record and reads nothing: it never selects a forge query.
	if len(args) > 0 && args[0] == "compose" {
		return composeRun(args[1:], stdout, stderr)
	}
	// park is the only path that changes the forge, and it names its one target.
	if len(args) > 0 && args[0] == "park" {
		return parkRun(args[1:], stdout, stderr)
	}
	unknown := func(err error) int {
		// A failed diagnostic write cannot change the UNKNOWN exit status.
		_, _ = fmt.Fprintln(stderr, "blocked-label-blocker-line.sh:", err)
		return 2
	}
	emit := func(report string, code int) int {
		if report != "" {
			if _, err := io.WriteString(stdout, report); err != nil {
				return unknown(fmt.Errorf("could not write report -- UNKNOWN: %w", err))
			}
		}
		return code
	}
	o, wantsHelp, err := arguments(args)
	if err != nil {
		return unknown(err)
	}
	if wantsHelp {
		return emit(help, 0)
	}
	records, err := load(o, stdin)
	if err != nil {
		return unknown(err)
	}
	// Validate all records before emitting a partial report.
	var issues, pulls []issue
	// How many issues of the type were read is part of the verdict: a type that
	// was renamed or switched off reads as none, which is not "none unstarted".
	examined := 0
	for i, item := range records {
		if item.Repo == "" || item.Number <= 0 || strings.IndexFunc(item.Repo, unicode.IsControl) >= 0 {
			return unknown(fmt.Errorf("record %d is missing or has invalid repo or number -- UNKNOWN", i))
		}
		name, err := item.typeName()
		if err != nil {
			return unknown(fmt.Errorf("record %d has an unreadable type -- UNKNOWN", i))
		}
		if item.pull {
			pulls = append(pulls, item)
			continue
		}
		issues = append(issues, item)
		if strings.EqualFold(name, unrecordedType) {
			examined++
		}
	}
	// The parked digest is a report of its own: it reads the pull requests the
	// validation above accepted and nothing about the issues beside them.
	if o.parkedDigest {
		digest, actionable, err := parkedDigestReport(pulls, o)
		if err != nil {
			return unknown(err)
		}
		if actionable {
			return emit(digest, 1)
		}
		return emit(digest, 0)
	}
	// Builder writes cannot fail. Check the external writer once the complete
	// report is ready, so an undelivered report never returns a valid verdict.
	var report strings.Builder
	var askRows []askRow
	bad, labelled, unlabelled, parked := 0, 0, 0, 0
	for _, item := range issues {
		line := visibleRecord(item.Body)
		if !item.blocked() {
			if declaresBlocker(line) {
				bad++
				unlabelled++
				_, _ = fmt.Fprintf(&report, "%-10s %s#%d  >>%s\n", "UNLABELLED", item.Repo, item.Number, snippet(line))
				continue
			}
			// With no blocker declared, content cannot tell a skipped issue from
			// ordinary work (#3142). Its type, its age and what is in flight can
			// (#3415) -- but only when the record says what type it is.
			if len(item.Type) == 0 {
				return unknown(fmt.Errorf("%s#%d carries no type, so whether it is a %s issue is unproven -- UNKNOWN", item.Repo, item.Number, unrecordedType))
			}
			age, finding, err := unrecorded(item, pulls, o.org, o.today, o.unrecordedMaxAge)
			if err != nil {
				return unknown(err)
			}
			if finding {
				bad++
				parked++
				// "**Blocker:** none" says nothing blocks the issue. That is no
				// reason to leave it unstarted, and writing it must not be a way
				// to clear the row without starting anything.
				reason := "with no record"
				if line != "" {
					reason = "while declaring no blocker"
				}
				_, _ = fmt.Fprintf(&report, "%-10s %s#%d  opened %s, unstarted for %d day(s) %s", "UNRECORDED", item.Repo, item.Number, item.CreatedAt[:10], age, reason)
				if len(*item.Assignees) > 0 {
					_, _ = fmt.Fprint(&report, "  [assigned]")
				}
				_, _ = fmt.Fprintln(&report)
			}
			continue
		}
		labelled++
		verdict, legacy := classify(line, o.today, o.maxAge)
		if verdict == "CONFORMS" && staleVerification(line, o.today, o.verifyMaxAge) {
			verdict = "STALE"
		}
		// Include stale ask records so their current need is verified alongside
		// missing records, without treating either as proof the maintainer must act.
		if verdict == "NO-ASK" || verdict == "STALE-ASK" {
			age, known := issueAge(item.CreatedAt, o.today)
			created := ""
			if known {
				created = item.CreatedAt[:10]
			}
			askRows = append(askRows, askRow{
				repo: item.Repo, number: item.Number, created: created,
				age: age, agedKnow: known, request: askRequest(line),
				stale: verdict == "STALE-ASK", legacy: legacy,
				opaque: requestIsOpaque(line),
			})
		}
		if verdict == "CONFORMS" && o.quiet {
			continue
		}
		_, _ = fmt.Fprintf(&report, "%-10s %s#%d", verdict, item.Repo, item.Number)
		if legacy {
			_, _ = fmt.Fprint(&report, "  [legacy: no class token]")
		}
		if verdict != "CONFORMS" {
			bad++
			if line != "" {
				_, _ = fmt.Fprintf(&report, "  >>%s", snippet(line))
			}
		}
		_, _ = fmt.Fprintln(&report)
	}
	// A parked pull request is judged by its one record comment (#3424).
	parkedPulls, parkedBad := 0, 0
	for _, item := range pulls {
		if !item.parked() {
			continue
		}
		parkedPulls++
		verdict, line, legacy := parkVerdict(parkRecords(item.thread), o)
		// An authority blocker on a pull request owes the same ask as one on an
		// issue, so the digest lists it too.
		if verdict == "NO-ASK" || verdict == "STALE-ASK" {
			age, known := issueAge(item.CreatedAt, o.today)
			created := ""
			if known {
				created = item.CreatedAt[:10]
			}
			askRows = append(askRows, askRow{
				repo: item.Repo, number: item.Number, created: created,
				age: age, agedKnow: known, request: askRequest(line),
				stale: verdict == "STALE-ASK", legacy: legacy,
				opaque: requestIsOpaque(line),
			})
		}
		if verdict == "CONFORMS" && o.quiet {
			continue
		}
		_, _ = fmt.Fprintf(&report, "%-10s %s#%d  [pull request]", verdict, item.Repo, item.Number)
		if legacy {
			_, _ = fmt.Fprint(&report, "  [legacy: no class token]")
		}
		if verdict != "CONFORMS" {
			bad++
			parkedBad++
			if line != "" {
				_, _ = fmt.Fprintf(&report, "  >>%s", snippet(line))
			}
		}
		_, _ = fmt.Fprintln(&report)
	}
	// The digest replaces the verdict report for its own consumer, but never
	// the verdict: a malformed record is still a finding when no ask is owed.
	if o.askDigest {
		code := 0
		if bad > 0 {
			code = 1
		}
		digest := askDigestReport(askRows)
		if other := bad - len(askRows); other > 0 {
			digest += fmt.Sprintf("\n%d finding(s) outside this digest. Run without `--ask-digest` to inspect the verdict report.\n", other)
		}
		return emit(digest, code)
	}
	noneUnstarted := fmt.Sprintf("none of the %d open %s issue(s) read has gone unstarted for more than %d day(s) with nothing on record", examined, unrecordedType, o.unrecordedMaxAge)
	if bad > 0 {
		if !o.quiet {
			if labelledBad := bad - unlabelled - parked - parkedBad; labelledBad > 0 {
				_, _ = fmt.Fprintf(&report, "\nblocked-label-blocker-line.sh: %d of %d open blocked-labelled issue(s) need repair (missing, malformed, not re-verified recently, or an unraised authority blocker).\n", labelledBad, labelled)
			}
			if unlabelled > 0 {
				_, _ = fmt.Fprintf(&report, "\nblocked-label-blocker-line.sh: %d open issue(s) declare a blocker without the blocked label: re-verify each, then label it or unblock it.\n", unlabelled)
			}
			if parked > 0 {
				_, _ = fmt.Fprintf(&report, "\nblocked-label-blocker-line.sh: %d of the %d open %s issue(s) read have gone unstarted for more than %d day(s) with nothing on record: start each, or record what really blocks it.\n", parked, examined, unrecordedType, o.unrecordedMaxAge)
			} else {
				_, _ = fmt.Fprintf(&report, "\nblocked-label-blocker-line.sh: %s.\n", noneUnstarted)
			}
			if parkedBad > 0 {
				_, _ = fmt.Fprintf(&report, "\nblocked-label-blocker-line.sh: %d of %d open blocked-labelled pull request(s) need repair: each carries exactly one record comment, re-verified recently, or loses the label.\n", parkedBad, parkedPulls)
			}
		}
		return emit(report.String(), 1)
	}
	if !o.quiet {
		_, _ = fmt.Fprintf(&report, "\nblocked-label-blocker-line.sh: all %d open blocked-labelled issue(s) carry a conforming **Blocker:** line, no unlabelled issue declares a blocker, and %s.\n", labelled, noneUnstarted)
		_, _ = fmt.Fprintf(&report, "blocked-label-blocker-line.sh: all %d open blocked-labelled pull request(s) carry one conforming record comment.\n", parkedPulls)
	}
	return emit(report.String(), 0)
}

// snippet bounds a reported record. Bodies are untrusted: reporting a rejected
// control must not execute it in the operator's terminal.
func snippet(line string) string {
	runes := []rune(line)
	if len(runes) > 100 {
		runes = runes[:100]
	}
	return strings.Map(func(r rune) rune {
		if unicode.IsControl(r) || unicode.In(r, unicode.Cf, unicode.Zl, unicode.Zp) {
			return unicode.ReplacementChar
		}
		return r
	}, string(runes))
}

func main() {
	// Let failed stdout/stderr writes reach run's UNKNOWN handling instead of
	// terminating the process before it can return the documented exit status.
	signal.Ignore(syscall.SIGPIPE)
	os.Exit(run(os.Args[1:], os.Stdin, os.Stdout, os.Stderr))
}
