package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strconv"
	"strings"
)

// A parked pull request keeps its blocker in a comment, not in its body: a
// dependency bot rewrites the body of its own pull request, and would erase
// the record (#3424). The blocked label says the pull request is parked. The
// record is the one comment this deployment wrote that carries recordMarker on
// a line of its own, so a run finds it without reading the thread and updates
// it in place. Earlier prose about the blocker carries no marker and is never
// read as a record.
const (
	recordMarker = "<!-- pr-blocker-record -->"
	// The own-output test of the contract: the exact author and the structural
	// disclosure prefix. A comment from anyone else is data and is never a
	// record, so no commenter can park a pull request or repair a finding.
	recordAuthor     = "devantler"
	disclosurePrefix = "> 🤖 Generated by the "
)

type comment struct {
	User struct {
		Login string `json:"login"`
	} `json:"user"`
	Body string `json:"body"`
}

// parked reports whether a pull request carries the blocked label. Unlike an
// issue record, one without a labels array is not read as labelled: earlier
// --input payloads list pull requests only for the issues they mention.
func (i issue) parked() bool {
	return i.Labels != nil && i.blocked()
}

// carriesMarker reports whether recordMarker stands on a line of its own
// outside a code fence, where a comment that merely quotes it would put it.
func carriesMarker(body string) bool {
	var fence byte
	fenceLength := 0
	for _, raw := range strings.Split(body, "\n") {
		line := strings.TrimSuffix(raw, "\r")
		// Four columns of indentation render as a code block, as in visibleRecord.
		if indent := line[:len(line)-len(strings.TrimLeft(line, " \t"))]; len(indent) > 3 || strings.Contains(indent, "\t") {
			continue
		}
		line = strings.Trim(line, " \t")
		if len(line) >= 3 && (line[0] == '`' || line[0] == '~') {
			n := 0
			for n < len(line) && line[n] == line[0] {
				n++
			}
			if n >= 3 {
				if fence == 0 {
					fence, fenceLength = line[0], n
					continue
				}
				if line[0] == fence && n >= fenceLength && n == len(line) {
					fence = 0
					continue
				}
			}
		}
		if fence == 0 && line == recordMarker {
			return true
		}
	}
	return false
}

// parkRecords returns the visible blocker line of every record comment, in
// thread order. A record comment with no visible line yields an empty string,
// which classify reads as MISSING.
func parkRecords(comments []comment) []string {
	var records []string
	for _, c := range comments {
		if c.User.Login == recordAuthor && strings.HasPrefix(c.Body, disclosurePrefix) && carriesMarker(c.Body) {
			records = append(records, visibleRecord(c.Body))
		}
	}
	return records
}

// inputComments reads the comments an --input record lists for a parked pull
// request. A record that lists none is UNKNOWN: read as an empty thread, it
// would report a record that exists as MISSING.
func inputComments(item issue) ([]comment, error) {
	var comments []comment
	if !strings.HasPrefix(strings.TrimSpace(string(item.Comments)), "[") || json.Unmarshal(item.Comments, &comments) != nil {
		return nil, fmt.Errorf("pull request %s#%d carries the blocked label but no comments array, so its record is unproven -- UNKNOWN", item.Repo, item.Number)
	}
	return comments, nil
}

// pullPath names one parked pull request on the forge. The repository name
// comes from the forge's own search result and is still checked, so nothing
// but a plain name ever reaches the query.
func pullPath(org, repo string, number int64) (string, error) {
	if !orgRE.MatchString(repo) || strings.Trim(repo, ".") == "" {
		return "", fmt.Errorf("pull request %d names an unusable repository -- UNKNOWN", number)
	}
	return "repos/" + org + "/" + repo + "/issues/" + strconv.FormatInt(number, 10), nil
}

// commentEndpoint names the comment read for one parked pull request.
func commentEndpoint(org, repo string, number int64) (string, error) {
	path, err := pullPath(org, repo, number)
	return path + "/comments?per_page=100", err
}

// commentCount reads how many comments the pull request has right now. The
// search result carries a count too, but it is older than the comment read by
// the whole sweep, and a comment landing in between would fail every verdict.
func commentCount(path string, number int64) (int64, error) {
	raw, err := forgeRead(path)
	if err != nil {
		return 0, errors.New("forge read failed -- UNKNOWN, never zero")
	}
	var record struct {
		Number   int64  `json:"number"`
		Comments *int64 `json:"comments"`
	}
	// The count must be that of the pull request asked for, not of whatever
	// object answered.
	if json.Unmarshal(raw, &record) != nil || record.Number != number || record.Comments == nil || *record.Comments < 0 {
		return 0, errors.New("pull request record carries no comment count -- UNKNOWN")
	}
	return *record.Comments, nil
}

// forgeComments reads every comment of a parked pull request. gh --paginate
// prints one array per page and no total, so the count is read first and the
// thread must match it: a read that returns another number is not complete.
// One comment arriving between the two reads is ordinary, so a mismatch is
// retried once; a second one is UNKNOWN, never a missing record.
func forgeComments(org string, item issue) ([]comment, error) {
	path, err := pullPath(org, item.Repo, item.Number)
	if err != nil {
		return nil, err
	}
	for attempt := 0; attempt < 2; attempt++ {
		expected, err := commentCount(path, item.Number)
		if err != nil {
			return nil, err
		}
		raw, err := forgeRead(path + "/comments?per_page=100")
		if err != nil {
			return nil, errors.New("forge read failed -- UNKNOWN, never zero")
		}
		comments := []comment{}
		decoder := json.NewDecoder(bytes.NewReader(raw))
		for {
			var page []comment
			err := decoder.Decode(&page)
			if err == io.EOF {
				break
			}
			if err != nil || page == nil {
				return nil, fmt.Errorf("unreadable comment page for %s#%d -- UNKNOWN", item.Repo, item.Number)
			}
			comments = append(comments, page...)
		}
		if int64(len(comments)) == expected {
			return comments, nil
		}
	}
	return nil, fmt.Errorf("truncated comment read for %s#%d -- UNKNOWN", item.Repo, item.Number)
}

// parkVerdict judges a parked pull request by its record comments: exactly one
// must exist, and its line is held to the issue grammar and the same
// verification age. More than one is DUPLICATE, because the record is updated
// in place and two of them are two statements of one blocker.
func parkVerdict(records []string, o options) (verdict, line string, legacy bool) {
	if len(records) == 0 {
		return "MISSING", "", false
	}
	if len(records) > 1 {
		return "DUPLICATE", "", false
	}
	verdict, legacy = classify(records[0], o.today, o.maxAge)
	if verdict == "CONFORMS" && staleVerification(records[0], o.today, o.verifyMaxAge) {
		verdict = "STALE"
	}
	return verdict, records[0], legacy
}
