package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"strconv"
	"strings"
)

// A parked pull request keeps its blocker in a comment, not in its body: a
// dependency bot rewrites the body of its own pull request, and would erase
// the record (#3424). The blocked label says the pull request is parked. The
// record is the one comment this deployment wrote that carries recordMarker on
// a line of its own, so a run finds it without reading the thread and updates
// it in place. Earlier prose about the blocker carries no marker and is never
// read as a record.
const (
	recordMarker = "<!-- pr-blocker-record -->"
	// The own-output test of the contract: the exact author and the structural
	// disclosure prefix. A comment from anyone else is data and is never a
	// record, so no commenter can park a pull request or repair a finding.
	recordAuthor     = "devantler"
	disclosurePrefix = "> 🤖 Generated by the "
)

type comment struct {
	User struct {
		Login string `json:"login"`
	} `json:"user"`
	Body string `json:"body"`
}

// parked reports whether a pull request carries the blocked label. Unlike an
// issue record, one without a labels array is not read as labelled: earlier
// --input payloads list pull requests only for the issues they mention.
func (i issue) parked() bool {
	return i.Labels != nil && i.blocked()
}

// carriesMarker reports whether recordMarker stands on a line of its own
// outside a code fence, where a comment that merely quotes it would put it.
func carriesMarker(body string) bool {
	var fence byte
	fenceLength := 0
	for _, raw := range strings.Split(body, "\n") {
		line := strings.Trim(strings.TrimSuffix(raw, "\r"), " \t")
		if len(line) >= 3 && (line[0] == '`' || line[0] == '~') {
			n := 0
			for n < len(line) && line[n] == line[0] {
				n++
			}
			if n >= 3 {
				if fence == 0 {
					fence, fenceLength = line[0], n
					continue
				}
				if line[0] == fence && n >= fenceLength && n == len(line) {
					fence = 0
					continue
				}
			}
		}
		if fence == 0 && line == recordMarker {
			return true
		}
	}
	return false
}

// parkRecords returns the visible blocker line of every record comment, in
// thread order. A record comment with no visible line yields an empty string,
// which classify reads as MISSING.
func parkRecords(comments []comment) []string {
	var records []string
	for _, c := range comments {
		if c.User.Login == recordAuthor && strings.HasPrefix(c.Body, disclosurePrefix) && carriesMarker(c.Body) {
			records = append(records, visibleRecord(c.Body))
		}
	}
	return records
}

// inputComments reads the comments an --input record lists for a parked pull
// request. A record that lists none is UNKNOWN: read as an empty thread, it
// would report a record that exists as MISSING.
func inputComments(item issue) ([]comment, error) {
	var comments []comment
	if !strings.HasPrefix(strings.TrimSpace(string(item.Comments)), "[") || json.Unmarshal(item.Comments, &comments) != nil {
		return nil, fmt.Errorf("pull request %s#%d carries the blocked label but no comments array, so its record is unproven -- UNKNOWN", item.Repo, item.Number)
	}
	return comments, nil
}

// commentEndpoint names the comment read for one parked pull request. The
// repository name comes from the forge's own search result and is still
// checked, so nothing but a plain name ever reaches the query.
func commentEndpoint(org, repo string, number int64) (string, error) {
	if !orgRE.MatchString(repo) || strings.Trim(repo, ".") == "" {
		return "", fmt.Errorf("pull request %d names an unusable repository -- UNKNOWN", number)
	}
	return "repos/" + org + "/" + repo + "/issues/" + strconv.FormatInt(number, 10) + "/comments?per_page=100", nil
}

// forgeComments reads every comment of a parked pull request. gh --paginate
// prints one array per page; the search result's comment count says how many
// there are, so a read that returns another number is UNKNOWN, never a
// missing record.
func forgeComments(org string, item issue) ([]comment, error) {
	count := strings.TrimSpace(string(item.Comments))
	expected, err := strconv.ParseInt(count, 10, 64)
	if err != nil || expected < 0 {
		return nil, fmt.Errorf("pull request %s#%d carries no comment count -- UNKNOWN", item.Repo, item.Number)
	}
	endpoint, err := commentEndpoint(org, item.Repo, item.Number)
	if err != nil {
		return nil, err
	}
	raw, err := forgeRead(endpoint)
	if err != nil {
		return nil, errors.New("forge read failed -- UNKNOWN, never zero")
	}
	comments := []comment{}
	decoder := json.NewDecoder(bytes.NewReader(raw))
	for {
		var page []comment
		err := decoder.Decode(&page)
		if err == io.EOF {
			break
		}
		if err != nil || page == nil {
			return nil, fmt.Errorf("unreadable comment page for %s#%d -- UNKNOWN", item.Repo, item.Number)
		}
		comments = append(comments, page...)
	}
	if int64(len(comments)) != expected {
		return nil, fmt.Errorf("truncated comment read for %s#%d -- UNKNOWN", item.Repo, item.Number)
	}
	return comments, nil
}

// parkVerdict judges a parked pull request by its record comments: exactly one
// must exist, and its line is held to the issue grammar and the same
// verification age. More than one is DUPLICATE, because the record is updated
// in place and two of them are two statements of one blocker.
func parkVerdict(records []string, o options) (verdict, line string, legacy bool) {
	if len(records) == 0 {
		return "MISSING", "", false
	}
	if len(records) > 1 {
		return "DUPLICATE", "", false
	}
	verdict, legacy = classify(records[0], o.today, o.maxAge)
	if verdict == "CONFORMS" && staleVerification(records[0], o.today, o.verifyMaxAge) {
		verdict = "STALE"
	}
	return verdict, records[0], legacy
}
