package main

import (
	"encoding/json"
	"errors"
	"strconv"
	"strings"
	"testing"
)

const (
	goodLine   = "**Blocker:** owner/repo#7 | upstream | last-verified 2026-09-01: open"
	recordHead = "> 🤖 Generated by the Agentic Engineer\n\n" + recordMarker + "\n"
)

func commentJSON(t *testing.T, login, body string) string {
	t.Helper()
	raw, err := json.Marshal(map[string]any{"user": map[string]string{"login": login}, "body": body})
	if err != nil {
		t.Fatal(err)
	}
	return string(raw)
}

// parkedPull is an --input pull request carrying the blocked label and the
// given comments. Its body declares a different blocker, which must never be
// read: the record of a pull request is its comment.
func parkedPull(comments ...string) string {
	return `[{"repo":"p","number":5,"pull_request":{},"labels":[{"name":"blocked"}],"body":"**Blocker:** body/only#1","comments":[` + strings.Join(comments, ",") + `]}]`
}

func TestParkedPullRequestIsJudgedByItsOneRecordComment(t *testing.T) {
	record := commentJSON(t, "devantler", recordHead+goodLine)
	for _, tc := range []struct {
		name     string
		comments []string
		code     int
		want     string
	}{
		{"one conforming record", []string{record}, 0, "all 1 open blocked-labelled pull request(s) carry one conforming record comment"},
		{"the record among unrelated comments", []string{commentJSON(t, "devantler", "> 🤖 Generated by the Agentic Engineer\n\nStatus."), record, commentJSON(t, "someone", "thanks")}, 0, "all 1 open"},
		{"no comment at all", nil, 1, "MISSING    p#5  [pull request]"},
		{"a blocker line without the marker", []string{commentJSON(t, "devantler", "> 🤖 Generated by the Agentic Engineer\n\n"+goodLine)}, 1, "MISSING    p#5  [pull request]"},
		{"the marker only inside a code fence", []string{commentJSON(t, "devantler", "> 🤖 Generated by the Agentic Engineer\n\n```\n"+recordMarker+"\n```\n"+goodLine)}, 1, "MISSING    p#5  [pull request]"},
		{"the marker inside other text", []string{commentJSON(t, "devantler", "> 🤖 Generated by the Agentic Engineer\n\nsee "+recordMarker+" here\n"+goodLine)}, 1, "MISSING    p#5  [pull request]"},
		{"a record from another author", []string{commentJSON(t, "someone", recordHead+goodLine)}, 1, "MISSING    p#5  [pull request]"},
		{"a record from an author whose name only starts the same", []string{commentJSON(t, "devantler-bot", recordHead+goodLine)}, 1, "MISSING    p#5  [pull request]"},
		{"a record without the disclosure line first", []string{commentJSON(t, "devantler", recordMarker+"\n"+goodLine)}, 1, "MISSING    p#5  [pull request]"},
		{"a record comment with no blocker line", []string{commentJSON(t, "devantler", recordHead+"nothing here")}, 1, "MISSING    p#5  [pull request]"},
		{"two record comments", []string{record, record}, 1, "DUPLICATE  p#5  [pull request]"},
		{"a malformed line", []string{commentJSON(t, "devantler", recordHead+"**Blocker:** owner/repo#7")}, 1, "MALFORMED  p#5  [pull request]  >>**Blocker:** owner/repo#7"},
		{"an authority blocker nobody was asked about", []string{commentJSON(t, "devantler", recordHead+"**Blocker:** approve the upgrade | authority | last-verified 2026-09-01: waiting")}, 1, "NO-ASK     p#5  [pull request]"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			code, out := runInput(t, parkedPull(tc.comments...))
			if code != tc.code || !strings.Contains(out, tc.want) {
				t.Fatalf("code=%d, want %d and %q; out:\n%s", code, tc.code, tc.want, out)
			}
			if strings.Contains(out, "body/only") || strings.Contains(out, "UNLABELLED") {
				t.Fatalf("the pull request's body was read as a record; out:\n%s", out)
			}
			if tc.code == 1 && !strings.Contains(out, "1 of 1 open blocked-labelled pull request(s) need repair") {
				t.Fatalf("no pull-request summary; out:\n%s", out)
			}
		})
	}
}

// The label is what parks a pull request. Without it nothing is judged,
// whatever the comments say, so an unlabelled pull request is always worked.
func TestUnlabelledPullRequestIsNotParked(t *testing.T) {
	for name, labels := range map[string]string{"an empty label set": `"labels":[],`, "another label": `"labels":[{"name":"dependencies"}],`, "no labels array": ""} {
		t.Run(name, func(t *testing.T) {
			code, out := runInput(t, `[{"repo":"p","number":5,"pull_request":{},`+labels+`"body":"x","comments":[`+commentJSON(t, "devantler", recordHead+"**Blocker:** broken")+`]}]`)
			if code != 0 || !strings.Contains(out, "all 0 open blocked-labelled pull request(s)") {
				t.Fatalf("code=%d out:\n%s", code, out)
			}
		})
	}
}

func TestParkedPullRequestRecordGoesStale(t *testing.T) {
	payload := parkedPull(commentJSON(t, "devantler", recordHead+goodLine))
	if code, out := runInput(t, payload, "--today", "2026-09-09", "--verify-max-age-days", "7"); code != 1 || !strings.Contains(out, "STALE      p#5  [pull request]") {
		t.Fatalf("code=%d out:\n%s", code, out)
	}
	// CONTROL: the same record on the last day inside the bound conforms.
	if code, out := runInput(t, payload, "--today", "2026-09-08", "--verify-max-age-days", "7"); code != 0 {
		t.Fatalf("code=%d out:\n%s", code, out)
	}
}

func TestQuietPrintsOnlyParkedFindings(t *testing.T) {
	if code, out := runInput(t, parkedPull(commentJSON(t, "devantler", recordHead+goodLine)), "--quiet"); code != 0 || out != "" {
		t.Fatalf("code=%d out:\n%s", code, out)
	}
	if code, out := runInput(t, parkedPull(), "--quiet"); code != 1 || out != "MISSING    p#5  [pull request]\n" {
		t.Fatalf("code=%d out:\n%q", code, out)
	}
}

// A parked pull request whose comments were not supplied is UNKNOWN: read as
// an empty thread it would report an existing record as MISSING.
func TestParkedPullRequestWithoutCommentsIsUnknown(t *testing.T) {
	for name, comments := range map[string]string{"no key": "", "a count": `,"comments":3`, "null": `,"comments":null`, "a string": `,"comments":"[]"`, "an object": `,"comments":{}`} {
		t.Run(name, func(t *testing.T) {
			code, out := runInput(t, `[{"repo":"p","number":5,"pull_request":{},"labels":[{"name":"blocked"}],"body":"x"`+comments+`}]`)
			if code != 2 || !strings.Contains(out, "no comments array") || strings.Contains(out, "MISSING") {
				t.Fatalf("code=%d out:\n%s", code, out)
			}
		})
	}
}

// A finding on a pull request is outside the ask digest, and still fails it.
func TestParkedFindingStillFailsTheAskDigest(t *testing.T) {
	code, out := runInput(t, parkedPull(), "--ask-digest")
	if code != 1 || !strings.Contains(out, "1 finding(s) outside this digest") {
		t.Fatalf("code=%d out:\n%s", code, out)
	}
}

func forgeParkedPull(t *testing.T, repo string) string {
	t.Helper()
	raw, err := json.Marshal(map[string]any{
		"repository_url": "https://api.github.com/repos/o/" + repo, "number": 900, "labels": []any{map[string]string{"name": "blocked"}},
		"pull_request": map[string]any{}, "user": map[string]string{"login": "renovate[bot]"}, "body": "bump",
		"created_at": "2026-08-01T00:00:00Z", "comments": 99, // stale by design: never read
	})
	if err != nil {
		t.Fatal(err)
	}
	return string(raw)
}

// attempt is what the forge answers for one try at a parked pull request's
// thread: its record, carrying the comment count, and then its comment pages.
type attempt struct {
	record, pages string
	pagesErr      error
}

func counted(n int) string { return `{"number":900,"comments":` + strconv.Itoa(n) + `}` }

// serveParked answers the two searches and then, try by try, the count and
// comment reads of platform#900. It returns how many comment reads happened.
func serveParked(t *testing.T, pull string, attempts ...attempt) *int {
	t.Helper()
	reads, try := 0, 0
	original := forgeRead
	t.Cleanup(func() { forgeRead = original })
	forgeRead = func(endpoint string) ([]byte, error) {
		switch endpoint {
		case searchEndpoint("o"):
			return []byte(searchPage(freshSecurityIssue)), nil
		case pullEndpoint("o"):
			return []byte(searchPage(pull)), nil
		case "repos/o/platform/issues/900":
			if try >= len(attempts) {
				t.Errorf("unexpected try %d", try+1)
				return nil, errors.New("unexpected try")
			}
			return []byte(attempts[try].record), nil
		case "repos/o/platform/issues/900/comments?per_page=100":
			reads++
			current := attempts[try]
			try++
			return []byte(current.pages), current.pagesErr
		}
		t.Errorf("unexpected read %q", endpoint)
		return nil, errors.New("unexpected read")
	}
	return &reads
}

func TestOrgReadJudgesAParkedPullRequestByItsComments(t *testing.T) {
	record := commentJSON(t, "devantler", recordHead+goodLine)
	other := commentJSON(t, "renovate[bot]", "rebased")
	pull := forgeParkedPull(t, "platform")
	t.Run("a record on the second page conforms", func(t *testing.T) {
		reads := serveParked(t, pull, attempt{counted(2), "[" + other + "]\n[" + record + "]", nil})
		if code, out := runOrg(t); code != 0 || *reads != 1 || !strings.Contains(out, "all 1 open blocked-labelled pull request(s)") {
			t.Fatalf("code=%d reads=%d out:\n%s", code, *reads, out)
		}
	})
	t.Run("no record is a finding", func(t *testing.T) {
		serveParked(t, pull, attempt{counted(1), "[" + other + "]", nil})
		if code, out := runOrg(t); code != 1 || !strings.Contains(out, "MISSING    platform#900  [pull request]") {
			t.Fatalf("code=%d out:\n%s", code, out)
		}
	})
	t.Run("no comments at all is a finding, from a complete empty read", func(t *testing.T) {
		serveParked(t, pull, attempt{counted(0), "[]", nil})
		if code, out := runOrg(t); code != 1 || !strings.Contains(out, "MISSING    platform#900  [pull request]") {
			t.Fatalf("code=%d out:\n%s", code, out)
		}
	})
	// A comment that lands between the count and the thread is ordinary: the
	// second try sees both agree. The first try alone would read MISSING.
	t.Run("a comment arriving between the two reads is retried once", func(t *testing.T) {
		reads := serveParked(t, pull, attempt{counted(1), "[" + other + "," + record + "]", nil}, attempt{counted(2), "[" + other + "," + record + "]", nil})
		if code, out := runOrg(t); code != 0 || *reads != 2 {
			t.Fatalf("code=%d reads=%d out:\n%s", code, *reads, out)
		}
	})
	// Each of these hands back the conforming record, so a guard that ignored
	// the defect would print a clean sweep.
	one := "[" + record + "]"
	for _, tc := range []struct {
		name     string
		attempts []attempt
		want     string
	}{
		{"the comment read fails after printing the record", []attempt{{counted(1), one, errors.New("exit status 1")}}, "forge read failed -- UNKNOWN"},
		{"fewer comments than counted, twice", []attempt{{counted(2), one, nil}, {counted(2), one, nil}}, "truncated comment read"},
		{"more comments than counted, twice", []attempt{{counted(0), one, nil}, {counted(0), one, nil}}, "truncated comment read"},
		{"an empty read where comments were counted, twice", []attempt{{counted(1), "", nil}, {counted(1), "", nil}}, "truncated comment read"},
		{"a page that is not an array", []attempt{{counted(1), `{"message":"Not Found"}`, nil}}, "unreadable comment page"},
		{"a null page", []attempt{{counted(1), "null", nil}}, "unreadable comment page"},
		{"a record with no comment count", []attempt{{`{"number":900}`, one, nil}}, "carries no comment count"},
		{"a record of another pull request", []attempt{{`{"number":901,"comments":1}`, one, nil}}, "carries no comment count"},
		{"a record with no number", []attempt{{`{"comments":1}`, one, nil}}, "carries no comment count"},
		{"a record whose comment count is null", []attempt{{`{"number":900,"comments":null}`, one, nil}}, "carries no comment count"},
		{"a record whose comment count is a string", []attempt{{`{"number":900,"comments":"1"}`, one, nil}}, "carries no comment count"},
		{"a record whose comment count is negative", []attempt{{`{"number":900,"comments":-1}`, one, nil}}, "carries no comment count"},
		{"a record that is not JSON", []attempt{{"", one, nil}}, "carries no comment count"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			serveParked(t, pull, tc.attempts...)
			if code, out := runOrg(t); code != 2 || !strings.Contains(out, tc.want) || strings.Contains(out, "pull request(s)") {
				t.Fatalf("code=%d, want 2 and %q; out:\n%s", code, tc.want, out)
			}
		})
	}
}

// The count read fails closed like every other read.
func TestOrgReadFailsClosedOnTheCountRead(t *testing.T) {
	original := forgeRead
	t.Cleanup(func() { forgeRead = original })
	forgeRead = func(endpoint string) ([]byte, error) {
		switch endpoint {
		case searchEndpoint("o"):
			return []byte(searchPage()), nil
		case pullEndpoint("o"):
			return []byte(searchPage(forgeParkedPull(t, "platform"))), nil
		case "repos/o/platform/issues/900":
			return []byte(counted(0)), errors.New("exit status 1")
		}
		return []byte("[]"), nil
	}
	if code, out := runOrg(t); code != 2 || !strings.Contains(out, "forge read failed -- UNKNOWN") {
		t.Fatalf("code=%d out:\n%s", code, out)
	}
}

// An authority blocker on a parked pull request owes an ask, and the digest
// must list it instead of saying no ask is owed.
func TestAskDigestListsAParkedPullRequest(t *testing.T) {
	for verdict, line := range map[string]string{
		"NO-ASK":    "**Blocker:** approve the upgrade | authority | last-verified 2026-09-01: waiting",
		"STALE-ASK": "**Blocker:** approve the upgrade | authority | last-verified 2026-09-01: waiting | asked slack 2026-08-01",
	} {
		t.Run(verdict, func(t *testing.T) {
			code, out := runInput(t, parkedPull(commentJSON(t, "devantler", recordHead+line)), "--ask-digest")
			if code != 1 || !strings.Contains(out, "p#​5") || !strings.Contains(out, "approve the upgrade") || strings.Contains(out, "no declared authority blocker") || strings.Contains(out, "outside this digest") {
				t.Fatalf("code=%d out:\n%s", code, out)
			}
		})
	}
}

// The marker counts only where it renders as nothing: four columns in, it is
// a code block that quotes the marker.
func TestMarkerIndentation(t *testing.T) {
	for body, want := range map[string]bool{
		recordMarker:                   true,
		"   " + recordMarker:           true,
		recordMarker + "  \r":          true,
		"    " + recordMarker:          false,
		" \t" + recordMarker:           false,
		"\t" + recordMarker:            false,
		"~~~\n" + recordMarker:         false,
		"```\nx\n```\n" + recordMarker: true,
	} {
		if got := carriesMarker(body); got != want {
			t.Errorf("carriesMarker(%q) = %v, want %v", body, got, want)
		}
	}
}

// Only a parked pull request costs a comment read.
func TestOrgReadSkipsCommentsOfUnparkedPullRequests(t *testing.T) {
	reads := serveParked(t, forgePull("platform", "devantler", "x"))
	if code, out := runOrg(t); code != 0 || *reads != 0 || !strings.Contains(out, "all 0 open blocked-labelled pull request(s)") {
		t.Fatalf("code=%d reads=%d out:\n%s", code, *reads, out)
	}
}

// The repository name reaches a forge path, so only a plain name is used.
func TestCommentEndpointRefusesAnUnusableRepository(t *testing.T) {
	for _, repo := range []string{"", ".", "..", "a/b", "a b", "a?b", "a#b", "a%2Fb"} {
		if endpoint, err := commentEndpoint("o", repo, 1); err == nil {
			t.Errorf("repo %q produced %q", repo, endpoint)
		}
	}
	if endpoint, err := commentEndpoint("o", ".github", 12); err != nil || endpoint != "repos/o/.github/issues/12/comments?per_page=100" {
		t.Errorf("endpoint=%q err=%v", endpoint, err)
	}
}

// The help is the only definition a caller has of where the record lives.
func TestHelpDefinesThePullRequestRecord(t *testing.T) {
	for _, want := range []string{recordMarker, recordAuthor, strings.TrimSpace(disclosurePrefix), "DUPLICATE", `"comments"`} {
		if !strings.Contains(help, want) {
			t.Errorf("help does not mention %q", want)
		}
	}
}
