package main

import (
	"strings"
	"testing"
)

// The two disclosure lines exactly as they appear in real bodies.
const (
	realInteractiveLine = "🤖 Generated with [Claude Code](https://claude.com/claude-code)"
	realRoutineLine     = "> 🤖 Generated by the Agentic Engineer"
)

func TestClassify(t *testing.T) {
	tests := []struct {
		name string
		body string
		want string
	}{
		// --- The regression this guard exists to prevent -------------------
		//
		// Every case below was misclassified `none` in production by a
		// body-start-anchored matcher, on a live PR that was the maintainer's.
		{
			name: "interactive marker on the LAST line",
			body: "## Summary\n\nSome change.\n\n" + realInteractiveLine,
			want: Interactive,
		},
		{
			name: "interactive marker on the last line, blockquoted",
			body: "## Summary\n\nSome change.\n\n> " + realInteractiveLine,
			want: Interactive,
		},
		{
			name: "interactive marker in the MIDDLE of the body",
			body: "## Summary\n\n" + realInteractiveLine + "\n\nMore prose.\n",
			want: Interactive,
		},
		{
			name: "routine marker under the org template's ### Motivation heading",
			body: "### Motivation\n\n" + realRoutineLine + "\n\nWhy this change.\n",
			want: Routine,
		},
		{
			name: "routine marker under a `-` bullet, as the org PR template emits",
			body: "### Motivation\n\n- " + realRoutineLine[2:] + "\n",
			want: Routine,
		},
		// A TAB after the list marker. `-\t` is recognised as a marker, so the
		// tab must be consumed with it — otherwise it survives into the content
		// and a real disclosure reads as `none`.
		{
			name: "routine marker under a `-` bullet separated by a TAB",
			body: "### Motivation\n\n-\t" + realRoutineLine[2:] + "\n",
			want: Routine,
		},
		{
			name: "interactive marker under a `*` bullet separated by a TAB",
			body: "## Summary\n\n*\t" + realInteractiveLine + "\n",
			want: Interactive,
		},
		{
			name: "interactive marker under a `-` bullet separated by a TAB",
			body: "## Summary\n\n-\t" + realInteractiveLine + "\n",
			want: Interactive,
		},

		// --- Placements that already worked --------------------------------
		{
			name: "interactive marker on line 1",
			body: "> " + realInteractiveLine + " in an interactive session with @devantler.\n\nBody.",
			want: Interactive,
		},
		{
			name: "routine marker on line 1",
			body: realRoutineLine + "\n\n## Why\n\nBecause.",
			want: Routine,
		},

		// --- Precedence ----------------------------------------------------
		{
			name: "both literals present — interactive wins wherever it sits",
			body: realRoutineLine + "\n\n## Why\n\nBecause.\n\n" + realInteractiveLine,
			want: Interactive,
		},
		{
			name: "both literals present — interactive first",
			body: realInteractiveLine + "\n\n" + realRoutineLine,
			want: Interactive,
		},

		// --- The opposite failure: a bare substring match ------------------
		//
		// A PR *about* this convention quotes both literals in prose. A
		// substring matcher parks it HANDS-OFF forever, because its body never
		// changes.
		{
			name: "interactive literal quoted mid-sentence does not match",
			body: "## Why\n\nA body carrying `Generated with [Claude Code]` classifies interactive.\n",
			want: None,
		},
		{
			name: "routine literal quoted mid-sentence does not match",
			body: "## Why\n\nWe match `Generated by the ` as a structural fragment.\n",
			want: None,
		},
		{
			name: "both literals quoted mid-sentence — still none",
			body: "Grep `Generated by the` (routine) vs `Generated with [Claude Code]` (interactive).\n",
			want: None,
		},

		// --- Indented code blocks carry no marker --------------------------
		{
			name: "interactive marker indented four spaces is an example, not a marker",
			body: "## Example\n\n    " + realInteractiveLine + "\n",
			want: None,
		},
		{
			name: "interactive marker indented by a leading tab is an example",
			body: "## Example\n\n\t" + realInteractiveLine + "\n",
			want: None,
		},
		{
			name: "three spaces is alignment, not a code block",
			body: "## Summary\n\n   " + realInteractiveLine + "\n",
			want: Interactive,
		},
		{
			name: "four spaces INSIDE a blockquote is still a code block",
			body: "## Example\n\n>     " + realInteractiveLine + "\n",
			want: None,
		},

		// --- Actor-word independence ---------------------------------------
		//
		// The actor was renamed twice. A matcher keyed to one spelling
		// silently reclassifies every PR authored under the others.
		{
			name: "legacy Daily AI Engineer actor still reads routine",
			body: "> 🤖 Generated by the Daily AI Engineer\n\nBody.",
			want: Routine,
		},
		{
			name: "legacy Daily AI Assistant actor still reads routine",
			body: "> 🤖 Generated by the Daily AI Assistant\n\nBody.",
			want: Routine,
		},

		// --- Containers ----------------------------------------------------
		{
			name: "nested blockquote, as when an agent quotes another agent",
			body: "## Summary\n\n> > " + realInteractiveLine + "\n",
			want: Interactive,
		},
		{
			name: "marker without the emoji prefix",
			body: "> Generated by the Agentic Engineer\n\nBody.",
			want: Routine,
		},
		{
			name: "CRLF line endings",
			body: "## Summary\r\n\r\n" + realInteractiveLine + "\r\n",
			want: Interactive,
		},

		// --- Neither -------------------------------------------------------
		{
			name: "empty body",
			body: "",
			want: None,
		},
		{
			name: "ordinary body with no disclosure",
			body: "## Why\n\nA human wrote this by hand.\n",
			want: None,
		},
		{
			name: "bolded disclosure is not a disclosure",
			body: "**Generated with [Claude Code]**\n",
			want: None,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if got := Classify(tc.body); got != tc.want {
				t.Errorf("Classify() = %q, want %q\nbody:\n%s", got, tc.want, tc.body)
			}
		})
	}
}

// TestBodyStartAnchorWouldFail pins the regression rather than merely
// describing it: it asserts that the production defect — classifying only when
// the marker sits at the start of the body — is actually caught by this suite.
//
// If a future change reintroduces body-start anchoring, the cases collected
// here are the ones that break.
func TestBodyStartAnchorWouldFail(t *testing.T) {
	// A body-start-anchored implementation, i.e. the shipped defect.
	bodyStartClassify := func(body string) string {
		first := strings.SplitN(body, "\n", 2)[0]
		switch {
		case lineCarries(first, interactiveLiteral):
			return Interactive
		case lineCarries(first, routineLiteral):
			return Routine
		default:
			return None
		}
	}

	// Reproduced from the live PRs measured on 2026-08-11: the marker is the
	// last line of the body on all four, and each is the maintainer's work.
	maintainerBodies := []string{
		"## Summary\n\nSome change.\n\n" + realInteractiveLine,
		"## Summary\n\nSome change.\n\n> " + realInteractiveLine,
		"### Motivation\n\nWhy.\n\n" + realInteractiveLine + "\n",
	}

	for _, body := range maintainerBodies {
		if got := bodyStartClassify(body); got != None {
			t.Fatalf("test setup is wrong: the body-start defect should report %q here, got %q", None, got)
		}
		if got := Classify(body); got != Interactive {
			t.Errorf("Classify() = %q, want %q — the body-start regression is NOT pinned", got, Interactive)
		}
	}
}
