// Command pr-ownership-disclosure classifies a pull-request body as the
// maintainer's hand-driven work, the routine's own output, or neither.
//
// A run uses this to decide whether a `devantler` PR may be acted on. The
// maintainer drives Claude Code interactively, so his PRs share the routine's
// author and branch namespace; the body's disclosure marker is the only signal
// that separates them.
//
// Three verdicts:
//
//	interactive — carries `Generated with [Claude Code]`. HANDS-OFF.
//	routine     — carries `Generated by the` and no interactive marker.
//	none        — neither. Genuinely unknown; NOT a synonym for either.
//
// `interactive` wins when both are present. The asymmetry is deliberate:
// reading the maintainer's PR as the routine's licenses an unrequested mutation
// of his work, while reading the routine's as his merely parks a PR a later run
// picks up.
//
// `routine` is corroborating, never decisive — the routine disclosure also
// appears on maintainer-interactive PRs, so the caller still weighs it against
// its own creation record.
//
// # Why a marker is matched as a LINE, anywhere in the body
//
// Anchoring at the start of the body is a measured fail-open. Marker placement
// varies: some bodies open with it, some close with it, and the org PR template
// puts it under a `### Motivation` heading and a `-` bullet. A body-start check
// reports `none` for every one of those — and `none` on the maintainer's PR is
// the expensive direction.
//
// A bare substring match fails the other way: a PR *about* this convention
// quotes the literal in prose and would park itself HANDS-OFF forever, since
// its body never changes.
//
// So a marker counts when a line, after its Markdown container prefixes are
// stripped, BEGINS with the literal. That matches every real placement and
// rejects mid-sentence quotation.
//
// There is no fenced-code suppression. A body that fences an example of the
// interactive literal classifies `interactive` and parks itself — the cheap
// direction, whose measured incidence is zero. The expensive direction is a
// real marker swallowed by a mis-parsed fence, which drives the maintainer's PR.
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strings"
)

// Verdicts.
const (
	Interactive = "interactive"
	Routine     = "routine"
	None        = "none"
)

// The two literals. Neither carries Markdown emphasis, so a bolded form is not
// a disclosure and is deliberately not matched.
//
// The routine marker is matched as a STRUCTURAL fragment, never by actor word:
// the actor has been renamed twice (Daily AI Assistant -> Daily AI Engineer ->
// Agentic Engineer), and a matcher keyed to one spelling silently reclassifies
// every PR authored under the others.
const (
	interactiveLiteral = "Generated with [Claude Code]"
	routineLiteral     = "Generated by the "
)

// codeBlockIndent is the indentation at which GitHub renders a line as an
// indented code block, which carries no marker. It is also what limits
// container alignment to three spaces — a fourth is a code block instead.
const codeBlockIndent = 4

// expandLeadingTabs rewrites leading tabs as spaces to the next 4-column tab
// stop, so indentation can be measured in spaces alone. A tab is not a fixed
// number of spaces: after `>` it advances to column 4, but at line start it
// advances to column 4 from column 0. Expanding first is what lets the
// container and indent rules below be written in plain space counts.
func expandLeadingTabs(line string) string {
	var b strings.Builder
	col := 0
	for i := 0; i < len(line); i++ {
		switch line[i] {
		case '\t':
			width := codeBlockIndent - (col % codeBlockIndent)
			b.WriteString(strings.Repeat(" ", width))
			col += width
		case ' ':
			b.WriteByte(' ')
			col++
		default:
			b.WriteString(line[i:])
			return b.String()
		}
	}
	return b.String()
}

// stripContainers removes Markdown container prefixes — blockquote `>` markers
// and `-`/`*` list markers — from a line, keeping whatever indentation remains
// inside them. It reports false when the line's indentation at the current
// depth opens an indented code block, which carries no marker.
//
// Containers nest: the org PR template's disclosure sits under a `-` bullet,
// and an agent quoting another agent produces `> > `. A container-blind matcher
// misses both.
func stripContainers(line string) (string, bool) {
	line = expandLeadingTabs(line)

	for {
		indent := 0
		for indent < len(line) && line[indent] == ' ' {
			indent++
		}
		if indent >= codeBlockIndent {
			// An indented code block. Its content is an example, not the
			// body's own voice. This is also what bounds container alignment
			// to three spaces: a fourth has already returned here.
			return "", false
		}
		if indent >= len(line) {
			// Nothing but whitespace.
			return "", true
		}

		rest := line[indent:]
		switch {
		case strings.HasPrefix(rest, ">"),
			strings.HasPrefix(rest, "- "), strings.HasPrefix(rest, "* "),
			strings.HasPrefix(rest, "-\t"), strings.HasPrefix(rest, "*\t"):
			// A container marker; consumed below.
		default:
			return rest, true
		}

		// Consume the marker and at most ONE following space or tab. A second
		// space is content indentation and must survive, so that four of them
		// still open an indented code block inside the container.
		//
		// Expand tabs for EVERY marker, not just `>`: the org PR template's
		// disclosure sits under a `-` bullet, and a `-\t` separator would
		// otherwise leave the tab in the content, so `lineCarries` would see a
		// leading tab and report `none` on a real disclosure.
		rest = expandLeadingTabs(rest[1:])
		if strings.HasPrefix(rest, " ") {
			rest = rest[1:]
		}
		line = rest
	}
}

// lineCarries reports whether a line, once its containers are stripped, BEGINS
// with the given literal.
//
// A leading 🤖 is skipped: both disclosures are conventionally emoji-prefixed
// (`> 🤖 Generated by the Agentic Engineer`), and the emoji is decoration
// rather than part of the literal.
func lineCarries(line, literal string) bool {
	content, ok := stripContainers(line)
	if !ok {
		return false
	}
	content = strings.TrimPrefix(content, "🤖")
	content = strings.TrimLeft(content, " ")
	return strings.HasPrefix(content, literal)
}

// Classify returns the verdict for a PR body.
func Classify(body string) string {
	body = strings.ReplaceAll(body, "\r\n", "\n")

	foundRoutine := false
	for _, line := range strings.Split(body, "\n") {
		if lineCarries(line, interactiveLiteral) {
			// Interactive wins outright; no need to read further.
			return Interactive
		}
		if lineCarries(line, routineLiteral) {
			foundRoutine = true
		}
	}
	if foundRoutine {
		return Routine
	}
	return None
}

func usage() {
	fmt.Fprint(os.Stderr, `Usage:
  pr-ownership-disclosure --input <file>|-

Classifies a pull-request body as the maintainer's interactive work, the
routine's own output, or neither. Prints one of:

  interactive   carries `+"`Generated with [Claude Code]`"+` — HANDS-OFF
  routine       carries `+"`Generated by the`"+` and no interactive marker
  none          neither; genuinely unknown

Exit codes:
  0  classified (verdict on stdout)
  2  usage or unreadable input
`)
}

func main() {
	input := flag.String("input", "", "file containing the PR body, or - for stdin")
	flag.Usage = usage
	flag.Parse()

	if *input == "" || flag.NArg() > 0 {
		usage()
		os.Exit(2)
	}

	var (
		data []byte
		err  error
	)
	if *input == "-" {
		data, err = io.ReadAll(os.Stdin)
	} else {
		data, err = os.ReadFile(*input)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "pr-ownership-disclosure: %v\n", err)
		os.Exit(2)
	}

	fmt.Println(Classify(string(data)))
}
