#!/usr/bin/env bash
# Hermetic test for bugbot-request-marker.sh (monorepo#2721).
#
# Each rule the check enforces has a positive case and a negative control, so a
# check that passes everything, or refuses everything, cannot make this green.
# The end-to-end case builds the pair with the real review-request composer, so
# the protocol the composer emits and the protocol this check accepts cannot
# drift apart. `gh` is stubbed on PATH: no network, no token.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
check="${script_dir}/bugbot-request-marker.sh"
composer="${script_dir}/review-request-comment.sh"
tmp="$(mktemp -d)"
bugbot_marker_test_finished=0
cleanup() {
  local rc=$?
  rm -rf "$tmp"
  if [ "$bugbot_marker_test_finished" != 1 ] && [ "$rc" -eq 0 ]; then
    echo "bugbot-request-marker.test: aborted before finishing; reporting failure rather than a clean pass" >&2
    rc=1
  fi
  exit "$rc"
}
trap cleanup EXIT

sha='0123456789abcdef0123456789abcdef01234567'
old='89abcdef0123456789abcdef0123456789abcdef'
disclosure='> 🤖 Generated by the Agentic Engineer'
marker="<!-- review-request-head: ${sha} provider=bugbot -->"
issue_a='https://api.github.com/repos/o/r/issues/1'
issue_b='https://api.github.com/repos/o/r/issues/2'
fails=0

bad() {
  echo "FAIL: $*" >&2
  fails=$((fails + 1))
}

# comment <id> <login> <issue_url> <body> — one REST-shaped comment object.
comment() {
  jq -n --argjson id "$1" --arg login "$2" --arg url "$3" --arg body "$4" \
    '{id: $id, html_url: "https://example.test/c/\($id)", issue_url: $url, user: {login: $login}, body: $body}'
}

# payload <comment-json>... — wrap comment objects into the array the check reads.
payload() {
  jq -s '.' <<<"$*"
}

# expect <label> <want-exit> <want-substring|-> <payload> [args...]
expect() {
  local label="$1" want_rc="$2" want="$3" input="$4" rc=0 out
  shift 4
  out="$("$check" --input - "$@" <<<"$input" 2>&1)" || rc=$?
  if [ "$rc" -ne "$want_rc" ]; then
    bad "${label}: expected exit ${want_rc}, got ${rc}: ${out}"
  elif [ "$want" != "-" ] && [[ "$out" != *"$want"* ]]; then
    bad "${label}: output lacks '${want}': ${out}"
  else
    echo "  ok   ${label}"
  fi
}

paired_disclosure="$(comment 1 devantler "$issue_a" "${disclosure}"$'\n'"${marker}")"
trigger="$(comment 2 devantler "$issue_a" '@cursor review')"

# --- pairing ------------------------------------------------------------------------
expect "paired trigger passes" 0 "triggers=1 paired=1 unpaired=0 stale-head=0" \
  "$(payload "$paired_disclosure" "$trigger")"
expect "trigger with no marker is unpaired" 1 "marker=none reason=no-marker" \
  "$(payload "$trigger")"
expect "disclosure without a marker is unpaired (the ksail#6244 shape)" 1 "reason=no-marker" \
  "$(payload "$(comment 1 devantler "$issue_a" "$disclosure")" "$trigger")"
expect "marker without the disclosure is unpaired" 1 "marker=https://example.test/c/1 reason=undisclosed-marker" \
  "$(payload "$(comment 1 devantler "$issue_a" "$marker")" "$trigger")"
expect "a marker behind other text on the first line is unpaired" 1 "reason=undisclosed-marker" \
  "$(payload "$(comment 1 devantler "$issue_a" "note"$'\n'"${disclosure}"$'\n'"${marker}")" "$trigger")"
expect "a CodeRabbit marker is not a Bugbot marker" 1 "reason=no-marker" \
  "$(payload "$(comment 1 devantler "$issue_a" "${disclosure}"$'\n'"<!-- review-request-head: ${sha} provider=cr -->")" "$trigger")"
expect "an abbreviated sha is not a marker" 1 "reason=no-marker" \
  "$(payload "$(comment 1 devantler "$issue_a" "${disclosure}"$'\n'"<!-- review-request-head: ${sha:0:10} provider=bugbot -->")" "$trigger")"
expect "two different Bugbot markers are ambiguous" 1 "reason=ambiguous-marker" \
  "$(payload "$(comment 1 devantler "$issue_a" "${disclosure}"$'\n'"${marker}"$'\n'"<!-- review-request-head: ${old} provider=bugbot -->")" "$trigger")"
expect "another author's marker never pairs" 1 "reason=no-marker" \
  "$(payload "$(comment 1 someone "$issue_a" "${disclosure}"$'\n'"${marker}")" "$trigger")"
expect "another author's comment in between is ignored" 0 "paired=1" \
  "$(payload "$paired_disclosure" "$(comment 5 coderabbitai[bot] "$issue_a" 'walkthrough')" "$trigger")"
expect "the same author's unrelated comment keeps the window open" 0 "paired=1" \
  "$(payload "$paired_disclosure" "$(comment 5 devantler "$issue_a" "${disclosure}"$'\n\nstatus')" "$trigger")"
expect "a newer authenticated marker replaces the older one" 0 "stale-head=0" \
  "$(payload \
    "$(comment 1 devantler "$issue_a" "${disclosure}"$'\n'"<!-- review-request-head: ${old} provider=bugbot -->")" \
    "$(comment 3 devantler "$issue_a" "${disclosure}"$'\n'"${marker}")" \
    "$(comment 4 devantler "$issue_a" '@cursor review')")" --head "$sha"
expect "an undisclosed marker does not replace an authenticated one" 0 "stale-head=0" \
  "$(payload "$paired_disclosure" \
    "$(comment 3 devantler "$issue_a" "<!-- review-request-head: ${old} provider=bugbot -->")" \
    "$(comment 4 devantler "$issue_a" '@cursor review')")" --head "$sha"
expect "a newer ambiguous marker ends the window" 1 "marker=https://example.test/c/3 reason=ambiguous-marker" \
  "$(payload "$paired_disclosure" \
    "$(comment 3 devantler "$issue_a" "${disclosure}"$'\n'"${marker}"$'\n'"<!-- review-request-head: ${old} provider=bugbot -->")" \
    "$(comment 4 devantler "$issue_a" '@cursor review')")"
expect "a second trigger does not reuse the first one's marker" 1 "triggers=2 paired=1 unpaired=1" \
  "$(payload "$paired_disclosure" "$trigger" "$(comment 3 devantler "$issue_a" '@cursor review')")"
expect "a marker in another discussion does not pair" 1 "reason=no-marker" \
  "$(payload "$paired_disclosure" "$(comment 2 devantler "$issue_b" '@cursor review')")"
expect "CRLF bodies are normalised" 0 "paired=1" \
  "$(payload "$(comment 1 devantler "$issue_a" "${disclosure}"$'\r\n'"${marker}"$'\r\n')" "$(comment 2 devantler "$issue_a" $'@cursor review\r')")"

# --- every shape that starts Bugbot is a trigger (monorepo#3520) ----------------------
# Measured on monorepo#3949, 2026-10-07: Bugbot started 8 seconds after a comment that OPENED with
# the command, whether the body was exactly the command, carried more text on the same line, or
# carried a footer on later lines (the GitHub connector appends one to every comment it posts).
# Counting only the exact bare body reported `triggers=0` over a live, unpaired request.
expect "a trigger with more text on its line is a live request" 1 "triggers=1 paired=0 unpaired=1" \
  "$(payload "$(comment 2 devantler "$issue_a" '@cursor review please')")"
expect "a trigger with more text on its line pairs with its marker" 0 "triggers=1 paired=1 unpaired=0 stale-head=0" \
  "$(payload "$paired_disclosure" "$(comment 2 devantler "$issue_a" '@cursor review please')")"
footer=$'\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n'
footer_trigger="$(comment 2 devantler "$issue_a" "@cursor review${footer}")"
expect "a trigger followed by a footer is a live request" 1 "triggers=1 paired=0 unpaired=1" \
  "$(payload "$footer_trigger")"
expect "a trigger followed by a footer reports its missing marker" 1 "marker=none reason=no-marker" \
  "$(payload "$footer_trigger")"
expect "a trigger followed by a footer pairs with its marker" 0 "triggers=1 paired=1 unpaired=0 stale-head=0" \
  "$(payload "$paired_disclosure" "$footer_trigger")"
expect "a trigger followed by any later line is a live request" 1 "triggers=1 paired=0 unpaired=1" \
  "$(payload "$(comment 2 devantler "$issue_a" $'@cursor review\nthanks')")"
expect "a CRLF trigger followed by a footer is a live request" 1 "triggers=1 paired=0 unpaired=1" \
  "$(payload "$(comment 2 devantler "$issue_a" $'@cursor review\r\n\r\n---\r\nfooter\r\n')")"
expect "a footer trigger does not reuse the bare trigger's marker" 1 "triggers=2 paired=1 unpaired=1" \
  "$(payload "$paired_disclosure" "$trigger" "$(comment 3 devantler "$issue_a" "@cursor review${footer}")")"
expect "a bare trigger does not reuse the footer trigger's marker" 1 "triggers=2 paired=1 unpaired=1" \
  "$(payload "$paired_disclosure" "$footer_trigger" "$(comment 3 devantler "$issue_a" '@cursor review')")"
expect "--head holds a footer trigger to the current head" 1 "STALE-HEAD https://example.test/c/2 marker=${sha} head=${old}" \
  "$(payload "$paired_disclosure" "$footer_trigger")" --head "$old"
# Only five shapes were measured, so every OTHER first line that names the command is counted:
# the costly error is a live request read as none, and Bugbot reads the raw body, so how Markdown
# would render the line (a code block, a quotation) says nothing about whether it starts.
unmeasured() { # unmeasured <label> <body> — an unmeasured first-line shape must count as a trigger
  expect "$1 is counted" 1 "triggers=1 paired=0 unpaired=1" "$(payload "$(comment 2 devantler "$issue_a" "$2")")"
}
unmeasured "a different letter case" '@Cursor Review'
unmeasured "a blank line before the command" $'\n@cursor review'
unmeasured "a line of other whitespace before the command" $'\xc2\xa0\n@cursor review'
unmeasured "three spaces before the command" '   @cursor review'
unmeasured "four spaces before the command" $'    @cursor review\n\nexample'
unmeasured "a tab before the command" $'\t@cursor review'
unmeasured "a no-break space before the command" $'\xc2\xa0@cursor review'
unmeasured "a quoted command" '> @cursor review'
unmeasured "text before the command on the first line" 'Requesting @cursor review now'
unmeasured "a full stop straight after the command" '@cursor review.'
unmeasured "a comma straight after the command" '@cursor review, thanks'
unmeasured "two spaces inside the command" '@cursor  review'
unmeasured "a tab inside the command" $'@cursor\treview'
unmeasured "bare carriage returns between the command and a footer" $'@cursor review\r---\rfooter'
# Negative controls for the one shape measured NOT to start Bugbot: the command below the first
# line. Measured on monorepo#3949 on 2026-10-07 below a disclosure line, alone on its own line and
# inside a sentence, with no check-run and no reply; and on 2026-07-20 below a sender line. None
# may be counted or end a pairing window.
expect "the command alone below a disclosure line is not a trigger" 0 "triggers=0" \
  "$(payload "$(comment 2 devantler "$issue_a" "${disclosure}"$'\n\n@cursor review')")"
expect "the command in a sentence below a disclosure line is not a trigger" 0 "triggers=0" \
  "$(payload "$(comment 2 devantler "$issue_a" "${disclosure}"$'\n\nI will post @cursor review once CI is green.')")"
expect "the command below any other first line is not a trigger" 0 "triggers=0" \
  "$(payload "$(comment 2 devantler "$issue_a" $'<!-- note -->\n@cursor review')")"
# Not the command at all: another command, and a longer word that merely starts with it.
expect "a different command with a footer is not a trigger" 0 "triggers=0" \
  "$(payload "$(comment 2 devantler "$issue_a" "@cursor investigate${footer}")")"
expect "a longer word that starts with the command is not a trigger" 0 "triggers=0" \
  "$(payload "$(comment 2 devantler "$issue_a" '@cursor reviewer notes')")"
expect "the command with a letter or underscore joined on is not a trigger" 0 "triggers=0" \
  "$(payload "$(comment 2 devantler "$issue_a" '@cursor review_notes')")"
expect "a non-trigger comment keeps the window open for a footer trigger" 0 "paired=1" \
  "$(payload "$paired_disclosure" \
    "$(comment 5 devantler "$issue_a" "${disclosure}"$'\n\nI will post @cursor review once CI is green.')" \
    "$(comment 6 devantler "$issue_a" "@cursor review${footer}")")"
expect "no triggers is clean" 0 "triggers=0 paired=0" \
  "$(payload "$paired_disclosure")"
expect "--author scopes the check to that exact login" 0 "triggers=0" \
  "$(payload "$trigger")" --author someone-else
expect "CLI-shaped author.login is accepted" 0 "paired=1" \
  "$(jq -n --arg d "${disclosure}"$'\n'"${marker}" \
    '[{id: 1, body: $d, author: {login: "devantler"}}, {id: 2, body: "@cursor review", author: {login: "devantler"}}]')"

# --- current head -------------------------------------------------------------------
expect "--head matching the last trigger passes" 0 "stale-head=0" \
  "$(payload "$paired_disclosure" "$trigger")" --head "$sha"
expect "--head differing from the last trigger's marker is stale" 1 "STALE-HEAD https://example.test/c/2 marker=${sha} head=${old}" \
  "$(payload "$paired_disclosure" "$trigger")" --head "$old"
expect "only the last trigger is held to --head" 0 "triggers=2 paired=2 unpaired=0 stale-head=0" \
  "$(payload \
    "$(comment 1 devantler "$issue_a" "${disclosure}"$'\n'"<!-- review-request-head: ${old} provider=bugbot -->")" \
    "$(comment 2 devantler "$issue_a" '@cursor review')" \
    "$paired_disclosure" \
    "$(comment 4 devantler "$issue_a" '@cursor review')")" --head "$sha"
expect "--head across two discussions is refused" 2 "one discussion" \
  "$(payload "$paired_disclosure" "$(comment 2 devantler "$issue_b" '@cursor review')")" --head "$sha"
expect "an abbreviated --head is refused" 2 "full 40-character" \
  "$(payload "$trigger")" --head "${sha:0:10}"

# --- fail closed on input it cannot verify ------------------------------------------
expect "empty input" 2 "empty payload" ""
expect "a GitHub error object" 2 "not an array" '{"message":"Not Found"}'
expect "a record without a body" 2 "not an array" '[{"id":1,"user":{"login":"devantler"}}]'
expect "a record without an author" 2 "not an array" '[{"id":1,"body":"@cursor review"}]'
expect "a record with an empty author" 2 "not an array" '[{"id":1,"body":"x","user":{"login":""}}]'
expect "a non-string issue_url" 2 "not an array" '[{"id":1,"body":"x","user":{"login":"devantler"},"issue_url":7}]'
expect "an unknown argument" 2 "unknown argument" "[]" --since 2026-01-01T00:00:00Z

# --- --help prints the whole header and nothing after it ----------------------------
# The range is a pair of line numbers, so a header that grows silently cuts the exit codes off.
help_rc=0
help_out="$("$check" --help 2>&1)" || help_rc=$?
if [ "$help_rc" -ne 0 ]; then
  bad "--help exited ${help_rc}"
elif [[ "$help_out" != *"author-attributed comments)" ]]; then
  bad "--help does not end at the last exit-code line: ${help_out: -80}"
elif [[ "$help_out" != "# bugbot-request-marker.sh"$'\n'* ]]; then
  bad "--help does not start at the script's name: ${help_out:0:80}"
else
  echo "  ok   --help prints the header from its first line to its last"
fi

# --- the contract states the measured rule, not the refuted one (monorepo#3520) -------
# The review-lanes guide said Bugbot exact-matches the whole body, and both checks were built on
# it. Pin the measured rule and each measured row, and require the refuted sentence to be gone from
# every guide: a check corrected while its premise stays in the contract gets "fixed" back.
guides="${script_dir}/../guides"
lanes_flat="$(tr '\n' ' ' <"${guides}/review-lanes.md" | tr -s ' ')"
contract_error() { # contract_error <flattened review-lanes text> — prints the first missing clause
  local flat="$1" clause
  # shellcheck disable=SC2016 # backticks are literal Markdown in the clauses, not substitutions
  for clause in \
    '**Bugbot starts on a comment that OPENS with the command; text AFTER it voids nothing**' \
    're-measured 2026-10-07 on monorepo#3949' \
    '| exactly `@cursor review` | started 8 s later |' \
    '| `@cursor review please` (more text on the same line) | started 8 s later |' \
    '| `@cursor review`, then a blank line, a rule and a footer | started 8 s later |' \
    '| a disclosure line, then a sentence that names `@cursor review` | none in 135 s |' \
    '| a disclosure line, then `@cursor review` alone on its own line | none in 137 s |' \
    '**Post only the exact bare body anyway**' \
    'These five rows are all that was measured.' \
    '`bugbot-request-marker.sh` leaves out that shape alone: it counts every comment whose first line names the command, measured or not, and requires its marker' \
    'checks that pairing for every comment on a PR whose first line names `@cursor review`'; do
    case "${flat}" in
      *"${clause}"*) ;;
      *) echo "${clause}"; return ;;
    esac
  done
}
missing_clause="$(contract_error "${lanes_flat}")"
if [ -n "${missing_clause}" ]; then
  bad "the review-lanes guide must say: ${missing_clause}"
else
  echo "  ok   the review-lanes guide states the measured trigger rule"
fi
# Controls: the same check must reject a guide that lost the rule, and one that lost a measured row.
mutated="${lanes_flat//text AFTER it voids nothing/text after it voids the request}"
if [ "${mutated}" = "${lanes_flat}" ] || [[ "$(contract_error "${mutated}")" != *'OPENS with the command'* ]]; then
  bad "control: the contract check did not reject a guide that reverted the rule"
else
  echo "  ok   control: a guide that reverts the rule is rejected"
fi
mutated="${lanes_flat//(more text on the same line) | started 8 s later/(more text on the same line) | none}"
if [ "${mutated}" = "${lanes_flat}" ] || [[ "$(contract_error "${mutated}")" != *'more text on the same line'* ]]; then
  bad "control: the contract check did not reject a guide that lost a measured row"
else
  echo "  ok   control: a guide that loses a measured row is rejected"
fi
stale_rc=0
stale="$(grep -n -i -E 'bugbot exact-matches|exact-matches the whole' "${guides}"/*.md)" || stale_rc=$?
if [ "${stale_rc}" -gt 1 ]; then
  bad "could not read the guides for the refuted premise (grep exit ${stale_rc})"
elif [ -n "${stale}" ] && ! grep -q 'Until then this section said Bugbot exact-matches the whole body' <<<"${stale}"; then
  bad "a guide still states the refuted exact-match premise: ${stale}"
elif [ "$(grep -c . <<<"${stale}")" -gt 1 ]; then
  bad "the refuted exact-match premise survives beside its correction: ${stale}"
else
  echo "  ok   no guide states the refuted exact-match premise"
fi

# --- end to end with the real composer ----------------------------------------------
composed_disclosure="$("$composer" --provider bugbot --head "$sha" --part disclosure)"
composed_trigger="$("$composer" --provider bugbot --part trigger)"
expect "the composer's Bugbot pair passes at its head" 0 "triggers=1 paired=1 unpaired=0 stale-head=0" \
  "$(payload "$(comment 1 devantler "$issue_a" "$composed_disclosure")" "$(comment 2 devantler "$issue_a" "$composed_trigger")")" \
  --head "$sha"
expect "the composer's trigger alone is unpaired" 1 "reason=no-marker" \
  "$(payload "$(comment 2 devantler "$issue_a" "$composed_trigger")")"

# --- --repo/--pr through a stubbed gh -----------------------------------------------
mkdir -p "$tmp/bin"
cat >"$tmp/bin/gh" <<'STUB'
#!/usr/bin/env bash
case "${GH_STUB_MODE:-}" in
  pages)
    # Two pages, concatenated the way `gh api --paginate` emits them.
    printf '%s\n' "$GH_STUB_PAGE1" "$GH_STUB_PAGE2"
    ;;
  fail) echo "HTTP 502" >&2; exit 1 ;;
  empty) ;;
esac
STUB
chmod +x "$tmp/bin/gh"

expect_gh() {
  local label="$1" mode="$2" want_rc="$3" want="$4" rc=0 out
  out="$(PATH="$tmp/bin:$PATH" GH_STUB_MODE="$mode" \
    GH_STUB_PAGE1="$(payload "$paired_disclosure")" GH_STUB_PAGE2="$(payload "$trigger")" \
    "$check" --repo o/r --pr 1 2>&1)" || rc=$?
  if [ "$rc" -ne "$want_rc" ]; then
    bad "${label}: expected exit ${want_rc}, got ${rc}: ${out}"
  elif [[ "$out" != *"$want"* ]]; then
    bad "${label}: output lacks '${want}': ${out}"
  else
    echo "  ok   ${label}"
  fi
}

expect_gh "a marker and trigger on different pages still pair" pages 0 "paired=1"
expect_gh "a gh failure fails closed" fail 2 "could not read"
expect_gh "an empty gh response fails closed" empty 2 "empty payload"

if [ "$fails" -ne 0 ]; then
  echo "bugbot-request-marker.test: ${fails} failure(s)" >&2
  exit 1
fi
echo "bugbot-request-marker.test: all assertions passed"
bugbot_marker_test_finished=1
