#!/usr/bin/env bash
#
# bugbot-request-marker.sh
#
# Checks the Bugbot review-request protocol: every bare `@cursor review` must be
# paired with a request marker, as AGENTS.md prescribes.
#
# Bugbot exact-matches the whole comment body, so its trigger cannot carry a
# disclosure or a marker. The contract therefore has the agent post them in the
# comment IMMEDIATELY BEFORE the trigger:
#
#   > 🤖 Generated by the Agentic Engineer
#   <!-- review-request-head: <full headRefOid> provider=bugbot -->
#
# and a marker is authoritative only from the exact author with that structural
# disclosure. The marker is what lets overlapping instances tell a live request
# from a stale-head one, so a trigger without it is a request nobody can account
# for.
#
# This is a review-request PROTOCOL check, deliberately separate from
# comment-disclosure-drift.sh (monorepo#2721). That guard grants the bare trigger
# its disclosure carve-out on the preceding disclosure alone; widening it to
# demand a marker would report disclosure-correct pairs as disclosure defects.
#
# Usage:
#   bugbot-request-marker.sh --input <file>|- [--head <sha>] [--author <login>]
#   bugbot-request-marker.sh --repo <owner>/<repo> --pr <number> [--head <sha>] [--author <login>]
#
#   --input   a JSON array of issue comments in API order (REST `user.login` or CLI
#             `author.login`; `issue_url` groups discussions, absent means one)
#   --repo/--pr  read that pull request's conversation comments through `gh`
#   --head    the pull request's current full head sha. The LAST trigger in the
#             discussion must then carry a marker naming it. Earlier triggers are
#             checked for pairing only: the head they were posted against is not
#             recoverable from the comment stream. Refused for a payload spanning
#             more than one discussion, where one head cannot apply.
#   --author  the exact login whose comments are checked (default: devantler)
#
# Pairing follows the AGENTS.md association rule, per discussion: a marker is
# associated with the NEXT bare trigger by the same author, ignoring other
# authors' comments; another authenticated Bugbot marker or a bare trigger ends
# that window. A marker is authenticated when its comment is by the same author,
# begins with `> 🤖 Generated by the `, and carries exactly one bugbot marker
# naming a full 40-character lowercase sha.
#
# Output: one line per finding, then a summary line.
#   UNPAIRED <trigger> marker=<comment|none> reason=<reason>
#     no-marker          no bugbot marker since the previous trigger
#     undisclosed-marker the only marker sits in a comment without the disclosure
#     ambiguous-marker   the latest marker comment names more than one sha
#   STALE-HEAD <trigger> marker=<sha> head=<sha>
#   bugbot-request-marker: triggers=N paired=N unpaired=N stale-head=N
#
# Exit codes:
#   0  every trigger is paired (and the last one names --head, when given)
#   1  at least one finding
#   2  the check could not verify what it claims (bad usage, a gh failure, or a
#      payload that is not an array of author-attributed comments)
set -Eeuo pipefail

input=""
repo=""
pr=""
head=""
author="devantler"

die() {
  echo "bugbot-request-marker: $1" >&2
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --input | --repo | --pr | --head | --author)
      [ $# -ge 2 ] || die "$1 needs a value"
      case "$1" in
        --input) input="$2" ;;
        --repo) repo="$2" ;;
        --pr) pr="$2" ;;
        --head) head="$2" ;;
        --author) author="$2" ;;
      esac
      shift 2
      ;;
    -h | --help)
      sed -n '3,58p' "${BASH_SOURCE[0]}"
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

command -v jq >/dev/null 2>&1 || die "jq is required"
[ -n "$author" ] || die "--author must not be empty"
if [ -n "$head" ] && [[ ! "$head" =~ ^[0-9a-f]{40}$ ]]; then
  die "--head must be a full 40-character lowercase sha"
fi

if [ -n "$input" ]; then
  [ -z "$repo$pr" ] || die "--input cannot be combined with --repo/--pr"
  if [ "$input" = "-" ]; then
    payload="$(cat)"
  else
    [ -r "$input" ] || die "cannot read $input"
    payload="$(cat -- "$input")"
  fi
elif [ -n "$repo" ] || [ -n "$pr" ]; then
  [[ "$repo" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || die "--repo must be <owner>/<repo>"
  [[ "$pr" =~ ^[1-9][0-9]*$ ]] || die "--pr must be a pull request number"
  command -v gh >/dev/null 2>&1 || die "gh is required for --repo/--pr"
  # One JSON array per page, concatenated; fail closed on a gh error or an empty
  # response so a swallowed 5xx cannot read as a discussion with no triggers.
  pages="$(gh api "repos/${repo}/issues/${pr}/comments?per_page=100" --paginate)" ||
    die "gh could not read ${repo}#${pr} comments"
  [ -n "$pages" ] || die "gh returned an empty payload for ${repo}#${pr}"
  payload="$(jq -s 'flatten(1)' <<<"$pages" 2>/dev/null)" ||
    die "could not flatten the paginated response for ${repo}#${pr}"
else
  die "give --input <file>|- or --repo <owner>/<repo> --pr <number>"
fi

[[ "$payload" =~ [^[:space:]] ]] || die "empty payload"

# A record the classifier cannot attribute would be skipped as another author's
# comment, so a malformed payload must fail here rather than read as clean.
jq -e '
  type == "array" and
  all(.[];
    type == "object" and
    ((.body | type) == "string") and
    ((.issue_url // "" | type) == "string") and
    (((.user.login? // .author.login? // "") | type) == "string") and
    ((.user.login? // .author.login? // "") | length > 0))
' <<<"$payload" >/dev/null 2>&1 ||
  die "payload is not an array of author-attributed comments"

if [ -n "$head" ]; then
  discussions="$(jq '[.[] | .issue_url // ""] | unique | length' <<<"$payload")"
  [ "$discussions" -le 1 ] || die "--head applies to one discussion; the payload spans ${discussions}"
fi

report="$(jq -r --arg author "$author" --arg head "$head" '
  def norm: gsub("\r"; "");
  def who: .user.login? // .author.login?;
  def ref: (.html_url // (.id | tostring));
  def is_trigger: (.body | norm) == "@cursor review";
  def bugbot_shas:
    [ .body | norm | split("\n")[] | gsub("^[ \t]+|[ \t]+$"; "")
      | capture("^<!-- review-request-head: (?<sha>[0-9a-f]{40}) provider=bugbot -->$")
      | .sha ] | unique;
  def disclosed: .body | norm | startswith("> 🤖 Generated by the ");

  # Per discussion: `window` is the authenticated marker awaiting its trigger;
  # `seen` remembers why none is valid (an undisclosed or ambiguous marker) so
  # an unpaired trigger reports the cause, not just the absence.
  ((reduce (.[] | select(who == $author)) as $c ({window: {}, seen: {}, triggers: []};
      ($c.issue_url // "") as $k
      | if ($c | is_trigger) then
          .window[$k] as $w
          | .seen[$k] as $s
          | .triggers += [
              if $w != null then {reason: null, sha: $w.sha, trigger: ($c | ref), marker: $w.ref}
              else {
                reason: (if $s == null then "no-marker" else "\($s.kind)-marker" end),
                trigger: ($c | ref),
                marker: (if $s == null then "none" else $s.ref end)
              }
              end ]
          | .window[$k] = null
          | .seen[$k] = null
        else
          ($c | bugbot_shas) as $shas
          | if ($shas | length) == 0 then .
            elif ($c | disclosed | not) then
              # Untrusted: never opens or ends a window.
              if .window[$k] == null then .seen[$k] = {kind: "undisclosed", ref: ($c | ref)} else . end
            elif ($shas | length) > 1 then
              .window[$k] = null | .seen[$k] = {kind: "ambiguous", ref: ($c | ref)}
            else
              .window[$k] = {sha: $shas[0], ref: ($c | ref)} | .seen[$k] = null
            end
        end
    )) | .triggers) as $triggers

  | ($triggers | map(select(.reason != null))) as $unpaired
  | (if $head != "" and ($triggers | length) > 0
        and ($triggers[-1].reason == null) and ($triggers[-1].sha != $head)
     then [$triggers[-1]] else [] end) as $stale

  | [ ($unpaired[] | "UNPAIRED \(.trigger) marker=\(.marker) reason=\(.reason)"),
      ($stale[] | "STALE-HEAD \(.trigger) marker=\(.sha) head=\($head)"),
      "bugbot-request-marker: triggers=\($triggers | length) paired=\(($triggers | length) - ($unpaired | length)) unpaired=\($unpaired | length) stale-head=\($stale | length)"
    ]
  | .[]
' <<<"$payload")" || die "could not analyse the payload"

printf '%s\n' "$report"

# The exit status comes from the summary counts, never from matching finding
# text: a formatting change there must not turn findings into a clean exit.
summary_re='(^|'$'\n'')bugbot-request-marker: triggers=[0-9]+ paired=[0-9]+ unpaired=([0-9]+) stale-head=([0-9]+)$'
[[ "$report" =~ $summary_re ]] || die "analysis produced no summary"
if [ "${BASH_REMATCH[2]}" -ne 0 ] || [ "${BASH_REMATCH[3]}" -ne 0 ]; then
  exit 1
fi
exit 0
