#!/usr/bin/env bash
#
# Contract test for comment-disclosure-drift.
#
# Two halves, because the guard has two:
#   1. the Go classifier's own suite (every defect shape, every false-positive guard)
#   2. the wrapper's contract — exit codes, usage validation, and above all that a
#      `gh` failure FAILS CLOSED instead of decoding to an empty comment set that
#      reports "no violations". A swallowed 5xx reading as clean is the exact
#      failure class this repository has been bitten by before.
set -Eeuo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
guard="$script_dir/comment-disclosure-drift.sh"

failures=0
tmpdir="$(mktemp -d "${TMPDIR:-/tmp}/comment-disclosure-drift-test.XXXXXX")"
# shellcheck disable=SC2329 # Invoked indirectly by the EXIT trap.
cleanup() { rm -rf -- "$tmpdir"; }
trap cleanup EXIT

# expect_exit <want> <label> -- <command...>
expect_exit() {
  local want="$1" label="$2"
  shift 3 # drop want, label and the literal --
  local got=0
  "$@" >"$tmpdir/out" 2>"$tmpdir/err" || got=$?
  if [ "$got" != "$want" ]; then
    echo "FAIL  $label: exit $got, want $want"
    sed 's/^/        /' "$tmpdir/err" | head -5
    failures=$((failures + 1))
    return
  fi
  echo "ok    $label"
}

# expect_stdout <pattern> <label>  -- reads the last expect_exit's stdout
expect_stdout() {
  local pattern="$1" label="$2"
  if grep -qF -- "$pattern" "$tmpdir/out"; then
    echo "ok    $label"
  else
    echo "FAIL  $label: stdout did not contain: $pattern"
    sed 's/^/        /' "$tmpdir/out" | head -10
    failures=$((failures + 1))
  fi
}

# expect_stderr <pattern> <label>  -- reads the last expect_exit's stderr.
# An exit code alone cannot say WHICH rejection fired, and every usage error here
# shares exit 2; pinning the message is what stops an assertion passing for an
# unrelated reason.
expect_stderr() {
  local pattern="$1" label="$2"
  if grep -qF -- "$pattern" "$tmpdir/err"; then
    echo "ok    $label"
  else
    echo "FAIL  $label: stderr did not contain: $pattern"
    sed 's/^/        /' "$tmpdir/err" | head -10
    failures=$((failures + 1))
  fi
}

echo "== Go classifier suite =="
if (cd "$script_dir/comment-disclosure-drift-go" && go test -race -cover ./...); then
  echo "ok    go test"
else
  echo "FAIL  go test"
  failures=$((failures + 1))
fi

echo
echo "== wrapper: usage validation fails closed (exit 2) =="
expect_exit 2 "no arguments" -- bash "$guard"
expect_exit 2 "unknown flag" -- bash "$guard" --nope
expect_exit 2 "--repo without --issue" -- bash "$guard" --repo owner/repo
expect_exit 2 "--repo not owner/repo" -- bash "$guard" --repo notaslug --issue 1
expect_exit 2 "--issue not numeric" -- bash "$guard" --repo owner/repo --issue abc
expect_exit 2 "--issue negative" -- bash "$guard" --repo owner/repo --issue -3
expect_exit 2 "--input with --repo" -- bash "$guard" --input - --repo owner/repo --issue 1
expect_exit 2 "unreadable --input" -- bash "$guard" --input "$tmpdir/absent.json"
expect_exit 2 "--author without value" -- bash "$guard" --repo owner/repo --issue 1 --author

echo
echo "== wrapper: payload classification =="
# A compliant body and the bare-trigger carve-out: both must pass.
# The bare Bugbot trigger is exempt only when its disclosure comment IMMEDIATELY
# precedes it, so the pair is what must classify clean.
printf '%s' '[{"id":1,"user":{"login":"devantler"},"body":"> 🤖 Generated by the Agentic Engineer\n\nrequesting a review"},
              {"id":2,"user":{"login":"devantler"},"body":"@cursor review"}]' >"$tmpdir/clean.json"
expect_exit 0 "clean payload exits 0" -- bash "$guard" --input "$tmpdir/clean.json"

# Each of the three defect shapes must exit 1 and name itself.
printf '%s' '[{"id":3,"html_url":"https://x/3","user":{"login":"devantler"},"body":"@coderabbitai full review\n\n> 🤖 Generated by the Agentic Engineer."}]' >"$tmpdir/trailing.json"
expect_exit 1 "appended disclosure after trigger exits 1" -- bash "$guard" --input "$tmpdir/trailing.json"
expect_stdout "undisclosed-trigger" "appended disclosure after trigger is named"

printf '%s' '[{"id":4,"html_url":"https://x/4","user":{"login":"devantler"},"body":"> Requested by the 🤖 Daily AI Engineer - CI is green"}]' >"$tmpdir/sender.json"
expect_exit 1 "sender marker exits 1" -- bash "$guard" --input "$tmpdir/sender.json"
expect_stdout "sender-marker" "sender marker is named"

printf '%s' '[{"id":5,"html_url":"https://x/5","user":{"login":"devantler"},"body":"@coderabbitai review\n\nPlease review exact head abc"}]' >"$tmpdir/annotated.json"
expect_exit 1 "undisclosed trigger exits 1" -- bash "$guard" --input "$tmpdir/annotated.json"
expect_stdout "undisclosed-trigger" "undisclosed trigger is named"

# The maintainer's own prose carries no robot marker. Flagging it would turn his
# control channel into a defect report -- the dangerous direction.
printf '%s' '[{"id":6,"user":{"login":"devantler"},"body":"Drop the human promotion gate. I always approve your work anyhow."}]' >"$tmpdir/maintainer.json"
expect_exit 0 "maintainer prose is not a violation" -- bash "$guard" --input "$tmpdir/maintainer.json"
expect_stdout "unattributable" "unattributable residual is disclosed on a clean run"

# A four-space-indented first line renders as a Markdown CODE BLOCK, so it SHOWS a
# trigger rather than issuing one. That is how the maintainer writes an example, and
# trimming the indentation made his comment byte-identical to an agent's trigger --
# flagging the control channel, the one direction this guard must never fail in.
printf '%s' '[{"id":20,"user":{"login":"devantler"},"body":"    @codex review\n\nThat is the trigger to use next time."}]' >"$tmpdir/indented-trigger.json"
expect_exit 0 "an indented trigger example is not agent evidence" -- bash "$guard" --input "$tmpdir/indented-trigger.json"

# A leading TAB is the other CommonMark code-block form.
printf '%s' '[{"id":21,"user":{"login":"devantler"},"body":"\t> Requested by the 🤖 Daily AI Engineer - example"}]' >"$tmpdir/indented-sender.json"
expect_exit 0 "a tab-indented sender marker is not agent evidence" -- bash "$guard" --input "$tmpdir/indented-sender.json"

# ...and the true positive is PRESERVED: one to three spaces is ordinary text in
# CommonMark, not a code block, so a slightly-indented real trigger still counts.
printf '%s' '[{"id":22,"html_url":"https://x/22","user":{"login":"devantler"},"body":"   @codex review\n\nhead abc"}]' >"$tmpdir/slight-indent.json"
expect_exit 1 "a 3-space indented trigger is still a violation" -- bash "$guard" --input "$tmpdir/slight-indent.json"
expect_stdout "undisclosed-trigger" "3-space indented trigger is named"

# An empty --author matches no record at all, so the guard would classify nothing and
# still exit 0 with "all 0 comments satisfy" -- a clean sweep over an unchecked corpus.
printf '%s' '[{"id":30,"html_url":"https://x/30","user":{"login":"devantler"},"body":"@codex review\n\nhead abc"}]' >"$tmpdir/emptyauthor.json"
expect_exit 2 "an empty --author fails closed, never a clean sweep" -- bash "$guard" --input "$tmpdir/emptyauthor.json" --author ""

# Another author's comment is never the agent's problem.
printf '%s' '[{"id":7,"user":{"login":"coderabbitai"},"body":"@coderabbitai review\n\nextra"}]' >"$tmpdir/otherauthor.json"
expect_exit 0 "other authors are skipped" -- bash "$guard" --input "$tmpdir/otherauthor.json"

echo
echo "== wrapper: unparseable payload fails closed, never 'clean' =="
printf 'not json at all' >"$tmpdir/garbage.json"
expect_exit 2 "garbage payload exits 2" -- bash "$guard" --input "$tmpdir/garbage.json"
: >"$tmpdir/empty.json"
expect_exit 2 "empty payload exits 2" -- bash "$guard" --input "$tmpdir/empty.json"

echo
echo "== wrapper: a gh failure fails closed =="
# Stub gh on PATH so the failure path is exercised without network access.
stubdir="$tmpdir/stub"
mkdir -p "$stubdir"
cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
echo "HTTP 502: 502 Bad Gateway" >&2
exit 1
STUB
chmod +x "$stubdir/gh"
expect_exit 2 "gh non-zero exits 2 (not 0)" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --issue 1

# A gh that succeeds but returns nothing must also fail closed: an empty payload
# would otherwise classify zero comments and report no violations.
#
# Measured: this assertion still passes with the wrapper's own `-s` check removed,
# because the Go guard's decode rejects an empty payload too. The two are
# deliberate defence-in-depth and the assertion pins the BEHAVIOUR; it does not
# discriminate which layer enforces it.
cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
exit 0
STUB
chmod +x "$stubdir/gh"
expect_exit 2 "gh empty-but-successful exits 2" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --issue 1

# Codex P1 (#2720): gh --paginate emits ONE ARRAY PER PAGE. A multi-page response
# must be flattened, not handed to the guard as concatenated arrays (which exits 2
# and silently stops checking the busiest discussions).
cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
printf '%s' '[{"id":1,"html_url":"https://x/1","user":{"login":"devantler"},"body":"> \ud83e\udd16 Generated by the Agentic Engineer\n\npage one"}]'
printf '%s' '[{"id":2,"html_url":"https://x/2","user":{"login":"devantler"},"body":"@codex review\n\npage two extra content"}]'
STUB
chmod +x "$stubdir/gh"
expect_exit 1 "multi-page response is flattened and classified" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --issue 1
expect_stdout "undisclosed-trigger" "violation on page TWO is found"

# CodeRabbit 🟠 (#2720): an issue with NO comments is legitimate. A valid `[]`
# must exit 0 (nothing to check), not 2 -- gh's raw output is already checked for
# byte-emptiness above, so a real `[]` is distinguishable from "gh produced nothing".
cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
printf '%s' '[]'
STUB
chmod +x "$stubdir/gh"
expect_exit 0 "valid empty comment list exits 0" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --issue 1

# CodeRabbit 🟠 (#2720): a record with no identifiable author previously passed the
# shape check and was then SKIPPED by the classifier as a non-matching author --
# a comment silently not checked, reported as clean. It must fail closed instead.
cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
printf '%s' '[{"id":1,"body":"@codex review\n\nextra","user":{}}]'
STUB
chmod +x "$stubdir/gh"
expect_exit 2 "author-less record fails closed" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --issue 1

# The `author` string shape is an equally valid attribution.
cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
printf '%s' '[{"id":1,"body":"plain maintainer prose","author":"devantler"}]'
STUB
chmod +x "$stubdir/gh"
expect_exit 0 "author-string shape is accepted" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --issue 1

# A GitHub error object must not survive as a clean sweep.
cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
printf '%s' '{"message":"Not Found","documentation_url":"https://docs.github.com"}'
STUB
chmod +x "$stubdir/gh"
expect_exit 2 "gh error object exits 2, never clean" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --issue 1

# And the success path through gh must still classify.
cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
printf '%s' '[{"id":9,"html_url":"https://x/9","user":{"login":"devantler"},"body":"@codex review\n\nextra content"}]'
STUB
chmod +x "$stubdir/gh"
expect_exit 1 "gh success path classifies" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --issue 1
expect_stdout "undisclosed-trigger" "gh success path names the shape"

echo
echo "== wrapper: --since sweeps the REPO, so regression is visible rather than found by chance =="
# Without a repo-wide mode the check can only be aimed at an issue number somebody
# already suspects -- which is how #2609's 18 offending comments accumulated across
# four issues nobody thought to point it at.

expect_exit 2 "--since without a value" -- bash "$guard" --repo owner/repo --since
expect_exit 2 "--since needs --repo" -- bash "$guard" --since 2026-08-10T00:00:00Z
expect_exit 2 "--since with --input" -- bash "$guard" --input - --since 2026-08-10T00:00:00Z
# Scope must be unambiguous: one issue OR the repo, never a silent preference.
expect_exit 2 "--since with --issue is ambiguous" -- bash "$guard" --repo owner/repo --issue 1 --since 2026-08-10T00:00:00Z
# A malformed timestamp is rejected locally so the caller reads a plain message
# rather than a 422, and so an obvious typo costs no network call. Measured
# 2026-08-11: GitHub answers an unparseable `since` with HTTP 422 -- it does NOT
# silently widen the window -- so this is defence in depth and a better error, not
# the only thing between a typo and a falsely-clean sweep.
#
# These two MUST run against a gh that would otherwise SUCCEED. Measured while
# ablating: without a stub, `owner/repo` does not exist, so real gh fails and the
# assertion passes on exit 2 whether or not the local validation exists at all --
# it pinned the fake repo, not the check. With a stub that returns a clean `[]`,
# exit 2 can only come from the local shape check, and the stderr assertion names
# which rejection fired.
cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
printf '%s' '[]'
STUB
chmod +x "$stubdir/gh"
expect_exit 2 "--since rejects a non-timestamp" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --since yesterday
expect_stderr "ISO-8601" "non-timestamp is rejected by the local shape check"
expect_exit 2 "--since rejects a date without a time" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --since 2026-08-10
expect_stderr "ISO-8601" "date-without-time is rejected by the local shape check"
# Positive control: the SAME stub, with a well-formed timestamp, must reach the
# classifier and exit 0 -- otherwise the two assertions above could be passing
# because the stub itself is broken.
expect_exit 0 "a well-formed --since reaches the classifier through the same stub" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --since 2026-08-10T00:00:00Z

# THE load-bearing assertion: --since must hit the repo-wide comments endpoint.
# A sweep that silently read one issue would classify a handful of comments and
# report the whole repo clean.
cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
printf '%s\n' "$*" >>"$ARGLOG"
printf '%s' '[{"id":40,"html_url":"https://x/40","user":{"login":"devantler"},"body":"@codex review\n\nhead abc"}]'
STUB
chmod +x "$stubdir/gh"
: >"$tmpdir/args"
expect_exit 1 "--since classifies and finds the violation" -- env PATH="$stubdir:$PATH" ARGLOG="$tmpdir/args" bash "$guard" --repo owner/repo --since 2026-08-10T00:00:00Z
expect_stdout "undisclosed-trigger" "--since names the shape"
if grep -qF 'repos/owner/repo/issues/comments' "$tmpdir/args" &&
  grep -qF 'since=2026-08-10T00:00:00Z' "$tmpdir/args" &&
  ! grep -qE 'repos/owner/repo/issues/[0-9]+/comments' "$tmpdir/args"; then
  echo "ok    --since queries the repo-wide endpoint with the timestamp"
else
  echo "FAIL  --since did not query the repo-wide endpoint; gh args were:"
  sed 's/^/        /' "$tmpdir/args"
  failures=$((failures + 1))
fi

# The fail-closed properties must hold on this path too -- they are per-endpoint,
# not per-flag, and a sweep that reads clean on a 502 is worse than no sweep.
cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
echo "HTTP 502: 502 Bad Gateway" >&2
exit 1
STUB
chmod +x "$stubdir/gh"
expect_exit 2 "--since fails closed on a gh error" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --since 2026-08-10T00:00:00Z

cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
printf '%s' '{"message":"Not Found","documentation_url":"https://docs.github.com"}'
STUB
chmod +x "$stubdir/gh"
expect_exit 2 "--since fails closed on an error object" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --since 2026-08-10T00:00:00Z

# Multi-page is the NORMAL case repo-wide (176 comments over ~2 days, measured), so
# the flatten must apply here or the busiest windows are exactly the unchecked ones.
cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
printf '%s' '[{"id":41,"html_url":"https://x/41","user":{"login":"devantler"},"body":"> 🤖 Generated by the Agentic Engineer\n\npage one"}]'
printf '%s' '[{"id":42,"html_url":"https://x/42","user":{"login":"devantler"},"body":"> Requested by the 🤖 Daily AI Engineer - page two"}]'
STUB
chmod +x "$stubdir/gh"
expect_exit 1 "--since flattens multiple pages" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --since 2026-08-10T00:00:00Z
expect_stdout "sender-marker" "--since finds a violation on page TWO"

# A quiet window is legitimately clean and must exit 0, not 2.
cat >"$stubdir/gh" <<'STUB'
#!/usr/bin/env bash
printf '%s' '[]'
STUB
chmod +x "$stubdir/gh"
expect_exit 0 "--since on a quiet window exits 0" -- env PATH="$stubdir:$PATH" bash "$guard" --repo owner/repo --since 2026-08-10T00:00:00Z

echo
if [ "$failures" -ne 0 ]; then
  echo "comment-disclosure-drift.test.sh: $failures assertion(s) failed"
  exit 1
fi
echo "comment-disclosure-drift.test.sh: all assertions passed"
