#!/usr/bin/env bash
#
# Guards the Agent Improver's own disclosure actor word.
#
# Why this needs a guard. The observation plane may only take a verdict on evidence INDEPENDENT of
# the Improver run being scored. Nothing on a public artifact carried that independence: measured
# 2026-08-20, all five Improver-authored PRs (#2933, #2924, #2915, #2895, #2907) began with the
# ENGINEER's disclosure; every actor on monorepo#2889's 12-event timeline was the same `devantler`
# login; and *Writer namespaces* deliberately shares one `claude/*` lane between both roles. So
# neither the login, the lane, nor the disclosure could say which role wrote a thing, and four
# consecutive Improver runs (t1222, t1234, t1246, t1259) scored ZERO hypotheses — each refusal
# individually correct, all four sharing one cause. A distinct actor word is the only role signal an
# artifact can carry.
#
# This is a MEASUREMENT TIGHTENING, never a loosening: AGENTS.md's disambiguator already instructs
# "Match the STRUCTURE, never the actor word", and both deployed guards match a structural prefix
# (`comment-disclosure-drift-go/main.go` canonicalPrefix, `pr-ownership-disclosure-go/main.go`
# routineLiteral). The new form therefore classifies as own-output/DATA with no code change — which
# assertion 3 proves behaviourally against the real guard rather than asserting it from the source.
#
# Assertions are scoped to their section, not the whole file: asserting against the whole
# constitution is a scope hole, because an unrelated passage carrying the phrase would satisfy the
# check while the real passage stayed wrong.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
constitution="${repo_root}/AGENTS.md"
guard="${repo_root}/.claude/scripts/comment-disclosure-drift.sh"
improver_form='> 🤖 Generated by the Agent Improver'
engineer_form='> 🤖 Generated by the Agentic Engineer'
passed=0

fail() {
  echo "improver-role-disclosure contract: FAIL — $*" >&2
  exit 1
}
ok() { passed=$((passed + 1)); }

[ -r "${constitution}" ] || fail "cannot read ${constitution}"
[ -x "${guard}" ] || fail "cannot execute ${guard} — assertion 3 would be vacuous"

# Extract ONLY the named section, then flatten it: sentences wrap across source lines, so a fragment
# spanning a line break would never match and the test would be always-red regardless of content.
# A sentinel proves the END anchor was actually seen, so a missing anchor is detected DIRECTLY
# rather than inferred from how much text got captured.
extract() {
  local start="$1" end="$2" sentinel='@@END-ANCHOR-SEEN@@' out
  out="$(
    awk -v s="${sentinel}" -v a="${start}" -v b="${end}" '
      index($0, a) { ins = 1 }
      ins && index($0, b) && !index($0, a) { ins = 0; print s }
      ins { print }
    ' "${constitution}"
  )"
  case "${out}" in
    *'@@END-ANCHOR-SEEN@@'*) ;;
    *) fail "section anchors not both found: '${start}' .. '${end}'" ;;
  esac
  printf '%s' "${out}" | tr '\n' ' '
}

canonical="$(extract '**AI-disclosure line (canonical):**' 'Everything below is the **shared engineering contract**')"
disambig="$(extract 'All of these are own-output,' 'The human maintainer posts')"

# 1. The canonical block must name the Improver's actor word, or no run knows to emit it.
case "${canonical}" in
  *"${improver_form}"*) ok ;;
  *) fail "the canonical AI-disclosure block does not name '${improver_form}'" ;;
esac

# 2. The disambiguator's permanently-own-output list must name it too. Without this, a comment the
#    Improver authored would read as the HUMAN MAINTAINER's instruction — the self-instruction loop
#    that disambiguator exists to close, and the expensive failure direction.
case "${disambig}" in
  *"${improver_form}"*) ok ;;
  *) fail "the own-output list does not name '${improver_form}'" ;;
esac

# 3. BEHAVIOURAL: the real deployed guard must accept the new form as a leading disclosure. This is
#    what proves no guard change is needed. Asserting it from the Go source would only restate the
#    intent; running the guard tests it.
tmp="$(mktemp -d)"
trap 'rm -rf "${tmp}"' EXIT
printf '%s' '[{"id":1,"html_url":"https://x/1","issue_url":"https://api.github.com/repos/o/r/issues/1","user":{"login":"devantler"},"body":"'"${improver_form}"'\n\nrecorded a verdict"}]' >"${tmp}/improver.json"
"${guard}" --input "${tmp}/improver.json" >/dev/null 2>&1 ||
  fail "the deployed guard rejects '${improver_form}' as a leading disclosure"
ok

# 4. NEGATIVE CONTROL for assertion 3. A guard that accepted everything would satisfy 3 vacuously,
#    so prove it still discriminates on the SAME actor word — only the position differs.
printf '%s' '[{"id":2,"html_url":"https://x/2","issue_url":"https://api.github.com/repos/o/r/issues/1","user":{"login":"devantler"},"body":"@coderabbitai review\n\n'"${improver_form}"'"}]' >"${tmp}/trailing.json"
if "${guard}" --input "${tmp}/trailing.json" >/dev/null 2>&1; then
  fail "guard accepted a TRAILING '${improver_form}' — assertion 3 is vacuous"
fi
ok

# 5. UNCHANGED HOLDOUT. Adding an actor word must not disturb the existing one; if this ever fails,
#    the change broke the Engineer's own disclosure and must be reverted rather than patched.
printf '%s' '[{"id":3,"html_url":"https://x/3","issue_url":"https://api.github.com/repos/o/r/issues/1","user":{"login":"devantler"},"body":"'"${engineer_form}"'\n\nunchanged holdout"}]' >"${tmp}/engineer.json"
"${guard}" --input "${tmp}/engineer.json" >/dev/null 2>&1 ||
  fail "holdout broke: the guard no longer accepts '${engineer_form}'"
ok

# 6. The legacy forms stay recognised FOREVER — retiring one would reclassify every comment written
#    under it as maintainer instruction.
for legacy in 'Daily AI Engineer' 'Daily AI Assistant'; do
  case "${disambig}" in
    *"${legacy}"*) ;;
    *) fail "legacy actor word '${legacy}' dropped from the own-output list" ;;
  esac
done
ok

echo "improver-role-disclosure contract: OK — ${passed} assertions passed"
