#!/usr/bin/env bash
# local-review-verdict.sh — decide whether a PR's review objects carry a qualifying clean LOCAL
# REVIEW ROUND for ONE exact head (monorepo#2697).
#
# WHY THIS EXISTS
#   AGENTS.md (*Local review round*) makes an agent's own posted review a green-review satisfier,
#   reported `green_review=self@<sha>`, when no review lane will deliver at the head. The surveyor
#   applied that rule by eye and missed a valid round on platform#3001 (2026-08-06): the digest
#   reported the PR blocked solely on the review gate while a clean round sat at its head. The
#   same PR also carries empty `devantler` review objects (reply containers), so "a devantler
#   review at the head" is not evidence either. This helper applies the whole shape test.
#
# USAGE
#   local-review-verdict.sh --head <40-hex-sha> [--input <file>|-]
#
#   --head   the FULL 40-character headRefOid (abbreviations are refused).
#   --input  the PR's review objects as returned by `gh api repos/<o>/<r>/pulls/<n>/reviews
#            --paginate` (default: stdin). Several concatenated pages are accepted. The caller
#            still owns the PR-class bind: a local round never qualifies on an EXTERNAL
#            contributor's PR, and this helper does not see who authored the PR.
#   Without --head, `--input -` is REQUIRED and stdin is one or more JSON objects, each with
#            exactly the keys `head` (the same full sha in every object), `per_page` (the page
#            size the request asked for, 1-100, the same in every object) and `reviews` (an
#            array of review objects): the per-page output of `gh api
#            …/pulls/<n>/reviews?per_page=100 --paginate --jq '{head:"<sha>",per_page:100,reviews:.}'`.
#            It is the only shape the surveyor's read-only guard admits for a declared helper,
#            which accepts `--input -` alone (monorepo#2697). A complete read is every page full
#            and the last one short; anything else is refused, because the pipe hides a `gh`
#            that failed part-way and a missing later page could hold the newest round. A PR
#            whose review count is an exact multiple of `per_page` is refused too (it cannot be
#            told apart from a truncated read); read it with `--head` instead.
#
# OUTPUT (one line on stdout)
#   GREEN self@<head>   the newest self-review at the head is clean and fully shaped
#   FINDINGS <n>        the newest self-review at the head reports <n> P0/P1 findings (or <n>
#                       findings with no P0/P1 breakdown); nits alone are GREEN
#   NONE <reason>       no qualifying round at this head; <reason> is one of
#                       no-self-review, no-disclosure, missing-lane:<lane>, no-verdict
#
#   A self-review is a review object authored by `devantler` whose commit_id equals --head and
#   whose body carries a `## Self-review (fallback` heading. It qualifies only when its body
#   also begins with the `> 🤖 Generated by the` disclosure, carries a list line for EACH of
#   CodeRabbit, Codex and Cursor Bugbot, and carries a standard verdict line with no P0/P1 finding.
#
# EXIT CODES
#   0  GREEN
#   1  FINDINGS or NONE — the gate is not satisfied by a local round
#   2  usage error or unreadable/unparseable input — nothing was judged
set -euo pipefail

usage() {
  sed -n '13,48p' "$0" >&2
  exit 2
}

head=""
input="-"
while [ "$#" -gt 0 ]; do
  case "$1" in
    --head)
      [ "$#" -ge 2 ] || usage
      head="$2"
      shift 2
      ;;
    --input)
      [ "$#" -ge 2 ] || usage
      input="$2"
      shift 2
      ;;
    -h | --help) usage ;;
    *) usage ;;
  esac
done

json_mode=0
if [ -z "$head" ]; then
  # Stdin-only JSON mode: the head travels with each page, so the guard's `--input -` is enough.
  [ "$input" = "-" ] || usage
  payload="$(cat)" || exit 2
  # Every page must carry exactly {head, per_page, reviews}, every page the SAME full head (a page
  # for another head spliced in would otherwise be judged against the first page's head) and the
  # same page size. Every page but the last must be full and the last short: the pipe reports the
  # classifier's status, not gh's, so a read that died after a full page looks complete otherwise.
  jq -se 'length >= 1
    and all(.[]; type == "object" and (keys == ["head", "per_page", "reviews"])
      and (.head | type == "string" and length == 40 and (test("[^0-9a-f]") | not))
      and (.per_page | type == "number" and . == floor and . >= 1 and . <= 100)
      and (.reviews | type == "array"))
    and (map(.head) | unique | length == 1)
    and (map(.per_page) | unique | length == 1)
    and (.[0].per_page as $p | all(.[:-1][]; (.reviews | length) == $p)
      and ((.[-1].reviews | length) < $p))' <<<"$payload" >/dev/null 2>&1 || {
    echo "local-review-verdict: stdin must be one or more JSON objects with exactly the keys head, per_page and reviews, all for one head and page size, every page but the last full and the last short (a complete read)" >&2
    exit 2
  }
  head="$(jq -rs '.[0].head' <<<"$payload")" || exit 2
  raw="$(jq -c '.reviews' <<<"$payload")" || exit 2
  json_mode=1
fi

grep -Eq '^[0-9a-f]{40}$' <<<"$head" || {
  echo "local-review-verdict: --head must be a full 40-character lowercase sha" >&2
  exit 2
}

if [ "$json_mode" = 1 ]; then
  :
elif [ "$input" = "-" ]; then
  raw="$(cat)" || exit 2
else
  [ -r "$input" ] || {
    echo "local-review-verdict: cannot read $input" >&2
    exit 2
  }
  raw="$(cat -- "$input")" || exit 2
fi

# Newest self-review at the head. Input that is not one or more JSON arrays — empty, null, a bare
# object, or an API error object after a page — is exit 2, never "no review found": a failed read
# must not look like an answer.
body="$(jq -rs --arg h "$head" '
  if length == 0 or any(.[]; type != "array") then error("not an array of review objects") else . end
  | [ .[][] ]
  | map(select(type == "object"
      and (.user.login // "") == "devantler"
      and (.commit_id // "") == $h
      and (.state // "") == "COMMENTED"
      and ((.body // "") | test("(?m)^##[ \t]+Self-review \\(fallback"))))
  | sort_by(.submitted_at // "")
  | if length == 0 then "" else last.body end
' <<<"$raw")" || {
  echo "local-review-verdict: input is not a JSON array of review objects" >&2
  exit 2
}

verdict() {
  printf '%s\n' "$1"
  case "$1" in GREEN*) exit 0 ;; *) exit 1 ;; esac
}

[ -n "$body" ] || verdict "NONE no-self-review"

# The disclosure must BEGIN the body: it is what marks this as agent output, not maintainer text.
first_line="${body%%$'\n'*}"
case "$first_line" in
  '> 🤖 Generated by the '*) ;;
  *) verdict "NONE no-disclosure" ;;
esac

# The body states the commit it reviewed, and a reader trusts THAT line rather than the object's
# `commit_id`. A body carried over from an earlier head keeps the old SHA while the object it is
# posted in carries the new one, so the two disagreeing means the round was not performed at this
# head — whichever of them is right. Require them to agree (monorepo#3487 review). Bold and
# backticks are formatting, not evidence, so each is optional; the full SHA still has to match.
grep -Eq "^(\*\*)?Reviewed commit:(\*\*)?[[:space:]]+\`?${head}\`?[[:space:]]*$" <<<"$body" ||
  verdict "NONE reviewed-commit-mismatch"

# The fallback is invalid without evidence for every lane.
for lane in "CodeRabbit" "Codex" "Cursor Bugbot"; do
  grep -Eq "^[[:space:]]*[-*][[:space:]]+(\*\*)?${lane}(\*\*)?([^[:alnum:]]|$)" <<<"$body" ||
    verdict "NONE missing-lane:${lane// /-}"
done

# Only P0/P1 findings block (nits do not), so `Verdict: N findings (P0: a, P1: b)` is judged on
# a + b. A count with no P0/P1 breakdown is not the standard shape and cannot be shown to be nits
# only, so it blocks — even a zero count.
count_line="$(sed -nE '/^Verdict:[[:space:]]+[0-9]+[[:space:]]+findings?/{p;q;}' <<<"$body")"
if [ -n "$count_line" ]; then
  total="$(sed -E 's/^Verdict:[[:space:]]+([0-9]+).*/\1/' <<<"$count_line")"
  # Anchor the WHOLE line: an unanchored match let `Verdict: 1 finding (P0: 0, P1: 0) extra`
  # read as a standard counted verdict and return GREEN on trailing text nobody wrote to a
  # contract (monorepo#3487 review). A line that is not exactly the standard form has no
  # demonstrable P0/P1 breakdown, so it falls through to `FINDINGS $total` and blocks.
  blocking="$(sed -nE 's/^Verdict:[[:space:]]+[0-9]+[[:space:]]+findings?[[:space:]]+\(P0:[[:space:]]*([0-9]+),[[:space:]]*P1:[[:space:]]*([0-9]+)\)[[:space:]]*$/\1 \2/p' <<<"$count_line")"
  [ -n "$blocking" ] || verdict "FINDINGS $total"
  p0="${blocking% *}"
  p1="${blocking#* }"
  [ $((p0 + p1)) -gt 0 ] && verdict "FINDINGS $((p0 + p1))"
  verdict "GREEN self@${head}"
fi
grep -Eq '^Verdict:[[:space:]]+no P0/P1 findings[[:space:]]*$' <<<"$body" || verdict "NONE no-verdict"

verdict "GREEN self@${head}"
