#!/usr/bin/env bash
# local-review-verdict.test.sh — RED/GREEN proof for local-review-verdict.sh (monorepo#2697).
# The fixture is platform#3001's real `devantler` review objects: one clean local round, one round
# whose verdict is not in the standard shape, and two empty reply containers. Every negative case
# edits ONE conjunct of the real clean round, so a pass cannot come from the wrong check.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "${here}/../.." && pwd)"
tool="${here}/local-review-verdict.sh"
fixture="${here}/fixtures/local-review-round-platform-3001.json"
green_head="63c61e5a251ef35a83ab21e98ec6b4aaecddf26a"
loose_head="db0b8ca7c8af0f26d8acda4556e8769a74b6baa3"
other_head="0123456789abcdef0123456789abcdef01234567"

tmp="$(mktemp -d)"
completed=0
# bash 3.2 can report a set -e abort inside an EXIT trap as exit 0, so require completion.
on_exit() {
  local status=$?
  rm -rf "${tmp}"
  if [ "${completed}" != 1 ] && [ "${status}" = 0 ]; then exit 1; fi
}
trap on_exit EXIT
failures=0
checks=0

expect() { # expect <name> <want-rc> <want-line> <head> <input-file>
  local name="$1" want_rc="$2" want="$3" head="$4" input="$5" got rc
  checks=$((checks + 1))
  set +e
  got="$(bash "${tool}" --head "${head}" --input "${input}" 2>"${tmp}/stderr")"
  rc=$?
  set -e
  if [ "${rc}" != "${want_rc}" ] || [ "${got}" != "${want}" ]; then
    echo "FAIL ${name}: want rc=${want_rc} '${want}', got rc=${rc} '${got}' ($(cat "${tmp}/stderr"))" >&2
    failures=$((failures + 1))
  else
    echo "ok   ${name}"
  fi
}

# Rewrite the body of the clean round only, leaving every other review object untouched.
edit_green() { # edit_green <jq-expression-over-.body> <out-file>
  jq --arg h "${green_head}" "map(if .commit_id == \$h and (.body | length) > 0 then .body |= ($1) else . end)" \
    "${fixture}" >"$2"
}

[ -s "${fixture}" ] || { echo "FAIL fixture missing or empty: ${fixture}" >&2; exit 1; }

# RED: the digest's behaviour this replaces. It reported platform#3001 with no qualifying review
# while the clean round sat at the head; the real object is there and fully shaped.
checks=$((checks + 1))
if [ "$(jq --arg h "${green_head}" '[.[] | select(.commit_id == $h and (.body | length) > 0)] | length' "${fixture}")" = 1 ]; then
  echo "ok   RED precondition: the clean round the digest missed is in the fixture at its head"
else
  echo "FAIL RED precondition: the fixture no longer carries the clean round at ${green_head}" >&2
  failures=$((failures + 1))
fi

expect "real clean round at its head" 0 "GREEN self@${green_head}" "${green_head}" "${fixture}"
expect "real clean round, stale head" 1 "NONE no-self-review" "${other_head}" "${fixture}"
expect "real round with a non-standard verdict" 1 "NONE no-verdict" "${loose_head}" "${fixture}"

# The empty reply containers alone are not a review, even at the head.
jq '[.[] | select((.body | length) == 0)]' "${fixture}" >"${tmp}/containers.json"
checks=$((checks + 1))
if [ "$(jq 'length' "${tmp}/containers.json")" -ge 1 ]; then echo "ok   fixture carries empty containers"; else
  echo "FAIL fixture carries no empty containers" >&2
  failures=$((failures + 1))
fi
for h in $(jq -r '.[].commit_id' "${tmp}/containers.json" | sort -u); do
  expect "empty containers only at ${h:0:10}" 1 "NONE no-self-review" "${h}" "${tmp}/containers.json"
done

# Ablations on the clean round, one conjunct each.
edit_green 'sub("^> 🤖 Generated by the [^\n]*\n"; "")' "${tmp}/no-disclosure.json"
expect "clean round minus disclosure" 1 "NONE no-disclosure" "${green_head}" "${tmp}/no-disclosure.json"

edit_green '"Some preamble.\n\n" + .' "${tmp}/late-disclosure.json"
expect "disclosure not on the first line" 1 "NONE no-disclosure" "${green_head}" "${tmp}/late-disclosure.json"

edit_green 'gsub("(?m)^- \\*\\*Codex\\*\\*[^\n]*\n"; "")' "${tmp}/no-codex.json"
expect "clean round minus the Codex lane" 1 "NONE missing-lane:Codex" "${green_head}" "${tmp}/no-codex.json"

edit_green 'gsub("(?m)^- \\*\\*Cursor Bugbot\\*\\*[^\n]*\n"; "")' "${tmp}/no-bugbot.json"
expect "clean round minus the Bugbot lane" 1 "NONE missing-lane:Cursor-Bugbot" "${green_head}" "${tmp}/no-bugbot.json"

edit_green 'gsub("(?m)^- \\*\\*CodeRabbit\\*\\*[^\n]*\n"; "")' "${tmp}/no-cr.json"
expect "clean round minus the CodeRabbit lane" 1 "NONE missing-lane:CodeRabbit" "${green_head}" "${tmp}/no-cr.json"

edit_green 'sub("(?m)^Verdict: no P0/P1 findings$"; "Verdict: 2 findings (P0: 0, P1: 2)")' "${tmp}/findings.json"
expect "clean round reporting findings" 1 "FINDINGS 2" "${green_head}" "${tmp}/findings.json"

# Nits alone do not block: only P0/P1 count. A count without that breakdown blocks.
edit_green 'sub("(?m)^Verdict: no P0/P1 findings$"; "Verdict: 3 findings (P0: 0, P1: 0)")' "${tmp}/nits-only.json"
expect "clean round reporting only nits" 0 "GREEN self@${green_head}" "${green_head}" "${tmp}/nits-only.json"
edit_green 'sub("(?m)^Verdict: no P0/P1 findings$"; "Verdict: 2 findings")' "${tmp}/no-breakdown.json"
expect "finding count with no P0/P1 breakdown" 1 "FINDINGS 2" "${green_head}" "${tmp}/no-breakdown.json"
edit_green 'sub("(?m)^Verdict: no P0/P1 findings$"; "Verdict: 0 findings")' "${tmp}/zero-count.json"
expect "an explicit zero count" 0 "GREEN self@${green_head}" "${green_head}" "${tmp}/zero-count.json"

edit_green 'gsub("(?m)^Verdict: no P0/P1 findings$"; "")' "${tmp}/no-verdict.json"
expect "clean round minus its verdict" 1 "NONE no-verdict" "${green_head}" "${tmp}/no-verdict.json"

edit_green 'gsub("(?m)^## Self-review \\(fallback"; "## Review notes (")' "${tmp}/no-heading.json"
expect "clean round minus the fallback heading" 1 "NONE no-self-review" "${green_head}" "${tmp}/no-heading.json"

# Only `devantler` may author a local round; the same body from anyone else is not one.
jq --arg h "${green_head}" 'map(if .commit_id == $h then .user.login = "coderabbitai[bot]" else . end)' \
  "${fixture}" >"${tmp}/other-author.json"
expect "clean round by another author" 1 "NONE no-self-review" "${green_head}" "${tmp}/other-author.json"

# A newer round at the same head decides: a later round with findings defeats the earlier green.
jq --arg h "${green_head}" '
  . + [ (.[] | select(.commit_id == $h and (.body | length) > 0)
        | .submitted_at = "2026-08-06T15:00:00Z"
        | .body |= sub("(?m)^Verdict: no P0/P1 findings$"; "Verdict: 1 finding (P0: 1, P1: 0)")) ]
' "${fixture}" >"${tmp}/newer-findings.json"
expect "newer round with findings at the head" 1 "FINDINGS 1" "${green_head}" "${tmp}/newer-findings.json"

# `gh api --paginate` emits one array per page; both pages are read.
{ jq '[.[0], .[1]]' "${fixture}"; jq '[.[2], .[3]]' "${fixture}"; } >"${tmp}/paged.json"
expect "two concatenated pages" 0 "GREEN self@${green_head}" "${green_head}" "${tmp}/paged.json"

# Unreadable and unparseable input judges nothing, rather than reading as "no round found".
printf 'not json\n' >"${tmp}/garbage.json"
expect "unparseable input" 2 "" "${green_head}" "${tmp}/garbage.json"
expect "missing input file" 2 "" "${green_head}" "${tmp}/does-not-exist.json"
expect "abbreviated head" 2 "" "${green_head:0:10}" "${fixture}"

# The contract names the helper where the local round is defined, so a reader finds it.
checks=$((checks + 1))
if grep -Fq 'local-review-verdict.sh' "${root}/AGENTS.md"; then
  echo "ok   contract: AGENTS.md names local-review-verdict.sh"
else
  echo "FAIL contract: AGENTS.md must name local-review-verdict.sh" >&2
  failures=$((failures + 1))
fi

completed=1
echo "local-review-verdict: ${checks} checks, ${failures} failures"
[ "${failures}" -eq 0 ]
