#!/usr/bin/env bash
# local-review-verdict.test.sh — RED/GREEN proof for local-review-verdict.sh (monorepo#2697).
# The fixture is platform#3001's real `devantler` review objects: one clean local round, one round
# whose verdict is not in the standard shape, and two empty reply containers. Every negative case
# edits ONE conjunct of the real clean round, so a pass cannot come from the wrong check.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "${here}/../.." && pwd)"
tool="${here}/local-review-verdict.sh"
fixture="${here}/fixtures/local-review-round-platform-3001.json"
green_head="63c61e5a251ef35a83ab21e98ec6b4aaecddf26a"
loose_head="db0b8ca7c8af0f26d8acda4556e8769a74b6baa3"
other_head="0123456789abcdef0123456789abcdef01234567"

tmp="$(mktemp -d)"
completed=0
# bash 3.2 can report a set -e abort inside an EXIT trap as exit 0, so require completion.
on_exit() {
  local status=$?
  rm -rf "${tmp}"
  if [ "${completed}" != 1 ] && [ "${status}" = 0 ]; then exit 1; fi
}
trap on_exit EXIT
failures=0
checks=0

expect() { # expect <name> <want-rc> <want-line> <head> <input-file>
  local name="$1" want_rc="$2" want="$3" head="$4" input="$5" got rc
  checks=$((checks + 1))
  set +e
  got="$(bash "${tool}" --head "${head}" --input "${input}" 2>"${tmp}/stderr")"
  rc=$?
  set -e
  if [ "${rc}" != "${want_rc}" ] || [ "${got}" != "${want}" ]; then
    echo "FAIL ${name}: want rc=${want_rc} '${want}', got rc=${rc} '${got}' ($(cat "${tmp}/stderr"))" >&2
    failures=$((failures + 1))
  else
    echo "ok   ${name}"
  fi
}

# Rewrite the body of the clean round only, leaving every other review object untouched.
edit_green() { # edit_green <jq-expression-over-.body> <out-file>
  jq --arg h "${green_head}" "map(if .commit_id == \$h and (.body | length) > 0 then .body |= ($1) else . end)" \
    "${fixture}" >"$2"
}

[ -s "${fixture}" ] || { echo "FAIL fixture missing or empty: ${fixture}" >&2; exit 1; }

# RED: the digest's behaviour this replaces. It reported platform#3001 with no qualifying review
# while the clean round sat at the head; the real object is there and fully shaped.
checks=$((checks + 1))
if [ "$(jq --arg h "${green_head}" '[.[] | select(.commit_id == $h and (.body | length) > 0)] | length' "${fixture}")" = 1 ]; then
  echo "ok   RED precondition: the clean round the digest missed is in the fixture at its head"
else
  echo "FAIL RED precondition: the fixture no longer carries the clean round at ${green_head}" >&2
  failures=$((failures + 1))
fi

expect "real clean round at its head" 0 "GREEN self@${green_head}" "${green_head}" "${fixture}"
expect "real clean round, stale head" 1 "NONE no-self-review" "${other_head}" "${fixture}"
expect "real round with a non-standard verdict" 1 "NONE no-verdict" "${loose_head}" "${fixture}"

# The empty reply containers alone are not a review, even at the head.
jq '[.[] | select((.body | length) == 0)]' "${fixture}" >"${tmp}/containers.json"
checks=$((checks + 1))
if [ "$(jq 'length' "${tmp}/containers.json")" -ge 1 ]; then echo "ok   fixture carries empty containers"; else
  echo "FAIL fixture carries no empty containers" >&2
  failures=$((failures + 1))
fi
for h in $(jq -r '.[].commit_id' "${tmp}/containers.json" | sort -u); do
  expect "empty containers only at ${h:0:10}" 1 "NONE no-self-review" "${h}" "${tmp}/containers.json"
done

# Ablations on the clean round, one conjunct each.
edit_green 'sub("^> 🤖 Generated by the [^\n]*\n"; "")' "${tmp}/no-disclosure.json"
expect "clean round minus disclosure" 1 "NONE no-disclosure" "${green_head}" "${tmp}/no-disclosure.json"

edit_green '"Some preamble.\n\n" + .' "${tmp}/late-disclosure.json"
expect "disclosure not on the first line" 1 "NONE no-disclosure" "${green_head}" "${tmp}/late-disclosure.json"
edit_green '"\n" + .' "${tmp}/blank-first-line.json"
expect "disclosure after a blank first line" 1 "NONE no-disclosure" "${green_head}" "${tmp}/blank-first-line.json"

edit_green 'gsub("(?m)^- \\*\\*Codex\\*\\*[^\n]*\n"; "")' "${tmp}/no-codex.json"
expect "clean round minus the Codex lane" 1 "NONE missing-lane:Codex" "${green_head}" "${tmp}/no-codex.json"

edit_green 'gsub("(?m)^- \\*\\*Cursor Bugbot\\*\\*[^\n]*\n"; "")' "${tmp}/no-bugbot.json"
expect "clean round minus the Bugbot lane" 1 "NONE missing-lane:Cursor-Bugbot" "${green_head}" "${tmp}/no-bugbot.json"

edit_green 'gsub("(?m)^- \\*\\*CodeRabbit\\*\\*[^\n]*\n"; "")' "${tmp}/no-cr.json"
expect "clean round minus the CodeRabbit lane" 1 "NONE missing-lane:CodeRabbit" "${green_head}" "${tmp}/no-cr.json"

edit_green 'sub("(?m)^Verdict: no P0/P1 findings$"; "Verdict: 2 findings (P0: 0, P1: 2)")' "${tmp}/findings.json"
expect "clean round reporting findings" 1 "FINDINGS 2" "${green_head}" "${tmp}/findings.json"

# Nits alone do not block: only P0/P1 count. A count without that breakdown blocks, even zero,
# because it is not the standard verdict shape.
edit_green 'sub("(?m)^Verdict: no P0/P1 findings$"; "Verdict: 3 findings (P0: 0, P1: 0)")' "${tmp}/nits-only.json"
expect "clean round reporting only nits" 0 "GREEN self@${green_head}" "${green_head}" "${tmp}/nits-only.json"
edit_green 'sub("(?m)^Verdict: no P0/P1 findings$"; "Verdict: 2 findings")' "${tmp}/no-breakdown.json"
expect "finding count with no P0/P1 breakdown" 1 "FINDINGS 2" "${green_head}" "${tmp}/no-breakdown.json"
edit_green 'sub("(?m)^Verdict: no P0/P1 findings$"; "Verdict: 0 findings")' "${tmp}/zero-count.json"
expect "zero count with no P0/P1 breakdown" 1 "FINDINGS 0" "${green_head}" "${tmp}/zero-count.json"

# --- the three conjuncts added after the monorepo#3487 review, one ablation each ----------
# Rewrite a FIELD of the clean round's object rather than its body.
edit_green_obj() { # edit_green_obj <jq-expression-over-the-object> <out-file>
  jq --arg h "${green_head}" "map(if .commit_id == \$h and (.body | length) > 0 then ($1) else . end)" \
    "${fixture}" >"$2"
}

# 1. The contract prescribes `event: COMMENT`, so the round is a COMMENTED review. An APPROVED or
#    CHANGES_REQUESTED object with an otherwise perfect body is not one — and an approval is
#    exactly the shape that must never satisfy a gate on one's own work.
edit_green_obj '.state = "APPROVED"' "${tmp}/approved.json"
expect "clean round submitted as APPROVED" 1 "NONE no-self-review" "${green_head}" "${tmp}/approved.json"
edit_green_obj '.state = "CHANGES_REQUESTED"' "${tmp}/changes-requested.json"
expect "clean round submitted as CHANGES_REQUESTED" 1 "NONE no-self-review" "${green_head}" "${tmp}/changes-requested.json"
# CONTROL: the same object explicitly re-stamped COMMENTED is still GREEN, so the two above fail
# on the state and not on the rewrite itself.
edit_green_obj '.state = "COMMENTED"' "${tmp}/commented.json"
expect "control: explicitly COMMENTED is still green" 0 "GREEN self@${green_head}" "${green_head}" "${tmp}/commented.json"

# 2. The body names the commit it reviewed, and a reader trusts that line over the object's
#    commit_id. A body carried over from an earlier head keeps the old SHA.
edit_green "sub(\"(?m)^\\\\*\\\\*Reviewed commit:\\\\*\\\\* \`${green_head}\`$\"; \"**Reviewed commit:** \`${other_head}\`\")" "${tmp}/stale-body-sha.json"
expect "body names a DIFFERENT commit than the object" 1 "NONE reviewed-commit-mismatch" "${green_head}" "${tmp}/stale-body-sha.json"
# The line's formatting is not the contract: rounds posted without backticks or without bold still
# name the head exactly, and rejecting them re-spends review quota on already-reviewed work.
edit_green "sub(\"(?m)^\\\\*\\\\*Reviewed commit:\\\\*\\\\* \`${green_head}\`$\"; \"**Reviewed commit:** ${green_head}\")" "${tmp}/sha-no-backticks.json"
expect "reviewed commit without backticks" 0 "GREEN self@${green_head}" "${green_head}" "${tmp}/sha-no-backticks.json"
edit_green "sub(\"(?m)^\\\\*\\\\*Reviewed commit:\\\\*\\\\* \`${green_head}\`$\"; \"Reviewed commit: \`${green_head}\`\")" "${tmp}/sha-no-bold.json"
expect "reviewed commit without bold" 0 "GREEN self@${green_head}" "${green_head}" "${tmp}/sha-no-bold.json"
# CONTROL: the relaxed form still binds the SHA — a different commit without backticks is rejected.
edit_green "sub(\"(?m)^\\\\*\\\\*Reviewed commit:\\\\*\\\\* \`${green_head}\`$\"; \"**Reviewed commit:** ${other_head}\")" "${tmp}/stale-sha-no-backticks.json"
expect "control: a different commit without backticks" 1 "NONE reviewed-commit-mismatch" "${green_head}" "${tmp}/stale-sha-no-backticks.json"
# A GREEN from an edit that never matched would pass on the unmodified round, so prove each edit landed.
edit_green '.' "${tmp}/identity.json"
for edited in sha-no-backticks sha-no-bold stale-sha-no-backticks; do
  checks=$((checks + 1))
  if cmp -s "${tmp}/identity.json" "${tmp}/${edited}.json"; then
    echo "FAIL fixture edit ${edited} changed nothing" >&2
    failures=$((failures + 1))
  else
    echo "ok   fixture edit ${edited} changed the round"
  fi
done

# 3. The counted verdict must be the WHOLE line. Unanchored, `… (P0: 0, P1: 0) extra` read as a
#    standard breakdown and returned GREEN on text nobody wrote to a contract.
edit_green 'sub("(?m)^Verdict: no P0/P1 findings$"; "Verdict: 1 finding (P0: 0, P1: 0) extra")' "${tmp}/verdict-trailing.json"
expect "counted verdict with trailing text" 1 "FINDINGS 1" "${green_head}" "${tmp}/verdict-trailing.json"
# CONTROL: the identical line WITHOUT the trailing text is GREEN, so the ablation fires on the
# trailing text rather than on the singular "finding" or the zero counts.
edit_green 'sub("(?m)^Verdict: no P0/P1 findings$"; "Verdict: 1 finding (P0: 0, P1: 0)")' "${tmp}/verdict-clean.json"
expect "control: the same counted verdict without trailing text" 0 "GREEN self@${green_head}" "${green_head}" "${tmp}/verdict-clean.json"

edit_green 'gsub("(?m)^Verdict: no P0/P1 findings$"; "")' "${tmp}/no-verdict.json"
expect "clean round minus its verdict" 1 "NONE no-verdict" "${green_head}" "${tmp}/no-verdict.json"

edit_green 'gsub("(?m)^## Self-review \\(fallback"; "## Review notes (")' "${tmp}/no-heading.json"
expect "clean round minus the fallback heading" 1 "NONE no-self-review" "${green_head}" "${tmp}/no-heading.json"

# Only `devantler` may author a local round; the same body from anyone else is not one.
jq --arg h "${green_head}" 'map(if .commit_id == $h then .user.login = "coderabbitai[bot]" else . end)' \
  "${fixture}" >"${tmp}/other-author.json"
expect "clean round by another author" 1 "NONE no-self-review" "${green_head}" "${tmp}/other-author.json"

# A newer round at the same head decides: a later round with findings defeats the earlier green.
jq --arg h "${green_head}" '
  . + [ (.[] | select(.commit_id == $h and (.body | length) > 0)
        | .submitted_at = "2026-08-06T15:00:00Z"
        | .body |= sub("(?m)^Verdict: no P0/P1 findings$"; "Verdict: 1 finding (P0: 1, P1: 0)")) ]
' "${fixture}" >"${tmp}/newer-findings.json"
expect "newer round with findings at the head" 1 "FINDINGS 1" "${green_head}" "${tmp}/newer-findings.json"

# `gh api --paginate` emits one array per page; both pages are read.
{ jq '[.[0], .[1]]' "${fixture}"; jq '[.[2], .[3]]' "${fixture}"; } >"${tmp}/paged.json"
expect "two concatenated pages" 0 "GREEN self@${green_head}" "${green_head}" "${tmp}/paged.json"

# Unreadable and unparseable input judges nothing, rather than reading as "no round found".
printf 'not json\n' >"${tmp}/garbage.json"
expect "unparseable input" 2 "" "${green_head}" "${tmp}/garbage.json"
: >"${tmp}/empty.json"
expect "empty input" 2 "" "${green_head}" "${tmp}/empty.json"
printf 'null\n' >"${tmp}/null.json"
expect "null input" 2 "" "${green_head}" "${tmp}/null.json"
jq '.[0]' "${fixture}" >"${tmp}/object.json"
expect "a bare review object instead of an array" 2 "" "${green_head}" "${tmp}/object.json"
{ jq '.' "${fixture}"; printf '{"message":"Bad credentials"}\n'; } >"${tmp}/array-then-object.json"
expect "an error object after a page" 2 "" "${green_head}" "${tmp}/array-then-object.json"
expect "missing input file" 2 "" "${green_head}" "${tmp}/does-not-exist.json"
expect "abbreviated head" 2 "" "${green_head:0:10}" "${fixture}"

# Stdin JSON mode (monorepo#2697): the surveyor guard admits a declared helper only as `--input -`,
# so the head travels in each page object. It must judge exactly as `--head` does.
expect_json() { # expect_json <name> <want-rc> <want-line> <stdin-file>
  local name="$1" want_rc="$2" want="$3" input="$4" got rc
  checks=$((checks + 1))
  set +e
  got="$(bash "${tool}" --input - <"${input}" 2>"${tmp}/stderr")"
  rc=$?
  set -e
  if [ "${rc}" != "${want_rc}" ] || [ "${got}" != "${want}" ]; then
    echo "FAIL ${name}: want rc=${want_rc} '${want}', got rc=${rc} '${got}' ($(cat "${tmp}/stderr"))" >&2
    failures=$((failures + 1))
  else
    echo "ok   ${name}"
  fi
}
# Parity: every fixture judged above, at every head, gives the same line and status both ways.
for f in "${fixture}" "${tmp}/newer-findings.json" "${tmp}/no-disclosure.json" "${tmp}/no-verdict.json"; do
  for h in "${green_head}" "${loose_head}" "${other_head}"; do
    set +e
    want="$(bash "${tool}" --head "${h}" --input "${f}" 2>/dev/null)"
    want_rc=$?
    set -e
    jq -c --arg h "${h}" '{head: $h, reviews: .}' "${f}" >"${tmp}/json-parity.json"
    expect_json "json parity $(basename "${f}") @${h:0:10}" "${want_rc}" "${want}" "${tmp}/json-parity.json"
  done
done
# Two pages, as `--paginate --jq` emits them, are both read.
{ jq -c --arg h "${green_head}" '{head: $h, reviews: [.[0], .[1]]}' "${fixture}"
  jq -c --arg h "${green_head}" '{head: $h, reviews: [.[2], .[3]]}' "${fixture}"; } >"${tmp}/json-paged.json"
expect_json "json: two page objects" 0 "GREEN self@${green_head}" "${tmp}/json-paged.json"
# Ablations, one conjunct each, against that passing two-page input.
{ jq -c --arg h "${green_head}" '{head: $h, reviews: [.[0], .[1]]}' "${fixture}"
  jq -c --arg h "${other_head}" '{head: $h, reviews: [.[2], .[3]]}' "${fixture}"; } >"${tmp}/json-mixed.json"
expect_json "json: pages disagree on the head" 2 "" "${tmp}/json-mixed.json"
jq -c --arg h "${green_head}" '{head: $h, reviews: ., extra: 1}' "${fixture}" >"${tmp}/json-extra.json"
expect_json "json: an extra key" 2 "" "${tmp}/json-extra.json"
jq -c --arg h "${green_head:0:10}" '{head: $h, reviews: .}' "${fixture}" >"${tmp}/json-short.json"
expect_json "json: abbreviated head" 2 "" "${tmp}/json-short.json"
jq -c --arg h "${green_head}" '{head: $h, reviews: .[0]}' "${fixture}" >"${tmp}/json-object.json"
expect_json "json: reviews is not an array" 2 "" "${tmp}/json-object.json"
jq -c '.' "${fixture}" >"${tmp}/json-bare.json"
expect_json "json: bare pages with no head" 2 "" "${tmp}/json-bare.json"
expect_json "json: empty stdin" 2 "" "${tmp}/empty.json"
checks=$((checks + 1))
if bash "${tool}" --input "${tmp}/json-paged.json" >/dev/null 2>&1; then
  echo "FAIL json: a FILE without --head must be refused (stdin only)" >&2
  failures=$((failures + 1))
else echo "ok   json: a file without --head is refused"; fi

# The contract names the helper where the local round is defined, so a reader finds it.
checks=$((checks + 1))
if grep -Fq 'local-review-verdict.sh' "${root}/AGENTS.md"; then
  echo "ok   contract: AGENTS.md names local-review-verdict.sh"
else
  echo "FAIL contract: AGENTS.md must name local-review-verdict.sh" >&2
  failures=$((failures + 1))
fi

completed=1
echo "local-review-verdict: ${checks} checks, ${failures} failures"
[ "${failures}" -eq 0 ]
