#!/usr/bin/env bash
# local-review-verdict.sh — decide whether a PR's review objects carry a qualifying clean LOCAL
# REVIEW ROUND for ONE exact head (monorepo#2697).
#
# WHY THIS EXISTS
#   AGENTS.md (*Local review round*) makes an agent's own posted review a green-review satisfier,
#   reported `green_review=self@<sha>`, when no review lane will deliver at the head. The surveyor
#   applied that rule by eye and missed a valid round on platform#3001 (2026-08-06): the digest
#   reported the PR blocked solely on the review gate while a clean round sat at its head. The
#   same PR also carries empty `devantler` review objects (reply containers), so "a devantler
#   review at the head" is not evidence either. This helper applies the whole shape test.
#
# USAGE
#   local-review-verdict.sh --head <40-hex-sha> [--input <file>|-]
#
#   --head   the FULL 40-character headRefOid (abbreviations are refused).
#   --input  the PR's review objects as returned by `gh api repos/<o>/<r>/pulls/<n>/reviews
#            --paginate` (default: stdin). Several concatenated pages are accepted. The caller
#            still owns the PR-class bind: a local round never qualifies on an EXTERNAL
#            contributor's PR, and this helper does not see who authored the PR.
#   Without --head, `--input -` is REQUIRED and stdin is the raw pages of
#            `gh api graphql --paginate -F number=<n> -f query='query($number:Int!,
#            $endCursor:String){repository(owner:"<o>",name:"<r>"){pullRequest(number:$number){
#            headRefOid reviews(first:100,after:$endCursor){totalCount nodes{author{login} state
#            body submittedAt commit{oid}} pageInfo{hasNextPage endCursor}}}}}'`. The head is the
#            PR's `headRefOid`, which must be the same on every page. It is the only shape the
#            surveyor's read-only guard admits for a declared helper, which accepts `--input -`
#            alone (monorepo#2697). The pipe reports this helper's status, not gh's, so a read is
#            judged only when it is provably complete: the reviews fetched equal `totalCount`,
#            every page agrees on it, and the last page has no next page. Anything else exits 2.
#
# OUTPUT (one line on stdout)
#   GREEN self@<head>   the newest self-review at the head is clean and fully shaped
#   FINDINGS <n>        the newest self-review at the head reports <n> P0/P1 findings (or <n>
#                       findings with no P0/P1 breakdown); nits alone are GREEN
#   NONE <reason>       no qualifying round at this head; <reason> is one of
#                       no-self-review, no-disclosure, missing-lane:<lane>, no-verdict
#
#   A self-review is a review object authored by `devantler` whose commit_id equals --head and
#   whose body carries a `## Self-review (fallback` heading. It qualifies only when its body
#   also begins with the `> 🤖 Generated by the` disclosure, carries a list line for EACH of
#   CodeRabbit, Codex and Cursor Bugbot, and carries a standard verdict line with no P0/P1 finding.
#
# EXIT CODES
#   0  GREEN
#   1  FINDINGS or NONE — the gate is not satisfied by a local round
#   2  usage error or unreadable/unparseable input — nothing was judged
set -euo pipefail

usage() {
  sed -n '13,47p' "$0" >&2
  exit 2
}

head=""
input="-"
while [ "$#" -gt 0 ]; do
  case "$1" in
    --head)
      [ "$#" -ge 2 ] || usage
      head="$2"
      shift 2
      ;;
    --input)
      [ "$#" -ge 2 ] || usage
      input="$2"
      shift 2
      ;;
    -h | --help) usage ;;
    *) usage ;;
  esac
done

json_mode=0
if [ -z "$head" ]; then
  # Stdin-only GraphQL mode: the head travels in each page, so the guard's `--input -` is enough.
  [ "$input" = "-" ] || usage
  payload="$(cat)" || exit 2
  # The pipe reports this helper's status, not gh's, so a read that died part-way would otherwise
  # look complete, and a missing page could hold the newest round. Judge only a read that GraphQL
  # itself shows is complete: every page for one head and one totalCount, the reviews fetched
  # equal to that totalCount, and no next page after the last.
  jq -se 'length >= 1
    and all(.[]; type == "object" and (.errors == null)
      and (.data.repository.pullRequest | type == "object")
      and (.data.repository.pullRequest.headRefOid | type == "string" and length == 40
        and (test("[^0-9a-f]") | not))
      and (.data.repository.pullRequest.reviews.totalCount | type == "number")
      and (.data.repository.pullRequest.reviews.nodes | type == "array"))
    and (map(.data.repository.pullRequest.headRefOid) | unique | length == 1)
    and (map(.data.repository.pullRequest.reviews.totalCount) | unique | length == 1)
    and ((map(.data.repository.pullRequest.reviews.nodes | length) | add)
      == .[0].data.repository.pullRequest.reviews.totalCount)
    and (.[-1].data.repository.pullRequest.reviews.pageInfo.hasNextPage == false)' \
    <<<"$payload" >/dev/null 2>&1 || {
    echo "local-review-verdict: stdin must be the complete GraphQL review pages for one head (reviews fetched must equal totalCount)" >&2
    exit 2
  }
  head="$(jq -rs '.[0].data.repository.pullRequest.headRefOid' <<<"$payload")" || exit 2
  # Present the nodes in the REST shape the judgement below reads.
  raw="$(jq -cs '[.[].data.repository.pullRequest.reviews.nodes[]
    | {user: {login: (.author.login // "")}, commit_id: (.commit.oid // ""), state, body,
       submitted_at: .submittedAt}]' <<<"$payload")" || exit 2
  json_mode=1
fi

grep -Eq '^[0-9a-f]{40}$' <<<"$head" || {
  echo "local-review-verdict: --head must be a full 40-character lowercase sha" >&2
  exit 2
}

if [ "$json_mode" = 1 ]; then
  :
elif [ "$input" = "-" ]; then
  raw="$(cat)" || exit 2
else
  [ -r "$input" ] || {
    echo "local-review-verdict: cannot read $input" >&2
    exit 2
  }
  raw="$(cat -- "$input")" || exit 2
fi

# Newest self-review at the head. Input that is not one or more JSON arrays — empty, null, a bare
# object, or an API error object after a page — is exit 2, never "no review found": a failed read
# must not look like an answer.
body="$(jq -rs --arg h "$head" '
  if length == 0 or any(.[]; type != "array") then error("not an array of review objects") else . end
  | [ .[][] ]
  | map(select(type == "object"
      and (.user.login // "") == "devantler"
      and (.commit_id // "") == $h
      and (.state // "") == "COMMENTED"
      and ((.body // "") | test("(?m)^##[ \t]+Self-review \\(fallback"))))
  | sort_by(.submitted_at // "")
  | if length == 0 then "" else last.body end
' <<<"$raw")" || {
  echo "local-review-verdict: input is not a JSON array of review objects" >&2
  exit 2
}

verdict() {
  printf '%s\n' "$1"
  case "$1" in GREEN*) exit 0 ;; *) exit 1 ;; esac
}

[ -n "$body" ] || verdict "NONE no-self-review"

# The disclosure must BEGIN the body: it is what marks this as agent output, not maintainer text.
first_line="${body%%$'\n'*}"
case "$first_line" in
  '> 🤖 Generated by the '*) ;;
  *) verdict "NONE no-disclosure" ;;
esac

# The body states the commit it reviewed, and a reader trusts THAT line rather than the object's
# `commit_id`. A body carried over from an earlier head keeps the old SHA while the object it is
# posted in carries the new one, so the two disagreeing means the round was not performed at this
# head — whichever of them is right. Require them to agree (monorepo#3487 review). Bold and
# backticks are formatting, not evidence, so each is optional; the full SHA still has to match.
grep -Eq "^(\*\*)?Reviewed commit:(\*\*)?[[:space:]]+\`?${head}\`?[[:space:]]*$" <<<"$body" ||
  verdict "NONE reviewed-commit-mismatch"

# The fallback is invalid without evidence for every lane.
for lane in "CodeRabbit" "Codex" "Cursor Bugbot"; do
  grep -Eq "^[[:space:]]*[-*][[:space:]]+(\*\*)?${lane}(\*\*)?([^[:alnum:]]|$)" <<<"$body" ||
    verdict "NONE missing-lane:${lane// /-}"
done

# Only P0/P1 findings block (nits do not), so `Verdict: N findings (P0: a, P1: b)` is judged on
# a + b. A count with no P0/P1 breakdown is not the standard shape and cannot be shown to be nits
# only, so it blocks — even a zero count.
count_line="$(sed -nE '/^Verdict:[[:space:]]+[0-9]+[[:space:]]+findings?/{p;q;}' <<<"$body")"
if [ -n "$count_line" ]; then
  total="$(sed -E 's/^Verdict:[[:space:]]+([0-9]+).*/\1/' <<<"$count_line")"
  # Anchor the WHOLE line: an unanchored match let `Verdict: 1 finding (P0: 0, P1: 0) extra`
  # read as a standard counted verdict and return GREEN on trailing text nobody wrote to a
  # contract (monorepo#3487 review). A line that is not exactly the standard form has no
  # demonstrable P0/P1 breakdown, so it falls through to `FINDINGS $total` and blocks.
  blocking="$(sed -nE 's/^Verdict:[[:space:]]+[0-9]+[[:space:]]+findings?[[:space:]]+\(P0:[[:space:]]*([0-9]+),[[:space:]]*P1:[[:space:]]*([0-9]+)\)[[:space:]]*$/\1 \2/p' <<<"$count_line")"
  [ -n "$blocking" ] || verdict "FINDINGS $total"
  p0="${blocking% *}"
  p1="${blocking#* }"
  [ $((p0 + p1)) -gt 0 ] && verdict "FINDINGS $((p0 + p1))"
  verdict "GREEN self@${head}"
fi
grep -Eq '^Verdict:[[:space:]]+no P0/P1 findings[[:space:]]*$' <<<"$body" || verdict "NONE no-verdict"

verdict "GREEN self@${head}"
