#!/usr/bin/env bash
#
# Behavioural test for maintainer-comment-candidates.sh (monorepo#3163).
#
# The wrapper is the surveyor's declared classifier for the maintainer-comment sweep, so this
# drives it exactly as the guard admits it — the payload on stdin, `--input -` and nothing
# else — and pins the property the issue is about: a row's artifact number, class and
# permalink come from the comment record itself, never from whatever artifact the caller was
# iterating over, and a payload that cannot prove that is UNKNOWN rather than clean.
set -Eeuo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tool="${here}/maintainer-comment-candidates.sh"

failures=0
checks=0
tmpdir="$(mktemp -d "${TMPDIR:-/tmp}/maintainer-comment-candidates-test.XXXXXX")"
# shellcheck disable=SC2317,SC2329 # Invoked indirectly by the EXIT trap.
cleanup() { rm -rf -- "${tmpdir}"; }
trap cleanup EXIT

fail() {
  echo "FAIL  $1"
  failures=$((failures + 1))
}

# run <stdin-file> <args...>: runs the tool, leaving stdout/stderr/status in tmpdir.
run() {
  local input="$1"
  shift
  local status=0
  "${tool}" "$@" <"${input}" >"${tmpdir}/out" 2>"${tmpdir}/err" || status=$?
  printf '%s\n' "${status}" >"${tmpdir}/status"
}

expect_status() {
  checks=$((checks + 1))
  local got
  got="$(cat "${tmpdir}/status")"
  if [ "${got}" = "$1" ]; then
    echo "ok    $2"
  else
    fail "$2: exit ${got}, want $1"
    sed 's/^/        /' "${tmpdir}/err" | head -5
  fi
}

expect_out() {
  checks=$((checks + 1))
  if grep -qF -- "$1" "${tmpdir}/out"; then
    echo "ok    $2"
  else
    fail "$2: stdout lacks: $1"
    sed 's/^/        /' "${tmpdir}/out" | head -10
  fi
}

expect_no_out() {
  checks=$((checks + 1))
  if grep -qF -- "$1" "${tmpdir}/out"; then
    fail "$2: stdout unexpectedly has: $1"
  else
    echo "ok    $2"
  fi
}

[ -x "${tool}" ] || {
  echo "FAIL  ${tool} is missing or not executable"
  exit 1
}

# 1. The 2026-09-02 shape: the real undisclosed comment lives on platform#3275. However the
#    surveyor came to read it — here interleaved with #3239's disclosed comments, as one
#    paginated REST read would carry them — the row names #3275 and its own permalink.
cat >"${tmpdir}/regression.json" <<'JSON'
[{"user":{"login":"devantler"},"body":"> 🤖 Generated by the Agentic Engineer\n\nStatus note.","created_at":"2026-08-29T18:23:09Z","html_url":"https://github.com/devantler-tech/platform/issues/3239#issuecomment-5337878100","issue_url":"https://api.github.com/repos/devantler-tech/platform/issues/3239"}]
[{"user":{"login":"devantler"},"body":"The merged scanner upgrade removed the local-mode abort.","created_at":"2026-08-28T19:51:48Z","html_url":"https://github.com/devantler-tech/platform/issues/3275#issuecomment-5457089789","issue_url":"https://api.github.com/repos/devantler-tech/platform/issues/3275"}]
JSON
run "${tmpdir}/regression.json" --input -
expect_status 0 "regression payload classifies"
# shellcheck disable=SC2016 # the backticks are literal digest text, not a substitution
expect_out 'CANDIDATE-MAINTAINER-ISSUE-COMMENT platform #3275 — `devantler` @2026-08-28T19:51:48Z: "The merged scanner upgrade removed the local-mode abort." https://github.com/devantler-tech/platform/issues/3275#issuecomment-5457089789' \
  "row names the artifact the comment lives on, with its permalink"
expect_no_out 'platform #3239' "the disclosed neighbour is never reported"
expect_out 'CANDIDATE-SCAN author=devantler records=2 considered=2 disclosed=1 maintainer=1 sibling=0 empty=0 artifacts=platform#3239,platform#3275' \
  "closing line accounts for every record and every artifact"

# 2. The shape the overlay actually pipes: `gh issue view <n> --json comments`.
cat >"${tmpdir}/gh-view.json" <<'JSON'
{"comments":[{"author":{"login":"coderabbitai"},"body":"Summary","createdAt":"2026-08-19T05:21:55Z","url":"https://github.com/devantler-tech/platform/issues/3275#issuecomment-1"},{"author":{"login":"devantler"},"body":"> Requested by the 🤖 Daily AI Engineer — CI is green","createdAt":"2026-08-20T00:00:00Z","url":"https://github.com/devantler-tech/platform/issues/3275#issuecomment-2"}]}
JSON
run "${tmpdir}/gh-view.json" --input -
expect_status 0 "gh view payload classifies"
# shellcheck disable=SC2016 # the backticks are literal digest text, not a substitution
expect_out 'CANDIDATE-SIBLING-ISSUE-COMMENT platform #3275 (missing disclosure) — `devantler` @2026-08-20T00:00:00Z:' \
  "a leading sender marker is a sibling's output, not a maintainer candidate"
expect_out 'CANDIDATE-SCAN author=devantler records=2 considered=1 disclosed=0 maintainer=0 sibling=1 empty=0 artifacts=platform#3275' \
  "other authors are counted, never reported"

# 3. A file path works too, for an orchestrator re-checking a saved read.
run /dev/null --input "${tmpdir}/gh-view.json"
expect_status 0 "--input <file> classifies"

# 4. Fail closed. A record whose parent disagrees with its permalink, one with no permalink, an
#    empty read (a failed `gh` call piped in) and an error body are all UNKNOWN, with no rows.
cat >"${tmpdir}/diverged.json" <<'JSON'
[{"user":{"login":"devantler"},"body":"steer","html_url":"https://github.com/devantler-tech/platform/issues/3239#issuecomment-1","issue_url":"https://api.github.com/repos/devantler-tech/platform/issues/3275"}]
JSON
run "${tmpdir}/diverged.json" --input -
expect_status 2 "a record whose issue_url disagrees with its permalink is UNKNOWN"
expect_no_out 'CANDIDATE-' "UNKNOWN prints no row and no closing line"

printf '%s\n' '{"comments":[{"author":{"login":"devantler"},"body":"steer"}]}' >"${tmpdir}/no-url.json"
run "${tmpdir}/no-url.json" --input -
expect_status 2 "a comment without a permalink is UNKNOWN"

: >"${tmpdir}/empty.json"
run "${tmpdir}/empty.json" --input -
expect_status 2 "an empty read is UNKNOWN, never a clean zero"
expect_no_out 'CANDIDATE-SCAN' "an empty read prints no closing line"

printf '%s\n' '{"message":"Not Found"}' >"${tmpdir}/error.json"
run "${tmpdir}/error.json" --input -
expect_status 2 "an API error body is UNKNOWN"

# 5. Usage. The guard admits exactly `--input -`; anything else is refused here too, so the
#    wrapper cannot grow a selector the guard would then have to reason about.
run "${tmpdir}/gh-view.json"
expect_status 2 "no --input is a usage error"
run "${tmpdir}/gh-view.json" --input - --repo devantler-tech/platform
expect_status 2 "an extra argument is a usage error"
run "${tmpdir}/gh-view.json" --input "${tmpdir}/does-not-exist.json"
expect_status 2 "an unreadable file is UNKNOWN"
run /dev/null --help
expect_status 0 "--help exits 0"
expect_out 'monorepo#3163' "--help names the motivating issue"

if [ "${failures}" -ne 0 ]; then
  echo "maintainer-comment-candidates.test.sh: ${failures} of ${checks} checks FAILED" >&2
  exit 1
fi
echo "maintainer-comment-candidates.test.sh: all ${checks} checks passed"
