#!/usr/bin/env bash
# Seed and validate agent-authored pull-request bodies at the write boundary.

set -euo pipefail

fail() {
  echo "pr-body contract: FAIL — $*" >&2
  exit 1
}

usage() {
  cat >&2 <<'EOF'
Usage:
  pr-body-contract.sh seed --repo OWNER/REPO --output FILE [--role agentic-engineer|agent-improver]
  pr-body-contract.sh check --repo OWNER/REPO --body-file FILE|-

seed fetches the repository's own default pull-request template, falling back to
OWNER/.github, and prepends the canonical role disclosure. Fill that file without
replacing its visible structure, run check, and pass it to gh with --body-file.
EOF
  exit 2
}

command_name="${1:-}"
[ -n "${command_name}" ] || usage
shift

repo=''
output=''
role='agentic-engineer'
body_file=''

while [ "$#" -gt 0 ]; do
  case "$1" in
    --repo)
      [ "$#" -ge 2 ] || usage
      repo="$2"
      shift 2
      ;;
    --output)
      [ "$#" -ge 2 ] || usage
      output="$2"
      shift 2
      ;;
    --role)
      [ "$#" -ge 2 ] || usage
      role="$2"
      shift 2
      ;;
    --body-file)
      [ "$#" -ge 2 ] || usage
      body_file="$2"
      shift 2
      ;;
    *) usage ;;
  esac
done

case "${repo}" in
  */*) ;;
  *) fail "--repo must be OWNER/REPO" ;;
esac

work_dir="$(mktemp -d)"
trap 'rm -rf "${work_dir}"' EXIT

strip_comments() {
  awk '
    {
      sub(/\r$/, "")
      line = $0
      output = ""
      while (1) {
        if (in_comment) {
          comment_end = index(line, "-->")
          if (comment_end == 0) {
            line = ""
            break
          }
          line = substr(line, comment_end + 3)
          in_comment = 0
          continue
        }

        comment_start = index(line, "<!--")
        if (comment_start == 0) {
          output = output line
          line = ""
          break
        }
        output = output substr(line, 1, comment_start - 1)
        line = substr(line, comment_start + 4)
        in_comment = 1
      }

      if (!in_comment || length(output) > 0) {
        print output
      }
    }
  ' "$1"
}

fetch_raw() {
  local source_repo="$1"
  local source_path="$2"
  local destination="$3"

  env -u GH_TOKEN -u GITHUB_TOKEN gh api \
    -H 'Accept: application/vnd.github.raw+json' \
    "repos/${source_repo}/contents/${source_path}" \
    >"${destination}" 2>/dev/null && [ -s "${destination}" ]
}

resolve_template() {
  local target_repo="$1"
  local destination="$2"
  local owner="${target_repo%%/*}"
  local candidate

  for candidate in \
    '.github/PULL_REQUEST_TEMPLATE.md' \
    '.github/pull_request_template.md' \
    'PULL_REQUEST_TEMPLATE.md' \
    'pull_request_template.md' \
    'docs/PULL_REQUEST_TEMPLATE.md' \
    'docs/pull_request_template.md'; do
    if fetch_raw "${target_repo}" "${candidate}" "${destination}"; then
      return 0
    fi
  done

  for candidate in \
    '.github/PULL_REQUEST_TEMPLATE.md' \
    '.github/pull_request_template.md'; do
    if fetch_raw "${owner}/.github" "${candidate}" "${destination}"; then
      return 0
    fi
  done

  fail "no effective GitHub pull request template found for ${target_repo} or ${owner}/.github"
}

validate_template() {
  local template="$1"
  local visible="${work_dir}/template-visible.md"
  strip_comments "${template}" >"${visible}"

  grep -Fqx '## Why' "${visible}" ||
    fail "effective template does not provide the required PM-facing heading: ## Why"
  grep -Fqx '## What' "${visible}" ||
    fail "effective template does not provide the required PM-facing heading: ## What"
}

validate_body() {
  local template="$1"
  local body="$2"
  local visible_template="${work_dir}/template-visible.md"
  local visible_body="${work_dir}/body-visible.md"
  local template_headings="${work_dir}/template-headings"
  local body_headings="${work_dir}/body-headings"
  local first_line
  local heading
  local count
  local line_number
  local previous_line=0
  local issue_count
  local issue_line
  local what_line
  local why_chars
  local what_chars
  local visible_chars

  strip_comments "${template}" >"${visible_template}"
  strip_comments "${body}" >"${visible_body}"
  validate_template "${template}"

  IFS= read -r first_line <"${body}" || fail "body is empty"
  first_line="${first_line%$'\r'}"
  case "${first_line}" in
    '> 🤖 Generated by the Agentic Engineer'|'> 🤖 Generated by the Agent Improver') ;;
    *) fail "first line must be the canonical role disclosure" ;;
  esac

  grep -E '^#{1,6} ' "${visible_template}" >"${template_headings}" || true
  [ -s "${template_headings}" ] || fail "effective template has no visible Markdown headings"
  grep -E '^#{1,6} ' "${visible_body}" >"${body_headings}" || true

  while IFS= read -r heading; do
    count="$(grep -Fxc "${heading}" "${visible_body}" || true)"
    [ "${count}" -eq 1 ] || fail "required template heading is missing: ${heading}"
    line_number="$(grep -nFx "${heading}" "${visible_body}" | head -n 1 | cut -d: -f1)"
    [ "${line_number}" -gt "${previous_line}" ] ||
      fail "template headings are out of order at: ${heading}"
    previous_line="${line_number}"
  done <"${template_headings}"

  while IFS= read -r heading; do
    grep -Fqx "${heading}" "${template_headings}" ||
      fail "body adds a non-template section: ${heading}"
  done <"${body_headings}"

  issue_count="$(grep -Ec '^(Fixes|Part of) #[0-9]+$' "${visible_body}" || true)"
  [ "${issue_count}" -eq 1 ] ||
    fail "body must contain exactly one issue relationship: Fixes #N or Part of #N"
  issue_line="$(grep -nE '^(Fixes|Part of) #[0-9]+$' "${visible_body}" | cut -d: -f1)"
  what_line="$(grep -nFx '## What' "${visible_body}" | cut -d: -f1)"
  [ "${issue_line}" -gt "${what_line}" ] || fail "issue relationship must follow the What section"

  why_chars="$(awk '
    /^## Why$/ { active = 1; next }
    /^## What$/ { active = 0 }
    active { line = $0; gsub(/[[:space:]]/, "", line); total += length(line) }
    END { print total + 0 }
  ' "${visible_body}")"
  what_chars="$(awk '
    /^## What$/ { active = 1; next }
    /^(Fixes|Part of) #[0-9]+$/ { active = 0 }
    active { line = $0; gsub(/[[:space:]]/, "", line); total += length(line) }
    END { print total + 0 }
  ' "${visible_body}")"
  [ "${why_chars}" -gt 0 ] || fail "Why section has no visible explanation"
  [ "${what_chars}" -gt 0 ] || fail "What section has no visible explanation"
  [ "${why_chars}" -le 800 ] || fail "Why section is too long for the PM review surface"
  [ "${what_chars}" -le 800 ] || fail "What section is too long for the PM review surface"

  if awk '
    /^## Why$/ { active = 1; next }
    /^## What$/ { active = 1; next }
    /^(Fixes|Part of) #[0-9]+$/ { active = 0 }
    active && /^[[:space:]]*[-*+] / { found = 1 }
    END { exit found ? 0 : 1 }
  ' "${visible_body}"; then
    fail "Why and What must be short prose, not bullet inventories"
  fi

  if grep -Eq '^[[:space:]]*(```|~~~)' "${visible_body}"; then
    fail "PR body must not contain code or command fences"
  fi

  visible_chars="$(wc -c <"${visible_body}" | tr -d '[:space:]')"
  [ "${visible_chars}" -le 2000 ] || fail "PR body is too long for the PM review surface"
}

template_file="${work_dir}/template.md"
resolve_template "${repo}" "${template_file}"
validate_template "${template_file}"

case "${command_name}" in
  seed)
    [ -n "${output}" ] || usage
    [ -z "${body_file}" ] || usage
    [ ! -e "${output}" ] || fail "refusing to overwrite existing output: ${output}"
    case "${role}" in
      agentic-engineer) disclosure='> 🤖 Generated by the Agentic Engineer' ;;
      agent-improver) disclosure='> 🤖 Generated by the Agent Improver' ;;
      *) fail "unsupported --role: ${role}" ;;
    esac
    {
      printf '%s\n\n' "${disclosure}"
      cat "${template_file}"
    } >"${output}"
    ;;
  check)
    [ -z "${output}" ] || usage
    [ -n "${body_file}" ] || usage
    [ "${role}" = 'agentic-engineer' ] || usage
    if [ "${body_file}" = '-' ]; then
      body_file="${work_dir}/stdin-body.md"
      cat >"${body_file}"
    fi
    [ -f "${body_file}" ] || fail "body file does not exist: ${body_file}"
    validate_body "${template_file}" "${body_file}"
    ;;
  *) usage ;;
esac
