#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
subject="${repo_root}/.claude/scripts/pr-body-contract.sh"
contract="${repo_root}/AGENTS.md"
maintenance_overlay="${repo_root}/.claude/skills/portfolio-maintenance/SKILL.md"
engineering_overlay="${repo_root}/.claude/skills/product-engineering/SKILL.md"
workflow="${repo_root}/.github/workflows/ci.yaml"
fixture_root="$(mktemp -d)"
trap 'rm -rf "${fixture_root}"' EXIT

fail() {
  echo "pr-body contract test: FAIL — $*" >&2
  exit 1
}

expect_ok() {
  local name="$1"
  shift
  if ! "$@" >"${fixture_root}/stdout" 2>"${fixture_root}/stderr"; then
    cat "${fixture_root}/stderr" >&2
    fail "${name} should pass"
  fi
}

expect_fail() {
  local name="$1"
  local expected="$2"
  shift 2
  if "$@" >"${fixture_root}/stdout" 2>"${fixture_root}/stderr"; then
    fail "${name} should fail"
  fi
  grep -Fq "${expected}" "${fixture_root}/stderr" || {
    cat "${fixture_root}/stderr" >&2
    fail "${name} did not report '${expected}'"
  }
}

[ -x "${subject}" ] || fail "subject is missing or not executable: ${subject}"

for authoring_surface in "${contract}" "${maintenance_overlay}" "${engineering_overlay}"; do
  grep -Fq '.claude/scripts/pr-body-contract.sh seed' "${authoring_surface}" ||
    fail "${authoring_surface#"${repo_root}/"} does not require seeding from the effective GitHub template"
  grep -Fq '.claude/scripts/pr-body-contract.sh check' "${authoring_surface}" ||
    fail "${authoring_surface#"${repo_root}/"} does not require validating the completed body"
done
grep -Fq 'read the published body back' "${contract}" ||
  fail "AGENTS.md does not require validation of GitHub's published body"
grep -Fq "'.claude/scripts/pr-body-contract.sh'" "${workflow}" ||
  fail "CI change detection does not include the PR-body guard"
grep -Fq "'.claude/scripts/pr-body-contract.test.sh'" "${workflow}" ||
  fail "CI change detection does not include the PR-body regression test"
grep -Fq 'bash .claude/scripts/pr-body-contract.test.sh' "${workflow}" ||
  fail "CI does not execute the PR-body regression test"

cat >"${fixture_root}/template.md" <<'EOF'
<!-- Keep this body short and written for a product manager. -->

## Why

<!-- The problem and why it matters. -->

## What

<!-- The outcome. -->

Fixes #
EOF

mkdir -p "${fixture_root}/bin"
cat >"${fixture_root}/bin/gh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

case "${GH_MODE:-}" in
  repo)
    case "$*" in
      *'repos/devantler-tech/platform/contents/.github/PULL_REQUEST_TEMPLATE.md'*)
        cat "${GH_TEMPLATE_FIXTURE}"
        ;;
      *) exit 1 ;;
    esac
    ;;
  org)
    case "$*" in
      *'repos/devantler-tech/platform/contents/'*) exit 1 ;;
      *'repos/devantler-tech/.github/contents/.github/PULL_REQUEST_TEMPLATE.md'*)
        cat "${GH_TEMPLATE_FIXTURE}"
        ;;
      *) exit 1 ;;
    esac
    ;;
  token)
    [ "${GH_TOKEN:-}" = 'fixture-token' ] || exit 1
    case "$*" in
      *'repos/devantler-tech/platform/contents/.github/PULL_REQUEST_TEMPLATE.md'*)
        cat "${GH_TEMPLATE_FIXTURE}"
        ;;
      *) exit 1 ;;
    esac
    ;;
  none) exit 1 ;;
  *) exit 2 ;;
esac
EOF
chmod +x "${fixture_root}/bin/gh"

cat >"${fixture_root}/good.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

<!-- Keeping the original template comments is allowed. -->

## Why

Product managers cannot reliably understand Codex pull requests because technical logs obscure the reason for the change.

## What

Require the shared template and stop a pull request before publication when its short problem-and-outcome explanation is missing.

Fixes #3402
EOF

expect_ok "canonical body" env \
  PATH="${fixture_root}/bin:${PATH}" \
  GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/good.md"

expect_ok "caller GitHub credential is preserved" env \
  PATH="${fixture_root}/bin:${PATH}" \
  GH_MODE=token \
  GH_TOKEN=fixture-token \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/good.md"

cat >"${fixture_root}/part-of.md" <<'EOF'
> 🤖 Generated by the Agent Improver

## Why

The same PR-body miss recurs across scheduled runs and needs a durable correction.

## What

Add a reusable write-boundary check while leaving the broader improvement issue open for measurement.

Part of #3402

👉 After merge: verify the next scheduled Codex pull request.
EOF

expect_ok "agent improver and part-of body" env \
  PATH="${fixture_root}/bin:${PATH}" \
  GH_MODE=org \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/part-of.md" \
  --role agent-improver

expect_fail "acting role disclosure mismatch" "disclosure does not match --role agentic-engineer" env \
  PATH="${fixture_root}/bin:${PATH}" \
  GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/part-of.md" \
  --role agentic-engineer

cat >"${fixture_root}/delivery-and-experiment.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The delivery fixes a concrete defect while a separate experiment remains open for later measurement.

## What

Close the delivery issue and retain the experiment relationship without claiming the measurement is complete.

Fixes #3402
Part of #3399
EOF

expect_ok "delivery issue with open experiment" env \
  PATH="${fixture_root}/bin:${PATH}" \
  GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/delivery-and-experiment.md"

cat >"${fixture_root}/same-delivery-and-experiment.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The body must not claim that one issue is both delivered and still open for measurement.

## What

Reject contradictory relationships to the same issue.

Fixes #3402
Part of #3402
EOF

expect_fail "delivery and experiment issue must differ" "delivery and experiment issue numbers must be distinct" env \
  PATH="${fixture_root}/bin:${PATH}" \
  GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/same-delivery-and-experiment.md"

cat >"${fixture_root}/summary.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Summary

- Add a validator.

## Validation

- shellcheck

Fixes #3402
EOF
expect_fail "summary and validation body" "required template heading is missing: ## Why" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/summary.md"

cat >"${fixture_root}/subheading.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The template can be bypassed with a smaller technical heading.

## What

Reject every visible heading that the effective template does not define.

### Validation

The shell test passed.

Fixes #3402
EOF
expect_fail "non-template subheading" "body adds a non-template section: ### Validation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/subheading.md"

cat >"${fixture_root}/setext-heading.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The body can hide an extra technical section behind alternate Markdown heading syntax.

## What

Reject non-template Setext headings as well as ATX headings.

Validation
----------

The shell test passed.

Fixes #3402
EOF
expect_fail "non-template Setext heading" "body adds a non-template Setext section: Validation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/setext-heading.md"

cat >"${fixture_root}/preamble.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

Changed src/parser.go and shellcheck passed.

## Why

The body needs the template's product-facing shape.

## What

Reject technical summaries before the first template section.

Fixes #3402
EOF
expect_fail "visible preamble" "body adds visible content before the effective template" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/preamble.md"

cat >"${fixture_root}/template-with-warning.md" <<'EOF'
> [!WARNING]
> Flag any maintainer action required after merge.

## Why

<!-- The problem and why it matters. -->

## What

<!-- The outcome. -->

Fixes #
EOF
expect_fail "required visible template structure" "required template structure is missing" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-warning.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/good.md"

cat >"${fixture_root}/template-with-checklist.md" <<'EOF'
## Why

- [ ] Confirm the product impact is described.

## What

<!-- The outcome. -->

Fixes #
EOF
cat >"${fixture_root}/body-with-required-checklist.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

- [ ] Confirm the product impact is described.

The current write path lets implementation detail replace the product decision surface.

## What

Preserve the repository checklist while validating the authored explanation separately.

Fixes #3402
EOF
expect_ok "required template checklist" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-checklist.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/body-with-required-checklist.md"

cat >"${fixture_root}/template-with-visible-boilerplate.md" <<'EOF'
## Why

Explain the product problem and why it matters.

## What

Explain the intended product outcome.

Fixes #
EOF
cat >"${fixture_root}/boilerplate-only.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Explain the product problem and why it matters.

## What

Explain the intended product outcome.

Fixes #3402
EOF
expect_fail "visible boilerplate without authored explanation" "Why section has no visible explanation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-visible-boilerplate.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/boilerplate-only.md"

cat >"${fixture_root}/template-with-inline-placeholder.md" <<'EOF'
## Why

<!-- The problem and why it matters. -->

## What

<!-- The outcome. -->

Fixes # <!-- Replace with the delivery issue number. -->
EOF
expect_ok "inline issue placeholder comment" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-inline-placeholder.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/good.md"

cat >"${fixture_root}/bullets.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

- Codex bodies are too technical.

## What

- Add a body validator.

Fixes #3402
EOF
expect_fail "implementation inventory" "Why and What must be short prose, not bullet inventories" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/bullets.md"

cat >"${fixture_root}/ordered-list.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

1. Codex bodies are too technical.

## What

1. Add a body validator.

Fixes #3402
EOF
expect_fail "ordered implementation inventory" "Why and What must be short prose, not bullet inventories" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/ordered-list.md"

cat >"${fixture_root}/post-issue-bullets.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The body should remain a short product explanation from beginning to end.

## What

Reject implementation inventories even when they follow the issue relationship.

Fixes #3402

- Changed parser.go.
- Ran shellcheck.
EOF
expect_fail "post-issue implementation inventory" "Why and What must be short prose, not bullet inventories" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/post-issue-bullets.md"

cat >"${fixture_root}/inline-code.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The `pr-body-contract.sh` parser accepts implementation details in a product-facing explanation.

## What

Reject inline code and command snippets as well as fenced code blocks.

Fixes #3402
EOF
expect_fail "inline technical snippet" "PR body must not contain code or command snippets" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/inline-code.md"

cat >"${fixture_root}/too-many-sentences.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The first sentence names the problem. The second explains its impact. The third adds context. The fourth turns the review surface into a long report.

## What

Keep each product-facing section concise.

Fixes #3402
EOF
expect_fail "too many section sentences" "Why and What must each contain 1 to 3 sentences" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/too-many-sentences.md"

cat >"${fixture_root}/missing-issue.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The PR body needs a clear reason.

## What

The PR body now has one.
EOF
expect_fail "missing issue relationship" "exactly one issue relationship" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/missing-issue.md"

cat >"${fixture_root}/late-disclosure.md" <<'EOF'
## Why

The disclosure is misplaced.

## What

Move it to the first line.

Fixes #3402

> 🤖 Generated by the Agentic Engineer
EOF
expect_fail "late disclosure" "first-line disclosure does not match --role agentic-engineer" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/late-disclosure.md"

expect_ok "seed from repository template" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" seed --repo devantler-tech/platform --output "${fixture_root}/seeded.md" --role agentic-engineer
head -n 1 "${fixture_root}/seeded.md" | grep -Fqx '> 🤖 Generated by the Agentic Engineer' ||
  fail "seeded body does not begin with the engineer disclosure"
grep -Fq '## Why' "${fixture_root}/seeded.md" || fail "seeded body lost the repository template"

expect_ok "seed from organization fallback" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=org GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" seed --repo devantler-tech/platform --output "${fixture_root}/seeded-org.md" --role agent-improver
head -n 1 "${fixture_root}/seeded-org.md" | grep -Fqx '> 🤖 Generated by the Agent Improver' ||
  fail "organization-fallback body does not begin with the improver disclosure"

cat >"${fixture_root}/reversed-template.md" <<'EOF'
## What

<!-- The outcome. -->

## Why

<!-- The problem and why it matters. -->

Fixes #
EOF
expect_fail "reversed Why and What template" "effective template must place ## Why before ## What" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/reversed-template.md" \
  "${subject}" seed --repo devantler-tech/platform --output "${fixture_root}/reversed-seed.md"

expect_fail "missing effective template" "no effective GitHub pull request template" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=none GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" seed --repo devantler-tech/platform --output "${fixture_root}/missing.md"

echo "pr-body contract test: PASS"
