#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
subject="${repo_root}/.claude/scripts/pr-body-contract.sh"
contract="${repo_root}/AGENTS.md"
maintenance_overlay="${repo_root}/.claude/skills/portfolio-maintenance/SKILL.md"
engineering_overlay="${repo_root}/.claude/skills/product-engineering/SKILL.md"
workflow="${repo_root}/.github/workflows/ci.yaml"
fixture_root="$(mktemp -d)"
trap 'rm -rf "${fixture_root}"' EXIT

fail() {
  echo "pr-body contract test: FAIL — $*" >&2
  exit 1
}

expect_ok() {
  local name="$1"
  shift
  if ! "$@" >"${fixture_root}/stdout" 2>"${fixture_root}/stderr"; then
    cat "${fixture_root}/stderr" >&2
    fail "${name} should pass"
  fi
}

expect_fail() {
  local name="$1"
  local expected="$2"
  shift 2
  if "$@" >"${fixture_root}/stdout" 2>"${fixture_root}/stderr"; then
    fail "${name} should fail"
  fi
  grep -Fq "${expected}" "${fixture_root}/stderr" || {
    cat "${fixture_root}/stderr" >&2
    fail "${name} did not report '${expected}'"
  }
}

[ -x "${subject}" ] || fail "subject is missing or not executable: ${subject}"

for authoring_surface in "${contract}" "${maintenance_overlay}" "${engineering_overlay}"; do
  grep -Fq '.claude/scripts/pr-body-contract.sh seed' "${authoring_surface}" ||
    fail "${authoring_surface#"${repo_root}/"} does not require seeding from the effective GitHub template"
  grep -Fq '.claude/scripts/pr-body-contract.sh check' "${authoring_surface}" ||
    fail "${authoring_surface#"${repo_root}/"} does not require validating the completed body"
done
grep -Fq 'read the published body back' "${contract}" ||
  fail "AGENTS.md does not require validation of GitHub's published body"
grep -Fq 'Before every Agentic Engineer or Agent Improver PR creation or body edit' "${contract}" ||
  fail "AGENTS.md does not scope the executable write gate to its supported routine roles"
grep -Fq -- '--allow-no-issue' "${contract}" ||
  fail "AGENTS.md does not bind the no-issue flag to the documented trivial-fix carve-out"
if grep -Fq 'Before every agent-authored PR creation or body edit' "${contract}"; then
  fail "AGENTS.md incorrectly applies the routine-role disclosure gate to interactive PRs"
fi
grep -Fq "'.claude/scripts/pr-body-contract.sh'" "${workflow}" ||
  fail "CI change detection does not include the PR-body guard"
grep -Fq "'.claude/scripts/pr-body-contract.test.sh'" "${workflow}" ||
  fail "CI change detection does not include the PR-body regression test"
grep -Fq 'bash .claude/scripts/pr-body-contract.test.sh' "${workflow}" ||
  fail "CI does not execute the PR-body regression test"
grep -Fq 'Enforce the routine-role PR body contract' "${workflow}" ||
  fail "required CI does not validate the published routine-role PR body"
grep -Fq 'types: [opened, synchronize, reopened, edited, ready_for_review]' "${workflow}" ||
  fail "required CI does not rerun for body edits and draft promotion"
grep -Fq "if: github.event.pull_request.head.repo.full_name == github.repository" "${workflow}" ||
  fail "the routine-role body check is not fenced to trusted same-repository code"
grep -Fq 'bash .claude/scripts/pr-body-contract.sh check' "${workflow}" ||
  fail "required CI does not invoke the PR-body contract against the event body"
# The candidate workflow must pass the runtime shell variable literally.
# shellcheck disable=SC2016
grep -Fq -- '--role "${role}"' "${workflow}" ||
  fail "required CI does not pass the role selected from the disclosure"
grep -Fq "'> 🤖 Generated by the Agentic Engineer') role='agentic-engineer'" "${workflow}" ||
  fail "required CI does not map the engineer disclosure to its contract role"
grep -Fq "'> 🤖 Generated by the Agent Improver') role='agent-improver'" "${workflow}" ||
  fail "required CI does not map the improver disclosure to its contract role"
grep -Fq "'> 🤖 Generated by the Daily AI Engineer') role='agentic-engineer'" "${workflow}" ||
  fail "required CI does not route the legacy engineer disclosure through body hygiene"
grep -Fq "'> 🤖 Generated by the Daily AI Assistant') role='agentic-engineer'" "${workflow}" ||
  fail "required CI does not route the legacy assistant disclosure through body hygiene"
grep -Fq "Generated by the (Agentic Engineer|Daily AI Engineer|Daily AI Assistant)[[:space:]]*$'" \
  "${workflow}" || fail "required CI does not detect a displaced routine-role disclosure"
grep -Fq "grep -Eq '^[[:space:]]*>[[:space:]]*🤖 Generated by the Agent Improver[[:space:]]*$'" \
  "${workflow}" || fail "required CI does not route an indented routine-role disclosure"
grep -Fq "contract_args+=(--allow-no-issue)" "${workflow}" ||
  fail "required CI does not preserve the explicit trivial-fix carve-out"
grep -Fq -- '- guard-pr-body-marker-collision' "${workflow}" ||
  fail "the routine-role PR-body guard is absent from the required status aggregate"

cat >"${fixture_root}/template.md" <<'EOF'
<!-- Keep this body short and written for a product manager. -->

## Why

<!-- The problem and why it matters. -->

## What

<!-- The outcome. -->

Fixes #
EOF

mkdir -p "${fixture_root}/bin"
cat >"${fixture_root}/bin/gh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

not_found() {
  echo 'gh: Not Found (HTTP 404)' >&2
  exit 1
}

case "${GH_MODE:-}" in
  repo)
    case "$*" in
      *'repos/devantler-tech/platform/contents/.github/PULL_REQUEST_TEMPLATE.md'*)
        cat "${GH_TEMPLATE_FIXTURE}"
        ;;
      *'repos/devantler-tech/platform/contents/.github --jq'*)
        echo 'PULL_REQUEST_TEMPLATE.md'
        ;;
      *) not_found ;;
    esac
    ;;
  org)
    case "$*" in
      *'repos/devantler-tech/platform/contents/'*) not_found ;;
      *'repos/devantler-tech/.github/contents/.github/PULL_REQUEST_TEMPLATE.md'*)
        cat "${GH_TEMPLATE_FIXTURE}"
        ;;
      *'repos/devantler-tech/.github/contents/.github --jq'*)
        echo 'PULL_REQUEST_TEMPLATE.md'
        ;;
      *) not_found ;;
    esac
    ;;
  org-root)
    case "$*" in
      *'repos/devantler-tech/platform/contents/'*) not_found ;;
      *'repos/devantler-tech/.github/contents/PULL_REQUEST_TEMPLATE.md'*)
        cat "${GH_TEMPLATE_FIXTURE}"
        ;;
      *'repos/devantler-tech/.github/contents --jq'*)
        echo 'PULL_REQUEST_TEMPLATE.md'
        ;;
      *) not_found ;;
    esac
    ;;
  token)
    [ "${GH_TOKEN:-}" = 'fixture-token' ] || exit 1
    case "$*" in
      *'repos/devantler-tech/platform/contents/.github/PULL_REQUEST_TEMPLATE.md'*)
        cat "${GH_TEMPLATE_FIXTURE}"
        ;;
      *'repos/devantler-tech/platform/contents/.github --jq'*)
        echo 'PULL_REQUEST_TEMPLATE.md'
        ;;
      *) not_found ;;
    esac
    ;;
  authfail)
    case "$*" in
      *'repos/devantler-tech/platform/contents/.github --jq'*)
        echo 'gh: Resource not accessible by integration (HTTP 403)' >&2
        exit 1
        ;;
      *'repos/devantler-tech/.github/contents/.github/PULL_REQUEST_TEMPLATE.md'*)
        cat "${GH_TEMPLATE_FIXTURE}"
        ;;
      *)
        echo 'gh: Not Found (HTTP 404)' >&2
        exit 1
        ;;
    esac
    ;;
  mixedcase)
    case "$*" in
      *'repos/devantler-tech/platform/contents --jq'*)
        echo 'Pull_Request_Template.txt'
        ;;
      *'repos/devantler-tech/platform/contents/Pull_Request_Template.txt'*)
        cat "${GH_TEMPLATE_FIXTURE}"
        ;;
      *) not_found ;;
    esac
    ;;
  none) not_found ;;
  *) exit 2 ;;
esac
EOF
chmod +x "${fixture_root}/bin/gh"

cat >"${fixture_root}/good.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

<!-- Keeping the original template comments is allowed. -->

## Why

Product managers cannot reliably understand Codex pull requests because technical logs obscure the reason for the change.

## What

Require the shared template and stop a pull request before publication when its short problem-and-outcome explanation is missing.

Fixes #3402
EOF

expect_ok "canonical body" env \
  PATH="${fixture_root}/bin:${PATH}" \
  GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/good.md"

expect_ok "caller GitHub credential is preserved" env \
  PATH="${fixture_root}/bin:${PATH}" \
  GH_MODE=token \
  GH_TOKEN=fixture-token \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/good.md"

cat >"${fixture_root}/part-of.md" <<'EOF'
> 🤖 Generated by the Agent Improver

## Why

The same PR-body miss recurs across scheduled runs and needs a durable correction.

## What

Add a reusable write-boundary check while leaving the broader improvement issue open for measurement.

Part of #3402

⚠️ Merge order: land #2 first, or deployment breaks.
EOF

expect_ok "agent improver and part-of body" env \
  PATH="${fixture_root}/bin:${PATH}" \
  GH_MODE=org \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/part-of.md" \
  --role agent-improver

cat >"${fixture_root}/canonical-operational-notes.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The maintainer needs product-relevant conditions at the decision surface.

## What

Keep each canonical operational note as one concise line.

Fixes #3402

⚠️ Merge order: land #2 first, or deployment breaks.
💥 Breaking change: existing clients must refresh their saved configuration.
📦 New dependency: a supported identity library enables sign-in.
👉 After merge/promotion: confirm the new sign-in path is available.
EOF
expect_ok "canonical operational note markers" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/canonical-operational-notes.md"

expect_fail "acting role disclosure mismatch" "disclosure does not match --role agentic-engineer" env \
  PATH="${fixture_root}/bin:${PATH}" \
  GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/part-of.md" \
  --role agentic-engineer

cat >"${fixture_root}/delivery-and-experiment.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The delivery fixes a concrete defect while a separate experiment remains open for later measurement.

## What

Close the delivery issue and retain the experiment relationship without claiming the measurement is complete.

Fixes #3402
Part of #3399
EOF

expect_ok "delivery issue with open experiment" env \
  PATH="${fixture_root}/bin:${PATH}" \
  GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/delivery-and-experiment.md"

cat >"${fixture_root}/same-delivery-and-experiment.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The body must not claim that one issue is both delivered and still open for measurement.

## What

Reject contradictory relationships to the same issue.

Fixes #3402
Part of #3402
EOF

expect_fail "delivery and experiment issue must differ" "delivery and experiment issue numbers must be distinct" env \
  PATH="${fixture_root}/bin:${PATH}" \
  GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/same-delivery-and-experiment.md"

cat >"${fixture_root}/split-relationships.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Two issue relationships must not create an unvalidated prose gap.

## What

Keep the delivery and experiment links together.

Fixes #3402

Additional delivery context hides here.

Part of #3399
EOF
expect_fail "prose between issue relationships" "issue relationship lines must be contiguous" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/split-relationships.md"

cat >"${fixture_root}/malformed-and-valid-relationship.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Every published issue relationship must identify a real issue.

## What

Reject malformed relationship lines even when a valid relationship is also present.

Part of #oops
Fixes #3402
EOF
expect_fail "malformed relationship beside valid relationship" \
  "every issue relationship marker must use the permitted shape" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/malformed-and-valid-relationship.md"

cat >"${fixture_root}/alternate-closing-keyword.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Every GitHub closing relationship must be visible to the contract.

## What

Reject alternate closing keywords outside the permitted relationship shape.

Closes #99
Fixes #3402
EOF
expect_fail "alternate closing keyword beside valid relationship" \
  "every issue relationship marker must use the permitted shape" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/alternate-closing-keyword.md"

cat >"${fixture_root}/cross-repository-closing-keyword.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Cross-repository relationships can close work outside the validated delivery issue.

## What

Reject closing relationships that target another repository.

Closes other/repository#99
Fixes #3402
EOF
expect_fail "cross-repository closing keyword" \
  "every issue relationship marker must use the permitted shape" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/cross-repository-closing-keyword.md"

cat >"${fixture_root}/url-closing-keyword.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

URL relationships can close work outside the validated delivery issue.

## What

Reject closing relationships expressed as full issue URLs.

Resolves https://github.com/other/repository/issues/99
Fixes #3402
EOF
expect_fail "URL closing keyword" "every issue relationship marker must use the permitted shape" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/url-closing-keyword.md"

cat >"${fixture_root}/summary.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Summary

- Add a validator.

## Validation

- shellcheck

Fixes #3402
EOF
expect_fail "summary and validation body" "required template heading is missing: ## Why" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/summary.md"

cat >"${fixture_root}/subheading.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The template can be bypassed with a smaller technical heading.

## What

Reject every visible heading that the effective template does not define.

### Validation

The shell test passed.

Fixes #3402
EOF
expect_fail "non-template subheading" "body adds a non-template section: ### Validation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/subheading.md"

cat >"${fixture_root}/indented-subheading.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

GitHub renders headings with up to three leading spaces.

## What

Reject indented non-template headings too.

   ### Validation

The shell test passed.

Fixes #3402
EOF
expect_fail "indented non-template subheading" "body adds a non-template section: ### Validation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/indented-subheading.md"

cat >"${fixture_root}/html-heading.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Raw HTML headings can create an undeclared technical review section.

## What

Reject HTML headings that are absent from the repository template.

<h3>Validation</h3>

The shell test passed.

Fixes #3402
EOF
expect_fail "non-template HTML heading" "body adds a non-template HTML section" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/html-heading.md"

cat >"${fixture_root}/quoted-heading.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Quoted Markdown must not hide an undeclared technical section.

## What

Reject headings inside blockquotes when the template does not define them.

> ### Validation

The shell test passed.

Fixes #3402
EOF
expect_fail "quoted non-template heading" "body adds a non-template section: ### Validation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/quoted-heading.md"

cat >"${fixture_root}/quoted-setext-heading.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Quoted Markdown must not hide an alternate undeclared section.

## What

Reject Setext headings inside blockquotes too.

> Validation
> ----------

The shell test passed.

Fixes #3402
EOF
expect_fail "quoted non-template Setext heading" \
  "body adds a non-template Setext section: Validation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/quoted-setext-heading.md"

cat >"${fixture_root}/template-with-indented-heading.md" <<'EOF'
## Why

   ### Product context

<!-- The problem and why it matters. -->

## What

<!-- The outcome. -->

Fixes #
EOF
cat >"${fixture_root}/body-with-indented-template-heading.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

   ### Product context

The template's indented heading must remain part of the visible review surface.

## What

Preserve the template heading while rejecting additional ones.

Fixes #3402
EOF
expect_ok "indented template heading" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-indented-heading.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/body-with-indented-template-heading.md"

cat >"${fixture_root}/normalized-duplicate-heading.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The body must contain each template section exactly once.

## Why ##

This duplicate renders as the same heading.

## What

Count normalized headings before accepting the body.

Fixes #3402
EOF
expect_fail "normalized duplicate template heading" "required template heading is missing: ## Why" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/normalized-duplicate-heading.md"

cat >"${fixture_root}/setext-heading.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The body can hide an extra technical section behind alternate Markdown heading syntax.

## What

Reject non-template Setext headings as well as ATX headings.

Validation
----------

The shell test passed.

Fixes #3402
EOF
expect_fail "non-template Setext heading" "body adds a non-template Setext section: Validation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/setext-heading.md"

cat >"${fixture_root}/preamble.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

Changed src/parser.go and shellcheck passed.

## Why

The body needs the template's product-facing shape.

## What

Reject technical summaries before the first template section.

Fixes #3402
EOF
expect_fail "visible preamble" "body adds visible content before the effective template" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/preamble.md"

cat >"${fixture_root}/template-with-warning.md" <<'EOF'
> [!WARNING]
> Flag any maintainer action required after merge.

## Why

<!-- The problem and why it matters. -->

## What

<!-- The outcome. -->

Fixes #
EOF
expect_fail "required visible template structure" "required template structure is missing" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-warning.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/good.md"

cat >"${fixture_root}/template-with-checklist.md" <<'EOF'
## Why

- [ ] Confirm the product impact is described.

## What

<!-- The outcome. -->

Fixes #
EOF
cat >"${fixture_root}/body-with-required-checklist.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

- [ ] Confirm the product impact is described.

The current write path lets implementation detail replace the product decision surface.

## What

Preserve the repository checklist while validating the authored explanation separately.

Fixes #3402
EOF
expect_ok "required template checklist" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-checklist.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/body-with-required-checklist.md"

cat >"${fixture_root}/body-with-completed-checklist.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

- [x] Confirm the product impact is described.

The current write path must support completing repository-owned requirements.

## What

Normalize checkbox state while preserving checklist text and order.

Fixes #3402
EOF
expect_ok "completed required template checklist" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-checklist.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/body-with-completed-checklist.md"

cat >"${fixture_root}/template-with-checklist-heading.md" <<'EOF'
## Why

<!-- The problem and why it matters. -->

## What

<!-- The outcome. -->

## Checklist

- [ ] Confirm the product impact is described.

Fixes #
EOF
cat >"${fixture_root}/empty-what-with-checklist-heading.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The body must include an authored outcome.

## What

## Checklist

- [x] Confirm the product impact is described.

Fixes #3402
EOF
expect_fail "template heading cannot satisfy empty What" "What section has no visible explanation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-checklist-heading.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/empty-what-with-checklist-heading.md"

cat >"${fixture_root}/authored-only-after-what.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The body must explain the intended outcome in What itself.

## What

## Checklist

- [x] Confirm the product impact is described.

This sentence belongs to the later checklist section, not What.

Fixes #3402
EOF
expect_fail "later template section cannot satisfy empty What" "What section has no visible explanation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-checklist-heading.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/authored-only-after-what.md"

cat >"${fixture_root}/template-with-visible-boilerplate.md" <<'EOF'
## Why

Explain the product problem and why it matters.

## What

Explain the intended product outcome.

Fixes #
EOF
cat >"${fixture_root}/boilerplate-only.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Explain the product problem and why it matters.

## What

Explain the intended product outcome.

Fixes #3402
EOF
expect_fail "visible boilerplate without authored explanation" "Why section has no visible explanation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-visible-boilerplate.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/boilerplate-only.md"

cat >"${fixture_root}/duplicated-boilerplate.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Explain the product problem and why it matters.
Explain the product problem and why it matters.

## What

Explain the intended product outcome.
Explain the intended product outcome.

Fixes #3402
EOF
expect_fail "duplicated visible template prose" "body repeats visible template content" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-visible-boilerplate.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/duplicated-boilerplate.md"

cat >"${fixture_root}/template-with-inline-placeholder.md" <<'EOF'
## Why

<!-- The problem and why it matters. -->

## What

<!-- The outcome. -->

Fixes # <!-- Replace with the delivery issue number. -->
EOF
expect_ok "inline issue placeholder comment" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-inline-placeholder.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/good.md"

cat >"${fixture_root}/template-with-leading-separator.md" <<'EOF'
---

## Why

<!-- The problem and why it matters. -->

## What

<!-- The outcome. -->

Fixes #
EOF
cat >"${fixture_root}/body-with-leading-separator.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

---

## Why

The validator must treat template lines as data even when they begin with a hyphen.

## What

Preserve a leading separator without passing it to grep as an option.

Fixes #3402
EOF
expect_ok "leading hyphen template structure" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-leading-separator.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/body-with-leading-separator.md"

cat >"${fixture_root}/bullets.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

- Codex bodies are too technical.

## What

- Add a body validator.

Fixes #3402
EOF
expect_fail "implementation inventory" "Why and What must be short prose, not bullet inventories" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/bullets.md"

cat >"${fixture_root}/table.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

| Problem | Impact |
| --- | --- |
| Technical bodies | Product intent is hidden |

## What

Keep the review surface as short prose.

Fixes #3402
EOF
expect_fail "Markdown table inventory" "Why and What must be short prose, not Markdown tables" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/table.md"

cat >"${fixture_root}/quoted-bullets.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Quoted Markdown must not hide an implementation inventory.

## What

> > - Add a body validator.

Fixes #3402
EOF
expect_fail "quoted implementation inventory" "Why and What must be short prose, not bullet inventories" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/quoted-bullets.md"

cat >"${fixture_root}/ordered-list.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

1. Codex bodies are too technical.

## What

1. Add a body validator.

Fixes #3402
EOF
expect_fail "ordered implementation inventory" "Why and What must be short prose, not bullet inventories" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/ordered-list.md"

cat >"${fixture_root}/post-issue-bullets.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The body should remain a short product explanation from beginning to end.

## What

Reject implementation inventories even when they follow the issue relationship.

Fixes #3402

- Changed parser.go.
- Ran shellcheck.
EOF
expect_fail "post-issue implementation inventory" "Why and What must be short prose, not bullet inventories" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/post-issue-bullets.md"

cat >"${fixture_root}/post-issue-prose.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The body should not carry an unbounded technical appendix after its issue relationship.

## What

Reject trailing prose unless it is inherited from the effective template.

Fixes #3402

Validation details and implementation notes continue here without sentence limits.
EOF
expect_fail "post-issue prose" "body adds non-template text after the final delivery relationship" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/post-issue-prose.md"

cat >"${fixture_root}/inline-code.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The `pr-body-contract.sh` parser accepts implementation details in a product-facing explanation.

## What

Reject inline code and command snippets as well as fenced code blocks.

Fixes #3402
EOF
expect_fail "inline technical snippet" "PR body must not contain code or command snippets" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/inline-code.md"

cat >"${fixture_root}/quoted-fence.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Quoted Markdown must not hide command output from the product review surface.

## What

Reject quoted code fences as well as ordinary ones.

> > ~~~
> > shellcheck passed
> > ~~~

Fixes #3402
EOF
expect_fail "quoted code fence" "PR body must not contain code or command fences" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/quoted-fence.md"

cat >"${fixture_root}/indented-code.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Markdown can hide a command behind indentation.

## What

Reject the indented command form.

    make verify

Fixes #3402
EOF
expect_fail "indented code block" "PR body must not contain indented code blocks" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/indented-code.md"

cat >"${fixture_root}/plain-technical-detail.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Changed src/parser.go because validate_body was broken.

## What

SC2317 is gone and 24 tests plus shellcheck pass.

Fixes #3402
EOF
expect_fail "unformatted technical detail" "PR body must not contain implementation or validation detail" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/plain-technical-detail.md"

cat >"${fixture_root}/pascal-case-symbols.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Named functions turn the product review surface back into an implementation review.

## What

Change ParseConfig and ValidateBody to fix the failure.

Fixes #3402
EOF
expect_fail "PascalCase function symbols" "PR body must not contain implementation or validation detail" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/pascal-case-symbols.md"

cat >"${fixture_root}/unqualified-pascal-case-symbol.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Named functions turn the product review surface back into an implementation review.

## What

ParseConfig now accepts the input so users can continue.

Fixes #3402
EOF
expect_fail "unqualified PascalCase function symbol" \
  "PR body must not contain implementation or validation detail" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/unqualified-pascal-case-symbol.md"

cat >"${fixture_root}/past-tense-pascal-case-symbol.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Named functions turn the product review surface back into an implementation review.

## What

Changed ReconcileCluster because users were blocked.

Fixes #3402
EOF
expect_fail "past-tense PascalCase function symbol" \
  "PR body must not contain implementation or validation detail" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/past-tense-pascal-case-symbol.md"

cat >"${fixture_root}/lower-camel-case-symbols.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Named functions turn the product review surface back into an implementation review.

## What

Change parseConfig and validateBody to accept requests.

Fixes #3402
EOF
expect_fail "lower-camel-case function symbols" \
  "PR body must not contain implementation or validation detail" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/lower-camel-case-symbols.md"

cat >"${fixture_root}/acronym-symbols.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Named functions turn the product review surface back into an implementation review.

## What

Update ParseHTTPResponse and HTTPClient so valid requests work again.

Fixes #3402
EOF
expect_fail "acronym-bearing implementation symbols" \
  "PR body must not contain implementation or validation detail" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/acronym-symbols.md"

cat >"${fixture_root}/implementation-verb-symbols.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Named functions turn the product review surface back into an implementation review.

## What

Implement ParseHTTPResponse so valid requests work again.

Fixes #3402
EOF
expect_fail "implementation verbs before symbols" \
  "PR body must not contain implementation or validation detail" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/implementation-verb-symbols.md"

cat >"${fixture_root}/product-proper-names.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

GitHub and CodeRabbit users need a clear product review surface.

## What

Keep legitimate product names while rejecting implementation symbols.

Fixes #3402
EOF
expect_ok "legitimate product proper names" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/product-proper-names.md"

cat >"${fixture_root}/portfolio-product-proper-names.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

OpenCost users cannot understand the current CloudWatch result.

## What

Clarify the product outcome while preserving legitimate product names.

Fixes #3402
EOF
expect_ok "portfolio product proper names" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/portfolio-product-proper-names.md"

cat >"${fixture_root}/dotted-product-name.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Node.js users need the supported runtime requirement stated plainly.

## What

Clarify the required runtime in product language.

Fixes #3402

📦 New dependency: Node.js is now required.
EOF
expect_ok "dotted product name" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/dotted-product-name.md"

cat >"${fixture_root}/os-product-names.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

iOS users cannot complete the current journey from their devices.

## What

Add iOS support and update macOS compatibility.

Fixes #3402
EOF
expect_ok "OS product names" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/os-product-names.md"

cat >"${fixture_root}/device-product-name.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

iPhone users cannot complete the current journey from their devices.

## What

Add iPhone support so guests can respond from their devices.

Fixes #3402
EOF
expect_ok "device product name" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/device-product-name.md"

cat >"${fixture_root}/unformatted-command.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Operational notes must state outcomes rather than exact commands.

## What

Keep the required follow-up understandable without implementation detail.

Fixes #3402

👉 After merge/promotion: Run kubectl apply --force in production.
EOF
expect_fail "unformatted command and option" \
  "PR body must not contain implementation or validation detail" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/unformatted-command.md"

cat >"${fixture_root}/web-url.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Users need a direct path to the product setup guidance.

## What

Link the outcome to https://example.com/setup for the affected users.

Fixes #3402
EOF
expect_ok "web URL in product prose" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/web-url.md"

cat >"${fixture_root}/raw-html-code-container.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Raw HTML must not turn the remainder of the body into hidden code.

## What

Reject preformatted HTML code containers.

<pre>deploy --force

Fixes #3402
EOF
expect_fail "raw HTML code container" "PR body must not contain raw HTML code containers" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/raw-html-code-container.md"

cat >"${fixture_root}/escaped-comment-delimiter.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

\<!-- Changed src/parser.go and all tests passed. -->

## What

Keep escaped comment delimiters visible to validation.

Fixes #3402
EOF
expect_fail "escaped comment delimiter remains visible" \
  "PR body must not contain implementation or validation detail" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/escaped-comment-delimiter.md"

cat >"${fixture_root}/extensionless-files.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Technical file names do not belong in the product review surface.

## What

Update the Dockerfile, Makefile, and go.mod.

Fixes #3402
EOF
expect_fail "extensionless and config file names" \
  "PR body must not contain implementation or validation detail" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/extensionless-files.md"

cat >"${fixture_root}/ordinary-slash-prose.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Authors and/or reviewers cannot understand the intended behavior.

## What

Keep ordinary slash constructions available in plain product prose.

Fixes #3402
EOF
expect_ok "ordinary slash prose" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/ordinary-slash-prose.md"

cat >"${fixture_root}/generic-validation-result.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The change needs a product-facing explanation.

## What

All tests and lint checks passed.

Fixes #3402
EOF
expect_fail "generic validation result" "PR body must not contain implementation or validation detail" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/generic-validation-result.md"

cat >"${fixture_root}/too-many-sentences.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The first sentence names the problem. The second explains its impact. The third adds context. The fourth turns the review surface into a long report.

## What

Keep each product-facing section concise.

Fixes #3402
EOF
expect_fail "too many section sentences" "Why and What must each contain 1 to 3 sentences" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/too-many-sentences.md"

cat >"${fixture_root}/quoted-sentences.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

“One.” “Two.” “Three.” “Four.”

## What

Count sentences whose punctuation appears before a closing quote.

Fixes #3402
EOF
expect_fail "quoted sentence endings" "Why and What must each contain 1 to 3 sentences" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/quoted-sentences.md"

cat >"${fixture_root}/hidden-link-definitions.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

[why]: # "Users are blocked."

## What

[what]: # "The outcome."

Fixes #3402
EOF
expect_fail "hidden link definitions are not prose" "Why section has no visible explanation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/hidden-link-definitions.md"

cat >"${fixture_root}/multiline-hidden-link-definition.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

[why]: https://example.com
  "Users are blocked."

## What

Restore a clear and reliable journey for affected users.

Fixes #3402
EOF
expect_fail "multiline hidden link definition is not prose" \
  "Why section has no visible explanation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/multiline-hidden-link-definition.md"

cat >"${fixture_root}/html-only-prose.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

<br>

## What

Restore a clear and reliable journey for affected users.

Fixes #3402
EOF
expect_fail "HTML-only markup is not prose" "Why section has no visible explanation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/html-only-prose.md"

cat >"${fixture_root}/thematic-break-only.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

---

## What

The required explanation must contain visible prose.

Fixes #3402
EOF
expect_fail "thematic break is not prose" "Why section has no visible explanation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/thematic-break-only.md"

cat >"${fixture_root}/abbreviated-prose.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Some readers, e.g. mobile users, need clarity. The current body confuses them. This matters.

## What

Keep ordinary abbreviations from inflating the sentence count.

Fixes #3402
EOF
expect_ok "ordinary prose abbreviation" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/abbreviated-prose.md"

cat >"${fixture_root}/missing-issue.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The PR body needs a clear reason.

## What

The PR body now has one.
EOF
expect_fail "missing issue relationship" "exactly one issue relationship" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/missing-issue.md"

expect_fail "no-issue carve-out requires a published marker" "no-issue mode requires the explicit trivial-fix marker" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/missing-issue.md" \
  --allow-no-issue

cat >"${fixture_root}/trivial-no-issue.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

A tiny documentation typo obscures the intended product wording.

## What

Correct the wording without creating a separate planning artifact.

No issue: trivial fix.
EOF
expect_ok "explicit trivial no-issue carve-out" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/trivial-no-issue.md" \
  --allow-no-issue

cat >"${fixture_root}/no-issue-with-closing-keyword.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

A no-issue body must not conceal a relationship that GitHub will close.

## What

Reject every closing keyword when the explicit no-issue carve-out is used.

Resolves #99
No issue: trivial fix.
EOF
expect_fail "closing keyword forbidden in no-issue mode" \
  "no-issue mode forbids relationship markers" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/no-issue-with-closing-keyword.md" --allow-no-issue

cat >"${fixture_root}/trivial-no-issue-with-trailing-prose.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

A tiny documentation typo obscures the intended product wording.

## What

Correct the wording without creating a separate planning artifact.

No issue: trivial fix.

Unbounded prose continues after the declared delivery boundary.
EOF
expect_fail "no-issue marker is the delivery boundary" \
  "body adds non-template text after the final delivery relationship" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/trivial-no-issue-with-trailing-prose.md" --allow-no-issue

cat >"${fixture_root}/template-with-post-issue-section.md" <<'EOF'
## Why

<!-- The problem and why it matters. -->

## What

<!-- The outcome. -->

Fixes #

## Checklist

- [ ] Confirm the product impact is described.
EOF
cat >"${fixture_root}/body-with-post-issue-section.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The template places required repository structure after the delivery relationship.

## What

Preserve that inherited structure while rejecting authored appendices.

Fixes #3402

## Checklist

- [x] Confirm the product impact is described.
EOF
expect_ok "template section after issue relationship" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-post-issue-section.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/body-with-post-issue-section.md"

cat >"${fixture_root}/template-with-post-issue-field.md" <<'EOF'
## Why

<!-- The problem and why it matters. -->

## What

<!-- The outcome. -->

Fixes #

## Risks

<!-- Describe product risks. -->
EOF
cat >"${fixture_root}/body-with-post-issue-field.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The effective template asks for product risks after the delivery relationship.

## What

Honor that requested field without opening an unrestricted appendix.

Fixes #3402

## Risks

Users may need to refresh their saved view once.
EOF
expect_ok "authored template field after issue relationship" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-post-issue-field.md" \
  "${subject}" check --repo devantler-tech/platform \
  --body-file "${fixture_root}/body-with-post-issue-field.md"

cat >"${fixture_root}/template-with-risks-section.md" <<'EOF'
## Why

<!-- The problem and why it matters. -->

## What

<!-- The outcome. -->

## Risks

<!-- List PM-relevant risks. -->

Fixes #
EOF
cat >"${fixture_root}/body-with-risks-list.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

The repository template asks for product risks outside the prose sections.

## What

Keep Why and What concise while honoring that separate section.

## Risks

- Users may need to refresh their saved view.

Fixes #3402
EOF
expect_ok "template-prescribed list outside Why and What" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/template-with-risks-section.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/body-with-risks-list.md"

cat >"${fixture_root}/zero-issue.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

Issue zero cannot identify real delivery work.

## What

Require a positive GitHub issue number.

Fixes #0
EOF
expect_fail "zero issue number" "exactly one issue relationship" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/zero-issue.md"
expect_fail "malformed relationship in no-issue mode" "no-issue mode forbids relationship markers" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/zero-issue.md" \
  --allow-no-issue

cat >"${fixture_root}/unresolved-placeholder.md" <<'EOF'
> 🤖 Generated by the Agentic Engineer

## Why

An unresolved template marker should never reach the published body.

## What

Require the seeded placeholder to be removed or completed.

Fixes #
Fixes #3402
EOF
expect_fail "unresolved issue placeholder" "body contains an unresolved issue placeholder" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/unresolved-placeholder.md"

cat >"${fixture_root}/late-disclosure.md" <<'EOF'
## Why

The disclosure is misplaced.

## What

Move it to the first line.

Fixes #3402

> 🤖 Generated by the Agentic Engineer
EOF
expect_fail "late disclosure" "first-line disclosure does not match --role agentic-engineer" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" check --repo devantler-tech/platform --body-file "${fixture_root}/late-disclosure.md"

expect_ok "seed from repository template" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" seed --repo devantler-tech/platform --output "${fixture_root}/seeded.md" --role agentic-engineer
head -n 1 "${fixture_root}/seeded.md" | grep -Fqx '> 🤖 Generated by the Agentic Engineer' ||
  fail "seeded body does not begin with the engineer disclosure"
grep -Fq '## Why' "${fixture_root}/seeded.md" || fail "seeded body lost the repository template"

expect_ok "seed from organization fallback" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=org GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" seed --repo devantler-tech/platform --output "${fixture_root}/seeded-org.md" --role agent-improver
head -n 1 "${fixture_root}/seeded-org.md" | grep -Fqx '> 🤖 Generated by the Agent Improver' ||
  fail "organization-fallback body does not begin with the improver disclosure"

expect_ok "seed from organization root template" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=org-root GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" seed --repo devantler-tech/platform --output "${fixture_root}/seeded-org-root.md"
grep -Fq '## Why' "${fixture_root}/seeded-org-root.md" ||
  fail "organization-root fallback lost the repository template"

expect_ok "seed from mixed-case text template" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=mixedcase GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" seed --repo devantler-tech/platform --output "${fixture_root}/seeded-mixedcase.md"
grep -Fq '## Why' "${fixture_root}/seeded-mixedcase.md" ||
  fail "mixed-case text template was not loaded"

cat >"${fixture_root}/reversed-template.md" <<'EOF'
## What

<!-- The outcome. -->

## Why

<!-- The problem and why it matters. -->

Fixes #
EOF
expect_fail "reversed Why and What template" "effective template must place ## Why before ## What" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=repo \
  GH_TEMPLATE_FIXTURE="${fixture_root}/reversed-template.md" \
  "${subject}" seed --repo devantler-tech/platform --output "${fixture_root}/reversed-seed.md"

expect_fail "missing effective template" "no effective GitHub pull request template" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=none GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" seed --repo devantler-tech/platform --output "${fixture_root}/missing.md"

expect_fail "template lookup authorization failure" \
  "template directory lookup failed for devantler-tech/platform/.github" env \
  PATH="${fixture_root}/bin:${PATH}" GH_MODE=authfail GH_TEMPLATE_FIXTURE="${fixture_root}/template.md" \
  "${subject}" seed --repo devantler-tech/platform --output "${fixture_root}/authfail.md"

echo "pr-body contract test: PASS"
