#!/usr/bin/env bash
#
# pr-ownership-disclosure.sh
#
# Thin wrapper around the Go guard in pr-ownership-disclosure-go/, matching
# comment-disclosure-drift.sh and memory-hygiene.sh: build to a temporary
# binary, feed it a PR body, print its verdict.
#
# Classifies a `devantler` pull-request body as the maintainer's hand-driven
# work, the routine's own output, or neither. The maintainer drives Claude Code
# interactively, so his PRs share the routine's author and branch namespace; the
# body's disclosure marker is the only signal that separates them.
#
#   interactive   carries `Generated with [Claude Code]` — HANDS-OFF
#   routine       carries `Generated by the` and no interactive marker
#   none          neither; genuinely unknown, NOT a synonym for either
#
# `interactive` is decisive. `routine` is corroborating only — the routine
# disclosure also appears on maintainer-interactive PRs, so the caller still
# weighs it against its own creation record before acting.
#
# A marker is matched as a LINE anywhere in the body, through its Markdown
# container prefixes — never anchored at the start of the body, and never as a
# bare substring. See the Go guard's package comment for why both of those fail,
# and in which direction.
#
# Usage:
#   pr-ownership-disclosure.sh --input <file>|-
#   pr-ownership-disclosure.sh --repo <owner>/<repo> --pr <number>
#
# Exit codes:
#   0  classified (verdict on stdout)
#   2  usage, unreadable input, or a failed fetch
set -Eeuo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

input=""
repo=""
pr=""

die() {
  echo "pr-ownership-disclosure: $1" >&2
  exit 2
}

while [ $# -gt 0 ]; do
  case "$1" in
    --input)
      [ $# -ge 2 ] || die "--input needs a value"
      input="$2"
      shift 2
      ;;
    --repo)
      [ $# -ge 2 ] || die "--repo needs a value"
      repo="$2"
      shift 2
      ;;
    --pr)
      [ $# -ge 2 ] || die "--pr needs a value"
      pr="$2"
      shift 2
      ;;
    -h|--help)
      sed -n '3,32p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

if [ -n "$input" ] && { [ -n "$repo" ] || [ -n "$pr" ]; }; then
  die "--input is mutually exclusive with --repo/--pr"
fi
if [ -z "$input" ]; then
  [ -n "$repo" ] && [ -n "$pr" ] || die "need --input, or both --repo and --pr"
fi

guard_binary=""
body_file=""

# shellcheck disable=SC2329 # Invoked indirectly by the EXIT trap.
cleanup() {
  [ -n "$guard_binary" ] && rm -f -- "$guard_binary"
  [ -n "$body_file" ] && rm -f -- "$body_file"
  return 0
}
trap cleanup EXIT

guard_binary="$(mktemp "${TMPDIR:-/tmp}/pr-ownership-disclosure.XXXXXX")" ||
  die "failed to allocate temporary binary"

if ! go -C "$script_dir/pr-ownership-disclosure-go" build -o "$guard_binary" .; then
  die "failed to build Go guard"
fi

if [ -n "$input" ]; then
  if [ "$input" = "-" ]; then
    "$guard_binary" --input -
    exit $?
  fi
  [ -r "$input" ] || die "cannot read body: $input"
  "$guard_binary" --input "$input"
  exit $?
fi

# Fetch the body. Never suppress stderr here: an API failure that reads as an
# empty body would classify `none`, which is the value that invites a run to act
# on what may be the maintainer's PR.
body_file="$(mktemp "${TMPDIR:-/tmp}/pr-ownership-body.XXXXXX")" ||
  die "failed to allocate temporary body file"

if ! gh pr view "$pr" --repo "$repo" --json body --jq '.body' >"$body_file"; then
  die "failed to fetch $repo#$pr"
fi

"$guard_binary" --input "$body_file"
