#!/usr/bin/env bash
#
# pr-ownership-disclosure.test.sh
#
# Covers the WRAPPER, not the Go guard — main_test.go owns the classification
# rules. What can only go wrong here is the wrapper forwarding its flags, and it
# already did: --enforce reached the two --input invocations and not the
# --repo/--pr one, so `--enforce --repo X --pr N` classified and exited 0 on a
# body that carries both literals. That is a fail-open on the flag whose whole
# purpose is to fail.
set -Eeuo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
wrapper="$script_dir/pr-ownership-disclosure.sh"
failures=0

fail() {
  echo "FAIL: $1" >&2
  failures=$((failures + 1))
}

work="$(mktemp -d)"
trap 'rm -rf -- "$work"' EXIT

printf '> 🤖 Generated by the Agentic Engineer\n\nWhy\n\n🤖 Generated with [Claude Code](x)\n' >"$work/collision.md"
printf '> 🤖 Generated by the Agentic Engineer\n\nFixes #1\n' >"$work/routine.md"
printf 'Hand written\n\n🤖 Generated with [Claude Code](x)\n' >"$work/interactive.md"

# --- Static: every guard invocation forwards --enforce -------------------------
#
# A behavioural test cannot reach the --repo/--pr path without the network, so
# the forwarding itself is asserted structurally. This is what catches a NEW
# invocation added later without the flag.
# shellcheck disable=SC2016 # The guard name is matched literally, not expanded.
invocations="$(grep -c '"\$guard_binary" \${enforce:+\$enforce} --input' "$wrapper" || true)"
# shellcheck disable=SC2016 # Literal match, as above.
total="$(grep -c '"\$guard_binary" .*--input' "$wrapper" || true)"

if [ "$invocations" -ne "$total" ] || [ "$total" -eq 0 ]; then
  fail "every \$guard_binary --input invocation must forward \${enforce:+\$enforce} (forwarding=$invocations of $total)"
fi

# --- Behavioural: --enforce decides the exit code ------------------------------
run_case() {
  local body="$1" want="$2" shift_args="${3:-}"
  local rc=0
  # shellcheck disable=SC2086 # shift_args is a deliberate word-split flag list.
  bash "$wrapper" $shift_args --input "$body" >/dev/null 2>&1 || rc=$?
  if [ "$rc" -ne "$want" ]; then
    fail "$(basename "$body") with '${shift_args:-no flags}': exit $rc, want $want"
  fi
}

run_case "$work/collision.md" 1 --enforce
run_case "$work/routine.md" 0 --enforce
run_case "$work/interactive.md" 0 --enforce

# Without --enforce the wrapper classifies and never fails, so an existing
# caller cannot start failing because the flag was added.
run_case "$work/collision.md" 0
run_case "$work/routine.md" 0
run_case "$work/interactive.md" 0

# --- The failure names its own fix --------------------------------------------
message="$(bash "$wrapper" --enforce --input "$work/collision.md" 2>&1 >/dev/null || true)"
for needle in "COLLISION" "Generated with [Claude Code]" "delete"; do
  case "$message" in
    *"$needle"*) ;;
    *) fail "the collision message must mention '$needle' so the failure names its own fix" ;;
  esac
done

if [ "$failures" -ne 0 ]; then
  echo "pr-ownership-disclosure.test.sh: $failures failure(s)" >&2
  exit 1
fi

echo "pr-ownership-disclosure.test.sh: OK"
