#!/usr/bin/env bash
# review-request-comment.sh — compose a review-request comment body in the ONE shape the
# contract allows, so no lane hand-writes a bare trigger again (monorepo#3319).
#
# WHY THIS EXISTS
#   AGENTS.md requires every review request to carry the disclosure line and a current-head
#   request marker IN THE SAME COMMENT as the trigger, with Bugbot the single exception (its
#   trigger must be the whole comment body, so its disclosure + marker go in a preceding
#   comment). Stated only as prose, lanes kept posting bare `@codex review` /
#   `@coderabbitai full review` comments: 49 in 24h across two lanes on 2026-09-13. An
#   undisclosed `devantler` comment reads as the HUMAN MAINTAINER to every later run, so each
#   one is agent output sitting on the control channel.
#
# USAGE
#   review-request-comment.sh --provider cr     --head <sha> [--full] [--actor <role>]
#   review-request-comment.sh --provider codex  --head <sha> [--focus <text>] [--actor <role>]
#   review-request-comment.sh --provider bugbot --head <sha> --part disclosure [--actor <role>]
#   review-request-comment.sh --provider bugbot --part trigger
#
#   --head   the FULL 40-character head sha the request is for (abbreviations are refused:
#            the marker binds the request to one commit).
#   --full   CodeRabbit only: `@coderabbitai full review` instead of `@coderabbitai review`.
#   --focus  Codex only: a single line appended as `@codex review for <text>`.
#   --part   Bugbot only, and required: `disclosure` prints the marker comment to post FIRST;
#            `trigger` prints the exact bare trigger to post immediately after it.
#   --actor  `engineer` (default) or `improver` — selects the canonical disclosure line.
#
#   The body goes to stdout with no trailing newline. Post it with `--body-file`, never
#   `--body "@file"` (which posts the path).
#
# EXIT CODES
#   0  body printed
#   1  usage error — nothing printed
set -euo pipefail

usage() {
  sed -n '14,31p' "$0" >&2
  exit 1
}

die() {
  echo "review-request-comment: $*" >&2
  exit 1
}

provider=""
head=""
full=0
focus=""
focus_set=0
part=""
actor="engineer"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --provider)
      [ "$#" -ge 2 ] || usage
      provider="$2"
      shift 2
      ;;
    --head)
      [ "$#" -ge 2 ] || usage
      head="$2"
      shift 2
      ;;
    --full)
      full=1
      shift
      ;;
    --focus)
      [ "$#" -ge 2 ] || usage
      focus="$2"
      focus_set=1
      shift 2
      ;;
    --part)
      [ "$#" -ge 2 ] || usage
      part="$2"
      shift 2
      ;;
    --actor)
      [ "$#" -ge 2 ] || usage
      actor="$2"
      shift 2
      ;;
    -h | --help)
      usage
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

case "${actor}" in
  engineer) disclosure='> 🤖 Generated by the Agentic Engineer' ;;
  improver) disclosure='> 🤖 Generated by the Agent Improver' ;;
  *) die "--actor must be engineer or improver, got '${actor}'" ;;
esac

require_head() {
  case "${head}" in
    '') die "--head is required for this comment" ;;
  esac
  if [ "${#head}" -ne 40 ] || [[ ! "${head}" =~ ^[0-9a-f]{40}$ ]]; then
    die "--head must be a full 40-character lowercase sha, got '${head}'"
  fi
}

marker() {
  printf '<!-- review-request-head: %s provider=%s -->' "${head}" "$1"
}

case "${provider}" in
  cr)
    [ "${focus_set}" -eq 0 ] || die "--focus applies to codex only"
    [ -z "${part}" ] || die "--part applies to bugbot only"
    require_head
    trigger='@coderabbitai review'
    [ "${full}" -eq 0 ] || trigger='@coderabbitai full review'
    # The trigger is the LAST line with nothing after it: trailing prose has been measured
    # to make CodeRabbit parse the request as chat.
    printf '%s\n%s\n\n%s' "${disclosure}" "$(marker cr)" "${trigger}"
    ;;
  codex)
    [ "${full}" -eq 0 ] || die "--full applies to cr only"
    [ -z "${part}" ] || die "--part applies to bugbot only"
    require_head
    trigger='@codex review'
    if [ "${focus_set}" -eq 1 ]; then
      case "${focus}" in
        '' | *$'\n'* | *$'\r'*) die "--focus must be a single non-empty line" ;;
      esac
      trigger="@codex review for ${focus}"
    fi
    printf '%s\n%s\n\n%s' "${disclosure}" "$(marker codex)" "${trigger}"
    ;;
  bugbot)
    [ "${full}" -eq 0 ] || die "--full applies to cr only"
    [ "${focus_set}" -eq 0 ] || die "--focus applies to codex only"
    case "${part}" in
      disclosure)
        require_head
        printf '%s\n%s' "${disclosure}" "$(marker bugbot)"
        ;;
      trigger)
        # Bugbot exact-matches the whole body: any extra byte, including a disclosure line,
        # silently voids the request. This is the one sanctioned bare trigger.
        [ -z "${head}" ] || die "--head belongs on the disclosure part, not the trigger"
        printf '%s' '@cursor review'
        ;;
      '') die "--part disclosure|trigger is required for bugbot" ;;
      *) die "--part must be disclosure or trigger, got '${part}'" ;;
    esac
    ;;
  '') die "--provider is required (cr, codex or bugbot)" ;;
  *) die "--provider must be cr, codex or bugbot, got '${provider}'" ;;
esac
