#!/usr/bin/env bash
# The ablation phrases below are literal jq source, so nothing in them is meant to expand.
# shellcheck disable=SC2016
# review-no-gate-guard.test.sh — behavioural proof for review-no-gate-guard.sh (monorepo#3231).
# The captured platform#3616 head pins the measured defect: a served request and a refused duplicate
# at one head. The synthetic cases pin each lane's review shapes and binds, every failed or partial
# read is UNKNOWN, and the ablations at the end remove one rule at a time to prove it is operative.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
tool="${here}/review-no-gate-guard.sh"
fixtures="${here}/fixtures"
capture="${fixtures}/no-gate-duplicate-request-platform-3616.json"
capture_head="c533c43f4d256e3470260fbf67fcdd1a51497b30"
summary_fixture="${fixtures}/coderabbit-summary-green-platform-4039.txt"
summary_head="47702cc36a99d2a28b81793199cbae1c68819a60"
codex_fixture="${fixtures}/codex-comment-finding-2559.json"
codex_head="948bb06f73809c3aee43501ed81a0904d0fa218e"
head="0123456789abcdef0123456789abcdef01234567"
other="89abcdef0123456789abcdef0123456789abcdef"
cr="coderabbitai[bot]"
codex="chatgpt-codex-connector[bot]"
disclosure='> 🤖 Generated by the Agentic Engineer'
reply_marker='<!-- This is an auto-generated reply by CodeRabbit -->'
invocation='<!-- CodeRabbit review command invocation: v2:0000 -->'

tmp="$(mktemp -d)"
completed=0
# bash 3.2 can report a set -e abort inside an EXIT trap as exit 0, so require completion.
on_exit() {
  local status=$?
  rm -rf "${tmp}"
  if [ "${completed}" != 1 ]; then
    echo "review-no-gate-guard.test.sh: aborted before finishing; reporting failure rather than a clean pass" >&2
    [ "${status}" != 0 ] || status=1
    exit "${status}"
  fi
}
trap on_exit EXIT
failures=0
checks=0

for f in "${capture}" "${summary_fixture}" "${codex_fixture}"; do
  [ -s "${f}" ] || { echo "FAIL fixture missing or empty: ${f}" >&2; exit 1; }
done

# --- Builders ----------------------------------------------------------------------------------
review() { # review <id> <login> <commit> <submitted_at|null> <body> [state]
  jq -n --argjson id "$1" --arg login "$2" --arg commit "$3" --arg at "$4" --arg body "$5" \
    --arg state "${6:-COMMENTED}" \
    '{id:$id, user:{login:$login}, commit_id:$commit,
      submitted_at:(if $at == "null" then null else $at end), state:$state, body:$body}'
}
comment() { # comment <id> <login> <created_at|null> <body> [updated_at]
  jq -n --argjson id "$1" --arg login "$2" --arg at "$3" --arg body "$4" --arg up "${5:-$3}" \
    '{id:$id, user:{login:$login}, created_at:(if $at == "null" then null else $at end),
      updated_at:(if $up == "null" then null else $up end), body:$body}'
}
check() { # check <id> <app-slug> <head_sha> <status> <conclusion|null> <title> <completed_at>
  jq -n --argjson id "$1" --arg slug "$2" --arg sha "$3" --arg status "$4" --arg conclusion "$5" \
    --arg title "$6" --arg at "$7" \
    '{id:$id, name:"Cursor Bugbot", head_sha:$sha, status:$status,
      conclusion:(if $conclusion == "null" then null else $conclusion end),
      completed_at:(if $at == "" then null else $at end), app:{slug:$slug}, output:{title:$title}}'
}
list() { # list <json object>... -> one JSON array
  if [ "$#" -eq 0 ]; then printf '[]'; else printf '%s\n' "$@" | jq -cs .; fi
}
doc() { # doc <reviews array> <comments array> <check_runs array> -> path of a new input file
  # mktemp, not a counter: this runs in a command substitution, where a counter never advances and
  # every call would overwrite the document an earlier case still holds.
  local f
  f="$(mktemp "${tmp}/case.XXXXXX")"
  printf '%s\n%s\n%s\n' "$1" "$2" "$3" | jq -cs '{reviews:.[0], comments:.[1], check_runs:.[2]}' >"${f}"
  printf '%s' "${f}"
}
request() { # request <id> <provider> <created_at> [head] [login] [first line]
  comment "$1" "${5:-devantler}" "$3" "${6-${disclosure}}

<!-- review-request-head: ${4:-${head}} provider=$2 -->

@reviewer review"
}

run() { # run <tool> <args...> -> sets got, rc
  local t="$1"
  shift
  set +e
  got="$(bash "${t}" "$@" 2>"${tmp}/stderr")"
  rc=$?
  set -e
}

expect() { # expect <name> <want-rc> <want-stdout> <args...>
  local name="$1" want_rc="$2" want="$3"
  shift 3
  checks=$((checks + 1))
  run "${tool}" "$@"
  if [ "${rc}" != "${want_rc}" ] || [ "${got}" != "${want}" ]; then
    echo "FAIL ${name}: want rc=${want_rc} '${want}', got rc=${rc} '${got}' ($(cat "${tmp}/stderr"))" >&2
    failures=$((failures + 1))
  else
    echo "ok   ${name}"
  fi
}

# expect_unknown <name> <stderr fragment> <args...> — exit 2, NOTHING on stdout, and the reason named.
expect_unknown() {
  local name="$1" fragment="$2"
  shift 2
  checks=$((checks + 1))
  run "${tool}" "$@"
  if [ "${rc}" != 2 ] || [ -n "${got}" ] || ! grep -Fq -- "${fragment}" "${tmp}/stderr"; then
    echo "FAIL ${name}: want rc=2, empty stdout and '${fragment}' on stderr; got rc=${rc} '${got}' ($(cat "${tmp}/stderr"))" >&2
    failures=$((failures + 1))
  else
    echo "ok   ${name}"
  fi
}

guard() { # guard <name> <want-rc> <want-stdout> <input file> <head> <provider> [extra args...]
  local name="$1" want_rc="$2" want="$3" file="$4" sha="$5" lane="$6"
  shift 6
  expect "${name}" "${want_rc}" "${want}" --input "${file}" --head "${sha}" --provider "${lane}" "$@"
}

# --- The measured defect: platform#3616, 2026-09-06 ----------------------------------------------
# 02:28:01Z request A (`full review`), 02:29:53Z request B (`review`) for the SAME head,
# 02:31:02Z CodeRabbit submits a review of that head with findings, 02:31:43Z it answers request B
# with `Action not completed`, 02:33:23Z the head is recorded `cr:no-gate` and Codex is requested.
guard "captured: a served request and a refused duplicate at one head is NOT a no-gate" 1 \
  "REVIEWED cr@${capture_head} FINDINGS review:5123840277 2026-09-06T02:31:02Z" \
  "${capture}" "${capture_head}" cr
# The same capture carries the two refusals that WERE the head's whole answer from their lanes.
guard "captured: Codex's usage-limit reply with no Codex review admits its no-gate" 0 \
  "ADMIT codex@${capture_head}" "${capture}" "${capture_head}" codex
guard "captured: Bugbot's failed run (neutral, Error) admits its no-gate" 0 \
  "ADMIT bugbot@${capture_head}" "${capture}" "${capture_head}" bugbot
# Negative control: the check is not inert. Without the review object the same refusal admits.
jq 'del(.reviews[] | select(.user.login == "coderabbitai[bot]"))' "${capture}" >"${tmp}/capture-no-review.json"
guard "captured, review removed: a refusal with no review at the head admits the no-gate" 0 \
  "ADMIT cr@${capture_head}" "${tmp}/capture-no-review.json" "${capture_head}" cr

# --- CodeRabbit: review objects -----------------------------------------------------------------
t_request="2026-09-21T10:00:00Z"
t_before="2026-09-21T09:00:00Z"
t_review="2026-09-21T10:05:00Z"
t_refusal="2026-09-21T10:06:00Z"
green_body='**Actionable comments posted: 0**'
# The real rate-limit reply shape (platform#3344, 2026-08-23).
rate_limited="${reply_marker}
${invocation}
\`@devantler\`, I will review the changes.

<details>
<summary>⚠️ Action not completed</summary>

Review rate limited.

> Note: CodeRabbit is an incremental review system and does not re-review already reviewed commits. This command is applicable only when automatic reviews are paused.

</details>"
req="$(request 1 cr "${t_request}")"
refusal="$(comment 2 "${cr}" "${t_refusal}" "${rate_limited}")"

guard "a rate-limit refusal with no review at the head admits the no-gate" 0 "ADMIT cr@${head}" \
  "$(doc '[]' "$(list "${req}" "${refusal}")" '[]')" "${head}" cr
guard "a finding-free review plus a later refusal is the head's green, not a no-gate" 1 \
  "REVIEWED cr@${head} GREEN review:11 ${t_review}" \
  "$(doc "$(list "$(review 11 "${cr}" "${head}" "${t_review}" "${green_body}")")" "$(list "${req}" "${refusal}")" '[]')" "${head}" cr
guard "a review of another head leaves this head without a review" 0 "ADMIT cr@${head}" \
  "$(doc "$(list "$(review 11 "${cr}" "${other}" "${t_review}" "${green_body}")")" "$(list "${req}" "${refusal}")" '[]')" "${head}" cr
guard "an empty object at the head is a reply container, not a review" 0 "ADMIT cr@${head}" \
  "$(doc "$(list "$(review 11 "${cr}" "${head}" "${t_review}" "")")" "$(list "${req}" "${refusal}")" '[]')" "${head}" cr
guard "a review-shaped object from another account is not CodeRabbit's review" 0 "ADMIT cr@${head}" \
  "$(doc "$(list "$(review 11 "coderabbitai" "${head}" "${t_review}" "${green_body}")")" "$(list "${req}" "${refusal}")" '[]')" "${head}" cr
guard "a review-shaped object saying the review did not run is not a review" 0 "ADMIT cr@${head}" \
  "$(doc "$(list "$(review 11 "${cr}" "${head}" "${t_review}" "${green_body}

<!-- This is an auto-generated comment: rate limited by coderabbit.ai -->")")" "$(list "${req}" "${refusal}")" '[]')" "${head}" cr
guard "an identified review whose finding count cannot be trusted still blocks the no-gate" 1 \
  "REVIEWED cr@${head} UNJUDGED review:11 ${t_review}" \
  "$(doc "$(list "$(review 11 "${cr}" "${head}" "${t_review}" "${green_body}

<details>
<summary>🔇 Additional comments (1)</summary>")")" "$(list "${req}" "${refusal}")" '[]')" "${head}" cr
guard "an approval CodeRabbit submitted at the head is its verdict, whatever the body holds" 1 \
  "REVIEWED cr@${head} UNJUDGED review:11 ${t_review}" \
  "$(doc "$(list "$(review 11 "${cr}" "${head}" "${t_review}" "Looks good." APPROVED)")" "$(list "${req}" "${refusal}")" '[]')" "${head}" cr
guard "an approval from another account is not CodeRabbit's verdict" 0 "ADMIT cr@${head}" \
  "$(doc "$(list "$(review 11 "devantler" "${head}" "${t_review}" "Looks good." APPROVED)")" "$(list "${req}" "${refusal}")" '[]')" "${head}" cr
# The object judged is the object selected: a reply container sharing a review's id cannot stand in for it.
guard "two objects under one id are each judged on their own" 1 \
  "REVIEWED cr@${head} GREEN review:11 ${t_review}" \
  "$(doc "$(list "$(review 11 "${cr}" "${head}" "${t_before}" "")" "$(review 11 "${cr}" "${head}" "${t_review}" "${green_body}")")" '[]' '[]')" "${head}" cr
guard "every review at the head is listed, oldest first" 1 \
  "REVIEWED cr@${head} FINDINGS review:12 ${t_before}
REVIEWED cr@${head} GREEN review:11 ${t_review}" \
  "$(doc "$(list "$(review 11 "${cr}" "${head}" "${t_review}" "${green_body}")" \
    "$(review 12 "${cr}" "${head}" "${t_before}" '**Actionable comments posted: 2**')")" '[]' '[]')" "${head}" cr

# --- CodeRabbit: reply comments and the summary -------------------------------------------------
verdict_reply="${reply_marker}
${invocation}
\`@devantler\` Reviewed pull request \`#7\` at \`${head:0:8}\`. I found no actionable issues."
finding_reply="${reply_marker}

I reviewed the change.

**P1 — Fail closed on a missing input**

The check reports success when the input is absent."
guard "a verdict reply naming the head is the head's green" 1 \
  "REVIEWED cr@${head} GREEN comment:3 ${t_review}" \
  "$(doc '[]' "$(list "${req}" "$(comment 3 "${cr}" "${t_review}" "${verdict_reply}")" "${refusal}")" '[]')" "${head}" cr
guard "a verdict reply naming another commit is not this head's review" 0 "ADMIT cr@${other}" \
  "$(doc '[]' "$(list "$(comment 3 "${cr}" "${t_review}" "${verdict_reply}")")" '[]')" "${other}" cr
# Past the prefilter (it follows this head's request), the verdict helper itself rejects the other commit.
guard "a verdict reply after this head's request, naming another commit, is not this head's review" 0 "ADMIT cr@${other}" \
  "$(doc '[]' "$(list "$(request 1 cr "${t_request}" "${other}")" "$(comment 3 "${cr}" "${t_review}" "${verdict_reply}")")" '[]')" "${other}" cr
guard "a verdict reply from another account is not CodeRabbit's review" 0 "ADMIT cr@${head}" \
  "$(doc '[]' "$(list "${req}" "$(comment 3 "devantler" "${t_review}" "${verdict_reply}")")" '[]')" "${head}" cr
guard "a finding reply after this head's authenticated request is the head's review" 1 \
  "REVIEWED cr@${head} FINDINGS comment:3 ${t_review}" \
  "$(doc '[]' "$(list "${req}" "$(comment 3 "${cr}" "${t_review}" "${finding_reply}")" "${refusal}")" '[]')" "${head}" cr
guard "a finding reply older than this head's request belongs to another head" 0 "ADMIT cr@${head}" \
  "$(doc '[]' "$(list "${req}" "$(comment 3 "${cr}" "${t_before}" "${finding_reply}")")" '[]')" "${head}" cr
guard "a finding reply with no request for this head cannot be bound to it" 0 "ADMIT cr@${head}" \
  "$(doc '[]' "$(list "$(request 1 cr "${t_request}" "${other}")" "$(comment 3 "${cr}" "${t_review}" "${finding_reply}")")" '[]')" "${head}" cr
guard "a request marker from another account binds nothing" 0 "ADMIT cr@${head}" \
  "$(doc '[]' "$(list "$(request 1 cr "${t_request}" "${head}" "someone-else")" "$(comment 3 "${cr}" "${t_review}" "${finding_reply}")")" '[]')" "${head}" cr
guard "a request marker without the disclosure line binds nothing" 0 "ADMIT cr@${head}" \
  "$(doc '[]' "$(list "$(request 1 cr "${t_request}" "${head}" "devantler" "Please review.")" "$(comment 3 "${cr}" "${t_review}" "${finding_reply}")")" '[]')" "${head}" cr
guard "another lane's request marker binds no CodeRabbit reply" 0 "ADMIT cr@${head}" \
  "$(doc '[]' "$(list "$(request 1 codex "${t_request}")" "$(comment 3 "${cr}" "${t_review}" "${finding_reply}")")" '[]')" "${head}" cr
summary_body="$(cat "${summary_fixture}")"
guard "a real summary carrying a finding-free verdict for the head is the head's green" 1 \
  "REVIEWED cr@${summary_head} GREEN summary:4 ${t_review}" \
  "$(doc '[]' "$(list "$(comment 4 "${cr}" "${t_before}" "${summary_body}" "${t_review}")")" '[]')" "${summary_head}" cr
guard "that summary is no review of another head" 0 "ADMIT cr@${head}" \
  "$(doc '[]' "$(list "$(comment 4 "${cr}" "${t_before}" "${summary_body}" "${t_review}")")" '[]')" "${head}" cr
guard "a summary-shaped comment from another account is not CodeRabbit's" 0 "ADMIT cr@${summary_head}" \
  "$(doc '[]' "$(list "$(comment 4 "devantler" "${t_before}" "${summary_body}" "${t_review}")")" '[]')" "${summary_head}" cr
# One comment can carry both markers (a summary quoting a reply). Each shape is judged on its own.
guard "a green summary that also quotes the reply marker is still the head's green" 1 \
  "REVIEWED cr@${summary_head} GREEN summary:4 ${t_review}" \
  "$(doc '[]' "$(list "$(comment 4 "${cr}" "${t_before}" "${summary_body}

${reply_marker}" "${t_review}")")" '[]')" "${summary_head}" cr

# --- Codex ---------------------------------------------------------------------------------------
codex_finding="$(jq -r '.[] | select(.body | test("^## Review finding")) | .body' "${codex_fixture}")"
codex_clean="$(jq -r '.[] | select(.body | test("Didn.t find any major issues")) | .body' "${codex_fixture}")"
if [ -z "${codex_finding}" ] || [ -z "${codex_clean}" ]; then
  echo "FAIL the Codex fixture lost a body" >&2
  exit 1
fi
usage_limit='You have reached your Codex usage limits for code reviews.'
codex_req="$(request 1 codex "${t_request}")"
guard "Codex: a usage-limit reply with no review admits the no-gate" 0 "ADMIT codex@${head}" \
  "$(doc '[]' "$(list "${codex_req}" "$(comment 2 "${codex}" "${t_refusal}" "${usage_limit}")")" '[]')" "${head}" codex
guard "Codex: a review object at the head is its findings, whatever a later refusal says" 1 \
  "REVIEWED codex@${head} FINDINGS review:21 ${t_review}" \
  "$(doc "$(list "$(review 21 "${codex}" "${head}" "${t_review}" "")")" "$(list "${codex_req}" "$(comment 2 "${codex}" "${t_refusal}" "${usage_limit}")")" '[]')" "${head}" codex
guard "Codex: a review object at another head is not this head's review" 0 "ADMIT codex@${head}" \
  "$(doc "$(list "$(review 21 "${codex}" "${other}" "${t_review}" "")")" '[]' '[]')" "${head}" codex
guard "Codex: a real clean pass naming the head is the head's green" 1 \
  "REVIEWED codex@${codex_head} GREEN comment:5 ${t_review}" \
  "$(doc '[]' "$(list "$(comment 5 "${codex}" "${t_review}" "${codex_clean}")")" '[]')" "${codex_head}" codex
guard "Codex: that clean pass is no review of another head" 0 "ADMIT codex@${head}" \
  "$(doc '[]' "$(list "$(comment 5 "${codex}" "${t_review}" "${codex_clean}")")" '[]')" "${head}" codex
guard "Codex: a real comment-form finding whose permalinks name the head is its review" 1 \
  "REVIEWED codex@${codex_head} FINDINGS comment:6 ${t_review}" \
  "$(doc '[]' "$(list "$(comment 6 "${codex}" "${t_review}" "${codex_finding}")")" '[]')" "${codex_head}" codex
guard "Codex: that finding is no review of another head" 0 "ADMIT codex@${head}" \
  "$(doc '[]' "$(list "${codex_req}" "$(comment 6 "${codex}" "${t_review}" "${codex_finding}")")" '[]')" "${head}" codex
unattributed='## Review finding

**P2 — Fail closed when the probe errors**

The probe treats an error as a clean result.'
guard "Codex: a finding naming no commit, after this head's request, counts for this head" 1 \
  "REVIEWED codex@${head} FINDINGS comment:6 ${t_review}" \
  "$(doc '[]' "$(list "${codex_req}" "$(comment 6 "${codex}" "${t_review}" "${unattributed}")")" '[]')" "${head}" codex
guard "Codex: a finding naming no commit, with no request for this head, binds nothing" 0 "ADMIT codex@${head}" \
  "$(doc '[]' "$(list "$(comment 6 "${codex}" "${t_review}" "${unattributed}")")" '[]')" "${head}" codex
guard "Codex: a clean pass posted by another account is not Codex's" 0 "ADMIT codex@${codex_head}" \
  "$(doc '[]' "$(list "$(comment 5 "devantler" "${t_review}" "${codex_clean}")")" '[]')" "${codex_head}" codex
# A finding that quotes the clean-pass sentence must still be read as a finding.
guard "Codex: a finding that quotes the clean-pass sentence is still a finding" 1 \
  "REVIEWED codex@${codex_head} FINDINGS comment:6 ${t_review}" \
  "$(doc '[]' "$(list "$(comment 6 "${codex}" "${t_review}" "${codex_finding}

An earlier pass said: Didn't find any major issues.")")" '[]')" "${codex_head}" codex

# --- Cursor Bugbot ------------------------------------------------------------------------------
guard "Bugbot: a successful review check at the head is the head's green" 1 \
  "REVIEWED bugbot@${head} GREEN check:31 ${t_review}" \
  "$(doc '[]' '[]' "$(list "$(check 31 cursor "${head}" completed success 'Bugbot Review' "${t_review}")")")" "${head}" bugbot
guard "Bugbot: a neutral review check at the head is its findings" 1 \
  "REVIEWED bugbot@${head} FINDINGS check:31 ${t_review}" \
  "$(doc '[]' '[]' "$(list "$(check 31 cursor "${head}" completed neutral 'Bugbot Review' "${t_review}")")")" "${head}" bugbot
guard "Bugbot: a successful check under an unknown title is still a delivered run" 1 \
  "REVIEWED bugbot@${head} UNJUDGED check:31 ${t_review}" \
  "$(doc '[]' '[]' "$(list "$(check 31 cursor "${head}" completed success 'Bugbot' "${t_review}")")")" "${head}" bugbot
guard "Bugbot: a review followed by a failed re-run is still the head's review" 1 \
  "REVIEWED bugbot@${head} FINDINGS check:31 ${t_review}" \
  "$(doc '[]' '[]' "$(list "$(check 31 cursor "${head}" completed neutral 'Bugbot Review' "${t_review}")" \
    "$(check 32 cursor "${head}" completed neutral 'Error' "${t_refusal}")")")" "${head}" bugbot
guard "Bugbot: a neutral Error check is a run that never happened" 0 "ADMIT bugbot@${head}" \
  "$(doc '[]' '[]' "$(list "$(check 31 cursor "${head}" completed neutral 'Error' "${t_review}")")")" "${head}" bugbot
guard "Bugbot: a same-named check from another app is not Bugbot's" 0 "ADMIT bugbot@${head}" \
  "$(doc '[]' '[]' "$(list "$(check 31 github-actions "${head}" completed success 'Bugbot Review' "${t_review}")")")" "${head}" bugbot
guard "Bugbot: a check at another commit is not this head's review" 0 "ADMIT bugbot@${head}" \
  "$(doc '[]' '[]' "$(list "$(check 31 cursor "${other}" completed success 'Bugbot Review' "${t_review}")")")" "${head}" bugbot

# --- A round restarted at the same head ----------------------------------------------------------
# A recorded refutation restarts the loop at the same head: request, review with findings, the
# resolution record, the restarting request, its refusal. The earlier round's review then no longer
# speaks for the restarted round, so that round's own refusal may be recorded.
t_resolved="2026-09-21T10:20:00Z"
t_rerequest="2026-09-21T10:21:00Z"
t_rerefusal="2026-09-21T10:22:00Z"
rereq="$(request 5 cr "${t_rerequest}")"
rerefusal="$(comment 6 "${cr}" "${t_rerefusal}" "${rate_limited}")"
restart_doc="$(doc "$(list "$(review 11 "${cr}" "${head}" "${t_review}" '**Actionable comments posted: 1**')")" \
  "$(list "${req}" "${rereq}" "${rerefusal}")" '[]')"
guard "without a round start, an earlier review at the head blocks the no-gate" 1 \
  "REVIEWED cr@${head} FINDINGS review:11 ${t_review}" "${restart_doc}" "${head}" cr
guard "a round restarted after that review admits the restarted round's no-gate" 0 \
  "ADMIT cr@${head} round-start=${t_resolved}" "${restart_doc}" "${head}" cr --round-start "${t_resolved}"
guard "a review at the round start is inside the round" 1 \
  "REVIEWED cr@${head} FINDINGS review:11 ${t_review}" "${restart_doc}" "${head}" cr --round-start "${t_review}"
# A round start is only the resolution record that a restarting request FOLLOWED. A time with no
# request after it restarted nothing, and would only hide the review.
expect_unknown "a round start at the refusal's own time is refused" "not followed by an authenticated" \
  --input "${restart_doc}" --head "${head}" --provider cr --round-start "${t_rerefusal}"
expect_unknown "a round start at the restarting request's own time is refused" "not followed by an authenticated" \
  --input "${restart_doc}" --head "${head}" --provider cr --round-start "${t_rerequest}"
expect_unknown "captured: the duplicate's refusal time cannot be passed off as a round start" \
  "not followed by an authenticated" \
  --input "${capture}" --head "${capture_head}" --provider cr --round-start 2026-09-06T02:31:43Z
expect_unknown "a round start with only another lane's request after it is refused" "not followed by an authenticated" \
  --input "${restart_doc}" --head "${head}" --provider codex --round-start "${t_resolved}"
# The round applies to every surface and lane, not only CodeRabbit review objects.
guard "a finding reply from the earlier round is outside the restarted round" 0 \
  "ADMIT cr@${head} round-start=${t_resolved}" \
  "$(doc '[]' "$(list "${req}" "$(comment 3 "${cr}" "${t_review}" "${finding_reply}")" "${rereq}" "${rerefusal}")" '[]')" \
  "${head}" cr --round-start "${t_resolved}"
codex_rereq="$(request 5 codex "${t_rerequest}")"
guard "Codex: a review from the earlier round is outside the restarted round" 0 \
  "ADMIT codex@${head} round-start=${t_resolved}" \
  "$(doc "$(list "$(review 21 "${codex}" "${head}" "${t_review}" "")")" "$(list "${codex_req}" "${codex_rereq}")" '[]')" \
  "${head}" codex --round-start "${t_resolved}"
bugbot_rereq="$(request 5 bugbot "${t_rerequest}")"
bugbot_restart="$(doc '[]' "$(list "${bugbot_rereq}")" "$(list "$(check 31 cursor "${head}" completed neutral 'Bugbot Review' "${t_review}")")")"
guard "Bugbot: a run from the earlier round is outside the restarted round" 0 \
  "ADMIT bugbot@${head} round-start=${t_resolved}" "${bugbot_restart}" "${head}" bugbot --round-start "${t_resolved}"
guard "Bugbot: without a round start that run is the head's review" 1 \
  "REVIEWED bugbot@${head} FINDINGS check:31 ${t_review}" "${bugbot_restart}" "${head}" bugbot
jq 'del(.comments)' "${bugbot_restart}" >"${tmp}/bugbot-no-comments.json"
expect_unknown "Bugbot: a round start cannot be checked without the comments" "comments" \
  --input "${tmp}/bugbot-no-comments.json" --head "${head}" --provider bugbot --round-start "${t_resolved}"

# --- A failed or partial read is UNKNOWN, never a no-gate ----------------------------------------
jq 'del(.reviews)' "${capture}" >"${tmp}/no-reviews.json"
expect_unknown "an input whose reviews were never read is UNKNOWN" "reviews" \
  --input "${tmp}/no-reviews.json" --head "${capture_head}" --provider cr
jq '.comments = null' "${capture}" >"${tmp}/null-comments.json"
expect_unknown "an input whose comments read came back empty-handed is UNKNOWN" "comments" \
  --input "${tmp}/null-comments.json" --head "${capture_head}" --provider cr
expect_unknown "Codex needs both surfaces too" "reviews" \
  --input "${tmp}/no-reviews.json" --head "${capture_head}" --provider codex
jq 'del(.check_runs)' "${capture}" >"${tmp}/no-checks.json"
expect_unknown "Bugbot's verdict needs the check-runs" "check_runs" \
  --input "${tmp}/no-checks.json" --head "${capture_head}" --provider bugbot
guard "CodeRabbit's verdict does not need the check-runs" 1 \
  "REVIEWED cr@${capture_head} FINDINGS review:5123840277 2026-09-06T02:31:02Z" \
  "${tmp}/no-checks.json" "${capture_head}" cr
printf '{"reviews": [' >"${tmp}/truncated.json"
expect_unknown "a truncated document is UNKNOWN" "exactly one JSON object" \
  --input "${tmp}/truncated.json" --head "${head}" --provider cr
printf '{"reviews":["oops"],"comments":[],"check_runs":[]}\n' >"${tmp}/not-objects.json"
expect_unknown "a surface that is not a list of objects is UNKNOWN" "reviews" \
  --input "${tmp}/not-objects.json" --head "${head}" --provider cr
expect_unknown "an unreadable input is UNKNOWN" "cannot read" \
  --input "${tmp}/absent.json" --head "${head}" --provider cr
# A lane's artifact at the head that lost its time is a read that lost a field. Skipping it would
# admit a no-gate over a review that is there.
expect_unknown "a CodeRabbit review at the head with no time is UNKNOWN" "cannot scan the reviews" \
  --input "$(doc "$(list "$(review 11 "${cr}" "${head}" null "${green_body}")")" '[]' '[]')" --head "${head}" --provider cr
expect_unknown "a Codex review at the head with no time is UNKNOWN" "cannot scan the reviews" \
  --input "$(doc "$(list "$(review 21 "${codex}" "${head}" null "")")" '[]' '[]')" --head "${head}" --provider codex
expect_unknown "a CodeRabbit reply with no time is UNKNOWN" "cannot scan the comments" \
  --input "$(doc '[]' "$(list "${req}" "$(comment 3 "${cr}" null "${verdict_reply}")")" '[]')" --head "${head}" --provider cr
expect_unknown "a completed Bugbot run with no time is UNKNOWN" "cannot scan the check-runs" \
  --input "$(doc '[]' '[]' "$(list "$(check 31 cursor "${head}" completed success 'Bugbot Review' "")")")" --head "${head}" --provider bugbot
# A sibling verdict helper that cannot run must stop the guard, not skip the artifact it would judge.
mkdir -p "${tmp}/alone"
cp "${tool}" "${tmp}/alone/review-no-gate-guard.sh"
checks=$((checks + 1))
run "${tmp}/alone/review-no-gate-guard.sh" --input "${capture}" --head "${capture_head}" --provider cr
if [ "${rc}" = 2 ] && [ -z "${got}" ] && grep -Fq "cannot judge review" "${tmp}/stderr"; then
  echo "ok   a missing verdict helper is UNKNOWN, not a skipped review"
else
  echo "FAIL a missing verdict helper: want rc=2, empty stdout and 'cannot judge review'; got rc=${rc} '${got}' ($(cat "${tmp}/stderr"))" >&2
  failures=$((failures + 1))
fi


# --- The gaps the review of #3807 left (monorepo#3821) -------------------------------------------
# 1. A request marker counts only on a line of its own. Round one: request, review with findings,
#    the resolution record. Afterwards a disclosed comment only QUOTES the marker, so no request
#    restarted the round and the round start has nothing to stand on.
quoting="$(comment 7 devantler "${t_rerequest}" "${disclosure}

The earlier request carried \`<!-- review-request-head: ${head} provider=cr -->\` in its body.")"
expect_unknown "a comment that only quotes the request marker restarts no round" "not followed by an authenticated" \
  --input "$(doc "$(list "$(review 11 "${cr}" "${head}" "${t_review}" "'**Actionable comments posted: 1**'")")" \
    "$(list "${req}" "${quoting}")" '[]')" --head "${head}" --provider cr --round-start "${t_resolved}"
indented="$(comment 7 devantler "${t_rerequest}" "${disclosure}

  <!-- review-request-head: ${head} provider=cr -->  
@coderabbitai review")"
guard "a marker on its own line still counts with spaces around it and a CR line ending" 0 \
  "ADMIT cr@${head} round-start=${t_resolved}" \
  "$(doc "$(list "$(review 11 "${cr}" "${head}" "${t_review}" "'**Actionable comments posted: 1**'")")" \
    "$(list "${req}" "$(jq -c '.body |= gsub("\n"; "\r\n")' <<<"${indented}")")" '[]')" \
  "${head}" cr --round-start "${t_resolved}"

# 2. Times are compared as text, which is sound only for UTC seconds. Any other spelling is refused.
expect_unknown "a review stamped with a non-UTC offset is UNKNOWN" "not a UTC time" \
  --input "$(doc "$(list "$(review 11 "${cr}" "${head}" "2026-09-06T04:31:02+02:00" "'**Actionable comments posted: 1**'")")" "$(list "${req}")" '[]')" \
  --head "${head}" --provider cr
expect_unknown "a time with fractional seconds is UNKNOWN" "not a UTC time" \
  --input "$(doc '[]' '[]' "$(list "$(check 31 cursor "${head}" completed success 'Bugbot Review' "2026-09-06T02:31:02.500Z")")")" \
  --head "${head}" --provider bugbot

# 3. A Bugbot run that has not completed is an accepted request with no answer yet.
expect_unknown "Bugbot: a run still in progress is UNKNOWN, not a no-gate" "has not completed" \
  --input "$(doc '[]' '[]' "$(list "$(check 31 cursor "${head}" in_progress null 'Bugbot Review' "")")")" \
  --head "${head}" --provider bugbot
expect_unknown "Bugbot: a queued run is UNKNOWN too" "has not completed" \
  --input "$(doc '[]' '[]' "$(list "$(check 31 cursor "${head}" queued null '' "")")")" \
  --head "${head}" --provider bugbot
guard "Bugbot: a review already delivered governs while a re-run is still in progress" 1 \
  "REVIEWED bugbot@${head} FINDINGS check:31 ${t_review}" \
  "$(doc '[]' '[]' "$(list "$(check 31 cursor "${head}" completed neutral 'Bugbot Review' "${t_review}")" \
    "$(check 32 cursor "${head}" in_progress null 'Bugbot Review' "")")")" "${head}" bugbot
guard "Bugbot: a run in progress at another commit does not hold this head" 0 "ADMIT bugbot@${head}" \
  "$(doc '[]' '[]' "$(list "$(check 31 cursor "${other}" in_progress null 'Bugbot Review' "")")")" "${head}" bugbot

# 4. Only the measured never-ran shape (neutral, titled Error) admits. Every other completed run is
#    an unmeasured shape to read by hand.
for conclusion in failure timed_out cancelled action_required; do
  guard "Bugbot: a completed run that ended ${conclusion} is read by hand, not admitted" 1 \
    "REVIEWED bugbot@${head} UNJUDGED check:31 ${t_review}" \
    "$(doc '[]' '[]' "$(list "$(check 31 cursor "${head}" completed "${conclusion}" 'Bugbot Review' "${t_review}")")")" "${head}" bugbot
done
guard "Bugbot: a neutral run under an unknown title is read by hand, not admitted" 1 \
  "REVIEWED bugbot@${head} UNJUDGED check:31 ${t_review}" \
  "$(doc '[]' '[]' "$(list "$(check 31 cursor "${head}" completed neutral 'Something new' "${t_review}")")")" "${head}" bugbot

# 5. The input is ONE document. A second one would otherwise be read past.
two_docs="${tmp}/two-documents.json"
cat "$(doc '[]' '[]' '[]')" "$(doc "$(list "$(review 11 "${cr}" "${head}" "${t_review}" "'**Actionable comments posted: 1**'")")" '[]' '[]')" >"${two_docs}"
expect_unknown "an input holding two documents is UNKNOWN" "exactly one JSON object" \
  --input "${two_docs}" --head "${head}" --provider cr
printf '[]\n' >"${tmp}/array.json"
expect_unknown "an input that is not an object is UNKNOWN" "exactly one JSON object" \
  --input "${tmp}/array.json" --head "${head}" --provider cr

# --- A recorded read on stdin --------------------------------------------------------------------
stdin_case() { # stdin_case <name> <want-rc> <want-stdout> <file fed to stdin> <provider>
  checks=$((checks + 1))
  set +e
  got="$(bash "${tool}" --input - --head "${capture_head}" --provider "$5" <"$4" 2>"${tmp}/stderr")"
  rc=$?
  set -e
  if [ "${rc}" != "$2" ] || [ "${got}" != "$3" ]; then
    echo "FAIL $1: want rc=$2 '$3', got rc=${rc} '${got}' ($(cat "${tmp}/stderr"))" >&2
    failures=$((failures + 1))
  else
    echo "ok   $1"
  fi
}
stdin_case "stdin: the captured head is judged the same way" 1 \
  "REVIEWED cr@${capture_head} FINDINGS review:5123840277 2026-09-06T02:31:02Z" "${capture}" cr
stdin_case "stdin: an empty read is UNKNOWN" 2 "" /dev/null cr

# --- Usage ---------------------------------------------------------------------------------------
expect_unknown "an abbreviated head is refused" "40-character" \
  --input "${capture}" --head "${capture_head:0:12}" --provider cr
expect_unknown "an unknown provider is refused" "provider" \
  --input "${capture}" --head "${capture_head}" --provider copilot
expect_unknown "a malformed round start is refused" "round-start" \
  --input "${capture}" --head "${capture_head}" --provider cr --round-start yesterday
expect_unknown "an input file and a live pull request together are refused" "either" \
  --input "${capture}" --repo devantler-tech/platform --pr 3616 --head "${capture_head}" --provider cr
expect_unknown "a pull request without a repository is refused" "either" \
  --pr 3616 --head "${capture_head}" --provider cr
expect_unknown "a pull request number that is not a number is refused" "--pr" \
  --repo devantler-tech/platform --pr 36x --head "${capture_head}" --provider cr

# --- Live reads through a stub gh ----------------------------------------------------------------
mkdir -p "${tmp}/bin"
# The stub maps the endpoint to a file in $STUB_DIR. A missing file is a failed read; a `<key>.rc`
# file makes the read print its pages and then fail, as a pagination that broke midway does.
cat >"${tmp}/bin/gh" <<'STUB'
#!/usr/bin/env bash
dir="${STUB_DIR:?}"
path=""
for a in "$@"; do case "$a" in api | --paginate) ;; *) path="$a" ;; esac; done
case "$path" in
  */pulls/*/reviews*) key=reviews ;;
  */pulls/*) key=pr ;;
  */issues/*/comments*) key=comments ;;
  */check-runs*) key=check-runs ;;
  *) exit 1 ;;
esac
printf '%s\n' "$path" >>"${dir}/requests.log"
[ -e "${dir}/${key}" ] || { echo "gh: HTTP 502" >&2; exit 1; }
cat "${dir}/${key}"
[ ! -e "${dir}/${key}.rc" ] || exit "$(cat "${dir}/${key}.rc")"
STUB
chmod +x "${tmp}/bin/gh"

stub() { # stub <name> -> a stub directory serving the captured head, two pages per list
  local d="${tmp}/stub/$1"
  mkdir -p "${d}"
  printf '{"number":3616,"head":{"sha":"%s"}}\n' "${capture_head}" >"${d}/pr"
  jq -c '.reviews[:1], .reviews[1:]' "${capture}" >"${d}/reviews"
  jq -c '.comments[:3], .comments[3:]' "${capture}" >"${d}/comments"
  jq -c '{total_count: (.check_runs | length), check_runs}' "${capture}" >"${d}/check-runs"
  printf '%s' "${d}"
}
live() { # live <name> <want-rc> <want-stdout> <stub dir> <provider>
  local name="$1" want_rc="$2" want="$3" dir="$4" lane="$5"
  checks=$((checks + 1))
  set +e
  got="$(PATH="${tmp}/bin:${PATH}" STUB_DIR="${dir}" bash "${tool}" --repo devantler-tech/platform \
    --pr 3616 --head "${capture_head}" --provider "${lane}" 2>"${tmp}/stderr")"
  rc=$?
  set -e
  if [ "${rc}" != "${want_rc}" ] || [ "${got}" != "${want}" ]; then
    echo "FAIL ${name}: want rc=${want_rc} '${want}', got rc=${rc} '${got}' ($(cat "${tmp}/stderr"))" >&2
    failures=$((failures + 1))
  else
    echo "ok   ${name}"
  fi
}

d="$(stub served)"
live "live: the review is found across pages" 1 \
  "REVIEWED cr@${capture_head} FINDINGS review:5123840277 2026-09-06T02:31:02Z" "${d}" cr
live "live: Codex's refusal with no review admits" 0 "ADMIT codex@${capture_head}" "${d}" codex
live "live: Bugbot's failed run admits" 0 "ADMIT bugbot@${capture_head}" "${d}" bugbot
# GitHub returns only the newest run of a check unless asked for all of them, and a failed re-run
# would then hide the review an earlier run delivered.
checks=$((checks + 1))
if grep -Fq 'check-runs?check_name=Cursor%20Bugbot&filter=all' "${d}/requests.log"; then
  echo "ok   live: the check-runs read asks for every run, not only the newest"
else
  echo "FAIL live: the check-runs read does not ask for filter=all ($(cat "${d}/requests.log"))" >&2
  failures=$((failures + 1))
fi
d="$(stub comments-failed)"
rm "${d}/comments"
live "live: a failed comments read is UNKNOWN" 2 "" "${d}" cr
d="$(stub reviews-failed)"
rm "${d}/reviews"
live "live: a failed reviews read is UNKNOWN" 2 "" "${d}" codex
# The first page arrived and holds no review, then the read failed: the review may be on page two.
d="$(stub reviews-partial)"
jq -c '.reviews[:1]' "${capture}" >"${d}/reviews"
printf '1' >"${d}/reviews.rc"
live "live: a reviews read that broke after its first page is UNKNOWN, never a no-gate" 2 "" "${d}" cr
d="$(stub reviews-empty)"
: >"${d}/reviews"
live "live: a read that returned nothing at all is UNKNOWN" 2 "" "${d}" cr
d="$(stub head-moved)"
printf '{"number":3616,"head":{"sha":"%s"}}\n' "${other}" >"${d}/pr"
live "live: a head that has moved is UNKNOWN" 2 "" "${d}" cr
d="$(stub pr-failed)"
rm "${d}/pr"
live "live: an unreadable pull request is UNKNOWN" 2 "" "${d}" cr
d="$(stub checks-failed)"
rm "${d}/check-runs"
live "live: a failed check-runs read is UNKNOWN" 2 "" "${d}" bugbot
d="$(stub checks-truncated)"
jq -c '{total_count: 150, check_runs}' "${capture}" >"${d}/check-runs"
live "live: check-runs short of their total are UNKNOWN" 2 "" "${d}" bugbot

# --- Ablations: each rule is what makes its case pass --------------------------------------------
# An ablated copy needs the sibling verdict helpers beside it.
mkdir -p "${tmp}/ablated"
for helper in coderabbit-review-verdict.sh coderabbit-comment-verdict.sh coderabbit-summary-verdict.sh; do
  ln -s "${here}/${helper}" "${tmp}/ablated/${helper}"
done
ablate() { # ablate <name> <literal> <replacement> <want-rc> <want-stdout> <args...>
  local name="$1" literal="$2" replacement="$3" want_rc="$4" want="$5" copy="${tmp}/ablated/review-no-gate-guard.sh"
  shift 5
  checks=$((checks + 1))
  LITERAL="${literal}" REPLACEMENT="${replacement}" awk '
    { i = index($0, ENVIRON["LITERAL"]) }
    i { $0 = substr($0, 1, i - 1) ENVIRON["REPLACEMENT"] substr($0, i + length(ENVIRON["LITERAL"])); hits++ }
    { print }
    END { exit hits == 1 ? 0 : 1 }' "${tool}" >"${copy}" || {
    echo "FAIL ablation '${name}': the literal did not match exactly once, so the result proves nothing" >&2
    failures=$((failures + 1))
    return 0
  }
  run "${copy}" "$@"
  if [ "${rc}" != "${want_rc}" ] || [ "${got}" != "${want}" ]; then
    echo "FAIL ablation '${name}': want rc=${want_rc} '${want}', got rc=${rc} '${got}' ($(cat "${tmp}/stderr"))" >&2
    failures=$((failures + 1))
  else
    echo "ok   ablation: ${name}"
  fi
}

# Without the review-object read, the measured defect returns: the refused duplicate reads as a no-gate.
ablate "dropping the review-object read admits the captured head again" \
  'select(.user.login == "coderabbitai[bot]" and .commit_id == $head)' \
  'select(false)' 0 "ADMIT cr@${capture_head}" \
  --input "${capture}" --head "${capture_head}" --provider cr
# Without the head bind, a review of any other commit would block this head's no-gate. (Codex: for
# CodeRabbit the verdict helper binds the head a second time.)
ablate "dropping the head bind lets another head's review block this one" \
  'select(.user.login == "chatgpt-codex-connector[bot]" and .commit_id == $head)' \
  'select(.user.login == "chatgpt-codex-connector[bot]")' 1 \
  "REVIEWED codex@${head} FINDINGS review:21 ${t_review}" \
  --input "$(doc "$(list "$(review 21 "${codex}" "${other}" "${t_review}" "")")" '[]' '[]')" --head "${head}" --provider codex
# Without the author bind on a request marker, any account could attach a finding reply to a head.
ablate "dropping the request marker's author bind lets another account bind a reply" \
  'select(.user.login == "devantler" and (body | startswith("> 🤖 Generated by the"))' \
  'select((body | startswith("> 🤖 Generated by the"))' 1 \
  "REVIEWED cr@${head} FINDINGS comment:3 ${t_review}" \
  --input "$(doc '[]' "$(list "$(request 1 cr "${t_request}" "${head}" "someone-else")" "$(comment 3 "${cr}" "${t_review}" "${finding_reply}")")" '[]')" --head "${head}" --provider cr
# Without the round filter, --round-start would be accepted and ignored.
ablate "dropping the round filter makes --round-start inert" \
  'def in_round: $round == "" or . >= $round;' \
  'def in_round: true;' 1 \
  "REVIEWED cr@${head} FINDINGS review:11 ${t_review}" \
  --input "${restart_doc}" --head "${head}" --provider cr --round-start "${t_resolved}"
# Without the check that a request follows the round start, any later time hides the review: here
# the duplicate's own refusal time, on the captured head.
ablate "dropping the round-start check lets a refusal's time hide the captured review" \
  'if [ -n "$round" ] && { [ -z "$latest_request" ] || [[ ! "$latest_request" > "$round" ]]; }; then' \
  'if false; then' 0 "ADMIT cr@${capture_head} round-start=2026-09-06T02:31:43Z" \
  --input "${capture}" --head "${capture_head}" --provider cr --round-start 2026-09-06T02:31:43Z
# Without the time requirement, a review that lost its time is skipped and the no-gate admitted.
ablate "dropping the time requirement skips a review that lost its time" \
  'def at: if type == "string" then . else error("an artifact carries no time") end' \
  'def at: if type == "string" then . else empty end' 0 "ADMIT cr@${head}" \
  --input "$(doc "$(list "$(review 11 "${cr}" "${head}" null "${green_body}")")" '[]' '[]')" --head "${head}" --provider cr
# Without the finding-first order, a Codex finding that quotes the clean-pass sentence is dropped.
ablate "judging the clean pass first drops a finding that quotes it" \
  'if $finding then [$t, .id, "FINDINGS", "comment"] | @tsv' \
  'if $clean then [$t, .id, "GREEN", "comment"] | @tsv elif false then empty' 0 "ADMIT codex@${codex_head}" \
  --input "$(doc '[]' "$(list "$(comment 6 "${codex}" "${t_review}" "${codex_finding}

An earlier pass said: Didn't find any major issues.")")" '[]')" --head "${codex_head}" --provider codex

# Without the own-line rule, a comment that only quotes the marker restarts the round and hides the review.
ablate "matching the marker anywhere lets a quoted marker restart the round" \
  'and (lines | index("<!-- review-request-head: \($head) provider=\($provider) -->") != null))' \
  'and (body | contains("<!-- review-request-head: \($head) provider=\($provider) -->")))' 0 \
  "ADMIT cr@${head} round-start=${t_resolved}" \
  --input "$(doc "$(list "$(review 11 "${cr}" "${head}" "${t_review}" '**Actionable comments posted: 1**')")" \
    "$(list "${req}" "${quoting}")" '[]')" --head "${head}" --provider cr --round-start "${t_resolved}"
# Without the UTC rule, a review stamped 09:21:30-01:00 (10:21:30Z) sorts before the round start it follows and is dropped.
ablate "dropping the UTC rule drops a review whose offset time sorts before the round start" \
  '| if test("^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$") then . else error("an artifact carries \(.), which is not a UTC time to the second") end;' \
  ';' 0 "ADMIT cr@${head} round-start=${t_resolved}" \
  --input "$(doc "$(list "$(review 11 "${cr}" "${head}" "2026-09-21T09:21:30-01:00" '**Actionable comments posted: 1**')")" \
    "$(list "${req}" "${rereq}")" '[]')" --head "${head}" --provider cr --round-start "${t_resolved}"
# Without the running-run stop, an accepted Bugbot request reads as a lane that delivered nothing.
ablate "dropping the running-run stop admits a no-gate while Bugbot is still reviewing" \
  'if [ -z "$found" ] && [ -n "$running" ]; then' 'if false; then' 0 "ADMIT bugbot@${head}" \
  --input "$(doc '[]' '[]' "$(list "$(check 31 cursor "${head}" in_progress null 'Bugbot Review' "")")")" --head "${head}" --provider bugbot
# Without the single-document rule, a second document is read past.
ablate "dropping the single-document rule reads past a second document" \
  'if length == 1 and (.[0] | type == "object") then .[0] else error("not one object") end' '.[0]' 0 \
  "ADMIT cr@${head}" --input "${two_docs}" --head "${head}" --provider cr

echo "review-no-gate-guard.test: ${checks} checks, ${failures} failed"
completed=1
[ "${failures}" -eq 0 ] || exit 1
