#!/usr/bin/env bash
# Hermetic test for review-request-comment.sh (monorepo#3319).
#
# Two kinds of assertion:
#   1. exact bytes for every allowed shape, and refusal (exit 1, nothing on stdout) for every
#      misuse — a composer that prints something on bad input would get posted anyway;
#   2. END-TO-END: every composed comment, posted the way the contract says, is fed to the
#      real comment-disclosure-drift guard and must come back clean. A bare-trigger control
#      must come back dirty, so a guard that passes everything cannot make this test green.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
composer="${script_dir}/review-request-comment.sh"
guard="${script_dir}/comment-disclosure-drift.sh"
tmpdir="$(mktemp -d)"
trap 'rm -rf "${tmpdir}"' EXIT

sha='0123456789abcdef0123456789abcdef01234567'
disclosure='> 🤖 Generated by the Agentic Engineer'
fail=0

bad() {
  echo "FAIL: $*" >&2
  fail=1
}

expect_body() {
  local what="$1" want="$2"
  shift 2
  local got rc=0
  got="$("${composer}" "$@" 2>"${tmpdir}/err")" || rc=$?
  if [ "${rc}" -ne 0 ]; then
    bad "${what}: exit ${rc}: $(cat "${tmpdir}/err")"
  elif [ "${got}" != "${want}" ]; then
    bad "${what}: body mismatch"
    printf '  want: %q\n  got:  %q\n' "${want}" "${got}" >&2
  fi
}

expect_refusal() {
  local what="$1"
  shift
  local rc=0
  "${composer}" "$@" >"${tmpdir}/out" 2>/dev/null || rc=$?
  if [ "${rc}" -ne 1 ]; then
    bad "${what}: expected exit 1, got ${rc}"
  fi
  if [ -s "${tmpdir}/out" ]; then
    bad "${what}: printed a body on refusal"
  fi
}

# --- 1. exact shapes ---------------------------------------------------------------------
expect_body "cr" \
  "${disclosure}"$'\n'"<!-- review-request-head: ${sha} provider=cr -->"$'\n\n''@coderabbitai review' \
  --provider cr --head "${sha}"
expect_body "cr --full" \
  "${disclosure}"$'\n'"<!-- review-request-head: ${sha} provider=cr -->"$'\n\n''@coderabbitai full review' \
  --provider cr --head "${sha}" --full
expect_body "codex" \
  "${disclosure}"$'\n'"<!-- review-request-head: ${sha} provider=codex -->"$'\n\n''@codex review' \
  --provider codex --head "${sha}"
expect_body "codex --focus" \
  "${disclosure}"$'\n'"<!-- review-request-head: ${sha} provider=codex -->"$'\n\n''@codex review for the retry loop' \
  --provider codex --head "${sha}" --focus 'the retry loop'
expect_body "bugbot disclosure" \
  "${disclosure}"$'\n'"<!-- review-request-head: ${sha} provider=bugbot -->" \
  --provider bugbot --head "${sha}" --part disclosure
expect_body "bugbot trigger" '@cursor review' --provider bugbot --part trigger
expect_body "improver actor" \
  '> 🤖 Generated by the Agent Improver'$'\n'"<!-- review-request-head: ${sha} provider=codex -->"$'\n\n''@codex review' \
  --provider codex --head "${sha}" --actor improver

# No trailing newline: Bugbot exact-matches the body.
"${composer}" --provider bugbot --part trigger >"${tmpdir}/trigger"
if [ "$(wc -c <"${tmpdir}/trigger" | tr -d ' ')" != "14" ]; then
  bad "bugbot trigger is not exactly the 14 bytes of '@cursor review'"
fi

# --- 1b. refusals ------------------------------------------------------------------------
expect_refusal "no provider" --head "${sha}"
expect_refusal "unknown provider" --provider copilot --head "${sha}"
expect_refusal "missing head" --provider cr
expect_refusal "abbreviated head" --provider codex --head 0123456789
expect_refusal "uppercase head" --provider cr --head "$(printf '%s' "${sha}" | tr 'a-f' 'A-F')"
expect_refusal "non-hex head" --provider cr --head 'zz23456789abcdef0123456789abcdef01234567'
expect_refusal "multiline focus" --provider codex --head "${sha}" --focus $'a\nb'
expect_refusal "empty focus" --provider codex --head "${sha}" --focus ''
expect_refusal "focus on cr" --provider cr --head "${sha}" --focus x
expect_refusal "full on codex" --provider codex --head "${sha}" --full
expect_refusal "bugbot without part" --provider bugbot --head "${sha}"
expect_refusal "bugbot bad part" --provider bugbot --head "${sha}" --part both
expect_refusal "bugbot trigger with head" --provider bugbot --head "${sha}" --part trigger
# --actor cannot change the bare trigger's bytes, so accepting it silently would hide a caller
# that believes it selected a role for the trigger.
expect_refusal "bugbot trigger with actor" --provider bugbot --part trigger --actor improver
expect_refusal "part on cr" --provider cr --head "${sha}" --part trigger
expect_refusal "bad actor" --provider cr --head "${sha}" --actor maintainer
expect_refusal "unknown flag" --provider cr --head "${sha}" --body x

# --- 2. end-to-end through the real drift guard ------------------------------------------
# Build a payload from composed bodies in posting order. jq --rawfile keeps every byte.
payload() {
  local out="$1"
  shift
  local args=() i=0
  for f in "$@"; do
    args+=(--rawfile "b${i}" "${f}")
    i=$((i + 1))
  done
  local n="$#"
  jq -n "${args[@]}" --argjson n "${n}" \
    '[range(0; $n) as $i | {id: ($i + 1), html_url: "https://x/\($i + 1)",
       user: {login: "devantler"}, body: $ARGS.named["b\($i)"]}]' >"${out}"
}

guard_rc() {
  local rc=0
  "${guard}" --input "$1" >"${tmpdir}/guard.out" 2>&1 || rc=$?
  printf '%s' "${rc}"
}

for spec in "cr:--provider cr --head ${sha}" \
  "cr-full:--provider cr --head ${sha} --full" \
  "codex:--provider codex --head ${sha}" \
  "codex-focus:--provider codex --head ${sha} --focus scope"; do
  name="${spec%%:*}"
  # shellcheck disable=SC2086 # the spec is a trusted literal word list
  "${composer}" ${spec#*:} >"${tmpdir}/${name}.body"
  payload "${tmpdir}/${name}.json" "${tmpdir}/${name}.body"
  rc="$(guard_rc "${tmpdir}/${name}.json")"
  [ "${rc}" = "0" ] || bad "drift guard flagged composed ${name} comment (exit ${rc}): $(cat "${tmpdir}/guard.out")"
done

"${composer}" --provider bugbot --head "${sha}" --part disclosure >"${tmpdir}/bb1.body"
"${composer}" --provider bugbot --part trigger >"${tmpdir}/bb2.body"
payload "${tmpdir}/bugbot.json" "${tmpdir}/bb1.body" "${tmpdir}/bb2.body"
rc="$(guard_rc "${tmpdir}/bugbot.json")"
[ "${rc}" = "0" ] || bad "drift guard flagged the composed bugbot pair (exit ${rc}): $(cat "${tmpdir}/guard.out")"

# Negative controls: the shapes #3319 measured must still be caught, or the clean results
# above prove nothing about the guard.
printf '%s' '@codex review' >"${tmpdir}/bare-codex.body"
payload "${tmpdir}/bare-codex.json" "${tmpdir}/bare-codex.body"
rc="$(guard_rc "${tmpdir}/bare-codex.json")"
[ "${rc}" = "1" ] || bad "negative control: a bare @codex review was not flagged (exit ${rc})"

printf '%s' '@coderabbitai full review' >"${tmpdir}/bare-cr.body"
payload "${tmpdir}/bare-cr.json" "${tmpdir}/bare-cr.body"
rc="$(guard_rc "${tmpdir}/bare-cr.json")"
[ "${rc}" = "1" ] || bad "negative control: a bare @coderabbitai full review was not flagged (exit ${rc})"

# The Bugbot trigger alone, with no disclosed neighbour, must not be granted the carve-out.
payload "${tmpdir}/bb-alone.json" "${tmpdir}/bb2.body"
rc="$(guard_rc "${tmpdir}/bb-alone.json")"
[ "${rc}" = "1" ] || bad "negative control: a lone bare @cursor review was not flagged (exit ${rc})"

if [ "${fail}" -ne 0 ]; then
  exit 1
fi
echo "review-request-comment: all shapes, refusals and drift-guard round-trips passed"
