#!/usr/bin/env bash
# shellcheck disable=SC2016,SC2034 # check() evals single-quoted conditions; early is read there.
# squash-closing-keywords.test.sh — RED/GREEN coverage for squash-closing-keywords.sh (monorepo#2731).
#
# The headline case is the #2720 shape: the body says `Fixes #2728` and `Part of #2609`, while an
# early commit still says `Fixes #2609`. A squash merge closed #2609 from that commit. The control is
# a PR whose commits and body agree, which must pass unchanged.
#
# Fixtures are hermetic: each case builds a throwaway local repository, so no network is used.

set -uo pipefail

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
SCRIPT="$SCRIPT_DIR/squash-closing-keywords.sh"
[ -f "$SCRIPT" ] || {
  echo "FAIL: script not found at $SCRIPT" >&2
  exit 1
}

FIX=$(mktemp -d)
trap 'rm -rf "$FIX"' EXIT
pass=0
fail=0

# new_repo — a fresh fixture repository with one base commit; prints its path.
new_repo() {
  local dir
  dir=$(mktemp -d "$FIX/repo.XXXXXX")
  git -C "$dir" init -q
  git -C "$dir" -c user.name=t -c user.email=t@example.com -c commit.gpgsign=false \
    commit -q --allow-empty -m "chore: base"
  printf '%s\n' "$dir"
}

# commit <repo> <message> — add an empty commit carrying <message>.
commit() {
  git -C "$1" -c user.name=t -c user.email=t@example.com -c commit.gpgsign=false \
    commit -q --allow-empty -m "$2"
}

# invoke <args…> — runs the guard and captures RC, OUT and ERR.
invoke() {
  RC=0
  "$SCRIPT" "$@" >"$FIX/out" 2>"$FIX/err" || RC=$?
  OUT=$(cat "$FIX/out")
  ERR=$(cat "$FIX/err")
}

# run <repo> <body> — checks the range base..HEAD, where base is the repository's first commit.
run() {
  printf '%s' "$2" >"$FIX/body.md"
  invoke --repo devantler-tech/monorepo --body-file "$FIX/body.md" \
    --base "$(git -C "$1" rev-list --max-parents=0 HEAD)" --head HEAD --repo-dir "$1"
}

check() {
  local name=$1 cond=$2
  if eval "$cond"; then
    pass=$((pass + 1))
  else
    fail=$((fail + 1))
    echo "FAIL: $name (rc=$RC out=[$OUT] err=[$ERR])" >&2
  fi
}

has() { grep -qF -- "$1" <<<"$OUT"; }

# --- RED: the #2720 shape ------------------------------------------------------------------------
repo=$(new_repo)
commit "$repo" $'fix(agents): first slice\n\nFixes #2609'
early=$(git -C "$repo" rev-parse --short=12 HEAD)
commit "$repo" $'fix(agents): deliver the child\n\nFixes #2728'
run "$repo" $'> 🤖 Generated by the Agentic Engineer\n\nFixes #2728\nPart of #2609\n'
check "an early commit closing a Part-of parent fails" '[ "$RC" -eq 1 ]'
check "the finding names the parent and the commit that closes it" \
  'has "OFFENDING #2609: commit $early (\"fix(agents): first slice\") closes it"'
check "the delivered child is not reported" '! has "OFFENDING #2728"'
check "the failure names the remedy" 'has "reword each commit above" && has "Part of #N"'
check "the summary counts every commit" 'has "examined=2 findings=1"'

# --- GREEN control: commits and body agree -------------------------------------------------------
repo=$(new_repo)
commit "$repo" $'fix(agents): deliver the child\n\nFixes #2728'
run "$repo" $'Fixes #2728\nPart of #2609\n'
check "commits that agree with the body pass" '[ "$RC" -eq 0 ] && has "examined=1 findings=0"'

# A commit that only mentions the parent without a closing keyword does not close it.
repo=$(new_repo)
commit "$repo" $'fix(agents): first slice toward #2609\n\nRefs #2609'
run "$repo" $'Part of #2609\n'
check "a bare mention of a Part-of issue passes" '[ "$RC" -eq 0 ]'

# A body that closes the issue as well as naming it Part of does not contradict the commit.
repo=$(new_repo)
commit "$repo" $'fix: finish it\n\nFixes #7'
run "$repo" $'Fixes #7\nPart of #7\n'
check "a body that also closes the issue passes" '[ "$RC" -eq 0 ]'

# A closing keyword for an issue the body does not name at all is outside this check.
repo=$(new_repo)
commit "$repo" $'fix: unrelated\n\nFixes #11'
run "$repo" $'Part of #12\n'
check "a closing keyword for an issue the body does not mark Part of passes" '[ "$RC" -eq 0 ]'

# --- keyword spellings GitHub honours -----------------------------------------------------------
for message in 'close #5' 'Closes: #5' 'closed #5' 'FIX #5' 'Fixed #5' 'resolve #5' 'Resolves #5' 'resolved: #5'; do
  repo=$(new_repo)
  commit "$repo" "chore: x"$'\n\n'"$message"
  run "$repo" $'Part of #5\n'
  check "\"$message\" closes a Part-of issue" '[ "$RC" -eq 1 ] && has "OFFENDING #5:"'
done

repo=$(new_repo)
commit "$repo" $'chore: x\n\nprefixes #5 and suffixed #5'
run "$repo" $'Part of #5\n'
check "a keyword inside a longer word is not a closing keyword" '[ "$RC" -eq 0 ]'

repo=$(new_repo)
commit "$repo" $'chore: x\n\nFixes #5'
run "$repo" $'part of: #5\n'
check "a Part-of spelled in lowercase with a colon is recognised" '[ "$RC" -eq 1 ]'

for body in 'Part of #2609, #2610' 'Part of #2609 and #2610' 'Part of #2609 & devantler-tech/monorepo#2610'; do
  repo=$(new_repo)
  commit "$repo" $'chore: x\n\nFixes #2610'
  run "$repo" "$body"
  check "every issue in \"$body\" is a Part-of issue" '[ "$RC" -eq 1 ] && has "OFFENDING #2610:"'
done

# GitHub closes only the first issue of `Fixes #1, #2`; the second needs its own keyword.
repo=$(new_repo)
commit "$repo" $'chore: x\n\nFixes #1, #2'
run "$repo" $'Part of #2\n'
check "an issue listed after a closing keyword's first reference is not closed" '[ "$RC" -eq 0 ]'

# --- reference forms -------------------------------------------------------------------------------
repo=$(new_repo)
commit "$repo" $'chore: x\n\nFixes Devantler-Tech/Monorepo#6'
run "$repo" $'Part of #6\n'
check "an owner/repo reference to this repository matches a bare Part of" \
  '[ "$RC" -eq 1 ] && has "OFFENDING #6:"'

repo=$(new_repo)
commit "$repo" $'chore: x\n\nFixes https://github.com/devantler-tech/monorepo/issues/8'
run "$repo" $'Part of #8\n'
check "an issue URL for this repository matches a bare Part of" '[ "$RC" -eq 1 ] && has "OFFENDING #8:"'

repo=$(new_repo)
commit "$repo" $'chore: x\n\nFixes devantler-tech/agent-plugins#108'
run "$repo" $'Part of devantler-tech/agent-plugins#108\n'
check "a closing keyword for another repository's Part-of issue fails too" \
  '[ "$RC" -eq 1 ] && has "OFFENDING devantler-tech/agent-plugins#108:"'

repo=$(new_repo)
commit "$repo" $'chore: x\n\nFixes devantler-tech/agent-plugins#9'
run "$repo" $'Part of #9\n'
check "the same number in another repository is a different issue" '[ "$RC" -eq 0 ]'

# --- every commit in the range is read, and only those -----------------------------------------
repo=$(new_repo)
commit "$repo" $'chore: x\n\nFixes #3'
commit "$repo" $'chore: y\n\nFixes #3'
run "$repo" $'Part of #3\n'
check "each offending commit is named" '[ "$RC" -eq 1 ] && has "examined=2 findings=2"'

repo=$(new_repo)
commit "$repo" $'chore: before the branch\n\nFixes #4'
base=$(git -C "$repo" rev-parse HEAD)
commit "$repo" $'chore: on the branch'
printf 'Part of #4\n' >"$FIX/body.md"
invoke --repo devantler-tech/monorepo --body-file "$FIX/body.md" --base "$base" --head HEAD --repo-dir "$repo"
check "a commit already on the base is not part of the squash" '[ "$RC" -eq 0 ] && has "examined=1"'

repo=$(new_repo)
invoke --repo devantler-tech/monorepo --body-file "$FIX/body.md" --base HEAD --head HEAD --repo-dir "$repo"
check "an empty range is stated, not assumed" '[ "$RC" -eq 0 ] && has "examined=0 findings=0"'

# --- fail closed ---------------------------------------------------------------------------------
invoke --repo devantler-tech/monorepo --body-file "$FIX/body.md" --base does-not-exist --head HEAD \
  --repo-dir "$repo"
check "an unresolvable revision is UNKNOWN, never clean" \
  '[ "$RC" -eq 2 ] && [ -z "$OUT" ] && grep -qF "UNKNOWN" <<<"$ERR"'

invoke --repo devantler-tech/monorepo --body-file "$FIX/missing.md" --base HEAD --head HEAD --repo-dir "$repo"
check "an unreadable body file is UNKNOWN" '[ "$RC" -eq 2 ] && [ -z "$OUT" ]'

invoke --repo monorepo --body-file "$FIX/body.md" --base HEAD --head HEAD --repo-dir "$repo"
check "a repository that is not owner/repo is UNKNOWN" '[ "$RC" -eq 2 ]'

invoke --repo devantler-tech/monorepo --body-file "$FIX/body.md" --base HEAD --head HEAD --repo-dir "$repo" \
  --unknown
check "an unknown argument is a usage error" '[ "$RC" -eq 2 ]'

invoke --repo devantler-tech/monorepo --body-file "$FIX/body.md" --base HEAD --head HEAD \
  --repo-dir "$FIX/not-a-repo"
check "a directory that is not a repository is UNKNOWN" '[ "$RC" -eq 2 ] && [ -z "$OUT" ]'

echo "squash-closing-keywords.test.sh: pass=$pass fail=$fail"
[ "$fail" -eq 0 ]
