#!/usr/bin/env bash
# submodule-agents-drift.test.sh — RED/GREEN coverage for the submodule AGENTS.md drift check (#2534).
#
# The defect this guards against is a FALSE CLEAN: a check that reports a pinned AGENTS.md is current
# while it still tells agents to follow a retired rule. So the assertions are weighted toward the ways
# a false clean is manufactured: a phrase the matcher misses, an exception that silently outlives the
# pin it was written for, and an unreadable repository read as "nothing found". The one false-positive
# control that matters is the legitimate "legacy prefixes stay recognised" wording.
#
# Fixtures are real git repositories in a scratch dir: one bare "remote" per product under an owner
# directory (devantler-tech/ or devantler/), and a superproject whose gitlinks pin chosen commits.
# Nothing depends on the network, the surrounding checkout, or wall-clock time.

# The fixture texts quote Markdown code spans, so backticks inside single quotes are intentional.
# shellcheck disable=SC2016
set -euo pipefail

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
SCRIPT="$SCRIPT_DIR/submodule-agents-drift.sh"
[ -f "$SCRIPT" ] || { echo "FAIL: script not found at $SCRIPT" >&2; exit 1; }

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

fails=0
asserts=0
note_fail() { echo "FAIL: $1" >&2; fails=$(( fails + 1 )); }

git_q() { git -c init.defaultBranch=main -c user.name=t -c user.email=t@e -c commit.gpgsign=false "$@"; }

# mkproduct <owner> <name> <agents-content|-> — build a product repo with one commit and a bare remote
# under $TMP/remotes/<owner>/<name>.git. Content "-" means the commit has no AGENTS.md. Prints the SHA.
mkproduct() {
  local owner=$1 name=$2 content=$3
  local work="$TMP/work/$owner/$name"
  local bare="$TMP/remotes/$owner/$name.git"
  mkdir -p "$work" "$(dirname "$bare")"
  git_q init -q "$work"
  if [ "$content" = "-" ]; then
    printf 'readme\n' >"$work/README.md"
  else
    printf '%s\n' "$content" >"$work/AGENTS.md"
  fi
  git_q -C "$work" add -A
  git_q -C "$work" commit -q -m "init $name"
  git_q clone -q --bare "$work" "$bare"
  git_q -C "$bare" config uploadpack.allowFilter true
  git_q -C "$bare" config uploadpack.allowAnySHA1InWant true
  git_q -C "$work" rev-parse HEAD
}

# mksuper <name> <path=url=sha>... — a superproject pinning each path at sha, with .gitmodules urls.
mksuper() {
  local name=$1
  shift
  local super="$TMP/super/$name"
  mkdir -p "$super/.claude"
  git_q init -q "$super"
  : >"$super/.gitmodules"
  local spec sub url sha
  for spec in "$@"; do
    sub=${spec%%=*}
    url=${spec#*=}
    url=${url%=*}
    sha=${spec##*=}
    git_q -C "$super" config -f .gitmodules "submodule.$sub.path" "$sub"
    git_q -C "$super" config -f .gitmodules "submodule.$sub.url" "$url"
    git_q -C "$super" update-index --add --cacheinfo "160000,$sha,$sub"
  done
  git_q -C "$super" add .gitmodules
  git_q -C "$super" commit -q -m "pin submodules"
  printf '%s\n' "$super"
}

# run_check <super> [args...] — run the check; sets OUT and RC.
run_check() {
  local super=$1
  shift
  set +e
  OUT=$(bash "$SCRIPT" --root "$super" "$@" 2>&1)
  RC=$?
  set -e
}

expect_rc() {
  asserts=$(( asserts + 1 ))
  [ "$RC" -eq "$2" ] || note_fail "$1: expected exit $2, got $RC; output: $OUT"
}

expect_line() {
  asserts=$(( asserts + 1 ))
  printf '%s\n' "$OUT" | grep -qE "$2" || note_fail "$1: expected a line matching /$2/; output: $OUT"
}

expect_no_line() {
  asserts=$(( asserts + 1 ))
  if printf '%s\n' "$OUT" | grep -qE "$2"; then
    note_fail "$1: expected no line matching /$2/; output: $OUT"
  fi
}

CURRENT='These conventions guide the autonomous **Agentic Engineer** — and any agentic tool.
Begin agent output with `> 🤖 Generated by the Agentic Engineer`; the legacy `Daily AI Engineer` and
`Daily AI Assistant` prefixes stay recognised as agent output.'

# --- 1. A current file is CLEAN, and the legacy-recognised wording is not drift. ---------------
clean_sha=$(mkproduct devantler-tech clean "$CURRENT")
super=$(mksuper clean "apps/clean=$TMP/remotes/devantler-tech/clean.git=$clean_sha")
run_check "$super"
expect_rc "clean file" 0
expect_line "clean file" "^CLEAN apps/clean ${clean_sha:0:8}"
expect_no_line "clean file" "^DRIFT"

# A legacy prefix written as an emitted line but explicitly marked legacy stays clean.
legacy_sha=$(mkproduct devantler-tech legacy-inline 'Output starts with `> 🤖 Generated by the Agentic Engineer` (the legacy `> 🤖 Generated by the Daily AI Engineer` form stays recognised).')
super=$(mksuper legacy "apps/legacy=$TMP/remotes/devantler-tech/legacy-inline.git=$legacy_sha")
run_check "$super"
expect_rc "legacy marked on the same line" 0
expect_line "legacy marked on the same line" "^CLEAN apps/legacy"

# --- 2. Each superseded claim is detected on its own: one fixture per phrase. -----------------
check_phrase() {
  local label=$1 text=$2 name=$3
  local sha super
  sha=$(mkproduct devantler-tech "$name" "$text")
  super=$(mksuper "$name" "apps/$name=$TMP/remotes/devantler-tech/$name.git=$sha")
  run_check "$super"
  expect_rc "phrase $label" 1
  expect_line "phrase $label" "^DRIFT apps/$name ${sha:0:8} .*$label"
}

check_phrase go-signal 'Ship a draft PR; the maintainer'"'"'s promotion to "ready" is the go-signal.' p-go-signal
check_phrase never-self-merge 'Never merge external PRs? No: never self-merge your own unreviewed drafts.' p-self-merge
check_phrase never-merge-external 'Drive trusted PRs to merge; never merge external PRs.' p-external
check_phrase old-role 'These conventions guide the autonomous **Daily AI Assistant** — and any agentic tool.' p-role-assistant
check_phrase old-role 'These conventions guide the autonomous **Daily AI Engineer** — and any agentic tool.' p-role-engineer
check_phrase old-prefix 'Begin every comment with `> 🤖 Generated by the Daily AI Engineer`.' p-prefix

# --- 3. A repository without AGENTS.md is reported, not failed. -------------------------------
none_sha=$(mkproduct devantler-tech noagents -)
super=$(mksuper noagents "apps/noagents=$TMP/remotes/devantler-tech/noagents.git=$none_sha")
run_check "$super"
expect_rc "no AGENTS.md" 0
expect_line "no AGENTS.md" "^NO-AGENTS-MD apps/noagents"

# --- 4. Submodules outside devantler-tech are out of scope, even with drift. ------------------
personal_sha=$(mkproduct devantler personal 'the maintainer'"'"'s promotion to ready is the go-signal')
super=$(mksuper personal "github/personal=$TMP/remotes/devantler/personal.git=$personal_sha")
run_check "$super"
expect_rc "out of scope" 0
expect_line "out of scope" "^OUT-OF-SCOPE github/personal"
expect_no_line "out of scope" "^DRIFT"

# --- 5. Exceptions: exact revision only, and stale rows fail. ---------------------------------
drift_sha=$(mkproduct devantler-tech lagging 'never merge external PRs')
super=$(mksuper excepted "apps/lagging=$TMP/remotes/devantler-tech/lagging.git=$drift_sha")
printf '# path\trevision\treason\napps/lagging\t%s\tpin predates the fix on main\n' "$drift_sha" >"$super/.claude/submodule-agents-drift-exceptions.tsv"
run_check "$super"
expect_rc "exception at the exact pin" 0
expect_line "exception at the exact pin" "^EXCEPTED apps/lagging ${drift_sha:0:8}"
expect_no_line "exception at the exact pin" "^DRIFT"

other_sha=$(printf '%040d' 7)
printf 'apps/lagging\t%s\tan older pin\n' "$other_sha" >"$super/.claude/submodule-agents-drift-exceptions.tsv"
run_check "$super"
expect_rc "exception for a different revision" 1
expect_line "exception for a different revision" "^STALE-EXCEPTION apps/lagging"
expect_line "exception for a different revision" "^DRIFT apps/lagging"

printf 'apps/lagging\t%s\tpin predates the fix\napps/gone\t%s\tno longer pinned\n' "$drift_sha" "$other_sha" >"$super/.claude/submodule-agents-drift-exceptions.tsv"
run_check "$super"
expect_rc "exception for a path that is not pinned" 1
expect_line "exception for a path that is not pinned" "^STALE-EXCEPTION apps/gone"

# --- 6. Unreadable repositories are UNKNOWN unless excepted at their exact pin. ---------------
ghost_sha=$(printf '%040d' 42)
super=$(mksuper unreadable "apps/ghost=$TMP/remotes/devantler-tech/ghost.git=$ghost_sha")
run_check "$super"
expect_rc "unreadable repository" 2
expect_line "unreadable repository" "^UNKNOWN apps/ghost"

printf 'apps/ghost\t%s\tprivate repository; not readable anonymously\n' "$ghost_sha" >"$super/.claude/submodule-agents-drift-exceptions.tsv"
run_check "$super"
expect_rc "unreadable but excepted" 0
expect_line "unreadable but excepted" "^EXCEPTED apps/ghost"

# A pinned revision the remote does not have is also UNKNOWN, never CLEAN.
super=$(mksuper missingpin "apps/clean=$TMP/remotes/devantler-tech/clean.git=$ghost_sha")
run_check "$super"
expect_rc "pin missing on the remote" 2
expect_line "pin missing on the remote" "^UNKNOWN apps/clean"
expect_no_line "pin missing on the remote" "^CLEAN"

# --- 7. A malformed exceptions file is UNKNOWN, never ignored. --------------------------------
super=$(mksuper malformed "apps/clean=$TMP/remotes/devantler-tech/clean.git=$clean_sha")
printf 'apps/clean\tabc123\tshort revision\n' >"$super/.claude/submodule-agents-drift-exceptions.tsv"
run_check "$super"
expect_rc "short revision in exceptions" 2

printf 'apps/clean\t%s\n' "$clean_sha" >"$super/.claude/submodule-agents-drift-exceptions.tsv"
run_check "$super"
expect_rc "missing reason in exceptions" 2

# --- 8. Enumeration failure is UNKNOWN. -------------------------------------------------------
mkdir -p "$TMP/not-a-repo"
run_check "$TMP/not-a-repo"
expect_rc "not a git repository" 2

# --- 9. SSH GitHub URLs are rewritten to anonymous HTTPS; other URLs pass through. ------------
set +e
resolved=$(bash "$SCRIPT" --resolve-url git@github.com:devantler-tech/ksail.git 2>&1)
set -e
asserts=$(( asserts + 1 ))
[ "$resolved" = "https://github.com/devantler-tech/ksail.git" ] || note_fail "ssh url rewrite: got '$resolved'"

set +e
resolved=$(bash "$SCRIPT" --resolve-url /srv/remotes/devantler-tech/x.git 2>&1)
set -e
asserts=$(( asserts + 1 ))
[ "$resolved" = "/srv/remotes/devantler-tech/x.git" ] || note_fail "local url passthrough: got '$resolved'"

if [ "$fails" -gt 0 ]; then
  echo "submodule-agents-drift.test.sh: $fails of $asserts assertions FAILED" >&2
  exit 1
fi

echo "submodule-agents-drift.test.sh: all $asserts assertions passed"
