package main

import (
	"bytes"
	"strings"
	"testing"
)

// The 2026-09-02 misattribution (monorepo#3163): the surveyor reported a real undisclosed
// `devantler` comment that lives on platform#3275 under platform#3239, an issue whose
// `devantler` comments are all disclosed. The orchestrator checked #3239, found nothing and
// discarded the finding. The fixtures keep the real URL shapes; the bodies are synthetic.
const (
	issue3239Disclosed = `{"author":{"login":"devantler"},"body":"> 🤖 Generated by the Agentic Engineer\n\nStatus note.","createdAt":"2026-08-29T18:23:09Z","url":"https://github.com/devantler-tech/platform/issues/3239#issuecomment-5337878100"}`
	issue3239Bot       = `{"author":{"login":"coderabbitai"},"body":"Summary by CodeRabbit","createdAt":"2026-08-19T05:21:55Z","url":"https://github.com/devantler-tech/platform/issues/3239#issuecomment-5337878167"}`
	issue3275Real      = `{"author":{"login":"devantler"},"body":"The merged scanner upgrade removed the local-mode abort.\n\nSecond paragraph.","createdAt":"2026-08-28T19:51:48Z","url":"https://github.com/devantler-tech/platform/issues/3275#issuecomment-5457089789"}`
)

func scanPayload(t *testing.T, payload string) CandidateScan {
	t.Helper()
	records, err := DecodeCandidatePayload([]byte(payload))
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	return ScanCandidates(records, "devantler")
}

// The row's number is a function of the comment's OWN url, so a payload that interleaves two
// issues cannot carry one issue's number onto the other's comment.
func TestCandidates_RowNumberComesFromTheCommentItself(t *testing.T) {
	payload := "[" + issue3239Bot + "," + issue3239Disclosed + "," + issue3275Real + "]"
	scan := scanPayload(t, payload)
	if len(scan.Rows) != 1 {
		t.Fatalf("want exactly one candidate, got %d: %+v", len(scan.Rows), scan.Rows)
	}
	row := scan.Rows[0].String()
	want := "CANDIDATE-MAINTAINER-ISSUE-COMMENT platform #3275 — `devantler` @2026-08-28T19:51:48Z: " +
		`"The merged scanner upgrade removed the local-mode abort." ` +
		"https://github.com/devantler-tech/platform/issues/3275#issuecomment-5457089789"
	if row != want {
		t.Fatalf("row:\n got %s\nwant %s", row, want)
	}
	if strings.Contains(row, "3239") {
		t.Fatalf("row names the neighbouring issue: %s", row)
	}
	if got := scan.Summary(); !strings.Contains(got, "artifacts=platform#3239,platform#3275") {
		t.Fatalf("summary must list every artifact the payload covered: %s", got)
	}
}

// The gh view shape the surveyor pipes (`gh issue view --json comments`) wraps the array.
func TestCandidates_GhViewObjectShape(t *testing.T) {
	scan := scanPayload(t, `{"comments":[`+issue3275Real+`]}`)
	if len(scan.Rows) != 1 || scan.Rows[0].Artifact.Number != 3275 || scan.Rows[0].Artifact.PullRequest {
		t.Fatalf("gh view payload: %+v", scan.Rows)
	}
}

// The artifact CLASS comes from the permalink path too: a PR's conversation, review and inline
// comments all live under /pull/<n>, an issue's under /issues/<n>.
func TestCandidates_ClassComesFromThePermalinkPath(t *testing.T) {
	cases := []struct {
		name, record, prefix string
	}{
		{"pr conversation", `{"user":{"login":"devantler"},"body":"do not merge","created_at":"2026-09-01T00:00:00Z","html_url":"https://github.com/devantler-tech/monorepo/pull/42#issuecomment-1","issue_url":"https://api.github.com/repos/devantler-tech/monorepo/issues/42"}`, "CANDIDATE-MAINTAINER-COMMENT monorepo #42 — "},
		{"pr review body", `{"user":{"login":"devantler"},"body":"redesign this","submitted_at":"2026-09-01T00:00:01Z","html_url":"https://github.com/devantler-tech/monorepo/pull/42#pullrequestreview-7","pull_request_url":"https://api.github.com/repos/devantler-tech/monorepo/pulls/42"}`, "CANDIDATE-MAINTAINER-COMMENT monorepo #42 — "},
		{"pr inline", `{"user":{"login":"devantler"},"body":"wrong call","created_at":"2026-09-01T00:00:02Z","html_url":"https://github.com/devantler-tech/monorepo/pull/42#discussion_r9","pull_request_url":"https://api.github.com/repos/devantler-tech/monorepo/pulls/42"}`, "CANDIDATE-MAINTAINER-COMMENT monorepo #42 — "},
		{"issue", `{"user":{"login":"devantler"},"body":"please split this","created_at":"2026-09-01T00:00:03Z","html_url":"https://github.com/devantler-tech/monorepo/issues/43#issuecomment-2","issue_url":"https://api.github.com/repos/devantler-tech/monorepo/issues/43"}`, "CANDIDATE-MAINTAINER-ISSUE-COMMENT monorepo #43 — "},
	}
	for _, tc := range cases {
		scan := scanPayload(t, "["+tc.record+"]")
		if len(scan.Rows) != 1 || !strings.HasPrefix(scan.Rows[0].String(), tc.prefix) {
			t.Errorf("%s: got %+v, want prefix %q", tc.name, scan.Rows, tc.prefix)
		}
	}
}

// Disclosed agent output is skipped whatever the actor word; a sender-marker body is the
// sibling's undisclosed output; merely MENTIONING an agent never demotes a comment.
func TestCandidates_DisclosureAndSenderMarkerGate(t *testing.T) {
	url := func(id string) string {
		return `"https://github.com/devantler-tech/monorepo/issues/7#issuecomment-` + id + `"`
	}
	payload := `[` +
		`{"author":{"login":"devantler"},"body":"> 🤖 Generated by the Daily AI Assistant\n\nold","url":` + url("1") + `},` +
		`{"author":{"login":"devantler"},"body":"> 🤖 Generated by the Agentic Engineer\n\n@coderabbitai review please","url":` + url("2") + `},` +
		`{"author":{"login":"devantler"},"body":"> Requested by the 🤖 Daily AI Engineer — CI is green","url":` + url("3") + `},` +
		`{"author":{"login":"devantler"},"body":"The last Codex agent run missed X; do Y.","url":` + url("4") + `}` +
		`]`
	scan := scanPayload(t, payload)
	if scan.Disclosed != 2 {
		t.Fatalf("disclosed: got %d, want 2", scan.Disclosed)
	}
	if len(scan.Rows) != 2 {
		t.Fatalf("want two rows, got %+v", scan.Rows)
	}
	if got := scan.Rows[0].String(); !strings.HasPrefix(got, "CANDIDATE-SIBLING-ISSUE-COMMENT monorepo #7 (missing disclosure) — ") {
		t.Errorf("sender marker: %s", got)
	}
	if got := scan.Rows[1].String(); !strings.HasPrefix(got, "CANDIDATE-MAINTAINER-ISSUE-COMMENT monorepo #7 — ") {
		t.Errorf("mention must stay a maintainer candidate: %s", got)
	}
	sibling := `[{"user":{"login":"devantler"},"body":"🤖 Sent by the Agentic Engineer","html_url":"https://github.com/devantler-tech/monorepo/pull/8#issuecomment-1"}]`
	if got := scanPayload(t, sibling).Rows[0].String(); !strings.HasPrefix(got, "CANDIDATE-SIBLING-COMMENT monorepo #8 (missing disclosure) — ") {
		t.Errorf("PR sibling: %s", got)
	}
}

// Other authors are never candidates but are counted, and every considered record lands in
// exactly one bucket, so the closing line always adds up.
func TestCandidates_SummaryAccountsForEveryRecord(t *testing.T) {
	payload := `[` + issue3239Bot + `,` + issue3239Disclosed + `,` + issue3275Real + `,` +
		`{"user":{"login":"devantler"},"body":"  \n","submitted_at":"2026-09-01T00:00:00Z","html_url":"https://github.com/devantler-tech/platform/pull/9#pullrequestreview-1","pull_request_url":"https://api.github.com/repos/devantler-tech/platform/pulls/9"}` +
		`]`
	scan := scanPayload(t, payload)
	want := "CANDIDATE-SCAN author=devantler records=4 considered=3 disclosed=1 maintainer=1 sibling=0 empty=1 artifacts=platform#3239,platform#3275,platform#9"
	if got := scan.Summary(); got != want {
		t.Fatalf("summary:\n got %s\nwant %s", got, want)
	}
}

func TestCandidates_EmptyPayloadArrayIsAnExplicitZero(t *testing.T) {
	scan := scanPayload(t, `{"comments":[]}`)
	want := "CANDIDATE-SCAN author=devantler records=0 considered=0 disclosed=0 maintainer=0 sibling=0 empty=0 artifacts=none"
	if got := scan.Summary(); got != want {
		t.Fatalf("summary: got %s, want %s", got, want)
	}
}

// `gh api --paginate` emits one array per page, concatenated.
func TestCandidates_ConcatenatedRESTPagesAreAllRead(t *testing.T) {
	page1 := `[{"user":{"login":"devantler"},"body":"first","created_at":"2026-09-01T00:00:00Z","html_url":"https://github.com/devantler-tech/monorepo/issues/5#issuecomment-1","issue_url":"https://api.github.com/repos/devantler-tech/monorepo/issues/5"}]`
	page2 := `[{"user":{"login":"devantler"},"body":"second","created_at":"2026-09-02T00:00:00Z","html_url":"https://github.com/devantler-tech/monorepo/issues/5#issuecomment-2","issue_url":"https://api.github.com/repos/devantler-tech/monorepo/issues/5"}]`
	scan := scanPayload(t, page1+"\n"+page2)
	if len(scan.Rows) != 2 || !strings.Contains(scan.Rows[1].String(), `"second"`) {
		t.Fatalf("both pages must be read: %+v", scan.Rows)
	}
}

// The gist is one line: the first line that is not a quote (he quotes agent text when replying),
// with double quotes neutralised so the row stays parseable, and bounded.
func TestCandidates_GistIsTheFirstOwnLine(t *testing.T) {
	body := `> the previous run said X\n\nNo — \"revert\" it,\tnow.`
	payload := `[{"user":{"login":"devantler"},"body":"` + body + `","html_url":"https://github.com/devantler-tech/monorepo/issues/5#issuecomment-1"}]`
	row := scanPayload(t, payload).Rows[0].String()
	if !strings.Contains(row, `: "No — 'revert' it, now." `) {
		t.Fatalf("gist: %s", row)
	}
	if !strings.Contains(row, " @unknown: ") {
		t.Fatalf("a record without a timestamp must say so: %s", row)
	}
	long := strings.Repeat("x", 300)
	payload = `[{"user":{"login":"devantler"},"body":"` + long + `","html_url":"https://github.com/devantler-tech/monorepo/issues/5#issuecomment-1"}]`
	row = scanPayload(t, payload).Rows[0].String()
	if strings.Contains(row, long) || !strings.Contains(row, `..." https://`) {
		t.Fatalf("gist must be bounded: %s", row)
	}
}

// Every way a payload can fail to identify the artifact or the author is UNKNOWN, never a row
// with a guessed number and never a clean zero.
func TestDecodeCandidatePayload_FailsClosed(t *testing.T) {
	ok := func(extra string) string {
		return `{"user":{"login":"devantler"},"body":"b"` + extra + `}`
	}
	cases := map[string]string{
		"empty":                     "",
		"null":                      "null",
		"object without comments":   `{}`,
		"null comments":             `{"comments":null}`,
		"error record":              `[{"message":"Not Found"}]`,
		"no url":                    `[` + ok(``) + `]`,
		"api url only":              `[` + ok(`,"url":"https://api.github.com/repos/devantler-tech/monorepo/issues/comments/1"`) + `]`,
		"url without anchor":        `[` + ok(`,"html_url":"https://github.com/devantler-tech/monorepo/issues/5"`) + `]`,
		"foreign host":              `[` + ok(`,"html_url":"https://example.com/devantler-tech/monorepo/issues/5#issuecomment-1"`) + `]`,
		"review anchor on issue":    `[` + ok(`,"html_url":"https://github.com/devantler-tech/monorepo/issues/5#discussion_r1"`) + `]`,
		"issue_url disagrees":       `[` + ok(`,"html_url":"https://github.com/devantler-tech/platform/issues/3239#issuecomment-1","issue_url":"https://api.github.com/repos/devantler-tech/platform/issues/3275"`) + `]`,
		"issue_url other repo":      `[` + ok(`,"html_url":"https://github.com/devantler-tech/platform/issues/5#issuecomment-1","issue_url":"https://api.github.com/repos/devantler-tech/monorepo/issues/5"`) + `]`,
		"pull_request_url differs":  `[` + ok(`,"html_url":"https://github.com/devantler-tech/platform/pull/5#discussion_r1","pull_request_url":"https://api.github.com/repos/devantler-tech/platform/pulls/6"`) + `]`,
		"pull_request_url on issue": `[` + ok(`,"html_url":"https://github.com/devantler-tech/platform/issues/5#issuecomment-1","pull_request_url":"https://api.github.com/repos/devantler-tech/platform/pulls/5"`) + `]`,
		"unparseable issue_url":     `[` + ok(`,"html_url":"https://github.com/devantler-tech/platform/issues/5#issuecomment-1","issue_url":"nope"`) + `]`,
		"null body":                 `[{"user":{"login":"devantler"},"body":null,"html_url":"https://github.com/devantler-tech/monorepo/issues/5#issuecomment-1"}]`,
		"padded author":             `[{"author":{"login":"devantler "},"body":"b","url":"https://github.com/devantler-tech/monorepo/issues/5#issuecomment-1"}]`,
		"author object no login":    `[{"author":{},"body":"b","url":"https://github.com/devantler-tech/monorepo/issues/5#issuecomment-1"}]`,
		"object then array":         `{"comments":[]}[]`,
		"two objects":               `{"comments":[]}{"comments":[]}`,
		"array of arrays":           `[[` + ok(`,"html_url":"https://github.com/devantler-tech/monorepo/issues/5#issuecomment-1"`) + `]]`,
		"scalar":                    `42`,
		"truncated":                 `[` + ok(`,"html_url":"https://github.com/devantler-tech/monorepo/issues/5#issuecomment-1"`),
	}
	for name, payload := range cases {
		if _, err := DecodeCandidatePayload([]byte(payload)); err == nil {
			t.Errorf("%s: decoded without error, want UNKNOWN", name)
		}
	}
}

// The CLI prints nothing but a diagnostic on UNKNOWN — no partial rows — and otherwise always
// ends with the CANDIDATE-SCAN line, which is the proof a consumer checks for.
func TestRunCandidates_ExitCodesAndClosingLine(t *testing.T) {
	var stdout, stderr bytes.Buffer
	if code := runCandidates([]byte(`[`+issue3275Real+`]`), "devantler", &stdout, &stderr); code != 0 {
		t.Fatalf("exit %d, stderr %s", code, stderr.String())
	}
	lines := strings.Split(strings.TrimRight(stdout.String(), "\n"), "\n")
	if len(lines) != 2 || !strings.HasPrefix(lines[0], "CANDIDATE-MAINTAINER-ISSUE-COMMENT platform #3275 ") ||
		!strings.HasPrefix(lines[1], "CANDIDATE-SCAN ") {
		t.Fatalf("output: %q", stdout.String())
	}

	stdout.Reset()
	stderr.Reset()
	bad := `[` + issue3275Real + `,{"author":{"login":"devantler"},"body":"b"}]`
	if code := runCandidates([]byte(bad), "devantler", &stdout, &stderr); code != 2 {
		t.Fatalf("bad payload: exit %d, want 2", code)
	}
	if stdout.Len() != 0 {
		t.Fatalf("UNKNOWN must not print partial rows: %q", stdout.String())
	}
	if !strings.Contains(stderr.String(), "UNKNOWN") {
		t.Fatalf("diagnostic must say UNKNOWN: %q", stderr.String())
	}
}
