package main

import (
	"encoding/json"
	"strings"
	"testing"
)

// The canonical form, as the lanes emit it today.
const compliantBody = "> 🤖 Generated by the Agentic Engineer\n\n## Why\n\nSomething.\n"

func TestClassify_CanonicalPrefixIsCompliant(t *testing.T) {
	if got := Classify(compliantBody); got != Compliant {
		t.Fatalf("canonical leading disclosure: got %q, want %q", got, Compliant)
	}
}

// The actor word has been renamed twice. A matcher keyed to one spelling would
// silently reclassify every comment written under the others, so every historical
// form must stay compliant -- permanently.
func TestClassify_EveryHistoricalActorWordStaysCompliant(t *testing.T) {
	actors := []string{
		"Agentic Engineer",
		"Agentic Engineer (Cursor cloud instance)",
		"Daily AI Engineer",
		"Daily AI Assistant",
		"Some Future Role Nobody Has Named Yet",
	}
	for _, actor := range actors {
		body := "> 🤖 Generated by the " + actor + "\n\nBody.\n"
		if got := Classify(body); got != Compliant {
			t.Errorf("actor %q: got %q, want %q", actor, got, Compliant)
		}
	}
}

// Shape A, measured live on world-at-ruin#661 comment 5150876600: the body opens
// with a review trigger and closes with the disclosure.
func TestClassify_TrailingDisclosureIsAViolation(t *testing.T) {
	body := "@coderabbitai full review\n\nPlease review exact head abc123.\n\n> 🤖 Generated by the Agentic Engineer.\n"
	if got := Classify(body); got != TrailingDisclosure {
		t.Fatalf("trailing disclosure: got %q, want %q", got, TrailingDisclosure)
	}
}

// A disclosure in the middle of the body is equally non-compliant: the contract
// anchors the test at the FIRST line, not "somewhere in the body".
func TestClassify_MidBodyDisclosureIsAViolation(t *testing.T) {
	body := "Some preamble the lane put first.\n\n> 🤖 Generated by the Agentic Engineer\n\nMore text.\n"
	if got := Classify(body); got != TrailingDisclosure {
		t.Fatalf("mid-body disclosure: got %q, want %q", got, TrailingDisclosure)
	}
}

// Shape B, measured live on ksail#6244 comment 5030838223.
func TestClassify_NonCanonicalSenderMarkerIsAViolation(t *testing.T) {
	bodies := []string{
		"> Requested by the 🤖 Daily AI Engineer — CI is green at the current head.\n",
		"🤖 Sent by the Agentic Engineer (Codex machine-local instance)\n\nDetail.\n",
		"> Posted by the 🤖 Agentic Engineer\n",
	}
	for _, body := range bodies {
		if got := Classify(body); got != SenderMarker {
			t.Errorf("sender marker %q: got %q, want %q", excerpt(body, 40), got, SenderMarker)
		}
	}
}

// Shape D, measured live on world-at-ruin#662: a trigger plus extra content and
// no disclosure anywhere. This both voids Bugbot's exact match AND publishes
// unattributed content.
func TestClassify_AnnotatedTriggerIsAViolation(t *testing.T) {
	body := "@coderabbitai review\n\nPlease review exact head 94171a33ec112cf86f559f037bf99a54fe996a43\n"
	if got := Classify(body); got != AnnotatedTrigger {
		t.Fatalf("annotated trigger: got %q, want %q", got, AnnotatedTrigger)
	}
}

// The carve-out. Bugbot exact-matches the whole comment body, so the trigger has
// to be posted bare with the disclosure in its own preceding comment. Flagging
// this would break the one review lane that requires it.
func TestClassify_BareTriggerIsExempt(t *testing.T) {
	bodies := []string{
		"@cursor review",
		"@cursor review\n",
		"  @cursor review  \n\n",
		"@codex review",
		"@coderabbitai review",
	}
	for _, body := range bodies {
		if got := Classify(body); got != BareTrigger {
			t.Errorf("bare trigger %q: got %q, want %q", body, got, BareTrigger)
		}
	}
}

// THE false-positive that matters most. A `devantler` comment with no robot
// marker is the human maintainer, and his comments are a control channel.
// Reporting one would flag the control channel as a defect -- the dangerous
// direction of the contract's asymmetric error model.
func TestClassify_MaintainerProseIsNeverAViolation(t *testing.T) {
	bodies := []string{
		"Drop the human promotion gate. I always approve your work anyhow.",
		"This is wrong. You need symmetric authority.",
		"the last Codex run missed the conflict check; please fix that first",
		"Looks good, merge it.",
		"",
		"\n\n",
	}
	for _, body := range bodies {
		got := Classify(body)
		if got.violating() {
			t.Errorf("maintainer prose %q classified as violation %q", excerpt(body, 40), got)
		}
	}
}

// The maintainer routinely QUOTES an agent's disclosed text when replying to it.
// A quote is mid-body, so it must not be read as the agent's own trailing
// disclosure -- but a nested quote is the specific shape to protect, because the
// contract calls out that he does exactly this.
func TestClassify_MaintainerQuotingAgentTextIsNotFlaggedAsSenderMarker(t *testing.T) {
	// He leads with his own words, so the first line is not a sender marker and
	// not a trigger. The nested quote below is his quotation of agent output.
	body := "No, this is the wrong approach.\n\n> > 🤖 Generated by the Agentic Engineer\n> > I decided X\n\nDo Y instead.\n"
	got := Classify(body)
	if got == SenderMarker || got == AnnotatedTrigger {
		t.Fatalf("maintainer reply quoting agent text: got %q, want a non-sender/non-trigger verdict", got)
	}
}

// A sentence that merely MENTIONS an agent is not a sender marker. The contract
// is explicit: the demotion trigger is a sender marker only.
func TestClassify_MentioningAnAgentIsNotASenderMarker(t *testing.T) {
	bodies := []string{
		"The Agentic Engineer should have caught this.",
		"I think the Daily AI Engineer generated this by mistake.",
	}
	for _, body := range bodies {
		if got := Classify(body); got.violating() {
			t.Errorf("mention %q classified as violation %q", body, got)
		}
	}
}

// A trigger line carrying prose on the SAME line is not a bare trigger: it voids
// the lane's exact match and carries unattributed content.
func TestClassify_TriggerWithInlineProseIsNotBare(t *testing.T) {
	body := "@cursor review please look at the auth path carefully"
	got := Classify(body)
	if got == BareTrigger {
		t.Fatalf("trigger with inline prose: got %q, want a violation", got)
	}
	if !got.violating() {
		t.Fatalf("trigger with inline prose: got %q, want a violating verdict", got)
	}
}

// CRLF must classify identically to LF. GitHub stores what the client sent and
// the lanes differ, so a compliant body posted with CRLF must not read as a
// violation.
func TestClassify_CRLFBodyClassifiesLikeLF(t *testing.T) {
	crlf := strings.ReplaceAll(compliantBody, "\n", "\r\n")
	if got := Classify(crlf); got != Compliant {
		t.Fatalf("CRLF canonical body: got %q, want %q", got, Compliant)
	}
}

// A leading blank line before an otherwise-canonical disclosure is NOT
// compliant: GitHub renders the first line as the body's opening, and the
// contract anchors at position zero.
func TestClassify_LeadingBlankLineBeforeDisclosureIsNotCompliant(t *testing.T) {
	body := "\n> 🤖 Generated by the Agentic Engineer\n\nBody.\n"
	if got := Classify(body); got == Compliant {
		t.Fatal("a body whose disclosure is preceded by a blank line must not read as compliant")
	}
}

func TestAnalyse_OnlyTheNamedAuthorIsConsidered(t *testing.T) {
	comments := []Comment{
		{ID: 1, Author: "devantler", Body: "@coderabbitai review\n\nextra\n"},
		{ID: 2, Author: "coderabbitai", Body: "@coderabbitai review\n\nextra\n"},
		{ID: 3, Author: "some-external", Body: "> 🤖 Generated by the Agentic Engineer\nfake\n"},
	}
	report := Analyse(comments, "devantler")
	if report.Considered != 1 {
		t.Fatalf("considered = %d, want 1", report.Considered)
	}
	if len(report.Findings) != 1 || report.Findings[0].ID != 1 {
		t.Fatalf("findings = %+v, want exactly comment 1", report.Findings)
	}
	if report.SkippedAuthors != 2 {
		t.Fatalf("skippedAuthors = %d, want 2", report.SkippedAuthors)
	}
}

// A raw `gh api .../comments` payload uses {"user":{"login":...}}. Accepting it
// unreshaped is what keeps the shell wrapper a thin pipe.
func TestAnalyse_AcceptsRestUserShape(t *testing.T) {
	raw := `[{"id":5150876600,"html_url":"https://example/1","user":{"login":"devantler"},
	          "body":"@coderabbitai full review\n\n> 🤖 Generated by the Agentic Engineer."}]`
	comments, err := decode([]byte(raw))
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	report := Analyse(comments, "devantler")
	if len(report.Findings) != 1 {
		t.Fatalf("findings = %d, want 1", len(report.Findings))
	}
	if report.Findings[0].Verdict != TrailingDisclosure {
		t.Fatalf("verdict = %q, want %q", report.Findings[0].Verdict, TrailingDisclosure)
	}
	if report.Findings[0].URL != "https://example/1" {
		t.Fatalf("url = %q, want the payload's html_url", report.Findings[0].URL)
	}
}

func TestDecode_AcceptsWrappedObject(t *testing.T) {
	raw := `{"comments":[{"id":7,"author":"devantler","body":"> 🤖 Generated by the Agentic Engineer\nok"}]}`
	comments, err := decode([]byte(raw))
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	if len(comments) != 1 || comments[0].ID != 7 {
		t.Fatalf("comments = %+v, want the single wrapped comment", comments)
	}
}

// An unreadable payload must FAIL CLOSED (exit 2 territory), never decode to an
// empty set that reports "no violations".
func TestDecode_RejectsGarbageRatherThanReportingClean(t *testing.T) {
	for _, raw := range []string{"", "   ", "not json", "{", `{"unexpected":1`} {
		if _, err := decode([]byte(raw)); err == nil {
			t.Errorf("decode(%q) succeeded; want an error so the guard fails closed", raw)
		}
	}
}

// A payload that is valid JSON but carries no comment array must not silently
// read as "zero comments, all clean".
func TestDecode_ObjectWithoutCommentsIsEmptyNotAnError(t *testing.T) {
	comments, err := decode([]byte(`{"message":"Not Found"}`))
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	if len(comments) != 0 {
		t.Fatalf("comments = %+v, want none", comments)
	}
	// The wrapper is responsible for treating an empty considered-set as
	// suspicious; the classifier's contract is only that it does not invent
	// findings. Pin that so a future refactor cannot fabricate one.
	report := Analyse(comments, "devantler")
	if len(report.Findings) != 0 || report.Considered != 0 {
		t.Fatalf("report = %+v, want an empty report", report)
	}
}

// excerpt must not cut a multi-byte rune in half, or the report itself emits
// mojibake for exactly the emoji this check is about.
func TestExcerpt_TrimsOnRuneBoundaries(t *testing.T) {
	line := strings.Repeat("🤖", 40)
	got := excerpt(line, 10)
	if !strings.HasSuffix(got, "...") {
		t.Fatalf("excerpt = %q, want a truncation marker", got)
	}
	trimmed := strings.TrimSuffix(got, "...")
	if len([]rune(trimmed)) != 10 {
		t.Fatalf("excerpt kept %d runes, want 10", len([]rune(trimmed)))
	}
	if strings.Contains(got, "�") {
		t.Fatalf("excerpt = %q, want no replacement character", got)
	}
}

func TestVerdict_OnlyTheThreeShapesViolate(t *testing.T) {
	violating := map[Verdict]bool{
		TrailingDisclosure: true,
		SenderMarker:       true,
		AnnotatedTrigger:   true,
	}
	all := []Verdict{Compliant, BareTrigger, TrailingDisclosure, SenderMarker, AnnotatedTrigger, Unattributable}
	for _, verdict := range all {
		if got, want := verdict.violating(), violating[verdict]; got != want {
			t.Errorf("%q.violating() = %v, want %v", verdict, got, want)
		}
	}
}

// The live sample the issue cited, as a regression corpus. Kept as JSON so it
// round-trips through the same decode path production uses.
func TestAnalyse_LiveSampleCorpus(t *testing.T) {
	corpus := []map[string]any{
		// world-at-ruin#661 5150876600 -- trailing disclosure
		{"id": 5150876600, "author": "devantler",
			"body": "@coderabbitai full review\n\n> 🤖 Generated by the Agentic Engineer."},
		// world-at-ruin#662 5151295297 -- annotated trigger, no disclosure at all
		{"id": 5151295297, "author": "devantler",
			"body": "@coderabbitai review\n\nPlease review exact head 94171a33ec112cf86f559f037bf99a54fe996a43"},
		// ksail#6244 5030838223 -- non-canonical sender marker
		{"id": 5030838223, "author": "devantler",
			"body": "> Requested by the 🤖 Daily AI Engineer — CI is green at the current head."},
		// ksail#6244 5030838309 -- the bare-trigger carve-out, must NOT be flagged
		{"id": 5030838309, "author": "devantler", "body": "@cursor review"},
		// a correctly-formed comment, must NOT be flagged
		{"id": 9999999999, "author": "devantler",
			"body": "> 🤖 Generated by the Agentic Engineer\n\n## Why\n\nReal work.\n"},
	}
	raw, err := json.Marshal(corpus)
	if err != nil {
		t.Fatalf("marshal corpus: %v", err)
	}
	comments, err := decode(raw)
	if err != nil {
		t.Fatalf("decode corpus: %v", err)
	}
	report := Analyse(comments, "devantler")

	if len(report.Findings) != 3 {
		t.Fatalf("findings = %d, want 3 (the three documented defect shapes)", len(report.Findings))
	}
	wantVerdicts := map[int64]Verdict{
		5030838223: SenderMarker,
		5150876600: TrailingDisclosure,
		5151295297: AnnotatedTrigger,
	}
	for _, finding := range report.Findings {
		want, ok := wantVerdicts[finding.ID]
		if !ok {
			t.Errorf("unexpected finding on comment %d (%q)", finding.ID, finding.Verdict)
			continue
		}
		if finding.Verdict != want {
			t.Errorf("comment %d: verdict %q, want %q", finding.ID, finding.Verdict, want)
		}
	}
	if report.Counts[BareTrigger] != 1 {
		t.Errorf("bare-trigger count = %d, want 1", report.Counts[BareTrigger])
	}
	if report.Counts[Compliant] != 1 {
		t.Errorf("compliant count = %d, want 1", report.Counts[Compliant])
	}
	// Findings must be ID-ordered so the report is stable run to run.
	for i := 1; i < len(report.Findings); i++ {
		if report.Findings[i-1].ID >= report.Findings[i].ID {
			t.Fatalf("findings are not ID-ordered: %+v", report.Findings)
		}
	}
}
