// comment-disclosure-drift classifies agent-authored GitHub comments that fail
// the contract's leading-disclosure test.
//
// AGENTS.md makes a `devantler` comment's FIRST line the trust discriminator: a
// body that begins with the structural `> 🤖 Generated by the ` prefix is the
// agent's own output (data), and a body without it is the human maintainer (a
// control channel whose contents are instructions). Lanes that emit the
// disclosure anywhere other than the first line therefore publish their own
// output as if it were maintainer instruction — the self-instruction loop the
// disambiguator exists to close.
//
// # Why this reports positive evidence only
//
// The naive check — "flag every `devantler` comment without a leading
// disclosure" — is unusable, because that description also fits every genuine
// maintainer comment. It would flag the maintainer's control channel as a
// defect, which is the dangerous direction of the contract's deliberately
// asymmetric error model.
//
// So a body is reported only when it carries affirmative evidence of agent
// authorship AND fails the leading-prefix test. Three such shapes are
// recognised, each anchored to the start or the end of the body so that a
// maintainer QUOTING an agent's disclosed text mid-body is not caught:
//
//	TrailingDisclosure   a canonical disclosure appears, but not as the first line
//	SenderMarker         the first line is a 🤖 first-person sender marker in a
//	                     non-canonical form (e.g. "> Requested by the 🤖 ...")
//	AnnotatedTrigger     the first line opens a review-lane trigger and the body
//	                     carries additional content, so the bare-trigger
//	                     carve-out does not apply
//
// # Known residual gap
//
// A body with no 🤖 marker, no canonical disclosure and no leading trigger — an
// agent's bare prose note — is NOT reported. It is indistinguishable by shape
// from a maintainer comment, and reporting it would mean flagging the control
// channel. This is a deliberate false-negative, not an oversight: the check
// makes the identifiable half of the defect visible instead of nothing, and
// never trades that for a false positive on the maintainer.
//
// The guard is network-free. It reads a JSON array of comments from a file or
// stdin; the shell wrapper owns the `gh` calls, keeping the untrusted-input
// boundary in one place.
package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
)

// canonicalPrefix is the one form that satisfies the contract. Matching is on
// the STRUCTURE, never the actor word: the role has been renamed twice (Daily
// AI Assistant -> Daily AI Engineer -> Agentic Engineer) and a matcher keyed to
// one spelling would silently reclassify every comment written under another.
const canonicalPrefix = "> 🤖 Generated by the "

// robotMarker is the emoji every recognised disclosure and sender marker mentions.
const robotMarker = "🤖"

// reviewTriggers are the review-lane commands an agent posts. The maintainer
// does not drive the review lanes — the engineer does — so a body OPENING with
// one of these is agent-authored on the contract's own division of labour.
//
// Bugbot is the reason the carve-out below exists at all: it exact-matches the
// whole comment body, so its trigger must be posted bare, with the disclosure
// in its own preceding comment.
var reviewTriggers = []string{
	"@coderabbitai",
	"@codex",
	"@cursor",
	"@copilot",
}

// senderPhrases are first-person automation sender forms that name an agent as
// the SENDER. Per AGENTS.md these still classify the body as agent output, but
// they are NOT the canonical prefix, so emitting one is the defect this reports.
//
// A body that merely MENTIONS an agent, run or tick is not a sender marker --
// the maintainer routinely writes "the last Codex run missed X" -- so these are
// matched only on the first line, in sender position.
var senderPhrases = []string{
	"generated by",
	"requested by",
	"sent by",
	"posted by",
	"written by",
}

// Verdict is the classification of one comment body.
type Verdict string

const (
	// Compliant means the body begins with the canonical disclosure prefix.
	Compliant Verdict = "compliant"
	// BareTrigger means the whole body is exactly a review-lane trigger, which
	// the contract exempts: the trigger must be the entire body for the lane to
	// fire, and the disclosure goes in its own preceding comment.
	BareTrigger Verdict = "bare-trigger"
	// TrailingDisclosure means a canonical disclosure is present but not first.
	TrailingDisclosure Verdict = "trailing-disclosure"
	// SenderMarker means the first line is a non-canonical 🤖 sender marker.
	SenderMarker Verdict = "sender-marker"
	// AnnotatedTrigger means the body opens a review trigger and adds content
	// without a leading disclosure.
	AnnotatedTrigger Verdict = "annotated-trigger"
	// Unattributable means no positive evidence of agent authorship. Reported as
	// a count only; see the "Known residual gap" note above.
	Unattributable Verdict = "unattributable"
)

// violating reports whether a verdict is a defect this guard fails on.
func (v Verdict) violating() bool {
	switch v {
	case TrailingDisclosure, SenderMarker, AnnotatedTrigger:
		return true
	default:
		return false
	}
}

// Comment is one GitHub comment, in the subset the classifier needs.
type Comment struct {
	ID     int64  `json:"id"`
	Body   string `json:"body"`
	URL    string `json:"html_url"`
	Author string `json:"author"`
	// User carries the REST shape (`{"user":{"login":...}}`) so a raw
	// `gh api .../comments` payload can be fed in without reshaping.
	User struct {
		Login string `json:"login"`
	} `json:"user"`
}

// login resolves the comment's author across both accepted payload shapes.
func (c Comment) login() string {
	if c.Author != "" {
		return c.Author
	}
	return c.User.Login
}

// normalise strips carriage returns so a CRLF body classifies identically to an
// LF one. GitHub stores what the client sent, and the lanes differ.
func normalise(body string) string {
	return strings.ReplaceAll(body, "\r", "")
}

// nonEmptyLines returns the body's lines with blank ones removed, each trimmed
// of surrounding whitespace.
func nonEmptyLines(body string) []string {
	var out []string
	for _, line := range strings.Split(body, "\n") {
		if trimmed := strings.TrimSpace(line); trimmed != "" {
			out = append(out, trimmed)
		}
	}
	return out
}

// hasCanonicalPrefix reports whether the body BEGINS WITH the canonical
// disclosure. Anchored at position zero: a disclosure merely appearing inside a
// body classifies nothing, because the maintainer quotes agent text when he
// replies to it.
func hasCanonicalPrefix(body string) bool {
	return strings.HasPrefix(body, canonicalPrefix)
}

// containsCanonicalDisclosure reports whether any line is a canonical
// disclosure, ignoring leading blockquote/whitespace decoration. Used only to
// prove agent authorship for a body that failed the leading-prefix test.
func containsCanonicalDisclosure(lines []string) bool {
	for _, line := range lines {
		if strings.HasPrefix(line, canonicalPrefix) {
			return true
		}
		// A trailing disclosure is frequently emitted with the sentence
		// punctuation the canonical form omits, e.g.
		// "> 🤖 Generated by the Agentic Engineer." -- still a disclosure.
		if strings.HasPrefix(line, strings.TrimSuffix(canonicalPrefix, " ")) {
			return true
		}
	}
	return false
}

// isSenderMarker reports whether a first line names an agent as the SENDER in a
// non-canonical form: it carries the robot emoji and a first-person sender
// phrase. Requiring both is what keeps a maintainer sentence that merely
// mentions a lane from being demoted to agent output.
func isSenderMarker(firstLine string) bool {
	if !strings.Contains(firstLine, robotMarker) {
		return false
	}
	lowered := strings.ToLower(firstLine)
	for _, phrase := range senderPhrases {
		if strings.Contains(lowered, phrase) {
			return true
		}
	}
	return false
}

// triggerPrefix returns the review trigger a line opens with, and whether it
// found one.
func triggerPrefix(line string) (string, bool) {
	for _, trigger := range reviewTriggers {
		if strings.HasPrefix(strings.ToLower(line), trigger) {
			return trigger, true
		}
	}
	return "", false
}

// isBareTrigger reports whether the ENTIRE body is a single review trigger
// command. This is the contract's narrow carve-out. A bare trigger is a machine
// command with no prose content: it instructs no agent and asserts nothing, so
// it cannot function as a disguised maintainer instruction.
func isBareTrigger(body string) bool {
	lines := nonEmptyLines(body)
	if len(lines) != 1 {
		return false
	}
	if _, ok := triggerPrefix(lines[0]); !ok {
		return false
	}
	// Guard against a trigger line that smuggles prose after the command, which
	// would both void the lane's exact match AND carry unattributed content.
	return len(strings.Fields(lines[0])) <= 2
}

// Classify assigns a verdict to one comment body.
func Classify(body string) Verdict {
	body = normalise(body)

	if hasCanonicalPrefix(body) {
		return Compliant
	}
	if isBareTrigger(body) {
		return BareTrigger
	}

	lines := nonEmptyLines(body)
	if len(lines) == 0 {
		return Unattributable
	}

	// Order matters: a canonical disclosure anywhere is the strongest available
	// evidence of agent authorship, so it is tested before the weaker shapes.
	if containsCanonicalDisclosure(lines) {
		return TrailingDisclosure
	}
	if isSenderMarker(lines[0]) {
		return SenderMarker
	}
	if _, ok := triggerPrefix(lines[0]); ok {
		return AnnotatedTrigger
	}
	return Unattributable
}

// Finding is one reported violation.
type Finding struct {
	ID      int64
	URL     string
	Verdict Verdict
	First   string
}

// Report is the outcome of classifying a comment set.
type Report struct {
	Findings       []Finding
	Counts         map[Verdict]int
	Considered     int
	SkippedAuthors int
}

// excerpt shortens a line for single-line reporting.
func excerpt(line string, max int) string {
	line = strings.TrimSpace(line)
	if len(line) <= max {
		return line
	}
	// Trim on a rune boundary so a multi-byte emoji is never cut in half.
	runes := []rune(line)
	if len(runes) <= max {
		return line
	}
	return string(runes[:max]) + "..."
}

// Analyse classifies every comment authored by the given login.
func Analyse(comments []Comment, author string) Report {
	report := Report{Counts: map[Verdict]int{}}
	for _, comment := range comments {
		if comment.login() != author {
			report.SkippedAuthors++
			continue
		}
		report.Considered++
		verdict := Classify(comment.Body)
		report.Counts[verdict]++
		if !verdict.violating() {
			continue
		}
		lines := nonEmptyLines(normalise(comment.Body))
		first := ""
		if len(lines) > 0 {
			first = lines[0]
		}
		report.Findings = append(report.Findings, Finding{
			ID:      comment.ID,
			URL:     comment.URL,
			Verdict: verdict,
			First:   excerpt(first, 60),
		})
	}
	sort.Slice(report.Findings, func(i, j int) bool {
		return report.Findings[i].ID < report.Findings[j].ID
	})
	return report
}

// decode parses a comment payload, accepting either a bare JSON array or an
// object with a "comments" array.
func decode(raw []byte) ([]Comment, error) {
	trimmed := strings.TrimSpace(string(raw))
	if trimmed == "" {
		return nil, errors.New("empty payload")
	}
	var comments []Comment
	if err := json.Unmarshal([]byte(trimmed), &comments); err == nil {
		return comments, nil
	}
	var wrapper struct {
		Comments []Comment `json:"comments"`
	}
	if err := json.Unmarshal([]byte(trimmed), &wrapper); err != nil {
		return nil, fmt.Errorf("payload is neither a comment array nor an object carrying one: %w", err)
	}
	return wrapper.Comments, nil
}

func main() {
	var (
		input  = flag.String("input", "-", `comment JSON file, or "-" for stdin`)
		author = flag.String("author", "devantler", "only classify comments by this exact login")
		all    = flag.Bool("all", false, "also print the non-violating verdict tally")
	)
	flag.Parse()

	var (
		raw []byte
		err error
	)
	if *input == "-" {
		raw, err = io.ReadAll(os.Stdin)
	} else {
		raw, err = os.ReadFile(*input)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "comment-disclosure-drift: cannot read comments: %v\n", err)
		os.Exit(2)
	}

	comments, err := decode(raw)
	if err != nil {
		fmt.Fprintf(os.Stderr, "comment-disclosure-drift: %v\n", err)
		os.Exit(2)
	}

	report := Analyse(comments, *author)

	for _, finding := range report.Findings {
		location := finding.URL
		if location == "" {
			location = fmt.Sprintf("comment %d", finding.ID)
		}
		fmt.Printf("VIOLATION %-19s %s\n    first line: %s\n", finding.Verdict, location, finding.First)
	}

	if *all {
		verdicts := []Verdict{Compliant, BareTrigger, TrailingDisclosure, SenderMarker, AnnotatedTrigger, Unattributable}
		for _, verdict := range verdicts {
			fmt.Printf("%-19s %d\n", verdict, report.Counts[verdict])
		}
	}

	if len(report.Findings) > 0 {
		fmt.Printf("comment-disclosure-drift: %d of %d %s comment(s) fail the leading-disclosure test\n",
			len(report.Findings), report.Considered, *author)
		os.Exit(1)
	}

	fmt.Printf("comment-disclosure-drift: all %d %s comment(s) satisfy the leading-disclosure test",
		report.Considered, *author)
	if unattributable := report.Counts[Unattributable]; unattributable > 0 {
		// Never let a clean exit read as full coverage: this class is the
		// documented residual gap, not a pass.
		fmt.Printf(" (%d unattributable, not checkable by shape)", unattributable)
	}
	fmt.Println()
}
