// comment-disclosure-drift classifies agent-authored GitHub comments that fail
// the contract's leading-disclosure test.
//
// AGENTS.md makes a `devantler` comment's FIRST line the trust discriminator: a
// body that begins with the structural `> 🤖 Generated by the ` prefix is the
// agent's own output (data), and a body without it is the human maintainer (a
// control channel whose contents are instructions). Lanes that emit the
// disclosure anywhere other than the first line therefore publish their own
// output as if it were maintainer instruction — the self-instruction loop the
// disambiguator exists to close.
//
// # Why this reports positive evidence only
//
// The naive check — "flag every `devantler` comment without a leading
// disclosure" — is unusable, because that description also fits every genuine
// maintainer comment. It would flag the maintainer's control channel as a
// defect, which is the dangerous direction of the contract's deliberately
// asymmetric error model.
//
// So a body is reported only when it carries affirmative evidence of agent
// authorship AND fails the leading-prefix test. Two such shapes are recognised,
// BOTH anchored to the first line, so that a maintainer quoting an agent's
// disclosed text anywhere in his reply is never caught:
//
//	SenderMarker         the first line OPENS with a 🤖 first-person sender marker in
//	                     a non-canonical form (e.g. "> Requested by the 🤖 ...")
//	UndisclosedTrigger   the first line opens a review-lane trigger and the body is
//	                     not the one exempt bare trigger
//
// Both are first-line anchored because the maintainer QUOTES agent output when he
// replies to it, and an unanchored scan reports his control-channel comment as the
// defect. See the note above Classify for why a trailing disclosure is NOT a shape.
//
// # Known residual gap
//
// A body with no leading sender marker and no leading trigger — an agent's bare
// prose note, or one whose only disclosure is appended at the END — is NOT reported. It is indistinguishable by shape
// from a maintainer comment, and reporting it would mean flagging the control
// channel. This is a deliberate false-negative, not an oversight: the check
// makes the identifiable half of the defect visible instead of nothing, and
// never trades that for a false positive on the maintainer.
//
// The guard is network-free. It reads a JSON array of comments from a file or
// stdin; the shell wrapper owns the `gh` calls, keeping the untrusted-input
// boundary in one place.
package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

// canonicalPrefix is the one form that satisfies the contract. Matching is on
// the STRUCTURE, never the actor word: the role has been renamed twice (Daily
// AI Assistant -> Daily AI Engineer -> Agentic Engineer) and a matcher keyed to
// one spelling would silently reclassify every comment written under another.
const canonicalPrefix = "> 🤖 Generated by the "

// reviewTriggers are the COMPLETE review commands AGENTS.md has the engineer
// post. A body opening with one is agent-authored on the contract's own division
// of labour: the engineer drives the review lanes and the maintainer does not.
//
// These are whole COMMANDS, not account prefixes, and the difference is the point.
// Matching "@codex" plus any boundary character also matches `@codex address that
// feedback`, `@codex please explain this` and `@copilot can you implement this?` —
// all things the maintainer plausibly writes, so an account-prefix rule reports
// his control channel. `@copilot` is absent entirely: Copilot reviews, but the
// contract never has us trigger it, so a comment addressed to it is his.
//
// `@codex review` is matched as a prefix so the contract's optional focus suffix
// (`@codex review for <topic>`) still counts.
var reviewTriggers = []string{
	"@coderabbitai full review",
	"@coderabbitai review",
	"@codex review",
	"@cursor review",
}

// senderMarkerPattern matches a first-person automation sender marker in SENDER
// POSITION — at the very start of the line, after optional blockquote decoration.
//
// Two things must hold together, and testing them INDEPENDENTLY is the bug this
// shape fixes. The phrase must be anchored at line start, or "The result generated
// by the 🤖 Agentic Engineer is wrong" (an instruction) reads as a marker. And the
// emoji must sit ADJACENT to the phrase, in one of the two positions real markers
// use, or "Generated by the build, the 🤖 disclosure is missing; fix it." satisfies
// an anchored phrase plus an unrelated emoji elsewhere on the line.
// A third thing must hold: the marker has to NAME AN AGENT. Stopping at "by the"
// classifies maintainer prose that merely opens with the phrase — "🤖 Generated by
// the build; investigate this." — as a sender marker, which reports his control
// channel as a violation. That is the same inversion this whole guard is built to
// avoid, arrived at from the other direction.
//
// The two errors are not symmetric, and that is what sets the strictness. Failing to
// recognise a sibling's non-canonical marker leaves its comment in the disclosed
// `unattributable` residual — a missed detection, visible in the output. Matching the
// maintainer turns his instruction into a CI failure. So this requires positive
// evidence of an agent name and accepts a missed detection as the cheaper error.
//
// Matched by ROLE NOUN rather than by actor name, deliberately: the actor has been
// renamed twice (Daily AI Assistant → Daily AI Engineer → Agentic Engineer) and a
// pattern keyed to one spelling silently stops matching comments written under the
// others. Every one of those names ends in the same role noun, and no ordinary
// sentence subject does. "[Claude Code]" is correctly NOT matched — that is the
// maintainer's interactive marker, not an agent sender.
//
// The definite article is OPTIONAL, because it carries none of the evidence.
// "🤖 Sent by Agentic Engineer" and "Requested by 🤖 Codex Agent" name an agent
// as the sender exactly as plainly as the articled forms do, and the contract
// defines the marker as a leading sender line naming an agent — it says nothing
// about the article. Requiring it left those forms in the `unattributable`
// residual, so a sibling could avoid detection by dropping one word. What still
// carries the evidence is unchanged: the emoji, the phrase in sender position,
// and the ROLE NOUN — so "🤖 Generated by build" matches no better than before.
const senderPhrase = `(?i:generated|requested|sent|posted|written)[ \t]+by(?:[ \t]+the)?`

const agentNameTail = `(?:[ \t]+[A-Z][A-Za-z0-9.]*){0,3}[ \t]+(?i:engineers?|assistants?|agents?|bots?)\b`

var senderMarkerPattern = regexp.MustCompile(
	`^(?:>[ \t]*)*(?:` +
		// emoji BEFORE the phrase: "🤖 Sent by the Agentic Engineer"
		`\x{1F916}[ \t]*` + senderPhrase + agentNameTail +
		`|` +
		// emoji AFTER the phrase: "> Requested by the 🤖 Daily AI Engineer"
		senderPhrase + `[ \t]+\x{1F916}` + agentNameTail +
		`)`)

// bareTriggerExemptBodies are the complete comment bodies that may carry no
// disclosure at all, compared case-insensitively after trimming.
//
// Deliberately just ONE entry. AGENTS.md grants the carve-out to Bugbot alone,
// because Bugbot exact-matches the whole comment body, so its trigger cannot
// share a comment with a disclosure line; every other lane's trigger is required
// to sit in the SAME disclosed comment as its request marker. Widening this to
// "any recognised trigger prefix" would exempt `@codex review`, `@coderabbitai
// review` and even `@cursor investigate` — leaving common real violations
// undetected and silently exempting commands that are not review triggers at all.
var bareTriggerExemptBodies = map[string]bool{
	"@cursor review": true,
}

// Verdict is the classification of one comment body.
type Verdict string

const (
	// Compliant means the body begins with the canonical disclosure prefix.
	Compliant Verdict = "compliant"
	// BareTrigger means the whole body is exactly a review-lane trigger, which
	// the contract exempts: the trigger must be the entire body for the lane to
	// fire, and the disclosure goes in its own preceding comment.
	BareTrigger Verdict = "bare-trigger"
	// SenderMarker means the first line is a non-canonical 🤖 sender marker.
	SenderMarker Verdict = "sender-marker"
	// UndisclosedTrigger means the body opens a review-lane trigger without a
	// leading disclosure and is not the one exempt bare trigger.
	UndisclosedTrigger Verdict = "undisclosed-trigger"
	// Unattributable means no positive evidence of agent authorship. Reported as
	// a count only; see the "Known residual gap" note above.
	Unattributable Verdict = "unattributable"
	// UnexpandedFileRef means the whole body is an `@`-prefixed filesystem
	// path — a post whose content never expanded. `--body "@file"` takes the
	// string literally; only `gh api -F field=@file` reads the file. `gh` exits
	// 0 and returns a comment URL either way, so this shape is invisible to the
	// caller and is what makes it worth detecting after the fact.
	UnexpandedFileRef Verdict = "unexpanded-file-ref"
)

// violating reports whether a verdict is a defect this guard fails on.
func (v Verdict) violating() bool {
	switch v {
	case SenderMarker, UndisclosedTrigger, UnexpandedFileRef:
		return true
	default:
		return false
	}
}

// Comment is one GitHub comment, in the subset the classifier needs.
type Comment struct {
	ID     int64  `json:"id"`
	Body   string `json:"body"`
	URL    string `json:"html_url"`
	Author string `json:"author"`
	// IssueURL identifies the discussion a comment belongs to. It matters only for
	// the bare-trigger carve-out, which is granted by the disclosure being the
	// IMMEDIATELY PRECEDING comment in the SAME discussion. A repo-wide sweep
	// interleaves discussions in one array, so without this the pairing can span
	// two of them. Absent (a hand-assembled payload), every record shares the empty
	// value, which is the single-discussion case the per-issue mode always was.
	IssueURL string `json:"issue_url"`
	// User carries the REST shape (`{"user":{"login":...}}`) so a raw
	// `gh api .../comments` payload can be fed in without reshaping.
	User struct {
		Login string `json:"login"`
	} `json:"user"`
}

// login resolves the comment's author across both accepted payload shapes.
func (c Comment) login() string {
	if c.Author != "" {
		return c.Author
	}
	return c.User.Login
}

// normalise strips carriage returns so a CRLF body classifies identically to an
// LF one. GitHub stores what the client sent, and the lanes differ.
func normalise(body string) string {
	return strings.ReplaceAll(body, "\r", "")
}

// nonEmptyLines returns the body's lines with blank ones removed, each trimmed
// of surrounding whitespace. Used for the reported excerpt, where indentation is
// noise; classification uses firstContentLine instead, which preserves it.
func nonEmptyLines(body string) []string {
	var out []string
	for _, line := range strings.Split(body, "\n") {
		if trimmed := strings.TrimSpace(line); trimmed != "" {
			out = append(out, trimmed)
		}
	}
	return out
}

// firstContentLine returns the body's first non-blank line WITH its original
// leading whitespace, and whether one exists. Classification needs the
// indentation that nonEmptyLines discards — see isMarkdownCodeBlock.
func firstContentLine(body string) (string, bool) {
	for _, line := range strings.Split(body, "\n") {
		if strings.TrimSpace(line) != "" {
			return line, true
		}
	}
	return "", false
}

// tabStop is CommonMark's tab width: a tab advances to the next multiple of it,
// and four spaces of content indent open an indented code block. One constant
// because they are the same number by definition, not by coincidence.
const tabStop = 4

// maxBlockquoteIndent is how many spaces may precede a `>` and still leave it a
// block-quote marker. It is tabStop-1 by derivation, not by coincidence: one
// more space would already have opened an indented code block, so the `>` would
// be content inside that block rather than a marker.
const maxBlockquoteIndent = tabStop - 1

// expandLeadingTabs rewrites tabs as the spaces CommonMark expands them to,
// measuring from the start of the line so every later column is the real one.
//
// Doing this FIRST is what lets the marker and indent rules below be written in
// plain spaces. CommonMark expands a tab to the next four-column tab stop and
// then lets a block-quote marker consume part of it, so a tab is worth between
// one and four columns depending on where it sits — `>\t` leaves three columns
// of indent while `> \t` leaves only two. Any rule that treats a tab as a fixed
// width gets one of those two wrong.
//
// Tabs after the indent are expanded too. They cannot change the measurement,
// and stopping at the first content character would cost a scan for no gain.
func expandLeadingTabs(line string) string {
	if !strings.ContainsRune(line, '\t') {
		return line
	}
	var b strings.Builder
	column := 0
	for _, r := range line {
		if r == '\t' {
			width := tabStop - (column % tabStop)
			b.WriteString(strings.Repeat(" ", width))
			column += width
			continue
		}
		b.WriteRune(r)
		column++
	}
	return b.String()
}

// blockquoteContent strips leading block-quote markers and returns the content
// inside them, KEEPING whatever indentation remains.
//
// CommonMark applies the indented-code-block rule inside a block quote, so
// `>     🤖 Sent by …` is an example of a marker rather than a marker. The
// code-block gate could not see that: run against the raw line, the leading `>`
// is content and the column count stops at zero, so the gate never fired and the
// sender-marker pattern — which consumes `>` and every following space itself —
// matched the maintainer's own quoted example.
//
// A marker is up to three spaces of indent, the `>`, and at most ONE following
// space. Each part matters:
//
//   - The three-space allowance is why ` >     🤖 …` is still a quoted example.
//     Requiring `>` at column zero left the line looking like ordinary content,
//     so the gate did not fire and the maintainer's example was reported as his
//     own sender marker — a false positive on the control channel.
//   - Consuming exactly one space is what makes `>` + five spaces reach column
//     four while `>` + one space does not.
//
// Four or more spaces before a `>` are NOT a marker: that is already a code
// block, and the `>` inside it is content. Leaving those spaces on the returned
// line is what lets isMarkdownCodeBlock reach that verdict on its own.
func blockquoteContent(line string) string {
	line = expandLeadingTabs(line)
	for {
		indent := 0
		for indent < maxBlockquoteIndent && indent < len(line) && line[indent] == ' ' {
			indent++
		}
		if indent >= len(line) || line[indent] != '>' {
			// Not a marker — return the line with its indent intact, so the
			// caller measures the content's real column.
			return line
		}
		line = strings.TrimPrefix(line[indent+1:], " ")
	}
}

// isMarkdownCodeBlock reports whether a line's indentation makes GitHub render
// it as an indented code block — four or more spaces, or a leading tab
// (CommonMark; one to three spaces is ordinary text).
//
// WHY THIS GATES CLASSIFICATION.
//
// Both positive-evidence shapes below read the first content line as the
// comment's OWN VOICE. An indented first line is not that: it is quoted or
// example text, which is exactly how the maintainer writes a comment that shows
// a trigger rather than issuing one:
//
//	@codex review
//
// Trimmed, that is byte-identical to an agent posting the trigger — so the guard
// reported his comment as `undisclosed-trigger`, i.e. it flagged the control
// channel as agent output. That is the one direction this guard must never fail
// in, and no refinement of the trigger match can separate the two, because after
// trimming there is nothing left to separate.
//
// The cost is bounded and measured: every real agent trigger in the portfolio is
// written flush-left, so requiring flush-left removes no true positive. An
// indented agent comment falls through to Unattributable — a documented false
// negative, taken deliberately over a false positive, exactly as the
// trailing-disclosure verdict was.
// Indentation is measured in COLUMNS, not characters, because that is what
// CommonMark measures: a tab advances to the next four-column tab stop, so
// " \t" and "  \t" both reach column 4 and render as an indented code block.
// Testing only for a leading tab or four literal spaces missed every mixed form,
// and a maintainer's indented example of a trigger was then classified as a live
// trigger — a false positive on the control channel.
func isMarkdownCodeBlock(line string) bool {
	column := 0
	for _, r := range line {
		switch r {
		case ' ':
			column++
		case '\t':
			column += tabStop - (column % tabStop)
		default:
			return false // content began before column 4
		}
		if column >= tabStop {
			return true
		}
	}
	// A line of nothing but whitespace has no content to misclassify either way.
	return false
}

// hasCanonicalPrefix reports whether the body BEGINS WITH the canonical
// disclosure. Anchored at position zero: a disclosure merely appearing inside a
// body classifies nothing, because the maintainer quotes agent text when he
// replies to it.
func hasCanonicalPrefix(body string) bool {
	return strings.HasPrefix(body, canonicalPrefix)
}

// NOTE — why there is no standalone "trailing disclosure" verdict.
//
// An earlier revision reported any body whose LAST line was a disclosure. That
// shape is INDISTINGUISHABLE from the maintainer quoting an agent and adding
// nothing after it:
//
//	I disagree.
//
//	> 🤖 Generated by the Agentic Engineer
//
// is byte-for-byte the same structure as an agent appending its own sign-off.
// Requiring the preceding line to be unquoted does not separate them, because his
// prose line is unquoted too. No refinement of this rule can, so it reported the
// control channel — the one direction this guard must never fail in.
//
// Every trailing-disclosure case measured live is ALSO trigger-led (world-at-ruin
// #661 comments 5150876600 and 5150913159 both open `@coderabbitai full review`),
// so UndisclosedTrigger catches them on independent evidence and no detection is
// lost. A lone prose-plus-trailing-disclosure body is now Unattributable — a
// documented false negative, taken deliberately over a false positive.

// isSenderMarker reports whether a first line names an agent as the SENDER in a
// non-canonical form. BOTH conditions are required:
//
//   - the robot emoji appears somewhere on the line (the marker's own convention
//     places it either before or after the sender phrase), and
//   - a first-person sender phrase sits in SENDER POSITION — at the start of the
//     line, per senderMarkerPattern.
//
// The anchor is what separates "> Requested by the 🤖 Daily AI Engineer — CI is
// green" (a marker) from "The result generated by the 🤖 Agentic Engineer is
// wrong" (a maintainer instruction that merely discusses generated output).
func isSenderMarker(firstLine string) bool {
	return senderMarkerPattern.MatchString(firstLine)
}

// triggerPrefix returns the review trigger a line opens with, and whether it
// found one.
// A word boundary after the command is required. Without it `@codex-team please
// clarify` reads as an `@codex review` command — but that is the maintainer
// addressing a different account, and reporting it would flag his control channel.
// The command must be followed by end-of-line or whitespace.
func triggerPrefix(line string) (string, bool) {
	lowered := strings.ToLower(line)
	for _, trigger := range reviewTriggers {
		if !strings.HasPrefix(lowered, trigger) {
			continue
		}
		rest := lowered[len(trigger):]
		if rest == "" || rest[0] == ' ' || rest[0] == '\t' {
			return trigger, true
		}
	}
	return "", false
}

// isBareTrigger reports whether the ENTIRE body is one of the exempt bare
// trigger commands. Matching is on the COMPLETE body against an exact allowlist,
// never on a recognised prefix plus a word count: a prefix rule exempts
// `@cursor investigate` and `@codex fix`, which are not review triggers and are
// not carved out.
// Byte-exactness is the point, not pedantry: the exemption exists only because
// Bugbot exact-matches the whole comment body, so a variant that would NOT fire
// the lane has no claim to it. Accepting `@Cursor Review`, a double-spaced variant
// or padding would hide a disclosure violation on a comment that also silently
// started no review.
//
// Nothing is trimmed. Measured across the portfolio, every real bare trigger is
// stored as exactly "@cursor review" (ksail#6244 comment 5030838309,
// platform#2702 comment 5030845280) with no padding and no trailing newline, so
// strict comparison costs no true exemption. Only CR normalisation is applied,
// because that is a transport artifact rather than body content.
func isBareTrigger(body string) bool {
	return bareTriggerExemptBodies[normalise(body)]
}

// isUnexpandedFileRef reports whether the whole body is an `@`-prefixed
// filesystem path and nothing else — the shape `gh ... --body "@file"` produces
// when the caller meant `--body-file`.
//
// The test is deliberately narrow, because a false positive here would report a
// real comment as a failed post. All four conjuncts are required: exactly one
// content line (more than one means content did land), no Unicode whitespace
// anywhere (a
// path mentioned in a sentence is a real comment), a leading `@` followed by a
// path root, and something after that root. A lone `@mention` therefore does not
// match, and the exempt bare trigger is classified before this is reached.
//
// Two residuals are accepted rather than closed, both of which fail toward
// under-reporting. A path containing a space is not matched, because requiring
// no whitespace is what keeps a path mentioned inside a sentence from being read
// as a failed post. And a bare relative reference such as `@notes.md` is not
// matched, because `@name` is also how a mention is written and the two cannot
// be told apart without guessing at file extensions. Every measured instance was
// an absolute path, which is what `--body "@$dir/file.md"` produces.
func isUnexpandedFileRef(body string) bool {
	trimmed := strings.TrimSpace(body)
	if strings.ContainsFunc(trimmed, unicode.IsSpace) {
		return false
	}
	for _, root := range []string{"@/", "@./", "@../"} {
		if strings.HasPrefix(trimmed, root) && len(trimmed) > len(root) {
			return true
		}
	}
	return false
}

// Classify assigns a verdict to one comment body.
func Classify(body string) Verdict {
	body = normalise(body)

	if hasCanonicalPrefix(body) {
		return Compliant
	}
	if isBareTrigger(body) {
		return BareTrigger
	}
	if isUnexpandedFileRef(body) {
		return UnexpandedFileRef
	}

	raw, ok := firstContentLine(body)
	if !ok {
		return Unattributable
	}
	// An indented first line is example/quoted text, not the comment's own
	// voice, so it carries no positive evidence of agent authorship. Measured
	// INSIDE any block quote, because CommonMark keeps applying the code-block
	// rule there and a quoted example is still an example.
	if isMarkdownCodeBlock(blockquoteContent(raw)) {
		return Unattributable
	}
	first := strings.TrimSpace(raw)

	// Trigger evidence first: the engineer drives the review lanes and the
	// maintainer does not, so a leading trigger is the strongest available signal.
	// There is deliberately no trailing-disclosure branch — see the note above.
	if _, ok := triggerPrefix(first); ok {
		return UndisclosedTrigger
	}
	if isSenderMarker(first) {
		return SenderMarker
	}
	return Unattributable
}

// Finding is one reported violation.
type Finding struct {
	ID      int64
	URL     string
	Verdict Verdict
	First   string
}

// Report is the outcome of classifying a comment set.
type Report struct {
	Findings       []Finding
	Counts         map[Verdict]int
	Considered     int
	SkippedAuthors int
}

// excerpt shortens a line to at most limit RUNES for single-line reporting.
//
// The budget is in runes, not bytes, so a multi-byte emoji is never cut in half —
// which matters here because the emoji is the very thing being reported on. The
// parameter is not named `max`: that shadows the predeclared identifier and
// golangci-lint reports it.
func excerpt(line string, limit int) string {
	line = strings.TrimSpace(line)
	runes := []rune(line)
	if len(runes) <= limit {
		return line
	}
	return string(runes[:limit]) + "..."
}

// Analyse classifies every comment authored by the given login.
//
// The comment ORDER matters for one rule. AGENTS.md grants Bugbot's bare trigger
// its exemption only because the disclosure sits in its own comment IMMEDIATELY
// BEFORE it, which is what keeps the thread self-documenting. A bare trigger
// standing alone therefore has no exemption to claim, and judging it per-body in
// isolation would clear exactly the unpaired case the carve-out excludes.
//
// "Immediately before" is a fact about ONE DISCUSSION, so the predecessor is
// tracked per issue_url rather than as a single global. A repo-wide payload
// interleaves discussions, and a global predecessor gets both directions wrong:
// issue A's disclosure would grant issue B's trigger a carve-out it never earned,
// and a comment from issue B standing between issue A's disclosure and A's trigger
// would revoke one that is legitimate within A.
func Analyse(comments []Comment, author string) Report {
	return analyse(comments, author, false)
}

// AnalyseSweep is Analyse for a repo-wide `--since` payload, where the carve-out is
// NEVER granted.
//
// `since` selects comments by UPDATED time, so a discussion's returned history is
// not contiguous: an edited old disclosure can arrive while the unchanged comment
// that really follows it does not (measured 2026-08-11 — a comment created
// 21:40:05Z came back in a window starting 22:00:00Z, edited at 22:31:08Z). Two
// records can therefore be adjacent in the payload with a real comment between
// them, so adjacency here is not evidence of the pairing the carve-out requires.
// Granting it on that evidence CLEARS a trigger whose true predecessor was never
// seen, which is a fail-open; refusing it costs a false report on a legitimate pair,
// which is visible and re-checkable with --issue. monorepo#2781 tracks fetching the
// real predecessor so precision can be restored.
func AnalyseSweep(comments []Comment, author string) Report {
	return analyse(comments, author, true)
}

func analyse(comments []Comment, author string, sweep bool) Report {
	report := Report{Counts: map[Verdict]int{}}
	lastWasDisclosure := map[string]bool{}
	for _, comment := range comments {
		if comment.login() != author {
			report.SkippedAuthors++
			continue
		}
		report.Considered++
		verdict := Classify(comment.Body)
		if verdict == BareTrigger && (sweep || !lastWasDisclosure[comment.IssueURL]) {
			// The exemption is conditional on the pairing; unpaired, it is an
			// undisclosed trigger like any other.
			verdict = UndisclosedTrigger
		}
		lastWasDisclosure[comment.IssueURL] = hasCanonicalPrefix(normalise(comment.Body))
		report.Counts[verdict]++
		if !verdict.violating() {
			continue
		}
		lines := nonEmptyLines(normalise(comment.Body))
		first := ""
		if len(lines) > 0 {
			first = lines[0]
		}
		report.Findings = append(report.Findings, Finding{
			ID:      comment.ID,
			URL:     comment.URL,
			Verdict: verdict,
			First:   excerpt(first, 60),
		})
	}
	sort.Slice(report.Findings, func(i, j int) bool {
		return report.Findings[i].ID < report.Findings[j].ID
	})
	return report
}

// validateRecords requires every record to carry an identifiable author and a
// body. Without this a truncated or error-shaped record passes JSON decoding,
// gets skipped by Analyse as a non-matching author, and the guard reports a clean
// sweep having checked nothing.
func validateRecords(raw []byte, expected int) error {
	var records []map[string]json.RawMessage
	if err := json.Unmarshal(raw, &records); err != nil {
		return fmt.Errorf("comment array is not a list of objects: %w", err)
	}
	if len(records) != expected {
		return errors.New("comment array shape changed between decodes")
	}
	for i, record := range records {
		if _, ok := record["body"]; !ok {
			return fmt.Errorf("comment %d has no \"body\" field", i)
		}
		if bytes := strings.TrimSpace(string(record["body"])); bytes == "null" {
			return fmt.Errorf("comment %d has a null \"body\"", i)
		}
		author, hasAuthor := record["author"]
		user, hasUser := record["user"]
		// Decode the author rather than comparing its RAW JSON against `""`, and
		// require the decoded login to be EXACTLY what login() will return.
		//
		// Validating a normalised value while comparing an unnormalised one is the
		// fail-open: a padded "devantler " trims to a non-empty login and passes
		// here, but login() hands Analyse the padded string, the exact-author
		// comparison misses, and the record is skipped as somebody else's — so a
		// comment carrying a real violation is never classified and the guard
		// reports a clean sweep. A whitespace-only "   " is the same bug with an
		// empty trim. GitHub logins never contain whitespace, so a padded one is
		// malformed input: fail closed rather than silently declining to check it.
		identifiable := func(login string) bool {
			return login != "" && login == strings.TrimSpace(login)
		}
		// Validate the representation login() will SELECT, not whichever one
		// happens to be valid. login() returns Author whenever it is non-empty, so
		// falling back to user.login for a malformed author validated a value the
		// comparison never sees: {"author":"devantler ","user":{"login":"devantler"}}
		// passed here, then login() returned the padded author, Analyse skipped the
		// record, and the comment went unchecked. The fallback is correct only when
		// author is genuinely absent or empty — which is exactly when login() uses it.
		authored := false
		selectsAuthor := false
		if hasAuthor {
			var login string
			if err := json.Unmarshal(author, &login); err == nil {
				if login != "" {
					selectsAuthor = true
					authored = identifiable(login)
				}
			} else {
				// A non-string author is malformed; it must not be rescued below.
				selectsAuthor = true
			}
		}
		if !selectsAuthor && hasUser {
			var login struct {
				Login string `json:"login"`
			}
			if err := json.Unmarshal(user, &login); err == nil && identifiable(login.Login) {
				authored = true
			}
		}
		if !authored {
			return fmt.Errorf("comment %d has no identifiable author", i)
		}
	}
	return nil
}

// isJSONArray reports whether an already-trimmed JSON value is a composite
// array, judged by its opening token.
//
// This is deliberately a SHAPE test, not a decode test: several non-array values
// unmarshal into a []Comment without error — `null` most importantly — so asking
// "did it decode?" cannot distinguish a real empty array from a missing payload.
// The opening token can, and every caller here has already trimmed and
// non-empty-checked its input, so the first byte is the whole answer.
func isJSONArray(trimmed string) bool {
	return strings.HasPrefix(trimmed, "[")
}

// decode parses a comment payload, accepting either a bare JSON array or an
// object with a "comments" array.
func decode(raw []byte) ([]Comment, error) {
	trimmed := strings.TrimSpace(string(raw))
	if trimmed == "" {
		return nil, errors.New("empty payload")
	}
	// Dispatch on the payload's ACTUAL top-level shape rather than on whether an
	// unmarshal happened to succeed. `null` decodes into a nil []Comment without
	// error, so a shape-blind bare path accepted a missing payload as zero records
	// and exited 0 claiming a clean sweep — the same fail-open the wrapped form
	// already rejected, reached through the other entry point. Deciding on the
	// first token makes both paths enforce one rule and keeps each error specific
	// to the form the caller actually sent.
	if isJSONArray(trimmed) {
		var comments []Comment
		if err := json.Unmarshal([]byte(trimmed), &comments); err != nil {
			return nil, fmt.Errorf("payload is not an array of comments: %w", err)
		}
		// Validate RECORDS, not just JSON syntax. The --input path is the
		// advertised way to feed an assembled payload (review comments, replies),
		// so an incomplete assembly must fail closed rather than classify nothing
		// and report clean: `[{"message":"Not Found"}]` has no author, so every
		// record would be skipped as non-matching and the run would exit 0.
		if err := validateRecords([]byte(trimmed), len(comments)); err != nil {
			return nil, err
		}
		return comments, nil
	}
	// An object form must CARRY the key. Unmarshal ignores unknown fields, so a
	// GitHub error body like {"message":"Not Found"} would otherwise decode to a
	// nil slice and report "all 0 comments satisfy" — a swallowed API error
	// masquerading as a clean sweep, which is the exact fail-open this guard
	// exists to avoid. Require the key, and require it to be an array.
	// Require the object token before probing. `null` unmarshals into a nil MAP
	// as happily as it does into a nil slice, so without this it would reach the
	// key lookup and be reported as an object missing its "comments" key — naming
	// the wrong fault to whoever has to fix the payload.
	if !strings.HasPrefix(trimmed, "{") {
		return nil, errors.New("payload is neither a comment array nor an object carrying one")
	}
	var probe map[string]json.RawMessage
	if err := json.Unmarshal([]byte(trimmed), &probe); err != nil {
		return nil, fmt.Errorf("payload is neither a comment array nor an object carrying one: %w", err)
	}
	raw, ok := probe["comments"]
	if !ok {
		return nil, errors.New(`object payload has no "comments" key`)
	}
	// The value must be an ACTUAL array, not merely something that unmarshals
	// into one. `null` decodes to a nil slice without error and would pass as
	// zero comments; requiring the array token also rejects a scalar or object
	// value, which the same rule now covers for the bare form above.
	if !isJSONArray(strings.TrimSpace(string(raw))) {
		return nil, errors.New(`object payload's "comments" value is not an array`)
	}
	var wrapped []Comment
	if err := json.Unmarshal(raw, &wrapped); err != nil {
		return nil, fmt.Errorf(`"comments" is not an array of comments: %w`, err)
	}
	// The wrapper form must clear the SAME record bar as a bare array, or
	// {"comments":[{"message":"Not Found"}]} decodes to a zero-valued comment,
	// gets skipped as a non-matching author, and exits 0 having checked nothing.
	if err := validateRecords(raw, len(wrapped)); err != nil {
		return nil, err
	}
	return wrapped, nil
}

func main() {
	var (
		input  = flag.String("input", "-", `comment JSON file, or "-" for stdin`)
		author = flag.String("author", "devantler", "only classify comments by this exact login")
		all    = flag.Bool("all", false, "also print the non-violating verdict tally")
		sweep  = flag.Bool("sweep", false, "payload is a repo-wide --since sweep: never grant the bare-trigger carve-out")
	)
	flag.Parse()

	// An empty --author matches NOTHING, because validateRecords already rejects
	// any record without an author. Every comment would land in SkippedAuthors,
	// Considered would be 0, and the guard would print "all 0 devantler
	// comment(s) satisfy" and exit 0 — a clean sweep over an unclassified
	// corpus. That is the same fail-open shape decode and validateRecords exist
	// to prevent, and the shell wrapper passing an unset variable is all it
	// would take, so refuse it here rather than reporting success.
	// Padded as well as empty. No GitHub login carries surrounding whitespace, so
	// `--author 'devantler '` matches nothing: every real record is skipped as a
	// different author and the guard exits 0 over an unclassified corpus — the same
	// clean-sweep fail-open, reached through the flag instead of the payload.
	if *author == "" || *author != strings.TrimSpace(*author) {
		fmt.Fprintln(os.Stderr, "comment-disclosure-drift: --author must be a non-empty login with no surrounding whitespace")
		os.Exit(2)
	}

	var (
		raw []byte
		err error
	)
	if *input == "-" {
		raw, err = io.ReadAll(os.Stdin)
	} else {
		raw, err = os.ReadFile(*input)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "comment-disclosure-drift: cannot read comments: %v\n", err)
		os.Exit(2)
	}

	comments, err := decode(raw)
	if err != nil {
		fmt.Fprintf(os.Stderr, "comment-disclosure-drift: %v\n", err)
		os.Exit(2)
	}

	report := Analyse(comments, *author)
	if *sweep {
		report = AnalyseSweep(comments, *author)
	}

	for _, finding := range report.Findings {
		location := finding.URL
		if location == "" {
			location = fmt.Sprintf("comment %d", finding.ID)
		}
		fmt.Printf("VIOLATION %-19s %s\n    first line: %s\n", finding.Verdict, location, finding.First)
	}

	if *all {
		verdicts := []Verdict{Compliant, BareTrigger, SenderMarker, UndisclosedTrigger, UnexpandedFileRef, Unattributable}
		for _, verdict := range verdicts {
			fmt.Printf("%-19s %d\n", verdict, report.Counts[verdict])
		}
	}

	if len(report.Findings) > 0 {
		fmt.Printf("comment-disclosure-drift: %d of %d %s comment(s) fail the leading-disclosure test\n",
			len(report.Findings), report.Considered, *author)
		os.Exit(1)
	}

	fmt.Printf("comment-disclosure-drift: all %d %s comment(s) satisfy the leading-disclosure test",
		report.Considered, *author)
	if unattributable := report.Counts[Unattributable]; unattributable > 0 {
		// Never let a clean exit read as full coverage: this class is the
		// documented residual gap, not a pass.
		fmt.Printf(" (%d unattributable, not checkable by shape)", unattributable)
	}
	fmt.Println()
}
