package main

import (
	"encoding/json"
	"strings"
	"testing"
)

// The canonical form, as the lanes emit it today.
const compliantBody = "> 🤖 Generated by the Agentic Engineer\n\n## Why\n\nSomething.\n"

func TestClassify_CanonicalPrefixIsCompliant(t *testing.T) {
	if got := Classify(compliantBody); got != Compliant {
		t.Fatalf("canonical leading disclosure: got %q, want %q", got, Compliant)
	}
}

// The actor word has been renamed twice. A matcher keyed to one spelling would
// silently reclassify every comment written under the others, so every historical
// form must stay compliant -- permanently.
func TestClassify_EveryHistoricalActorWordStaysCompliant(t *testing.T) {
	actors := []string{
		"Agentic Engineer",
		"Agentic Engineer (Cursor cloud instance)",
		"Daily AI Engineer",
		"Daily AI Assistant",
		"Some Future Role Nobody Has Named Yet",
	}
	for _, actor := range actors {
		body := "> 🤖 Generated by the " + actor + "\n\nBody.\n"
		if got := Classify(body); got != Compliant {
			t.Errorf("actor %q: got %q, want %q", actor, got, Compliant)
		}
	}
}

// Measured live on world-at-ruin#661 comment 5150876600. The disclosure is
// appended at the END, but the body is caught on INDEPENDENT evidence: it opens
// with a review trigger. That corroboration is what makes the detection safe.
func TestClassify_AppendedDisclosureAfterTriggerIsCaught(t *testing.T) {
	body := "@coderabbitai full review\n\nPlease review exact head abc123.\n\n> 🤖 Generated by the Agentic Engineer.\n"
	if got := Classify(body); got != UndisclosedTrigger {
		t.Fatalf("appended disclosure after trigger: got %q, want %q", got, UndisclosedTrigger)
	}
}

// Codex P1 (#2720): a LONE trailing disclosure after unquoted prose is
// byte-for-byte the shape of the maintainer quoting an agent and adding nothing
// after it. No rule separates the two, so this must NOT be reported -- a
// deliberate false negative, taken over a false positive on the control channel.
func TestClassify_LoneTrailingDisclosureIsNotAViolation(t *testing.T) {
	bodies := []string{
		"I disagree.\n\n> 🤖 Generated by the Agentic Engineer\n",
		"Reviewer evidence note for exact head abc123.\n\n> 🤖 Generated by the Agentic Engineer\n",
	}
	for _, body := range bodies {
		if got := Classify(body); got.violating() {
			t.Errorf("lone trailing disclosure %q: got violation %q", excerpt(body, 40), got)
		}
	}
}

// Codex P1 (#2720): a disclosure in the MIDDLE of the body must NOT be reported.
// That is the maintainer's ordinary "Quote reply" shape -- he quotes the agent and
// then writes his response underneath, so his own text is last. Reporting it would
// flag the control channel, the one direction this guard must never fail in.
func TestClassify_MidBodyDisclosureIsNotAViolation(t *testing.T) {
	body := "Some preamble.\n\n> 🤖 Generated by the Agentic Engineer\n\nMore text after it.\n"
	if got := Classify(body); got.violating() {
		t.Fatalf("mid-body disclosure: got violation %q, want a non-violating verdict", got)
	}
}

// Codex P1 (#2720): the emoji must be ADJACENT to the sender phrase. An anchored
// phrase plus an unrelated emoji elsewhere on the line is maintainer prose.
func TestClassify_AnchoredPhraseWithUnrelatedEmojiIsNotASenderMarker(t *testing.T) {
	bodies := []string{
		"Generated by the build, the 🤖 disclosure is missing; fix it.",
		"Requested by the team, but the 🤖 marker is wrong.",
	}
	for _, body := range bodies {
		if got := Classify(body); got.violating() {
			t.Errorf("prose %q classified as violation %q", body, got)
		}
	}
}

// Codex P2 (#2720): a login that merely SHARES a trigger prefix is a different
// account, and addressing it is the maintainer's own comment.
func TestClassify_LongerLoginIsNotATrigger(t *testing.T) {
	bodies := []string{
		"@codex-team please clarify this",
		"@cursorless what do you think?",
		"@coderabbitai-staging review",
		"@codex-team review",
	}
	for _, body := range bodies {
		if got := Classify(body); got.violating() {
			t.Errorf("addressing %q classified as violation %q", body, got)
		}
	}
}

// Codex P1 (#2720): the SINGLE-level quote is the normal GitHub "Quote reply"
// shape and previously produced an exit 1 on the maintainer's own comment. The
// nested "> >" form was already covered; this is the common one.
func TestClassify_SingleLevelQuoteReplyIsNotAViolation(t *testing.T) {
	bodies := []string{
		// He quotes the agent, then answers underneath.
		"> 🤖 Generated by the Agentic Engineer\n> I decided to do X\n\nNo, do Y instead.\n",
		// He quotes a multi-line block whose LAST line is the disclosure.
		"Disagree.\n\n> I decided to do X\n> 🤖 Generated by the Agentic Engineer\n",
		// Quote-only reply, no trailing disclosure.
		"> 🤖 Generated by the Agentic Engineer\n> I decided to do X\n",
	}
	for _, body := range bodies {
		if got := Classify(body); got.violating() {
			t.Errorf("single-level quote reply %q: got violation %q", excerpt(body, 46), got)
		}
	}
}

// Shape B, measured live on ksail#6244 comment 5030838223.
func TestClassify_NonCanonicalSenderMarkerIsAViolation(t *testing.T) {
	bodies := []string{
		"> Requested by the 🤖 Daily AI Engineer — CI is green at the current head.\n",
		"🤖 Sent by the Agentic Engineer (Codex machine-local instance)\n\nDetail.\n",
		"> Posted by the 🤖 Agentic Engineer\n",
	}
	for _, body := range bodies {
		if got := Classify(body); got != SenderMarker {
			t.Errorf("sender marker %q: got %q, want %q", excerpt(body, 40), got, SenderMarker)
		}
	}
}

// Shape D, measured live on world-at-ruin#662: a trigger plus extra content and
// no disclosure anywhere. This both voids Bugbot's exact match AND publishes
// unattributed content.
func TestClassify_UndisclosedTriggerIsAViolation(t *testing.T) {
	body := "@coderabbitai review\n\nPlease review exact head 94171a33ec112cf86f559f037bf99a54fe996a43\n"
	if got := Classify(body); got != UndisclosedTrigger {
		t.Fatalf("annotated trigger: got %q, want %q", got, UndisclosedTrigger)
	}
}

// The carve-out. Bugbot exact-matches the whole comment body, so the trigger has
// to be posted bare with the disclosure in its own preceding comment. Flagging
// this would break the one review lane that requires it.
func TestClassify_BareTriggerIsExempt(t *testing.T) {
	bodies := []string{
		// Measured: every real bare trigger is stored as exactly this.
		"@cursor review",
		// CR is a transport artifact, not body content, so it is normalised away.
		"@cursor review\r",
	}
	for _, body := range bodies {
		if got := Classify(body); got != BareTrigger {
			t.Errorf("bare cursor trigger %q: got %q, want %q", body, got, BareTrigger)
		}
	}
}

// Codex P1 (#2720): Bugbot exact-matches the literal body, so a variant that would
// NOT fire the lane has no claim to the exemption -- exempting it would hide a
// disclosure violation on a comment that also silently started no review.
// Asserting only "not exempted" would pass while a variant went unreported, so each
// variant pins the verdict it actually earns. The double-spaced body is the one that
// earns no violation: it matches no trigger shape, so the guard has no POSITIVE
// evidence that an agent authored it. That residual is deliberate -- reporting a
// merely trigger-ish body would be the absence-based test this guard rejects, which
// flags the maintainer's own comments -- so it is pinned as a known non-violating
// case rather than quietly satisfying a weaker assertion.
func TestClassify_BugbotExemptionIsByteExact(t *testing.T) {
	want := map[string]Verdict{
		"@Cursor Review":        UndisclosedTrigger,
		"@cursor  review":       Unattributable,
		"@cursor review please": UndisclosedTrigger,
		"  @cursor review  ":    UndisclosedTrigger,
		"@cursor review\n":      UndisclosedTrigger,
		"\n@cursor review":      UndisclosedTrigger,
	}
	for body, expected := range want {
		got := Classify(body)
		if got == BareTrigger {
			t.Errorf("%q was exempted; the exemption is byte-exact", body)
		}
		if got != expected {
			t.Errorf("%q: got %q, want %q", body, got, expected)
		}
	}
}

// Codex P1 (#2720): the carve-out is Bugbot's ALONE. Every other lane must carry
// the disclosure in the same comment as its trigger, so a bare trigger for those
// lanes is a real violation -- and a prefix+word-count rule also wrongly exempted
// commands that are not review triggers at all.
func TestClassify_OnlyTheCursorTriggerIsExempt(t *testing.T) {
	for _, body := range []string{"@codex review", "@coderabbitai review", "@coderabbitai full review"} {
		got := Classify(body)
		if got == BareTrigger {
			t.Errorf("%q was exempted; only the exact Cursor trigger is carved out", body)
		}
		if !got.violating() {
			t.Errorf("%q: got %q, want a violating verdict", body, got)
		}
	}
}

// Codex P1 (#2720): positive evidence is the complete review COMMAND, not the
// account. `@codex address that feedback` and friends are things the maintainer
// plausibly writes, so an account-prefix rule reported his control channel.
// `@copilot` is not a lane we trigger at all.
func TestClassify_NonReviewCommandsToThoseAccountsAreNotEvidence(t *testing.T) {
	bodies := []string{
		"@codex address that feedback",
		"@codex please explain this",
		"@copilot can you implement this issue?",
		"@copilot review",
		"@cursor investigate",
		"@codex fix",
		"@coderabbitai resolve",
	}
	for _, body := range bodies {
		if got := Classify(body); got.violating() {
			t.Errorf("non-review command %q classified as violation %q", body, got)
		}
	}
}

// The contract's optional focus suffix must still count as a trigger.
func TestClassify_ReviewCommandWithFocusSuffixIsATrigger(t *testing.T) {
	body := "@codex review for concurrency\n\nplease look at the locking"
	if got := Classify(body); got != UndisclosedTrigger {
		t.Fatalf("focus-suffixed trigger: got %q, want %q", got, UndisclosedTrigger)
	}
}

// THE false-positive that matters most. A `devantler` comment with no robot
// marker is the human maintainer, and his comments are a control channel.
// Reporting one would flag the control channel as a defect -- the dangerous
// direction of the contract's asymmetric error model.
func TestClassify_MaintainerProseIsNeverAViolation(t *testing.T) {
	bodies := []string{
		"Drop the human promotion gate. I always approve your work anyhow.",
		"This is wrong. You need symmetric authority.",
		"the last Codex run missed the conflict check; please fix that first",
		"Looks good, merge it.",
		"",
		"\n\n",
	}
	for _, body := range bodies {
		got := Classify(body)
		if got.violating() {
			t.Errorf("maintainer prose %q classified as violation %q", excerpt(body, 40), got)
		}
	}
}

// The maintainer routinely QUOTES an agent's disclosed text when replying to it.
// A quote is mid-body, so it must not be read as the agent's own trailing
// disclosure -- but a nested quote is the specific shape to protect, because the
// contract calls out that he does exactly this.
func TestClassify_MaintainerQuotingAgentTextIsNotFlaggedAsSenderMarker(t *testing.T) {
	// He leads with his own words, so the first line is not a sender marker and
	// not a trigger. The nested quote below is his quotation of agent output.
	body := "No, this is the wrong approach.\n\n> > 🤖 Generated by the Agentic Engineer\n> > I decided X\n\nDo Y instead.\n"
	got := Classify(body)
	if got == SenderMarker || got == UndisclosedTrigger {
		t.Fatalf("maintainer reply quoting agent text: got %q, want a non-sender/non-trigger verdict", got)
	}
}

// A sentence that merely MENTIONS an agent is not a sender marker. The contract
// is explicit: the demotion trigger is a sender marker only.
func TestClassify_MentioningAnAgentIsNotASenderMarker(t *testing.T) {
	bodies := []string{
		"The Agentic Engineer should have caught this.",
		"I think the Daily AI Engineer generated this by mistake.",
		// Codex P1 (#2720): carries BOTH the emoji and a sender phrase, but the
		// phrase is not in sender position -- this is an instruction ABOUT
		// generated output, not a marker saying an agent sent it.
		"The result generated by the 🤖 Agentic Engineer is wrong; restore the previous behavior.",
		"Please check what was requested by the 🤖 Agentic Engineer earlier.",
	}
	for _, body := range bodies {
		if got := Classify(body); got.violating() {
			t.Errorf("mention %q classified as violation %q", body, got)
		}
	}
}

// A trigger line carrying prose on the SAME line is not a bare trigger: it voids
// the lane's exact match and carries unattributed content.
func TestClassify_TriggerWithInlineProseIsNotBare(t *testing.T) {
	body := "@cursor review please look at the auth path carefully"
	got := Classify(body)
	if got == BareTrigger {
		t.Fatalf("trigger with inline prose: got %q, want a violation", got)
	}
	if !got.violating() {
		t.Fatalf("trigger with inline prose: got %q, want a violating verdict", got)
	}
}

// CRLF must classify identically to LF. GitHub stores what the client sent and
// the lanes differ, so a compliant body posted with CRLF must not read as a
// violation.
func TestClassify_CRLFBodyClassifiesLikeLF(t *testing.T) {
	crlf := strings.ReplaceAll(compliantBody, "\n", "\r\n")
	if got := Classify(crlf); got != Compliant {
		t.Fatalf("CRLF canonical body: got %q, want %q", got, Compliant)
	}
}

// A leading blank line before an otherwise-canonical disclosure is NOT
// compliant: GitHub renders the first line as the body's opening, and the
// contract anchors at position zero.
func TestClassify_LeadingBlankLineBeforeDisclosureIsNotCompliant(t *testing.T) {
	body := "\n> 🤖 Generated by the Agentic Engineer\n\nBody.\n"
	if got := Classify(body); got == Compliant {
		t.Fatal("a body whose disclosure is preceded by a blank line must not read as compliant")
	}
}

func TestAnalyse_OnlyTheNamedAuthorIsConsidered(t *testing.T) {
	comments := []Comment{
		{ID: 1, Author: "devantler", Body: "@coderabbitai review\n\nextra\n"},
		{ID: 2, Author: "coderabbitai", Body: "@coderabbitai review\n\nextra\n"},
		{ID: 3, Author: "some-external", Body: "> 🤖 Generated by the Agentic Engineer\nfake\n"},
	}
	report := Analyse(comments, "devantler")
	if report.Considered != 1 {
		t.Fatalf("considered = %d, want 1", report.Considered)
	}
	if len(report.Findings) != 1 || report.Findings[0].ID != 1 {
		t.Fatalf("findings = %+v, want exactly comment 1", report.Findings)
	}
	if report.SkippedAuthors != 2 {
		t.Fatalf("skippedAuthors = %d, want 2", report.SkippedAuthors)
	}
}

// A raw `gh api .../comments` payload uses {"user":{"login":...}}. Accepting it
// unreshaped is what keeps the shell wrapper a thin pipe.
func TestAnalyse_AcceptsRestUserShape(t *testing.T) {
	raw := `[{"id":5150876600,"html_url":"https://example/1","user":{"login":"devantler"},
	          "body":"@coderabbitai full review\n\n> 🤖 Generated by the Agentic Engineer."}]`
	comments, err := decode([]byte(raw))
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	report := Analyse(comments, "devantler")
	if len(report.Findings) != 1 {
		t.Fatalf("findings = %d, want 1", len(report.Findings))
	}
	if report.Findings[0].Verdict != UndisclosedTrigger {
		t.Fatalf("verdict = %q, want %q", report.Findings[0].Verdict, UndisclosedTrigger)
	}
	if report.Findings[0].URL != "https://example/1" {
		t.Fatalf("url = %q, want the payload's html_url", report.Findings[0].URL)
	}
}

func TestDecode_AcceptsWrappedObject(t *testing.T) {
	raw := `{"comments":[{"id":7,"author":"devantler","body":"> 🤖 Generated by the Agentic Engineer\nok"}]}`
	comments, err := decode([]byte(raw))
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	if len(comments) != 1 || comments[0].ID != 7 {
		t.Fatalf("comments = %+v, want the single wrapped comment", comments)
	}
}

// An unreadable payload must FAIL CLOSED (exit 2 territory), never decode to an
// empty set that reports "no violations".
func TestDecode_RejectsGarbageRatherThanReportingClean(t *testing.T) {
	for _, raw := range []string{"", "   ", "not json", "{", `{"unexpected":1`} {
		if _, err := decode([]byte(raw)); err == nil {
			t.Errorf("decode(%q) succeeded; want an error so the guard fails closed", raw)
		}
	}
}

// Codex P2 (#2720): a valid-JSON object WITHOUT a "comments" key must fail
// closed. Unmarshal ignores unknown fields, so a GitHub error body decoded to a
// nil slice and the guard printed "all 0 comments satisfy" and exited 0 -- a
// swallowed API error masquerading as a clean sweep.
func TestDecode_ObjectWithoutCommentsKeyFailsClosed(t *testing.T) {
	for _, raw := range []string{`{"message":"Not Found"}`, `{}`, `{"comments":null}`, `{"comments":{}}`} {
		if _, err := decode([]byte(raw)); err == nil {
			t.Errorf("decode(%s) succeeded; want an error so the guard fails closed", raw)
		}
	}
}

// The wrapped form is still accepted when the key IS present and an array.
func TestDecode_EmptyCommentsArrayIsAccepted(t *testing.T) {
	comments, err := decode([]byte(`{"comments":[]}`))
	if err != nil {
		t.Fatalf("decode: %v", err)
	}
	if len(comments) != 0 {
		t.Fatalf("comments = %+v, want none", comments)
	}
}

// excerpt must not cut a multi-byte rune in half, or the report itself emits
// mojibake for exactly the emoji this check is about.
func TestExcerpt_TrimsOnRuneBoundaries(t *testing.T) {
	line := strings.Repeat("🤖", 40)
	got := excerpt(line, 10)
	if !strings.HasSuffix(got, "...") {
		t.Fatalf("excerpt = %q, want a truncation marker", got)
	}
	trimmed := strings.TrimSuffix(got, "...")
	if len([]rune(trimmed)) != 10 {
		t.Fatalf("excerpt kept %d runes, want 10", len([]rune(trimmed)))
	}
	if strings.Contains(got, "�") {
		t.Fatalf("excerpt = %q, want no replacement character", got)
	}
}

func TestVerdict_OnlyTheTwoShapesViolate(t *testing.T) {
	violating := map[Verdict]bool{
		SenderMarker:       true,
		UndisclosedTrigger: true,
	}
	all := []Verdict{Compliant, BareTrigger, SenderMarker, UndisclosedTrigger, Unattributable}
	for _, verdict := range all {
		if got, want := verdict.violating(), violating[verdict]; got != want {
			t.Errorf("%q.violating() = %v, want %v", verdict, got, want)
		}
	}
}

// The live sample the issue cited, as a regression corpus. Kept as JSON so it
// round-trips through the same decode path production uses.
func TestAnalyse_LiveSampleCorpus(t *testing.T) {
	corpus := []map[string]any{
		// world-at-ruin#661 5150876600 -- trailing disclosure
		{"id": 5150876600, "author": "devantler",
			"body": "@coderabbitai full review\n\n> 🤖 Generated by the Agentic Engineer."},
		// world-at-ruin#662 5151295297 -- annotated trigger, no disclosure at all
		{"id": 5151295297, "author": "devantler",
			"body": "@coderabbitai review\n\nPlease review exact head 94171a33ec112cf86f559f037bf99a54fe996a43"},
		// ksail#6244 5030838223 -- non-canonical sender marker
		{"id": 5030838223, "author": "devantler",
			"body": "> Requested by the 🤖 Daily AI Engineer — CI is green at the current head."},
		// ksail#6244 5030838309 -- the bare-trigger carve-out, must NOT be flagged
		{"id": 5030838309, "author": "devantler", "body": "@cursor review"},
		// a correctly-formed comment, must NOT be flagged
		{"id": 9999999999, "author": "devantler",
			"body": "> 🤖 Generated by the Agentic Engineer\n\n## Why\n\nReal work.\n"},
	}
	raw, err := json.Marshal(corpus)
	if err != nil {
		t.Fatalf("marshal corpus: %v", err)
	}
	comments, err := decode(raw)
	if err != nil {
		t.Fatalf("decode corpus: %v", err)
	}
	report := Analyse(comments, "devantler")

	// The bare @cursor review at 5030838309 follows a SENDER-MARKER comment, not a
	// canonical disclosure, so its exemption is unpaired and it is reported too.
	if len(report.Findings) != 4 {
		t.Fatalf("findings = %d, want 4", len(report.Findings))
	}
	wantVerdicts := map[int64]Verdict{
		5030838223: SenderMarker,
		5030838309: UndisclosedTrigger,
		5150876600: UndisclosedTrigger,
		5151295297: UndisclosedTrigger,
	}
	for _, finding := range report.Findings {
		want, ok := wantVerdicts[finding.ID]
		if !ok {
			t.Errorf("unexpected finding on comment %d (%q)", finding.ID, finding.Verdict)
			continue
		}
		if finding.Verdict != want {
			t.Errorf("comment %d: verdict %q, want %q", finding.ID, finding.Verdict, want)
		}
	}
	if report.Counts[BareTrigger] != 0 {
		t.Errorf("bare-trigger count = %d, want 0 (the trigger is unpaired)", report.Counts[BareTrigger])
	}
	if report.Counts[Compliant] != 1 {
		t.Errorf("compliant count = %d, want 1", report.Counts[Compliant])
	}
	// Findings must be ID-ordered so the report is stable run to run.
	for i := 1; i < len(report.Findings); i++ {
		if report.Findings[i-1].ID >= report.Findings[i].ID {
			t.Fatalf("findings are not ID-ordered: %+v", report.Findings)
		}
	}
}

// Codex P1 (#2720): the Bugbot carve-out is conditional on the disclosure sitting
// in its own comment IMMEDIATELY BEFORE the trigger. Judged per-body in isolation,
// an unpaired bare trigger cleared the guard -- exactly the case the contract
// excludes.
func TestAnalyse_BareTriggerNeedsItsPrecedingDisclosure(t *testing.T) {
	paired := []Comment{
		{ID: 1, Author: "devantler", Body: "> 🤖 Generated by the Agentic Engineer\n\nRequesting a review."},
		{ID: 2, Author: "devantler", Body: "@cursor review"},
	}
	if report := Analyse(paired, "devantler"); len(report.Findings) != 0 {
		t.Errorf("paired trigger reported: %+v", report.Findings)
	}

	unpaired := []Comment{{ID: 1, Author: "devantler", Body: "@cursor review"}}
	report := Analyse(unpaired, "devantler")
	if len(report.Findings) != 1 || report.Findings[0].Verdict != UndisclosedTrigger {
		t.Errorf("unpaired trigger: findings = %+v, want one undisclosed-trigger", report.Findings)
	}

	// Preceded by a NON-disclosure comment is still unpaired.
	wrongNeighbour := []Comment{
		{ID: 1, Author: "devantler", Body: "> Requested by the 🤖 Daily AI Engineer - CI is green"},
		{ID: 2, Author: "devantler", Body: "@cursor review"},
	}
	if report := Analyse(wrongNeighbour, "devantler"); len(report.Findings) != 2 {
		t.Errorf("wrong-neighbour pairing: findings = %+v, want both reported", report.Findings)
	}

	// A comment from another login is skipped BEFORE the pairing state is updated, so
	// it does not break an otherwise valid disclosure/trigger pair. That ordering is
	// deliberate: anyone may comment between the two, and letting a stranger's remark
	// turn our own compliant pair into a violation would report the wrong party. This
	// pins the ordering, so moving the SkippedAuthors branch below the assignment
	// fails here instead of silently changing who gets reported.
	interleaved := []Comment{
		{ID: 1, Author: "devantler", Body: "> 🤖 Generated by the Agentic Engineer\n\nRequesting a review."},
		{ID: 2, Author: "someone-else", Body: "looks good to me"},
		{ID: 3, Author: "devantler", Body: "@cursor review"},
	}
	if report := Analyse(interleaved, "devantler"); len(report.Findings) != 0 {
		t.Errorf("interleaved foreign comment broke the pairing: %+v", report.Findings)
	}
}

// Codex P1 (#2720): --input is the advertised path for an assembled payload, so an
// incomplete assembly must fail closed rather than classify nothing and exit 0.
func TestDecode_ArrayRecordsMustCarryAuthorAndBody(t *testing.T) {
	bad := []string{
		`[{"message":"Not Found"}]`,
		`[{"id":1,"body":"x"}]`,
		`[{"id":1,"body":"x","user":{}}]`,
		`[{"id":1,"user":{"login":"devantler"}}]`,
		`[{"id":1,"body":null,"user":{"login":"devantler"}}]`,
		`[{"id":1,"body":"x","author":""}]`,
	}
	for _, raw := range bad {
		if _, err := decode([]byte(raw)); err == nil {
			t.Errorf("decode(%s) succeeded; want an error so the guard fails closed", raw)
		}
	}
	good := []string{
		`[{"id":1,"body":"x","user":{"login":"devantler"}}]`,
		`[{"id":1,"body":"","author":"devantler"}]`,
		`[]`,
	}
	for _, raw := range good {
		if _, err := decode([]byte(raw)); err != nil {
			t.Errorf("decode(%s) failed: %v", raw, err)
		}
	}
}

// Codex P1 (#2720): the WRAPPED input form bypassed record validation entirely,
// so {"comments":[{"message":"Not Found"}]} decoded to a zero-valued comment and
// the guard reported a clean sweep having checked nothing.
func TestDecode_WrappedFormValidatesRecordsToo(t *testing.T) {
	bad := []string{
		`{"comments":[{"message":"Not Found"}]}`,
		`{"comments":[{"id":1,"body":"x"}]}`,
		`{"comments":[{"id":1,"user":{"login":"devantler"}}]}`,
	}
	for _, raw := range bad {
		if _, err := decode([]byte(raw)); err == nil {
			t.Errorf("decode(%s) succeeded; want an error so the guard fails closed", raw)
		}
	}
	if _, err := decode([]byte(`{"comments":[{"id":1,"body":"x","author":"devantler"}]}`)); err != nil {
		t.Errorf("valid wrapped payload rejected: %v", err)
	}
}
