export type Locale = 'en' | 'da';

// Introductory guide prices, not a checkout catalogue. Scope and running costs
// are confirmed in a written quote before a project starts.
export const offers = [
  { id: 'website', setup: 2995, monthly: 99 },
  { id: 'app', setup: 7995, monthly: 299 },
  { id: 'service', setup: 4995, monthly: 199 },
] as const;

export const inquiryUrl = 'https://www.linkedin.com/in/nikolai-emil-damm-14a786150/';

export const copy = {
  en: {
    title: 'Websites & software for small businesses | Devantler Tech',
    description: 'Websites, small web apps and web services for Danish small businesses. Clear introductory prices, agreed scope and optional hosting from Devantler Tech.',
    skip: 'Skip to content', navigation: 'Main navigation', language: 'Choose language',
    services: 'Services & prices', work: 'Selected work', products: 'Products', process: 'How it works', contact: 'Get in touch',
    eyebrow: 'Independent software studio · Denmark',
    headline: 'Good software.\nBuilt for your business.',
    intro: 'A clear website. A useful tool. One less manual task. Devantler Tech builds and hosts focused software for small businesses and sole traders.',
    primary: 'Tell me what you need', secondary: 'Explore services',
    availability: 'Planning projects from November 2026',
    promise: ['Small, well-defined projects', 'Build + optional hosting', 'Direct contact with the developer'],
    previewLabel: 'From idea to everyday use', previewTitle: 'Keep the useful.\nLeave the complicated.',
    previewSteps: ['A website people understand', 'A tool that fits your workflow', 'Hosting with an agreed monthly cost'],
    servicesTitle: 'Start small. Build what matters.',
    servicesIntro: 'Introductory starting prices for a focused first version. We agree the deliverables, schedule and total before work begins.',
    starting: 'Build from', monthly: 'Optional hosting from', perMonth: '/ month', currency: 'DKK',
    offerCopy: [
      { title: 'A professional website', description: 'Make your business easy to find, understand and contact.', includes: ['Up to 5 straightforward pages', 'Mobile-friendly design', 'Your content, services and contact details', 'Basic search and sharing metadata'], boundary: 'You supply your logo, text and images. Copywriting, extra languages, booking and online payments are quoted separately.' },
      { title: 'A small web app', description: 'Replace a recurring manual task with a tool made for the way you work.', includes: ['One clearly defined workflow', 'A focused browser-based interface', 'Agreed data inputs and outputs', 'Testing and a practical handover'], boundary: 'A compact first version, not a full business system. Complex permissions, payments, sensitive data and integrations need a separate scope.' },
      { title: 'A web service', description: 'Connect a small process or let two systems exchange useful information.', includes: ['One bounded automation or connection', 'Agreed inputs, outputs and limits', 'Basic operating documentation', 'Testing against the agreed use case'], boundary: 'External subscriptions, API charges, extra integrations and high-volume processing are not included in the starting price.' },
    ],
    priceNote: 'Prices are indicative and in DKK. Domains, external tools and usage-based charges are additional unless included in your quote. Hosting capacity, maintenance, backups and support scope are agreed separately. No VAT is charged under the current PMV setup.',
    hostingTitle: 'Hosting that fits the project—not the other way around.',
    hostingText: 'Your project can run on the Devantler Tech platform when its needs fit. Traffic, storage and any external services determine the final monthly price. If a new feature increases those costs, you receive a revised quote before it is added.',
    fitTitle: 'A good fit for planned, manageable work.',
    fitText: 'This is a small independent business, not an on-call agency. Changes are scheduled and quoted; feature requests are not delivered at a moment’s notice. Emergency response, 24/7 support and large infrastructure projects are not offered.',
    workTitle: 'Real projects. Honest context.',
    workIntro: 'Examples from the existing portfolio—not a list of paid client commissions.',
    workItems: [
      { title: 'AS Coaching og Vaner', kind: 'Family project · Business website', text: 'A small website hosted for a family member: an example of a focused online presence.' },
      { title: 'Wedding App', kind: 'Family project · Web app', text: 'A small self-hosted service created around a family wedding.' },
    ],
    portfolioLink: 'Explore the project portfolio',
    productsTitle: 'Open-source roots. Useful products.',
    productsIntro: 'The technical portfolio remains available alongside client work. Paid managed editions will only be introduced where they add value and real demand exists.',
    ksailText: 'Tools for creating and operating Kubernetes clusters. Explore the public project and documentation.',
    pluginsText: 'Reusable skills and plugin bundles for AI coding assistants. Explore the public catalogue.',
    productLink: 'Explore project', subscriptionNote: 'No paid product subscriptions are available yet. Open-source offerings are not being replaced by paid-only versions.',
    processTitle: 'A clear agreement before a line of code.',
    steps: [
      { title: 'Describe the need', text: 'Share what your business does, the problem you want solved, your budget and your preferred timing.' },
      { title: 'Agree a small scope', text: 'Receive a written proposal covering deliverables, cost, hosting needs, ownership, support and a realistic schedule.' },
      { title: 'Review, launch, improve', text: 'Try the result before launch. Later changes and any additional monthly costs are agreed separately.' },
    ],
    founderTitle: 'A small studio, with a named developer.',
    founderText: 'Devantler Tech is run by Nikolai Emil Damm. The personal profile, engineering projects and blog show the work behind the business.',
    profile: 'Meet Nikolai', blog: 'Read the blog', technical: 'Technical projects',
    contactTitle: 'What would make your working day easier?',
    contactText: 'Start with a short description. You do not need a technical specification—just the problem, a rough budget and when you would like to begin.',
    contactAction: 'Discuss your project on LinkedIn',
    contactNote: 'The link opens Nikolai’s public LinkedIn profile. There is no automatic booking or instant-support service.',
    footer: 'Websites, software and hosting for small businesses.', englishNote: 'Supporting profile, blog and technical documentation are currently in English.',
  },
  da: {
    title: 'Hjemmesider og software til små virksomheder | Devantler Tech',
    description: 'Hjemmesider, små webapps og webservices til danske små virksomheder. Vejledende introduktionspriser, aftalt omfang og valgfri hosting hos Devantler Tech.',
    skip: 'Spring til indhold', navigation: 'Hovednavigation', language: 'Vælg sprog',
    services: 'Ydelser og priser', work: 'Udvalgte projekter', products: 'Produkter', process: 'Sådan foregår det', contact: 'Kontakt',
    eyebrow: 'Uafhængigt softwarestudio · Danmark',
    headline: 'God software.\nBygget til din virksomhed.',
    intro: 'En overskuelig hjemmeside. Et nyttigt værktøj. Én manuel opgave mindre. Devantler Tech bygger og hoster fokuseret software til små virksomheder og enkeltmandsvirksomheder.',
    primary: 'Fortæl om dit behov', secondary: 'Se ydelserne',
    availability: 'Planlægger projekter fra november 2026',
    promise: ['Små, velafgrænsede projekter', 'Udvikling og valgfri hosting', 'Direkte kontakt med udvikleren'],
    previewLabel: 'Fra idé til daglig brug', previewTitle: 'Behold det nyttige.\nUndgå det komplicerede.',
    previewSteps: ['En hjemmeside, folk forstår', 'Et værktøj til din arbejdsgang', 'Hosting til en aftalt månedspris'],
    servicesTitle: 'Start småt. Byg det, der gør en forskel.',
    servicesIntro: 'Vejledende introduktionspriser for en afgrænset første version. Vi aftaler leverancer, tidsplan og samlet pris, før arbejdet begynder.',
    starting: 'Udvikling fra', monthly: 'Valgfri hosting fra', perMonth: '/ måned', currency: 'kr.',
    offerCopy: [
      { title: 'En professionel hjemmeside', description: 'Gør det nemt at finde, forstå og kontakte din virksomhed.', includes: ['Op til 5 enkle sider', 'Mobilvenligt design', 'Dit indhold, dine ydelser og kontaktoplysninger', 'Grundlæggende metadata til søgning og deling'], boundary: 'Du leverer logo, tekst og billeder. Tekstforfatning, ekstra sprog, booking og onlinebetaling aftales og prissættes særskilt.' },
      { title: 'En lille webapp', description: 'Erstat en tilbagevendende manuel opgave med et værktøj til din måde at arbejde på.', includes: ['Én klart afgrænset arbejdsgang', 'En fokuseret brugerflade i browseren', 'Aftalte data ind og ud', 'Test og en praktisk overdragelse'], boundary: 'En kompakt første version, ikke et komplet virksomhedssystem. Komplekse adgangsrettigheder, betaling, følsomme data og integrationer kræver en særskilt aftale.' },
      { title: 'En webservice', description: 'Forbind en lille proces, eller lad to systemer udveksle nyttig information.', includes: ['Én afgrænset automatisering eller forbindelse', 'Aftalte input, output og begrænsninger', 'Grundlæggende driftsdokumentation', 'Test af den aftalte anvendelse'], boundary: 'Eksterne abonnementer, API-gebyrer, ekstra integrationer og behandling af store datamængder indgår ikke i startprisen.' },
    ],
    priceNote: 'Priserne er vejledende og i danske kroner. Domæner, eksterne værktøjer og forbrugsafhængige gebyrer kommer oveni, medmindre de er med i tilbuddet. Hostingkapacitet, vedligeholdelse, backup og support aftales særskilt. Der opkræves ikke moms under den nuværende PMV-ordning.',
    hostingTitle: 'Hosting, der passer til projektet—ikke omvendt.',
    hostingText: 'Dit projekt kan køre på Devantler Tech-platformen, når behovet passer. Trafik, lagerplads og eventuelle eksterne tjenester afgør den endelige månedspris. Hvis en ny funktion øger udgifterne, får du et revideret tilbud, før den tilføjes.',
    fitTitle: 'Til planlagt og overskueligt arbejde.',
    fitText: 'Dette er en lille, uafhængig virksomhed, ikke et bureau på tilkaldevagt. Ændringer planlægges og prissættes; nye funktioner leveres ikke med et øjebliks varsel. Akut beredskab, support døgnet rundt og store infrastrukturprojekter tilbydes ikke.',
    workTitle: 'Rigtige projekter. Ærlig sammenhæng.',
    workIntro: 'Eksempler fra den eksisterende portefølje—ikke en liste over betalte kundeopgaver.',
    workItems: [
      { title: 'AS Coaching og Vaner', kind: 'Familieprojekt · Hjemmeside', text: 'En lille hjemmeside hostet for et familiemedlem: et eksempel på en fokuseret tilstedeværelse online.' },
      { title: 'Wedding App', kind: 'Familieprojekt · Webapp', text: 'En lille selvhostet tjeneste bygget i forbindelse med et bryllup i familien.' },
    ],
    portfolioLink: 'Se projektporteføljen',
    productsTitle: 'Rødder i open source. Nyttige produkter.',
    productsIntro: 'Den tekniske portefølje er stadig tilgængelig ved siden af kundeopgaverne. Betalte, hostede udgaver introduceres kun, hvor de tilfører værdi, og der er reel efterspørgsel.',
    ksailText: 'Værktøjer til at oprette og drive Kubernetes-klynger. Se det offentlige projekt og dokumentationen.',
    pluginsText: 'Genbrugelige færdigheder og pluginpakker til AI-kodeassistenter. Se det offentlige katalog.',
    productLink: 'Se projektet', subscriptionNote: 'Der tilbydes endnu ingen betalte produktabonnementer. Open source-tilbud erstattes ikke af udgaver, der kun kan købes.',
    processTitle: 'En klar aftale før den første linje kode.',
    steps: [
      { title: 'Beskriv dit behov', text: 'Fortæl, hvad din virksomhed laver, hvilket problem du vil løse, dit budget og din ønskede tidsplan.' },
      { title: 'Aftal et lille omfang', text: 'Få et skriftligt forslag med leverancer, pris, hostingbehov, ejerskab, support og en realistisk tidsplan.' },
      { title: 'Afprøv, lancér, forbedr', text: 'Afprøv resultatet før lancering. Senere ændringer og eventuelle ekstra månedlige udgifter aftales særskilt.' },
    ],
    founderTitle: 'Et lille studio med en navngiven udvikler.',
    founderText: 'Devantler Tech drives af Nikolai Emil Damm. Den personlige profil, udviklingsprojekterne og bloggen viser arbejdet bag virksomheden.',
    profile: 'Mød Nikolai', blog: 'Læs bloggen', technical: 'Tekniske projekter',
    contactTitle: 'Hvad ville gøre din arbejdsdag lettere?',
    contactText: 'Start med en kort beskrivelse. Du behøver ikke en teknisk specifikation—bare problemet, et omtrentligt budget og hvornår du gerne vil begynde.',
    contactAction: 'Tal om dit projekt på LinkedIn',
    contactNote: 'Linket åbner Nikolais offentlige LinkedIn-profil. Der er ingen automatisk booking eller øjeblikkelig support.',
    footer: 'Hjemmesider, software og hosting til små virksomheder.', englishNote: 'Profil, blog og teknisk dokumentation er foreløbig på engelsk.',
  },
} as const;
