export const supporting = {
  en: {
    aboutTitle: 'About Devantler Tech',
    aboutDescription: 'Meet Nikolai Emil Damm, the founder and developer behind Devantler Tech’s one-person software business on Funen, Denmark.',
    aboutIntro: 'One person, from the first conversation to the finished software.',
    founderRole: 'Founder & developer',
    founderText: 'I’m Nikolai. Devantler Tech is my independent software business on Funen, Denmark. I build websites, small web apps and services, and maintain a collection of open-source developer tools.',
    founderNote: 'There is no account manager or large team behind the scenes. You talk directly to the person building your project. I keep the work small enough to give it proper attention alongside my other commitments.',
    approachTitle: 'What working together looks like',
    principles: [
      { title: 'A clear first version', text: 'We agree what the software needs to do, what it costs and what can wait. A useful small project is a better starting point than a long list of promises.' },
      { title: 'Planned work, not an emergency service', text: 'Changes fit an agreed schedule. Support, maintenance and hosting limits are written down, and extra scope or running costs need a new agreement.' },
      { title: 'Something you can understand and use', text: 'You get a chance to try the result and a practical handover. The technical choices serve the work your business needs to get done.' },
    ],
    backgroundTitle: 'Background & public work',
    backgroundText: 'My background spans software development, developer tools and running applications. The CV contains the professional detail; the public projects and journal show the work itself.',
    cv: 'Download Nikolai’s CV (English PDF)', github: 'Explore Nikolai’s public code',
    projectsTitle: 'Projects by Devantler Tech',
    projectsDescription: 'Explore Devantler Tech’s public software, reusable tools and templates, alongside family projects and earlier research.',
    projectsIntro: 'Tools, libraries and ideas to build on, alongside websites and small apps made here.',
    openTitle: 'Built in the open',
    openIntro: 'A collection of tools, libraries, templates and a game in development. Some are building blocks you can use; others offer ideas to learn from. None requires a paid subscription.',
    starSnapshot: 'Ordered by GitHub stars, checked',
    reuseNote: 'Check each repository’s licence before reusing its code.',
    moreProducts: 'More tools, libraries & templates',
    engineeringTitle: 'The checks behind the work',
    engineeringIntro: 'Examples from the public portfolio: KSail runs Go tests and linting, plus CodeQL analysis. GitHub’s advanced security tooling also includes secret scanning and dependency alerts. The Wedding App has browser and accessibility tests. Agents help with review and updates under documented merge rules; I remain responsible for delivery.',
    engineeringScope: 'These are working practices, not a certification or a promise of flawless software. Checks are selected for each project; ongoing care is scoped separately.',
    engineeringSources: ['KSail: tests & linting', 'KSail: CodeQL security analysis', 'Wedding App: accessibility tests', 'Portfolio: maintenance & review rules'],
    pluginsTitle: 'Agent Plugins',
    familyTitle: 'Websites & small apps',
    familyIntro: 'These family projects show the kind of focused work I build and host. They are examples, not paid client commissions or testimonials.',
    moreTitle: 'Explore the wider portfolio',
    moreText: 'The technical portfolio includes tools, platforms and experiments. Older research is kept separately so completed work is not mistaken for a current offering.',
    active: 'Active technical projects', completed: 'Completed projects & research', english: 'Technical details and journal articles are in English.',
    contact: 'Discuss a small project',
    projectIndex: 'Project sections', currentLabel: 'Public software', familyLabel: 'Personal & family work',
    realScreenshot: 'The actual KSail terminal interface.',
    researchLabel: 'Earlier work · not a current offering', researchTitle: 'Research & completed work',
    researchProject: 'Data products & data spaces',
    researchText: 'My master’s research explored how independent data products could work together in a data space, with a prototype built in .NET. It is background research, not a service you can buy.',
    thesis: 'Read the thesis (English PDF)', researchExpand: 'Research background & diagrams (English)',
  },
  da: {
    aboutTitle: 'Om Devantler Tech',
    aboutDescription: 'Mød Nikolai Emil Damm, stifteren og udvikleren bag Devantler Techs enkeltmandsvirksomhed på Fyn.',
    aboutIntro: 'Én person, fra den første samtale til den færdige software.',
    founderRole: 'Stifter og udvikler',
    founderText: 'Jeg hedder Nikolai. Devantler Tech er min uafhængige softwarevirksomhed på Fyn. Jeg bygger hjemmesider, små webapps og services og vedligeholder en række open source-værktøjer til udviklere.',
    founderNote: 'Der er ingen kundekonsulent eller stort team bag kulisserne. Du taler direkte med den, der bygger dit projekt. Jeg holder opgaverne små nok til at give dem ordentlig opmærksomhed ved siden af mine øvrige forpligtelser.',
    approachTitle: 'Sådan samarbejder vi',
    principles: [
      { title: 'En klar første version', text: 'Vi aftaler, hvad softwaren skal kunne, hvad den koster, og hvad der kan vente. Et nyttigt, lille projekt er et bedre udgangspunkt end en lang liste af løfter.' },
      { title: 'Planlagt arbejde, ikke akut beredskab', text: 'Ændringer følger en aftalt tidsplan. Support, vedligeholdelse og hostinggrænser beskrives skriftligt. Ekstra opgaver eller driftsudgifter kræver en ny aftale.' },
      { title: 'Noget, du kan forstå og bruge', text: 'Du får mulighed for at afprøve resultatet og en praktisk overdragelse. De tekniske valg skal understøtte det arbejde, din virksomhed har brug for at få gjort.' },
    ],
    backgroundTitle: 'Baggrund og offentlige projekter',
    backgroundText: 'Min baggrund omfatter softwareudvikling, udviklerværktøjer og drift af applikationer. CV’et indeholder de faglige detaljer; de offentlige projekter og journalen viser selve arbejdet.',
    cv: 'Hent Nikolais CV (engelsk PDF)', github: 'Se Nikolais offentlige kode',
    projectsTitle: 'Projekter fra Devantler Tech',
    projectsDescription: 'Se Devantler Techs offentlige software, genbrugelige værktøjer og skabeloner samt familieprojekter og tidligere forskning.',
    projectsIntro: 'Værktøjer, biblioteker og idéer at bygge videre på samt hjemmesider og små apps lavet her.',
    openTitle: 'Udviklet i det åbne',
    openIntro: 'En samling af værktøjer, biblioteker, skabeloner og et spil under udvikling. Nogle er byggesten, du kan bruge; andre giver idéer at lære af. Ingen kræver et betalt abonnement.',
    starSnapshot: 'Sorteret efter GitHub-stjerner, kontrolleret',
    reuseNote: 'Se licensen i hvert repositorium, før du genbruger koden.',
    moreProducts: 'Flere værktøjer, biblioteker og skabeloner',
    engineeringTitle: 'Kontrollen bag arbejdet',
    engineeringIntro: 'Eksempler fra den offentlige portefølje: KSail kører Go-tests og kodekontrol samt CodeQL-analyse. GitHubs avancerede sikkerhedsværktøjer omfatter også scanning efter hemmeligheder og advarsler om afhængigheder. Wedding App har browser- og tilgængelighedstests. Agenter hjælper med gennemgang og opdateringer efter dokumenterede mergeregler; jeg har stadig ansvaret for leveringen.',
    engineeringScope: 'Det er arbejdsmetoder, ikke en certificering eller et løfte om fejlfri software. Kontrollen vælges til hvert projekt; løbende vedligeholdelse aftales særskilt.',
    engineeringSources: ['KSail: tests og kodekontrol', 'KSail: CodeQL-sikkerhedsanalyse', 'Wedding App: tilgængelighedstests', 'Porteføljen: vedligeholdelse og reviewregler'],
    pluginsTitle: 'Agent Plugins',
    familyTitle: 'Hjemmesider og små apps',
    familyIntro: 'Disse familieprojekter viser den slags afgrænsede opgaver, jeg bygger og hoster. De er eksempler, ikke betalte kundeopgaver eller kundeudtalelser.',
    moreTitle: 'Se den bredere portefølje',
    moreText: 'Den tekniske portefølje omfatter værktøjer, platforme og eksperimenter. Ældre forskning står særskilt, så afsluttede projekter ikke forveksles med aktuelle tilbud.',
    active: 'Aktive tekniske projekter (engelsk)', completed: 'Afsluttede projekter og forskning (engelsk)', english: 'Tekniske detaljer og journalartikler er på engelsk.',
    contact: 'Tal om et lille projekt',
    projectIndex: 'Projektsektioner', currentLabel: 'Offentlig software', familyLabel: 'Personlige projekter og familieprojekter',
    realScreenshot: 'Den faktiske KSail-brugerflade i terminalen.',
    researchLabel: 'Tidligere arbejde · ikke et aktuelt tilbud', researchTitle: 'Forskning og afsluttede projekter',
    researchProject: 'Dataprodukter og datarum',
    researchText: 'Mit speciale undersøgte, hvordan selvstændige dataprodukter kunne samarbejde i et datarum, med en prototype bygget i .NET. Det er baggrundsforskning, ikke en ydelse, du kan købe.',
    thesis: 'Læs specialet (engelsk PDF)', researchExpand: 'Forskningsbaggrund og diagrammer (engelsk)',
  },
} as const;
