export const supporting = {
  en: {
    aboutTitle: 'About Devantler Tech',
    aboutDescription: 'Meet Nikolai Emil Damm, the founder and developer behind Devantler Tech’s one-person software business on Funen, Denmark.',
    aboutIntro: 'One person, from the first conversation to the finished software.',
    founderRole: 'Founder & developer',
    founderText: 'I’m Nikolai. Devantler Tech is my independent software business on Funen, Denmark. I build websites, small web apps and services, and maintain a collection of open-source developer tools.',
    founderNote: 'There is no account manager or large team behind the scenes. You talk directly to the person building your project. I keep the work small enough to give it proper attention alongside my other commitments.',
    approachTitle: 'What working together looks like',
    principles: [
      { title: 'A clear first version', text: 'We agree what the software needs to do, what it costs and what can wait. A useful small project is a better starting point than a long list of promises.' },
      { title: 'Planned work, not an emergency service', text: 'Changes fit an agreed schedule. Support, maintenance and hosting limits are written down, and extra scope or running costs need a new agreement.' },
      { title: 'Something you can understand and use', text: 'You get a chance to try the result and a practical handover. The technical choices serve the work your business needs to get done.' },
    ],
    backgroundTitle: 'Background & public work',
    backgroundText: 'My background spans software development, developer tools and running applications. The CV contains the professional detail; the public projects and journal show the work itself.',
    cv: 'Download Nikolai’s CV (English PDF)', github: 'Explore Nikolai’s public code',
    projectsTitle: 'Projects by Devantler Tech',
    projectsDescription: 'Explore Devantler Tech’s open-source software and family projects, with clear distinctions between available tools, experiments and client services.',
    projectsIntro: 'Open-source tools, websites and small apps built and maintained here.',
    openTitle: 'Built in the open',
    openIntro: 'These are public software projects, not products you need a paid subscription to use. The technical documentation explains each project’s capabilities and limits.',
    pluginsTitle: 'Agent Plugins',
    familyTitle: 'Websites & small apps',
    familyIntro: 'These family projects show the kind of focused work I build and host. They are examples, not paid client commissions or testimonials.',
    moreTitle: 'Explore the wider portfolio',
    moreText: 'The technical portfolio includes tools, platforms and experiments. Older research is kept separately so completed work is not mistaken for a current offering.',
    active: 'Active technical projects', completed: 'Completed projects & research', english: 'Technical details and journal articles are in English.',
    contact: 'Discuss a small project',
  },
  da: {
    aboutTitle: 'Om Devantler Tech',
    aboutDescription: 'Mød Nikolai Emil Damm, stifteren og udvikleren bag Devantler Techs enkeltmandsvirksomhed på Fyn.',
    aboutIntro: 'Én person, fra den første samtale til den færdige software.',
    founderRole: 'Stifter og udvikler',
    founderText: 'Jeg hedder Nikolai. Devantler Tech er min uafhængige softwarevirksomhed på Fyn. Jeg bygger hjemmesider, små webapps og services og vedligeholder en række open source-værktøjer til udviklere.',
    founderNote: 'Der er ingen kundekonsulent eller stort team bag kulisserne. Du taler direkte med den, der bygger dit projekt. Jeg holder opgaverne små nok til at give dem ordentlig opmærksomhed ved siden af mine øvrige forpligtelser.',
    approachTitle: 'Sådan samarbejder vi',
    principles: [
      { title: 'En klar første version', text: 'Vi aftaler, hvad softwaren skal kunne, hvad den koster, og hvad der kan vente. Et nyttigt, lille projekt er et bedre udgangspunkt end en lang liste af løfter.' },
      { title: 'Planlagt arbejde, ikke akut beredskab', text: 'Ændringer følger en aftalt tidsplan. Support, vedligeholdelse og hostinggrænser beskrives skriftligt. Ekstra opgaver eller driftsudgifter kræver en ny aftale.' },
      { title: 'Noget, du kan forstå og bruge', text: 'Du får mulighed for at afprøve resultatet og en praktisk overdragelse. De tekniske valg skal understøtte det arbejde, din virksomhed har brug for at få gjort.' },
    ],
    backgroundTitle: 'Baggrund og offentlige projekter',
    backgroundText: 'Min baggrund omfatter softwareudvikling, udviklerværktøjer og drift af applikationer. CV’et indeholder de faglige detaljer; de offentlige projekter og journalen viser selve arbejdet.',
    cv: 'Hent Nikolais CV (engelsk PDF)', github: 'Se Nikolais offentlige kode',
    projectsTitle: 'Projekter fra Devantler Tech',
    projectsDescription: 'Se Devantler Techs open source-software og familieprojekter med en klar skelnen mellem tilgængelige værktøjer, eksperimenter og ydelser til kunder.',
    projectsIntro: 'Open source-værktøjer, hjemmesider og små apps, der bliver bygget og vedligeholdt her.',
    openTitle: 'Udviklet som open source',
    openIntro: 'Dette er offentlige softwareprojekter, ikke produkter, der kræver et betalt abonnement. Den tekniske dokumentation beskriver muligheder og begrænsninger for hvert projekt.',
    pluginsTitle: 'Agent Plugins',
    familyTitle: 'Hjemmesider og små apps',
    familyIntro: 'Disse familieprojekter viser den slags afgrænsede opgaver, jeg bygger og hoster. De er eksempler, ikke betalte kundeopgaver eller kundeudtalelser.',
    moreTitle: 'Se den bredere portefølje',
    moreText: 'Den tekniske portefølje omfatter værktøjer, platforme og eksperimenter. Ældre forskning står særskilt, så afsluttede projekter ikke forveksles med aktuelle tilbud.',
    active: 'Aktive tekniske projekter (engelsk)', completed: 'Afsluttede projekter og forskning (engelsk)', english: 'Tekniske detaljer og journalartikler er på engelsk.',
    contact: 'Tal om et lille projekt',
  },
} as const;
