---
name: "TODOs"
permissions:
  issues: write
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  todos:
    uses: devantler-tech/reusable-workflows/.github/workflows/scan-for-todo-comments.yaml@e05d75a58aeb49b09150f828b97975765f38f809 # v2.4.0
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
