---
name: "TODOs"
permissions:
  contents: read
  issues: write
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  todos:
    uses: devantler-tech/actions/.github/workflows/scan-for-todo-comments.yaml@4e92d0ea39484fc4f693ab47d1e952c43bdc9716 # v11.0.3
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
