---
name: "TODOs"
permissions:
  contents: read
  issues: write
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  todos:
    uses: devantler-tech/reusable-workflows/.github/workflows/scan-for-todo-comments.yaml@d87d78b80422efad5133db7f480dc12027cb9fa5 # v5.6.2
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
